'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict'),pw=require('playwright');
const cfg=JSON.parse(fs.readFileSync('tools/release-check/config.json','utf8')),kind=process.env.HSK_BROWSER||'chromium',candidate=path.resolve('candidate'),prior=path.resolve('prior');
const B=require(path.join(candidate,'new-hsk1/hsk1/stage2/bank.js')),E=require(path.join(candidate,'new-hsk1/hsk1/stage2/engine.js')),C=require(path.join(candidate,'new-hsk1/hsk1/stage3/catalog.js')),E3=require(path.join(candidate,'new-hsk1/hsk1/stage3/engine.js'));
const out=path.resolve('release-evidence');fs.mkdirSync(out,{recursive:true});
const report={mode:cfg.mode,browser:kind,candidate:cfg.candidate,startedAt:new Date().toISOString(),checks:[],tasks:[],media:[],errors:[],network:[],cancelled:[],externalFailures:[],screenshots:[],passed:false};
let browser,server,root=prior,page,active='start';const wait=ms=>new Promise(r=>setTimeout(r,ms));
let BASE=cfg.baseURL+'new-hsk1/hsk1/';
function save(){fs.writeFileSync(path.join(out,`${cfg.mode}-${kind}-browser.json`),JSON.stringify(report,null,2));}
async function check(name,fn){active=name;try{await fn();report.checks.push({name,status:'passed'});}catch(e){report.checks.push({name,status:'failed',error:e.stack});throw e;}finally{save();}}
function order(q){const target=E.normal(q.answers[0]),t=q.tokens.map(E.normal);function walk(left,text,out){if(!left.length)return text===target?out:null;for(const i of left)if(target.startsWith(text+t[i])){const v=walk(left.filter(j=>j!==i),text+t[i],out.concat(i));if(v)return v;}return null;}const v=walk(t.map((_,i)=>i),'',[]);assert.ok(v);return v;}
async function open(relative){await page.goto(BASE+relative,{waitUntil:'domcontentloaded'});if(await page.locator('#pwOverlay').isVisible().catch(()=>false)){await page.locator('#pwInput').fill('Ranlaoshimeimei');await page.locator('#pwBtn').click();await page.locator('#pwOverlay').waitFor({state:'hidden'});}const u=new URL(page.url());if(u.pathname.endsWith('learning.html')){const m=u.searchParams.get('mode')||'homework';if(m==='homework')await page.locator('#lesson-list [data-lesson="15"]').waitFor();else if(m==='progress')await page.locator('.integrated-progress-table').waitFor();else await page.locator('#lesson-checks [data-lesson="15"]').waitFor({state:'attached'});}}
async function state(key){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)||'null'),key);}
async function submit(){await page.locator('#submit-group').click();await page.locator('#submitted-result').waitFor();}
async function shot(name){const f=`${cfg.mode}-${kind}-${name}.png`;await page.screenshot({path:path.join(out,f),fullPage:false});report.screenshots.push(f);}
async function play(id){await page.locator('#play-audio').click();await page.waitForFunction(()=>document.getElementById('lesson-audio').ended,null,{timeout:30000});const r=await page.locator('#lesson-audio').evaluate(a=>({id:a.dataset.mediaId,src:a.src,rate:a.playbackRate,duration:a.duration,ended:a.ended}));assert.equal(r.id,id);const hash=crypto.createHash('sha256').update(Buffer.from(r.src.split(',')[1],'base64')).digest('hex');const expected=await page.evaluate(id=>window.HSKStep3MediaIndex.clips[id].sha256,id);assert.equal(hash,expected);delete r.src;report.media.push({...r,sha256:hash});}
(async()=>{
 if(cfg.mode==='preflight'){
  server=http.createServer((req,res)=>{const url=new URL(req.url,'http://127.0.0.1');let p=path.resolve(root,decodeURIComponent(url.pathname).replace(/^\/hsk-hub\//,''));if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');const data=fs.readFileSync(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.mp3':'audio/mpeg'};res.writeHead(200,{'Content-Type':types[path.extname(p)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(18771,'127.0.0.1',r));BASE='http://127.0.0.1:18771/hsk-hub/new-hsk1/hsk1/';
 }
 browser=await pw[kind].launch({headless:true});report.browserVersion=browser.version();const context=await browser.newContext({viewport:{width:1104,height:900},locale:'vi-VN',acceptDownloads:true});page=await context.newPage();page.setDefaultTimeout(25000);
 page.on('dialog',d=>d.accept());page.on('pageerror',e=>report.errors.push({check:active,error:e.message}));page.on('response',r=>{if(r.status()<400)return;const rec={url:r.url(),status:r.status(),check:active};(r.url().startsWith(BASE)?report.network:report.externalFailures).push(rec);});page.on('requestfailed',r=>{const rec={url:r.url(),error:r.failure()?.errorText,check:active};if(/abort|cancel/i.test(rec.error))report.cancelled.push(rec);else(r.url().startsWith(BASE)?report.network:report.externalFailures).push(rec);});
 if(cfg.mode==='preflight'){
  await check('Production assets -> candidate -> prior assets -> candidate preserve synthetic legacy and new records on the same origin',async()=>{
   const s={};s.window=s;vm.createContext(s);for(const f of ['learning-bank.js','learning-engine.js'])vm.runInContext(fs.readFileSync(path.join(prior,'new-hsk1/hsk1',f),'utf8'),s);
   const old=s.HSKLearnEngine.blank(),L=s.HSK1_NEW_BANK.find(x=>x.lesson===3);
   for(const k of ['choice','sort','translation']){for(const q of L[k])s.HSKLearnEngine.group(old,3,k).draft[q.id]=k==='sort'?order(q):q.answer;assert.equal(s.HSKLearnEngine.submit(old,3,k,L[k]).ok,true);}
   await open('index.html');await page.locator('#lessonGrid').waitFor();const oldRaw=JSON.stringify(old);await page.evaluate(raw=>localStorage.setItem('ran_hsk1_learning_v2',raw),oldRaw);
   root=candidate;await open('learning.html?mode=homework&lesson=3&stage=choice');assert.equal((await state(E.KEY)).lessons[3]?.translation?.completed||false,false);
   // Compatible objective submissions migrate as submissions, so the student explicitly starts a redo.
   await page.locator('#stages [data-stage="choice"]').click();
   if(await page.locator('[data-restart]').count())await page.locator('[data-restart]').click();
   const q=B[2].choice[0];await page.locator(`[data-option="${q.id}"][data-index="${q.answer}"]`).click();await wait(350);const newer=await page.evaluate(k=>localStorage.getItem(k),E.KEY);assert.ok(newer);await shot('candidate-before-rollback');
   root=prior;await open('index.html');await page.locator('#lessonGrid').waitFor();assert.equal(await page.evaluate(k=>localStorage.getItem(k),E.KEY),newer);assert.equal(await page.evaluate(()=>localStorage.getItem('ran_hsk1_learning_v2')),oldRaw);
   root=candidate;await open('learning.html?mode=homework&lesson=3');assert.equal((await state(E.KEY)).lessons[3].choice.draft[q.id],q.answer);assert.equal((await state(E.KEY)).lessons[3]?.translation?.completed||false,false);await shot('candidate-after-rollback');
   report.rollback={productionTouched:false,newRecordPreserved:true,legacyRecordPreserved:true,translationNotFalselyCompleted:true};
  });
 }else{
  await check('Actual published homepage, wrong/correct password and fifteen course entries',async()=>{
   await page.goto(BASE+'index.html',{waitUntil:'domcontentloaded'});await page.locator('#pwInput').fill('wrong-release-test');await page.locator('#pwBtn').click();assert.equal(await page.locator('#pwOverlay').isVisible(),true);await page.locator('#pwInput').fill('Ranlaoshimeimei');await page.locator('#pwBtn').click();await page.locator('#pwOverlay').waitFor({state:'hidden'});await page.locator('#lessonGrid').waitFor();assert.equal(await page.evaluate(()=>window.HSK1_LESSONS.length),15);await shot('home');
  });
  for(let l=1;l<=15;l++)await check(`Published lesson ${l}: original modules and complete 15 homework submissions`,async()=>{
   await open(`lesson.html?id=${l}&sec=vocab`);await page.locator('#vocabGrid .vcard').first().waitFor();for(const sec of ['text','grammar','hanzi','practice']){await page.locator(`.section-tab[data-sec="${sec}"]`).first().click();assert.equal(await page.locator('#'+sec).isVisible(),true);}
   await open(`learning.html?mode=homework&lesson=${l}`);const L=B[l-1];assert.equal(await page.locator('#stages [data-stage="sort"]').isDisabled(),true);await page.locator('#submit-group').click();assert.equal(await page.locator('#form-error').isVisible(),true);
   for(const [i,q] of L.choice.entries())await page.locator(`[data-option="${q.id}"][data-index="${(q.answer+(i===0?1:0))%4}"]`).click();await submit();assert.match(await page.locator('#submitted-result').innerText(),/4\/5/);await page.locator('#stages [data-stage="sort"]').click();
   for(const q of L.sort)for(const i of order(q))await page.locator(`[data-token="${q.id}"][data-index="${i}"]`).click();await submit();assert.match(await page.locator('#submitted-result').innerText(),/5\/5/);await page.locator('#stages [data-stage="translation"]').click();await page.locator('#student-name').fill('KIỂM THỬ PHÁT HÀNH / 发布测试');
   const values=L.translation.map((_,i)=>`发布验证第${l}课第${i+1}题。\nTiếng Việt — giữ nguyên <b>文本</b>`);for(let i=0;i<5;i++)await page.locator('#input-'+L.translation[i].id).fill(values[i]);await submit();await page.locator('[data-receipt]').click();assert.match(await page.locator('#receipt').innerText(),/Không chấm điểm/);for(let i=0;i<5;i++)assert.equal(await page.locator('.s1-written-answer').nth(i).textContent(),values[i]);if([1,8,15].includes(l))await shot('receipt-'+l);await page.locator('[data-close-receipt]').click();await wait(300);const totals=E.totals(await state(E.KEY),l,L);assert.equal(totals.homework.submitted,15);assert.equal(totals.automatic.firstCorrect,9);assert.equal(totals.manual.submitted,5);for(const k of ['choice','sort','translation'])report.tasks.push(...L[k].map(q=>({id:q.id,kind:k,lesson:l,status:'passed'})));
  });
  for(let l=1;l<=15;l++)await check(`Published lesson ${l}: five real listening recordings, feedback and separate grades`,async()=>{
   await open(`learning.html?mode=listening&lesson=${l}`);await page.locator('#start-listening').click();await page.locator('#listening-question').waitFor();await page.locator('#audio-rate').selectOption('1.5');
   for(let n=0;n<5;n++){const id=await page.locator('#listening-question').getAttribute('data-question-id'),q=C.listening.find(x=>x.id===id);assert.equal(q.lesson,l);assert.equal(await page.locator('#listen-transcript').count(),0);await play(id);await page.locator(`[data-listen-option="${(q.answer+(n===0?1:0))%4}"]`).click();await page.locator('#listening-feedback').waitFor();report.tasks.push({id,kind:'listening',lesson:l,status:'passed'});if(n<4)await page.locator('#listen-next').click();}
  });
  await check('Published multi-course vocabulary, refresh, real backup export and mobile help',async()=>{
   await open('learning.html?mode=vocab&intent=resume');await page.locator('#clear-lessons').click();for(const n of [3,6,15])await page.locator(`#lesson-checks [data-lesson="${n}"]`).check();await page.locator('#start-review').click();await page.locator('#reveal-card').click();await page.locator('[data-rating="hard"]').click();const before=await state(E3.KEY);await page.reload({waitUntil:'domcontentloaded'});await page.locator('#review-card').waitFor();assert.deepEqual((await state(E3.KEY)).cards,before.cards);
   await page.locator('#backup-details').evaluate(el=>el.open=true);const download=page.waitForEvent('download');await page.locator('#export-backup').click();await (await download).saveAs(path.join(out,`live-${kind}-media-backup.json`));
   for(const width of [320,390,768,1104]){await page.setViewportSize({width,height:900});await open('help.html');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await shot('help-'+width);}
   await open('learning.html?mode=progress');assert.match(await page.locator('.integrated-progress-table').innerText(),/15/);const h=E.courseTotals(await state(E.KEY),B),m=E3.listeningSummary(await state(E3.KEY),C);assert.equal(h.homework.submitted,225);assert.equal(m.overall.answered,75);assert.equal(m.overall.firstCorrect,60);assert.equal(new Set(report.tasks.map(x=>x.id)).size,300);assert.equal(report.media.length,75);await shot('progress');
  });
 }
 await check('No uncaught application errors or unexpected first-party failures',async()=>{assert.deepEqual(report.errors,[]);assert.deepEqual(report.network,[]);});report.passed=true;
})().catch(async e=>{report.error=e.stack;process.exitCode=1;if(page)await shot('failure').catch(()=>{});}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));report.finishedAt=new Date().toISOString();save();console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,tasks:report.tasks.length,media:report.media.length,error:report.error}));});
