import {bilingualText,setBilingual} from '../../app/bilingual.ts';
import {createActivityCard,createFeedbackEpoch} from '../../shared/activity-card.ts';
import {getSourceLesson,incompleteSourceFields,sourceRecordKey,type SourceActivity,type SourceField,type Copy} from '../../services/source-activities/content.ts';
import {archivedSourceRecords,blankSourceData} from '../../services/source-activities/state.ts';
import {getSourceSession,type SourceSession} from '../../services/source-activities/store.ts';
import type {Preview} from '../../services/storage/index.ts';
import type {SourceData} from '../../services/source-activities/state.ts';
import type {TextbookContent} from '../../services/content/textbook.ts';
import type {AudioService} from '../../services/audio/index.ts';
import type {OfficialViRegistry} from '../../services/content/official-vi-revisions.ts';
import {button,element} from '../textbook/dom.ts';
import {numberTables} from './numbers.ts';
import {resolveSourceFigure} from './figures.ts';
import {sourceActivityTable,tableFieldIds} from './tables.ts';
import './source-activities.css';
const copy=(zh:string,vi:string):Copy=>({zh,vi});
const states:Record<string,Copy>={empty:copy('尚无原版活动记录','Chưa có bản ghi hoạt động gốc'),saved:copy('原版活动已保存','Đã lưu hoạt động gốc'),saving:copy('正在保存原版活动…','Đang lưu hoạt động gốc…'),unsaved:copy('原版活动尚未保存，请重试或导出草稿','Chưa lưu hoạt động gốc; hãy thử lại hoặc xuất bản nháp'),conflict:copy('其他标签页已更新记录。请先导出草稿，再读取最新记录','Tab khác đã cập nhật. Hãy xuất bản nháp trước khi đọc bản mới'),corrupt:copy('原始记录无法读取，已阻止覆盖。请下载原始数据','Không đọc được dữ liệu gốc; đã chặn ghi đè. Hãy tải dữ liệu gốc'),unavailable:copy('无法安全保存，草稿仍在当前页面，可导出','Không thể lưu an toàn; bản nháp còn trong trang này và có thể xuất')};
export function mountSourceActivities(host:HTMLElement,options:{signal:AbortSignal;content:TextbookContent;audio:AudioService;session?:SourceSession;officialVi?:OfficialViRegistry;download?:(name:string,text:string)=>void},lessonId=4){
  const sourceLesson=getSourceLesson(lessonId,options.officialVi);
  if(!sourceLesson)return {dispose(){}};
  const lesson=sourceLesson;
  const {signal}=options,session=options.session??getSourceSession(),store=session.store;
  const section=element('section');section.className='source-activities';section.dataset.hsk1SourcePilot=String(lessonId);section.dataset.sourceLesson=String(lessonId);
  section.append(element('h2',copy(`第${lessonId}课 · 原版活动`,`Bài ${lessonId} · Hoạt động từ sách`)),
    element('p',copy('按教材原活动顺序练习。记录独立保存，不计入原作业成绩。','Luyện tập theo thứ tự hoạt động trong sách. Bản ghi được lưu riêng, không tính vào điểm bài tập cũ.')),
    element('p',copy('数据页及统一备份已包含本组记录；也可以单独导出原版活动。','Trang dữ liệu và bản sao lưu thống nhất bao gồm nhóm này; cũng có thể xuất riêng hoạt động gốc.')));
  const status=element('p');status.setAttribute('role','status');status.dataset.sourceSaveStatus='';section.append(status);
  const actions=element('div');actions.className='source-actions';
  function download(name:string,text:string){if(options.download){options.download(name,text);return;}const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=element('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
  const retry=button(copy('重试保存','Thử lưu lại'),()=>{void session.flush();},signal);
  const backup=button(copy('导出原版活动（含草稿）','Xuất hoạt động gốc (kèm bản nháp)'),()=>download('hsk1-source-activities.json',store.exportBackup()),signal);backup.dataset.sourceExport='';
  const original=button(copy('下载原始数据','Tải dữ liệu gốc'),()=>{const raw=store.exportOriginal();if(raw!==null)download('hsk1-source-original.json',raw);},signal);
  const reload=button(copy('放弃当前草稿并读取最新记录','Bỏ bản nháp hiện tại và đọc bản mới'),()=>showReload(),signal);
  const input=element('input');input.type='file';input.accept='.json,application/json';input.id='source-import-file';const label=element('label',copy('导入独立活动备份','Nhập bản sao lưu hoạt động riêng'));label.htmlFor=input.id;
  const reset=button(copy('预览清空原版活动','Xem trước xóa hoạt động gốc'),()=>{try{showPreview(store.previewReplacement(blankSourceData(),'reset'));}catch{showError();}},signal);
  const restore=button(copy('预览恢复上次替换前的记录','Xem trước khôi phục trước lần thay thế'),()=>showRestore(),signal);
  actions.append(retry,backup,original,reload,label,input,reset,restore);section.append(actions);
  const preview=element('div');preview.className='source-preview';preview.hidden=true;preview.setAttribute('role','region');preview.setAttribute('aria-label','确认数据操作 · Xác nhận thao tác dữ liệu');section.append(preview);
  let operation:AbortController|undefined,pending:Preview<SourceData>|undefined;
  const composingFields=new Set<string>();
  const clearPreview=()=>{fileEpoch++;operation?.abort();operation=undefined;pending=undefined;preview.replaceChildren();preview.hidden=true;};
  const cancel=()=>{const epoch=fileEpoch;return button(copy('取消','Hủy'),()=>{if(epoch===fileEpoch)clearPreview();},signal);};
  function showError(){setBilingual(status,copy('操作未完成；数据格式无效、已发生冲突或当前记录不可读。请保留导出副本。','Thao tác chưa hoàn tất; định dạng sai, có xung đột hoặc không đọc được dữ liệu. Hãy giữ bản xuất.'));}
  function showReload(){if(composingFields.size){showError();return;}clearPreview();const epoch=fileEpoch;preview.hidden=false;preview.append(element('p',copy('将放弃当前标签页尚未保存的原版活动草稿。请先导出。','Sẽ bỏ bản nháp hoạt động gốc chưa lưu trong tab này. Hãy xuất trước.')),button(copy('确认放弃并读取','Xác nhận bỏ và đọc lại'),()=>{if(epoch!==fileEpoch)return;store.reloadDiscardingDraft();clearPreview();draw();},signal),cancel());}
  function showRestore(){if(composingFields.size){showError();return;}clearPreview();const epoch=fileEpoch,token=JSON.stringify({data:store.snapshot().data,revision:store.snapshot().revision});preview.hidden=false;preview.append(element('p',copy('恢复上次导入或清空前的原版活动记录。原作业记录不变。','Khôi phục hoạt động gốc trước lần nhập hoặc xóa gần nhất. Không thay đổi bài tập cũ.')),button(copy('确认恢复','Xác nhận khôi phục'),()=>{if(operation||epoch!==fileEpoch)return;if(composingFields.size||token!==JSON.stringify({data:store.snapshot().data,revision:store.snapshot().revision})){clearPreview();showError();return;}operation=new AbortController();const request=operation;void store.restore(request.signal).then(result=>{if(request.signal.aborted||operation!==request)return;if(result.ok&&!signal.aborted){clearPreview();draw();}else if(!signal.aborted)showError();});},signal),cancel());}
  function showPreview(held:Preview<SourceData>){if(composingFields.size){showError();return;}clearPreview();pending=held;const epoch=fileEpoch,before=Object.keys(store.snapshot().data.records).length,after=Object.keys(held.data.records).length;preview.hidden=false;preview.append(element('p',copy(`仅替换原版活动：现有${before}组 → 备份${after}组。保留一次恢复副本。原作业与旧版记录不变。`,`Chỉ thay hoạt động gốc: ${before} nhóm hiện tại → ${after} nhóm trong bản nhập. Giữ một bản khôi phục. Không thay bài tập và dữ liệu cũ.`)),button(copy('确认替换原版活动','Xác nhận thay hoạt động gốc'),()=>{if(pending!==held||epoch!==fileEpoch||operation)return;if(composingFields.size){clearPreview();showError();return;}operation=new AbortController();const request=operation;void store.confirm(held,request.signal).then(result=>{if(request.signal.aborted||operation!==request)return;if(result.ok&&!signal.aborted){clearPreview();draw();}else if(!signal.aborted){clearPreview();showError();}});},signal),cancel());}
  input.addEventListener('change',()=>{clearPreview();const file=input.files?.[0];if(!file)return;if(file.size>32*1024*1024){showError();return;}const readEpoch=++fileEpoch;void file.text().then(text=>{if(signal.aborted||readEpoch!==fileEpoch)return;try{showPreview(store.previewBackup(text));}catch{showError();}}).catch(()=>{if(!signal.aborted&&readEpoch===fileEpoch)showError();});},{signal});
  let fileEpoch=0;
  const body=element('div');body.className='source-activity-grid';if(lesson.numberTables)section.append(numberTables(lesson.numberTables));section.append(body);
  let cardLifetime=new AbortController();
  function draw(){for(const id of composingFields)session.setComposing(id,false);composingFields.clear();cardLifetime.abort();cardLifetime=new AbortController();body.replaceChildren();for(const a of lesson.activities)body.append(card(a,cardLifetime.signal));}
  function card(a:SourceActivity,cardSignal:AbortSignal){
    const {card,fields,feedback}=createActivityCard(document,a.id);card.dataset.activityVersion=a.version;card.dataset.kind=a.kind;
    card.append(element('h3',a.title),element('p',a.instruction));if(a.prompt.zh||a.prompt.vi)card.append(element('p',a.prompt));if(a.pinyin)card.append(element('p',a.pinyin));
    for(const id of [...(a.figure?[a.figure]:[]),...(a.figures??[])]){const resolved=resolveSourceFigure(lessonId,id,id===a.figure?a.figureSHA256:a.figureSHA256s?.[id],options.officialVi);if(resolved){const {figure,url}=resolved,f=element('figure'),img=element('img');img.src=url;img.alt=bilingualText(figure.alt);if(figure.kind==='original-schematic'){img.width=360;img.height=220;}img.loading='lazy';f.append(img,element('figcaption',figure.note));card.append(f);}else card.append(element('p',copy('本题原图暂不可用','Hình gốc của câu này hiện chưa dùng được')));}
    if(a.example)card.append(element('small',copy('教材提供的对话开头','Phần mở đầu hội thoại được cho trong sách')),element('p',a.example));
    if(a.audio){const resolved=options.content.resolveScene(lessonId,a.audio.sceneId);const play=button(copy('播放本题原对话','Phát hội thoại gốc của câu này'),()=>{if(resolved.available)void options.audio.play({...resolved.request,label:bilingualText(copy(`第${lessonId}课原版听力 · 音轨${a.audio!.track}`,`Nghe bài ${lessonId} · Tệp ${a.audio!.track}`))},{signal:cardSignal});},cardSignal);play.dataset.sourceSceneAudio=a.audio.sceneId;play.disabled=!resolved.available;card.append(play);if(!resolved.available)card.append(element('p',copy('原音频暂不可用','Âm thanh gốc hiện chưa dùng được')));}
    const key=sourceRecordKey(a),old=store.snapshot().data.records[key];let values={...old?.draft.values},composing=false,busy=false;
    const epoch=createFeedbackEpoch();
    function change(id:string,value:string){epoch.next();feedback.replaceChildren();values[id]=value;session.edit(a,values,composing);}
    function field(f:SourceField){const row=element('div');row.className='activity-field';const label=element('label',f.label);label.htmlFor=a.id+'-'+f.id;row.append(label);if(f.pinyin){const pinyin=element('p',f.pinyin);pinyin.className='source-field-pinyin';row.append(pinyin);}
      const input=f.input==='select'?element('select'):f.input==='textarea'?element('textarea'):element('input');input.id=label.htmlFor;input.dataset.sourceField=f.id;
      if(input instanceof HTMLSelectElement){const empty=element('option','请选择 · Hãy chọn');empty.value='';input.append(empty);for(const o of f.options??[]){const option=element('option',`${o.id}. ${o.zh} · ${o.py} · ${o.vi}`);option.value=o.id;input.append(option);}input.addEventListener('change',()=>change(f.id,input.value),{signal:cardSignal});}
      else{if(input instanceof HTMLInputElement)input.type='text';else input.rows=3;input.maxLength=5000;input.autocomplete='off';input.addEventListener('compositionstart',()=>{composing=true;composingFields.add(a.id);session.setComposing(a.id,true);epoch.next();feedback.replaceChildren();},{signal:cardSignal});input.addEventListener('compositionend',()=>{composing=false;composingFields.delete(a.id);session.setComposing(a.id,false);change(f.id,input.value);},{signal:cardSignal});input.addEventListener('input',()=>change(f.id,input.value),{signal:cardSignal});}
      input.required=f.required!==false;input.value=values[f.id]??'';if(f.required===false)row.append(element('small',copy('选填','Không bắt buộc')));row.append(input);return row;
    }
    const inTable=a.table?tableFieldIds(a.table):new Set<string>();if(a.table){card.dataset.hasTable='';fields.append(sourceActivityTable(a.table,a.title,id=>field(a.fields.find(f=>f.id===id)!)));}for(const f of a.fields)if(!inTable.has(f.id))fields.append(field(f));
    const sourceNote=()=>element('small',copy(`教材第${a.source.printedPage}页 · PDF第${a.source.pdfPage}页 · ${a.version}`,`SGK trang ${a.source.printedPage} · PDF trang ${a.source.pdfPage} · ${a.version}`));
    if(!a.fields.length){card.dataset.readonly='';card.append(fields,sourceNote());return card;}
    const history=element('details');history.className='source-history';
    function drawHistory(){history.replaceChildren();const entries=store.snapshot().data.records[key]?.history??[];history.append(element('summary',copy(`本版本记录（${entries.length}次）`,`Bản ghi phiên bản này (${entries.length} lần)`)));for(const entry of entries){const p=element('p',new Date(entry.at).toISOString()+' · '+Object.entries(entry.values).map(([id,value])=>id+': '+value).join(' / '));history.append(p);}}
    function reveal(){feedback.replaceChildren();for(const f of a.fields){if(f.required===false&&!values[f.id]?.trim())continue;if(f.assessment==='answer-key'){const answer=f.options?.find(o=>o.id===f.answer);feedback.append(element('p',copy(values[f.id]===f.answer?'本空正确':'请再看本空',values[f.id]===f.answer?'Chỗ này đúng':'Hãy xem lại chỗ này')),element('p',copy(`参考答案：${answer?.id}. ${answer?.zh}`,`Đáp án: ${answer?.id}. ${answer?.zh}`)),element('small',copy(`配套客观题答案 · PDF第${f.answerSource?.pdfPage}页`,`Đáp án kèm sách · PDF trang ${f.answerSource?.pdfPage}`)));}else {feedback.append(element('p',copy('已保存开放表达，不计分。','Đã lưu câu trả lời mở, không chấm điểm.')));if(f.reference)feedback.append(element('p',copy('一种参考表达（不是唯一答案）','Một cách diễn đạt tham khảo (không phải đáp án duy nhất)')),element('p',f.reference));}if(f.feedbackNote)feedback.append(element('p',f.feedbackNote));}drawHistory();}
    const submit=button(copy('保存并查看反馈','Lưu và xem phản hồi'),()=>{if(busy)return;const request=epoch.next();feedback.replaceChildren();if(composing){feedback.append(element('p',copy('请先完成输入法组词','Hãy hoàn tất nhập bằng bộ gõ')));return;}if(incompleteSourceFields(a,values)){feedback.append(element('p',copy('请先完成本组输入','Hãy điền hết nhóm này trước')));return;}busy=true;submit.disabled=true;const submitted={...values};void session.submit(a,submitted,cardSignal).then(result=>{if(cardSignal.aborted)return;busy=false;submit.disabled=false;const snapshot=store.snapshot(),row=snapshot.data.records[key];if(result.ok&&snapshot.status==='saved'&&epoch.current(request)&&row?.history.some(h=>h.id===result.submissionId)&&a.fields.every(f=>row.draft.values[f.id]===submitted[f.id]))reveal();else if(epoch.current(request))feedback.append(element('p',copy('尚未确认保存，参考答案仍隐藏。请重试或导出草稿。','Chưa xác nhận lưu; đáp án vẫn ẩn. Hãy thử lại hoặc xuất bản nháp.')));}).catch(()=>{if(!cardSignal.aborted){busy=false;submit.disabled=false;showError();}});},cardSignal);
    card.append(fields,submit,feedback,history,sourceNote());drawHistory();const last=old?.history.at(-1);if(store.snapshot().status==='saved'&&last&&a.fields.every(f=>last.values[f.id]===values[f.id]))reveal();return card;
  }
  if(lesson.bonus){const item=lesson.bonus,bonus=element('aside');bonus.className='source-bonus';bonus.append(element('h3',item.title),element('p',copy(`教材彩蛋${item.printedResourceId} · 第${item.printedPage}页。原视频尚未取得，当前没有可播放内容。`,`Nội dung bổ sung ${item.printedResourceId} · Trang ${item.printedPage}. Chưa có video gốc; hiện không có nội dung để phát.`)));section.append(bonus);}
  const archives=element('details');archives.className='source-archive';section.append(archives);
  function update(){const s=store.snapshot(),recovery=store.pendingRecovery();status.dataset.state=s.status;status.dataset.recovery=recovery;setBilingual(status,recovery==='none'?states[s.status]:copy('上次的数据操作还未确认完成，已暂停修改记录。请先导出备份，不要清除浏览器数据。','Thao tác dữ liệu trước đó chưa được xác nhận hoàn tất nên đã tạm dừng thay đổi. Hãy xuất bản sao lưu trước và không xóa dữ liệu trình duyệt.'));retry.disabled=!s.canWrite||s.status==='saving'||recovery!=='none';original.hidden=s.status!=='corrupt';restore.disabled=!s.hasRecovery;archives.replaceChildren(element('summary',copy('旧版本记录（只读）','Bản ghi phiên bản cũ (chỉ đọc)')));const older=archivedSourceRecords(s.data,lessonId,lesson.activities);archives.hidden=!older.length;for(const row of older){const box=element('article');box.append(element('h4',row.context.title),element('p',row.context.instruction),element('p',row.context.prompt),element('p',row.version),element('small',copy(`原版本教材第${row.context.source.printedPage}页 · PDF第${row.context.source.pdfPage}页`,`Phiên bản gốc: SGK trang ${row.context.source.printedPage} · PDF trang ${row.context.source.pdfPage}`)));if(row.context.table)box.append(sourceActivityTable(row.context.table,row.context.title,id=>{const field=row.context.fields.find(f=>f.id===id)!,cell=element('div');cell.append(element('p',field.label),element('p',row.draft.values[id]??''));return cell;}));for(const f of row.context.fields){box.append(element('p',f.label));if(f.pinyin)box.append(element('p',f.pinyin));if(f.options)box.append(element('p',f.options.map(o=>`${o.id}. ${o.zh} · ${o.py} · ${o.vi}`).join(' / ')));}for(const h of row.history)box.append(element('p',new Date(h.at).toISOString()+' · '+Object.values(h.values).join(' / ')));box.append(element('p',copy('该版本草稿','Bản nháp phiên bản này')),element('p',Object.values(row.draft.values).join(' / ')));archives.append(box);}}
  const unsubscribe=store.subscribe(update);host.append(section);draw();update();
  let closed=false;const close=()=>{if(closed)return;closed=true;for(const id of composingFields)session.setComposing(id,false);composingFields.clear();fileEpoch++;clearPreview();cardLifetime.abort();unsubscribe();if(store.snapshot().hasUnsavedChanges)void session.flush();};signal.addEventListener('abort',close,{once:true});if(signal.aborted)close();
  return {dispose(){close();signal.removeEventListener('abort',close);section.remove();}};
}
