import {existsSync,readFileSync,mkdirSync,copyFileSync,writeFileSync,readdirSync,lstatSync} from 'node:fs';import {resolve,join,relative} from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const root=resolve(import.meta.dirname,'..'),args=process.argv.slice(2),option=(n,d)=>{const i=args.indexOf(n);return i<0?d:args[i+1]},source=option('--source',execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim()),input=resolve(root,option('--input','dist')),output=resolve(root,option('--output','unified-frozen')),release=args.includes('--release');
const dirty=!!execFileSync('git',['status','--porcelain','--','src','content','public','tools','../hsk1-app/src'],{cwd:root,encoding:'utf8'}).trim();if(dirty&&(release||!args.includes('--allow-dirty-checkpoint')))throw Error('Commit the tested runtime before freezing; dirty checkpoints require explicit diagnostic flag');
if(!/^[0-9a-f]{40}$/.test(source))throw Error('Invalid source commit');if(existsSync(output))throw Error('Frozen output must be new; never overwrite a tested artifact');
if(release){const gate=JSON.parse(readFileSync(resolve(root,'docs/unified-final-acceptance.json'),'utf8'));if(gate.sourceCommit!==source||gate.lessons!==48||gate.textbookLessons!==33||gate.pages!==422||!Array.isArray(gate.stages)||gate.stages.length!==16||gate.stages.some(s=>s.status!=='passed')||!gate.browsers?.chromium||!gate.browsers?.webkit)throw Error('All sixteen acceptance stages are required before a production package')}
function files(dir){const out=[];function walk(folder){for(const n of readdirSync(folder).sort()){const p=join(folder,n),s=lstatSync(p);if(s.isSymbolicLink())throw Error('Symlinks cannot enter a release');if(s.isDirectory())walk(p);else if(s.isFile())out.push(relative(dir,p));}}walk(dir);return out}
const allowed=p=>p==='index.html'||p==='content-manifest.json'||p==='course-assets/HANZI-PROVENANCE.json'||/^assets\/[\w.-]+\.(js|css|json)$/.test(p)||/^illustrations\/[\w.-]+\.svg$/.test(p)||/^course-assets\/(?:hsk[23]\/audio\/\d+-[1-8]\.mp3|audio\/\d+-[1-7]\.mp3|hanzi\/[^/]+\.json|[A-Z-]+LICENSE\.txt|HANZI-[A-Z-]+\.txt)$/.test(p);
const names=files(input);for(const p of names)if(!allowed(p))throw Error('Unapproved public input '+p);for(const p of names)if(/\.(pdf|zip|rar)$/i.test(p))throw Error('Source books cannot enter public assets');
const hash=b=>createHash('sha256').update(b).digest('hex'),manifest=JSON.parse(readFileSync(join(input,'content-manifest.json'),'utf8'));if(manifest.lessons.length!==33)throw Error('Course 2/3 content missing');
for(const t of manifest.audio){const bytes=readFileSync(join(input,t.file));if(bytes.length!==t.bytes||hash(bytes)!==t.sha256)throw Error('Original HSK2/3 audio identity mismatch '+t.file)}
const hsk1=JSON.parse(readFileSync(resolve(root,'../hsk1-app/content/media-references.json'),'utf8'));for(const t of hsk1.originalTracks){const bytes=readFileSync(join(input,'course-assets/audio',t.id+'.mp3'));if(bytes.length!==t.bytes||hash(bytes)!==t.sha256)throw Error('Protected HSK1 audio mismatch '+t.id)}
const html=readFileSync(join(input,'index.html'),'utf8');if(!html.includes('src="./assets/'))throw Error('Unrecognized build entry');
function entry(level,base,view='courses'){return html.replace('<meta name="hsk-level" content="2">',`<meta name="hsk-level" content="${level}"><meta name="asset-base" content="${base}"><meta name="hsk-entry-view" content="${view}">`).replaceAll('"./assets/',`"${base}assets/`)}
const write=(path,data)=>{mkdirSync(join(output,path,'..'),{recursive:true});writeFileSync(join(output,path),data)};
for(const path of names.filter(n=>n!=='index.html')){mkdirSync(join(output,'course-engine',path,'..'),{recursive:true});copyFileSync(join(input,path),join(output,'course-engine',path))}
write('index.html',entry(1,'./course-engine/','portal'));
for(const level of [1,2,3]){write(`new-hsk${level}/hsk${level}/index.html`,entry(level,'../../course-engine/'));write(`new-hsk${level}/index.html`,entry(level,'../course-engine/'));}
for(const file of ['lesson.html','learning.html','lesson9-pilot.html'])write(`new-hsk1/hsk1/${file}`,entry(1,'../../course-engine/'));
const records=files(output).map(path=>{const bytes=readFileSync(join(output,path));return {path,bytes:bytes.length,sha256:hash(bytes)}});
write('course-engine/unified-release-manifest.json',JSON.stringify({schemaVersion:1,mode:release?'release':'checkpoint',sourceCommit:source,protectedProduction:'2da6a5c80c62d4ff5bdfa72a5bdb929b2b1ff3d4',app:'hsk123-unified',sourceDirty:dirty,lessons:48,editions:{hsk1:'existing-hsk1',hsk2:'2026.1',hsk3:'2026.1'},originalAudioTracks:manifest.audio.length+hsk1.originalTracks.length,files:records},null,2)+'\n');console.log(JSON.stringify({source,mode:release?'release':'checkpoint',output,files:records.length,lessons:48},null,2));
