"""Record this reviewer's already completed per-change reading decisions.
This writes only independent QA evidence. It is not a runtime approval generator.
"""
import hashlib,json
from pathlib import Path
here=Path(__file__).resolve().parent
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
rows=json.loads((here/'change-decisions.initial.json').read_text())
assert len(rows)==135
selected={49:'清楚 / động từ → hiểu rõ',55:'要求 / động từ → đòi hỏi',56:'差 / tính từ → kém',64:'努力 / tính từ → chăm chỉ',65:'努力 / động từ → nỗ lực',119:'清楚 / động từ → hiểu rõ',125:'要求 / động từ → đòi hỏi',126:'差 / tính từ → kém',134:'努力 / tính từ → chăm chỉ',135:'努力 / động từ → nỗ lực'}
inline={29,91};short_grammar={67,71};combined_headings={73,75,77,108}
activity_titles={86,88,90,93,95,97,99,101};read_notes={89,94,98};picture_notes={105,106,107};range_titles={103,104}
for r in rows:
 n=r['ordinal'];r['manualFullOldAndNewValueRead']=True;r['manualSourceAndChineseOwnerReviewCompleted']=True
 if r['kind']=='directOfficial':
  reason='Full proposed value equals the full accepted printed source occurrence. Exact original field and Chinese owner match were independently checked; no editorial tail is discarded or claimed as an official fragment.'
  if '/lines/' in r['field']:
   reason+=' The actual original Chinese scene line and its role were compared with the appendix translation; pronouns refer to the same speaker/addressee. Role labels remain original metadata, separate from Vietnamese text.'
  if n in (41,42,43):reason+=' The letter has no printed speaker; its salutation/body paragraphs are retained as letter text, without manufacturing a Vietnamese speaker.'
  if n==27:reason='The actual owner Chinese is ……; 旁白 is only the existing speaker label. The source is printed ... without a speaker. Replacing the existing punctuation leaf with ... is a punctuation variant, not a new utterance; Chinese/speaker metadata remain untouched.'
  if n==68:reason+=' Owner ／ and source / are slash typography variants in the same Chinese grammar title.'
  if n==72:reason+=' The exact lesson-title translation is reused for the same Chinese teacher-to-student example. The source has no final period; that source punctuation remains unchanged. Student em is the addressee and teacher cô refers to the speaker.'
  if n==110:reason+=' The owner joins two Chinese clauses with a comma, while the accepted source separates them by a period. Both express the same complete rule; the full Vietnamese source paragraph, including the structure and Ví dụ:, is retained.'
  if n==15:reason+=' HELD: accepted source fragments physically span PDF201/202, printed189/190. The new wording is complete, but the draft cites only PDF201/printed189; this incomplete anchor is not accepted.'
 elif n in selected:reason='Exact contiguous, sense-specific excerpt: '+selected[n]+'. The source row prints multiple POS/glosses together; unchanged local/canonical POS and stable sense identity determine the selected meaning. This is explicitly terminologyDerived, never a whole-entry verbatim claim; no new glue or changed sense identity is present.'
 elif n in inline:reason='Only the source-printed 关于 gloss expands from về to về, liên quan đến. The surrounding editorial question, printed-Chinese/pinyin annotation and quote/parenthesis punctuation remain byte-for-byte. The full consumer is derived; the Chinese-only question is not represented as a printed Vietnamese question.'
 elif n in short_grammar:reason='The target is a concise existing grammar explanation. Its entire new wording is an exact initial contiguous part of the source paragraph, stopping at a complete sentence before the printed structure/Ví dụ:. The separately stored full-source explanation retains the complete rule and structure. The concise field is correctly derived, not directOfficial, and no unsupported words are added.'
 elif n==69:reason='The four actual source rule paragraphs for 在……上/中/下 are kept complete, in original conceptual order. The only new uncited glue is three newline characters between paragraphs. Existing Chinese structures, examples and practice fields remain intact. No sentence fragment is presented as a full direct source.'
 elif n in combined_headings:reason='Two complete source headings are joined with the existing title separator : . The full composite is derived; both concepts correspond to the exact Chinese owner, without an invented source heading. Colon/space is UI glue, not a publisher quotation.'
 elif n in activity_titles:reason='Only the exact printed Bài khoá N heading replaces Bài khóa N. The existing : bài tập sau khi nghe / : bài tập sau khi đọc suffix remains byte-for-byte and agrees with the actual listening/reading activity. The full title is derived, not a printed full textbook title.'
 elif n in read_notes:reason='The full printed Phân vai đọc to đoạn hội thoại... instruction replaces its old prefix. The complete existing reference-answer/self-check/non-unique-scoring suffix remains byte-for-byte. The source instruction and editorial tail are separate evidence scopes.'
 elif n==102:reason='Both complete source instructions—Đọc to bài khoá. and the country-system comparison—are joined with one separating space. The existing two-record-field, chosen-country, privacy and non-unique-answer/self-check tail remains byte-for-byte. No editorial text is claimed as verbatim textbook wording.'
 elif n in range_titles:reason='The exact contiguous official lexical prefix is selected up to—but excluding—the terminal period. The existing (1–5) / (6–10) range is preserved byte-for-byte and matches the real split exercise. The root override is independently accepted as a derived title construction; no official combined title is invented.'
 elif n in picture_notes:reason='The complete source picture-description instruction replaces its old prefix. The entire existing Chinese-only picture-dialogue translation and reference-answer/self-check/non-unique-scoring tail remains byte-for-byte and coherent with the actual Chinese owner. Only the source prefix is certified; the old editorial dialogue is not turned into a publisher translation or newly retranslated.'
 elif n==109:reason='The complete printed four-person discussion/share/vote/use-language instruction replaces its old prefix. The existing record-field/editorial/privacy/no-unique-answer/no-automatic-scoring suffix remains byte-for-byte and fits the activity. This is derived with a full cited prefix, not a full publisher quotation.'
 else:raise AssertionError(('unreviewed derived ordinal',n))
 r['manualRationale']=reason
 r['uncitedRangeManualDecision']='All ranges inspected in full; existing ranges are unchanged editorial/layout material. Only ordinal69 adds three newline separators.' if r['uncitedRanges'] else 'No uncited target text.'
(here/'change-decisions.initial.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
review=json.loads((here/'initial-structural-review.json').read_text())
assert review['proposalSHA256']=='fb744e2808f60f28d43830179ec2f164f66e293789628710bbe90ee153e0b7f1'
review.update(manualFullChangeCoverage=135,manualDerivedCoverage=37,manualRemainingDerivedExcludingTwoRangeTitles=35,curatedOverrideCoverage=3,sourcePageScopeHeldCount=1,sourcePageScopeHeldOrdinal=15,fullTrustedAcceptance=False,reasonFullTrustedAcceptanceFalse='One initial incomplete cross-page source anchor is held. Final root-author aggregate and canonical hash have not been reviewed yet.',decisionFileSHA256=sha(here/'change-decisions.initial.json'))
repo=here.parents[4]
extra=[{'file':'course-app/docs/resume-20261004/qa-official-vi/hsk3-l10-source/page-evidence/'+name,'sha256':sha(repo/'course-app/docs/resume-20261004/qa-official-vi/hsk3-l10-source/page-evidence'/name),'actuallyVisuallyViewedByThisReviewer':True}for name in ['independent-p103-grammar-detail.png','independent-p104-vocab-detail.png']]
review['additionalDetailVisualEvidence']=extra
(here/'initial-review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n')
context=json.loads((here/'input-copy/context-investigation.initial.json').read_text())
contextreview={'schemaVersion':1,'status':'independently-accepted-context-correction-candidate-awaiting-final-aggregate-hash-review','reviewer':'qa_hsk1_05_08','author':'root','contextInvestigationInputSHA256':sha(here/'input-copy/context-investigation.initial.json'),'sourcePDFSHA256':context['officialPDFSHA256'],'sourceRecordId':context['printedSource']['sourceId'],'candidateOrdinalOutsideInitialManifest':136,'target':context['target'],'classification':'official-book-erratum','publisherIssuedCorrection':False,'originalPrintedVietnamesePreserved':context['printedSource']['vi'],'sourceTranscriptionChanged':False,'independentVisualPages':[102,103,202],'semanticReview':{'sourceContextRead':'PDF102/printed90 actually prints hỏi bài bạn học, placing the classmate after hỏi bài as the apparent recipient.','ChineseContextRead':'在李老师办公室，刘小雪跟同学问问题。 expresses Liu Xiaoxue together with a classmate asking questions in teacher Li’s office.','corroboratingDialogue':'The previous source dialogue explicitly proposes both students go together to ask cô Lý. The next Chinese dialogue begins 我们想问问您, and its appendix says chúng em ... hỏi cô. Teacher Li answers.','proposedCorrectionRead':'Lưu Tiểu Tuyết cùng bạn học hỏi bài ở trong phòng làm việc của cô Lý. places cùng bạn học before the action to identify joint askers, preserves the full official name and office description, and does not falsely claim publisher-issued errata.','decision':'accept explicit editorial correction to printed source wording, retaining original source and correction rationale as separate evidence'},'actualBaselineExpectedGuard':'The real /texts/2/context/vi equals the candidate expectedEffectiveValue in the immutable raw baseline, and its actual Chinese owner equals the printed Chinese anchor.','finalManifestAccepted':False,'trustedRuntimeProofGenerated':False,'productionChanged':False}
(here/'context-candidate-review.json').write_text(json.dumps(contextreview,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'initialReviewSHA256':sha(here/'initial-review.json'),'decisionFileSHA256':sha(here/'change-decisions.initial.json'),'contextReviewSHA256':sha(here/'context-candidate-review.json')},ensure_ascii=False))
