'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../../new-hsk1/hsk1/learning-engine.js');
const kinds=['choice','sort','translation','listening'];
const bank=Array.from({length:15},(_,i)=>({lesson:i+1,...Object.fromEntries(kinds.map(kind=>[kind,Array.from({length:5},(_,j)=>kind==='sort'?{id:`L${i+1}-${kind}-${j+1}`,kind,tokens:['我','明天','在学校','学习'],answers:['我明天在学校学习。','明天我在学校学习。']}:{id:`L${i+1}-${kind}-${j+1}`,kind,options:['你好','再见','谢谢','不客气'],answer:j%4})]))}));
function fill(state,lesson,kind,wrong=0){const g=E.group(state,lesson,kind);bank[lesson-1][kind].forEach((q,i)=>{g.draft[q.id]=q.kind==='sort'?(i<wrong?[3,2,1,0]:[0,1,2,3]):(q.answer+(i<wrong?1:0))%4;});return g;}
function pass(state,lesson,kind,now=1000){fill(state,lesson,kind);return E.submit(state,lesson,kind,bank[lesson-1][kind],now);}
function jsonClone(v){return JSON.parse(JSON.stringify(v));}

test('choice and independent listening open initially, later homework groups stay locked',()=>{const s=E.blank();for(let id=1;id<=15;id++){assert.equal(E.canOpen(s,id,'choice'),true);assert.equal(E.canOpen(s,id,'listening'),true);assert.equal(E.canOpen(s,id,'sort'),false);assert.equal(E.canOpen(s,id,'translation'),false);assert.deepEqual(E.submit(s,id,'sort',bank[id-1].sort),{ok:false,reason:'locked'});}});
test('submitting unanswered items points to them and preserves answers without unlocking',()=>{const s=E.blank(),g=E.group(s,1,'choice'),qs=bank[0].choice;g.draft[qs[0].id]=qs[0].answer;const r=E.submit(s,1,'choice',qs);assert.equal(r.reason,'missing');assert.equal(r.missing.length,4);assert.equal(g.first,null);assert.equal(g.draft[qs[0].id],qs[0].answer);assert.equal(E.canOpen(s,1,'sort'),false);});
test('first result remains 3/5 after all wrong items are corrected and next group unlocks',()=>{const s=E.blank(),qs=bank[0].choice,g=fill(s,1,'choice',2);assert.equal(E.submit(s,1,'choice',qs).correct,3);assert.equal(E.canOpen(s,1,'sort'),false);g.draft[qs[0].id]=qs[0].answer;assert.equal(E.correct(s,1,'choice',qs).remaining.length,1);assert.equal(E.canOpen(s,1,'sort'),false);g.draft[qs[1].id]=qs[1].answer;assert.equal(E.correct(s,1,'choice',qs).completed,true);assert.equal(E.canOpen(s,1,'sort'),true);assert.equal(g.first.correct,3);assert.equal(g.attempt.correct,3);assert.equal(E.canOpen(s,1,'translation'),false);});
test('all-correct submission unlocks the next homework group without a redundant correction click',()=>{const s=E.blank();pass(s,1,'choice');assert.equal(E.canOpen(s,1,'sort'),true);pass(s,1,'sort');assert.equal(E.canOpen(s,1,'translation'),true);});
test('redo never rewrites the first score or relocks completed downstream homework',()=>{const s=E.blank();fill(s,1,'choice',2);E.submit(s,1,'choice',bank[0].choice,1000);fill(s,1,'choice');E.correct(s,1,'choice',bank[0].choice);pass(s,1,'sort');pass(s,1,'translation');E.restart(s,1,'choice');fill(s,1,'choice',5);E.submit(s,1,'choice',bank[0].choice,2000);const g=E.group(s,1,'choice');assert.equal(g.first.correct,3);assert.equal(g.attempt.correct,0);assert.equal(g.history.length,2);assert.equal(E.canOpen(s,1,'translation'),true);});
test('repeat submit cannot inflate attempts or overwrite the first grade',()=>{const s=E.blank();pass(s,1,'choice');fill(s,1,'choice',5);assert.equal(E.submit(s,1,'choice',bank[0].choice).reason,'submitted');assert.equal(E.group(s,1,'choice').history.length,1);});
test('sort accepts alternate natural time position and sentence punctuation',()=>{const q=bank[8].sort[0];assert.equal(E.check(q,[0,1,2,3]),true);assert.equal(E.check(q,[1,0,2,3]),true);assert.equal(E.check(q,[0,3,2,1]),false);});
test('sort tracks duplicate text as separate tokens and rejects missing/repeated token indexes',()=>{const q={kind:'sort',tokens:['我','的','书','和','你','的','书'],answers:['我的书和你的书']};assert.equal(E.check(q,[0,1,2,3,4,5,6]),true);assert.equal(E.check(q,[0,5,6,3,4,1,2]),true);assert.equal(E.isAnswered(q,[0,1,2,3,4,1,2]),false);assert.equal(E.isAnswered(q,[0,1,2]),false);assert.equal(E.isAnswered(q,[0,1,2,3,4,5,9]),false);});
test('choice tracks original option identity independent of shuffled screen position',()=>{const q=bank[0].choice[2];assert.equal(E.check(q,2),true);assert.equal(E.check(q,0),false);assert.equal(E.check(q,'2'),false);assert.equal(E.check(q,-1),false);});
test('each lesson retains its own unlock state while listening remains independent',()=>{const s=E.blank();pass(s,1,'choice');pass(s,8,'listening');assert.equal(E.canOpen(s,1,'sort'),true);assert.equal(E.canOpen(s,8,'sort'),false);assert.equal(E.canOpen(s,2,'sort'),false);});
test('freshly loaded JSON and validated backup retain partial drafts, first scores, corrections and completion',()=>{const s=E.blank();fill(s,1,'choice',1);E.submit(s,1,'choice',bank[0].choice,1000);fill(s,1,'choice');E.correct(s,1,'choice',bank[0].choice);const sort=E.group(s,1,'sort');sort.draft[bank[0].sort[0].id]=[1,0];const imported=E.validateImport(jsonClone(s),bank);assert.equal(E.group(imported,1,'choice').first.correct,4);assert.equal(E.canOpen(imported,1,'sort'),true);assert.deepEqual(E.group(imported,1,'sort').draft[bank[0].sort[0].id],[1,0]);assert.equal(E.canOpen(imported,1,'translation'),false);});
test('backup recomputes answer scores rather than trusting stale numerical scores',()=>{const s=E.blank();pass(s,1,'choice');s.lessons[1].choice.first.correct=0;const r=E.validateImport(s,bank);assert.equal(r.lessons[1].choice.first.correct,5);});
test('backup rejects questions from the wrong lesson and corrupt choice or sort answers',()=>{const s=E.blank();E.group(s,1,'choice').draft[bank[1].choice[0].id]=0;assert.throws(()=>E.validateImport(s,bank));const t=E.blank();E.group(t,1,'choice').draft[bank[0].choice[0].id]=99;assert.throws(()=>E.validateImport(t,bank));const u=E.blank();E.group(u,1,'sort').draft[bank[0].sort[0].id]=[0,0];assert.throws(()=>E.validateImport(u,bank));});
test('lesson result combines 15 homework and five listening questions using first scores',()=>{const s=E.blank();pass(s,1,'choice');pass(s,1,'sort');fill(s,1,'translation',2);E.submit(s,1,'translation',bank[0].translation);fill(s,1,'translation');E.correct(s,1,'translation',bank[0].translation);fill(s,1,'listening',1);E.submit(s,1,'listening',bank[0].listening);assert.deepEqual(E.totals(s,1),{correct:17,answered:20,total:20,completed:3,done:false});fill(s,1,'listening');E.correct(s,1,'listening',bank[0].listening);assert.equal(E.totals(s,1).done,true);assert.equal(E.totals(s,1).correct,17);});
test('wrong answers enter immediate review; right answers have future review dates',()=>{const s=E.blank();fill(s,1,'choice',1);E.submit(s,1,'choice',bank[0].choice,1000);assert.equal(s.questionReviews[bank[0].choice[0].id].dueAt,1000);assert.ok(s.questionReviews[bank[0].choice[1].id].dueAt>1000);assert.equal(s.questionReviews[bank[0].choice[0].id].mistakes,1);});
