'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {serve,launch,login}=require('./browser-support.cjs');const {solveSort,wrongSort}=require('./question-helpers.cjs');
const out=process.env.HSK_TEST_OUTPUT||path.resolve(__dirname,'../../../tmp/browser-test');
const KEY='ran_hsk1_learning_v2';
const readState=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);
async function answer(page,q,wrong=false){const card=page.locator(`[data-testid="question-${q.id}"]`);if(q.kind==='sort'){if(await card.locator('[data-sort-clear]').isEnabled())await card.locator('[data-sort-clear]').click();for(const token of (wrong?wrongSort(q):solveSort(q)))await card.locator(`[data-token="${token}"]`).click();}else await card.locator(`[data-option="${wrong?(q.answer+1)%4:q.answer}"]`).click();}
(async()=>{
 fs.mkdirSync(out,{recursive:true});const server=await serve(),browser=await launch();const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();const errors=[],failed=[],checks=[];
 function observe(p){p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(server.baseURL)&&r.status()>=400)failed.push({status:r.status(),url:r.url().replace(server.baseURL,'')});});}observe(page);
 let backupPath=path.join(out,'test-progress-backup.json');
 try{
  let bank;
  if(process.env.HSK_TEST_RESUME==='1'){
   const previous=JSON.parse(fs.readFileSync(path.join(out,'learning-browser.json')));checks.push(...previous.checks.filter(x=>!x.startsWith('downloaded backup')&&!x.startsWith('invalid backup')));
   await page.goto(server.baseURL+'learning.html?mode=progress',{waitUntil:'domcontentloaded'});await login(page);page.once('dialog',d=>d.accept());await page.locator('#importProgress').setInputFiles(backupPath);await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).lessons[15]?.listening?.completed===true,KEY);bank=await page.evaluate(()=>window.HSK1_NEW_BANK);
  }else{
  await page.goto(server.baseURL+'learning.html?mode=homework&lesson=1&stage=translation',{waitUntil:'domcontentloaded'});await login(page);await page.locator('[data-testid="locked-message"]').waitFor();checks.push('direct URL cannot open locked translation group');
  bank=await page.evaluate(()=>window.HSK1_NEW_BANK);assert.equal(bank.length,15);
  for(let lesson=1;lesson<=15;lesson++){
   const L=bank.find(x=>x.lesson===lesson);
   for(const kind of ['choice','sort','translation','listening']){
    const mode=kind==='listening'?'listening':'homework';await page.goto(server.baseURL+`learning.html?mode=${mode}&lesson=${lesson}&stage=${kind}`,{waitUntil:'domcontentloaded'});await login(page);const qs=L[kind];assert.equal(await page.locator('[data-qid]').count(),5);
    if(lesson===1&&kind==='choice'){await page.locator('[data-testid="submit-group"]').click();assert.match(await page.locator('[data-testid="group-notice"]').innerText(),/5 câu/);}
    if(kind==='listening'){for(const q of qs)assert.ok(!(await page.locator(`[data-qid="${q.id}"]`).innerText()).includes(q.transcript),'Listening transcript must stay hidden before submission');}
    for(let i=0;i<qs.length;i++)await answer(page,qs[i],i===0);
    if(lesson===1&&kind==='choice'){const before=await readState(page);await page.reload({waitUntil:'domcontentloaded'});await login(page);const after=await readState(page);assert.deepEqual(after.lessons[1].choice.draft,before.lessons[1].choice.draft);assert.deepEqual(after.lessons[1].choice.orders,before.lessons[1].choice.orders);checks.push('refresh restores drafts and shuffled option order');}
    await page.locator('[data-testid="submit-group"]').click();await page.locator('[data-testid="score-summary"]').waitFor();assert.match(await page.locator('[data-testid="current-score"]').innerText(),/^4/);assert.equal(await page.locator('.la-feedback').count(),5);
    let s=await readState(page);assert.equal(s.lessons[lesson][kind].first.correct,4);assert.equal(s.lessons[lesson][kind].completed,false);
    if(kind==='choice')assert.equal(await page.locator('[data-stage="sort"]').isDisabled(),true);if(kind==='sort')assert.equal(await page.locator('[data-stage="translation"]').isDisabled(),true);
    await page.locator('[data-testid="correct-group"]').click();assert.equal((await readState(page)).lessons[lesson][kind].completed,false);
    await answer(page,qs[0]);await page.locator('[data-testid="correct-group"]').click();await page.locator('[data-testid="group-complete"]').waitFor();s=await readState(page);assert.equal(s.lessons[lesson][kind].first.correct,4);assert.equal(s.lessons[lesson][kind].attempt.correct,4);assert.equal(s.lessons[lesson][kind].completed,true);
    if(kind==='choice')assert.equal(await page.locator('[data-stage="sort"]').isEnabled(),true);if(kind==='sort')assert.equal(await page.locator('[data-stage="translation"]').isEnabled(),true);
   }
   checks.push(`lesson ${lesson}: all 20 questions, 4 score summaries, explanations, correction gates and first scores verified`);console.log(`PASS lesson ${lesson}/15`);
  }
  await page.goto(server.baseURL+'learning.html?mode=homework&lesson=15&stage=choice',{waitUntil:'domcontentloaded'});await page.locator('[data-testid="retry-group"]').click();for(const q of bank[14].choice)await answer(page,q);await page.locator('[data-testid="submit-group"]').click();assert.match(await page.locator('[data-testid="current-score"]').innerText(),/^5/);assert.match(await page.locator('[data-testid="first-score"]').innerText(),/4\/5/);assert.equal(await page.locator('[data-stage="translation"]').isEnabled(),true);checks.push('redo scores 5/5 while first remains 4/5 and downstream groups stay open');
  }
  await page.goto(server.baseURL+'learning.html?mode=progress',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('[data-testid="progress-table"] tbody tr').count(),15);assert.match(await page.locator('.la-stats').innerText(),/300\/300/);assert.match(await page.locator('.la-stats').innerText(),/240\/300/);await page.screenshot({path:path.join(out,'progress-desktop.png'),fullPage:true});
  const downloadPromise=page.waitForEvent('download');await page.locator('#exportProgress').click();const download=await downloadPromise;await download.saveAs(backupPath);const backup=JSON.parse(fs.readFileSync(backupPath));assert.equal(Object.keys(backup.lessons).length,15);
  const restore=await browser.newContext({viewport:{width:390,height:844}}),rp=await restore.newPage();observe(rp);await rp.goto(server.baseURL+'learning.html?mode=progress',{waitUntil:'domcontentloaded'});await login(rp);rp.once('dialog',d=>d.accept());await rp.locator('#importProgress').setInputFiles(backupPath);await rp.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).lessons[15]?.listening?.completed===true,KEY);assert.deepEqual((await readState(rp)).lessons[1].choice.first,backup.lessons[1].choice.first);checks.push('downloaded backup restores all 15 lessons into fresh browser context using normal login');
  await rp.locator('#importProgress').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{broken')});assert.match(await rp.locator('#importStatus').innerText(),/Không thể mở/);assert.equal(Object.keys((await readState(rp)).lessons).length,15);checks.push('invalid backup reports error without losing current progress');
  for(const mode of ['homework','listening','vocab','review','progress']){await rp.goto(server.baseURL+`learning.html?mode=${mode}&lesson=9&stage=sort`,{waitUntil:'domcontentloaded'});await rp.locator('#learningMain h1').waitFor();assert.equal(await rp.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true,`no horizontal page overflow: ${mode}`);await rp.screenshot({path:path.join(out,`${mode}-mobile.png`),fullPage:false});}
  checks.push('all five modules render at 390px without horizontal page overflow');
  await page.goto(server.baseURL+'learning.html?mode=review',{waitUntil:'domcontentloaded'});await page.locator('[data-review-id]').first().click();const reviewQid=await page.locator('[data-qid]').getAttribute('data-qid');const reviewQ=bank.flatMap(L=>['choice','sort','translation','listening'].flatMap(k=>L[k])).find(q=>q.id===reviewQid);await answer(page,reviewQ);await page.locator('#reviewCheck').click();assert.equal(await page.locator('.la-feedback.good').count(),1);assert.equal((await readState(page)).lessons[reviewQ.lesson][reviewQ.kind].first.correct,4);checks.push('review records successful retrieval without changing first homework grade');
  await page.goto(server.baseURL+'learning.html?mode=review',{waitUntil:'domcontentloaded'});await page.locator('[data-review-id]').first().click();const wrongReviewId=await page.locator('[data-qid]').getAttribute('data-qid');const wrongReview=bank.flatMap(L=>['choice','sort','translation','listening'].flatMap(k=>L[k])).find(q=>q.id===wrongReviewId);await answer(page,wrongReview,true);await page.locator('#reviewCheck').click();assert.equal(await page.locator('.la-feedback.bad').count(),1);assert.ok(!(await page.locator('.la-feedback h3').innerText()).includes('Đã sửa đúng'));assert.equal((await readState(page)).lessons[wrongReview.lesson][wrongReview.kind].first.correct,4);checks.push('wrong review answer stays wrong in feedback and does not change first grade');
  await page.goto(server.baseURL+'learning.html?mode=listening&lesson=1',{waitUntil:'domcontentloaded'});await page.locator('#openListenMix').click();await page.locator('input[name="listenLesson"][value="2"]').check();await page.locator('#startListenMix').click();const mixedQid=await page.locator('[data-qid]').getAttribute('data-qid');const mixedQ=bank.flatMap(L=>L.listening).find(q=>q.id===mixedQid);await answer(page,mixedQ,true);await page.locator('#mixCheck').click();assert.equal(await page.locator('.la-feedback.bad').count(),1);assert.ok(!(await page.locator('.la-feedback h3').innerText()).includes('Đã sửa đúng'));assert.equal((await readState(page)).lessons[mixedQ.lesson].listening.first.correct,4);checks.push('mixed listening wrong answer stays wrong and preserves first listening grade');
  await page.goto(server.baseURL+'learning.html?mode=vocab',{waitUntil:'domcontentloaded'});await page.locator('[data-lv-action="none"]').click();await page.locator('[data-testid="vocab-lesson-1"]').check();await page.locator('[data-testid="vocab-lesson-3"]').check();await page.locator('[data-testid="vocab-lesson-5"]').check();await page.locator('[data-testid="vocab-start"]').click();const position=await page.locator('[data-testid="vocab-position"]').innerText();assert.equal(await page.locator('[data-testid="vocab-known"]').isDisabled(),true);await page.locator('[data-testid="vocab-reveal"]').click();await page.locator('[data-testid="vocab-known"]').click();const nextPosition=await page.locator('[data-testid="vocab-position"]').innerText();assert.notEqual(nextPosition,position);await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('[data-testid="vocab-position"]').innerText(),nextPosition);checks.push('mixed 1/3/5 vocabulary integrates with persistent self-rating state');
  await page.locator('[data-testid="vocab-audio"]').click();await page.waitForFunction(()=>document.querySelector('#playerStatus').textContent.includes('Đang phát'),null,{timeout:12000});await page.locator('#playerStop').click();checks.push('mixed vocabulary plays through the real original-audio player');
  await page.screenshot({path:path.join(out,'vocab-desktop.png'),fullPage:false});
  const vocabState=await readState(page);await page.goto(server.baseURL+'learning.html?mode=progress',{waitUntil:'domcontentloaded'});const vocabDownloadPromise=page.waitForEvent('download');await page.locator('#exportProgress').click();await (await vocabDownloadPromise).saveAs(backupPath);await rp.goto(server.baseURL+'learning.html?mode=progress',{waitUntil:'domcontentloaded'});rp.once('dialog',d=>d.accept());await rp.locator('#importProgress').setInputFiles(backupPath);await rp.waitForFunction(key=>Object.keys(JSON.parse(localStorage.getItem(key)).words).length>0,KEY);assert.deepEqual((await readState(rp)).words,vocabState.words);assert.deepEqual((await readState(rp)).preferences.vocab.session,vocabState.preferences.vocab.session);checks.push('backup restores vocabulary self-ratings and active mixed-review queue');
  await restore.close();
 }catch(error){errors.push(error.stack);throw error;}finally{await browser.close();await server.close();const report={browser:'Chromium 153.0.8010.0',checks,errors,failed};fs.writeFileSync(path.join(out,'learning-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
 if(errors.length||failed.length)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exit(1);});
