'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');const {serve,login}=require('./browser-support.cjs');
const out=process.env.HSK_TEST_OUTPUT||path.resolve(__dirname,'../../../tmp/live-smoke');
(async()=>{
 fs.mkdirSync(out,{recursive:true});const local=process.env.HSK_TEST_BASE_URL?null:await serve();const baseURL=process.env.HSK_TEST_BASE_URL||local.baseURL;
 const options={headless:true,args:['--no-sandbox']};if(process.env.HSK_BROWSER_PATH)options.executablePath=process.env.HSK_BROWSER_PATH;
 if(process.env.HSK_TEST_PROXY){const proxy=new URL(process.env.HSK_TEST_PROXY);options.proxy={server:proxy.origin};if(proxy.username)options.proxy.username=decodeURIComponent(proxy.username);if(proxy.password)options.proxy.password=decodeURIComponent(proxy.password);}
 const browser=await chromium.launch(options),context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(()=>{const OriginalAudio=window.Audio;window.__testAudioInstances=[];window.Audio=function(...args){const a=new OriginalAudio(...args);window.__testAudioInstances.push(a);return a;};window.Audio.prototype=OriginalAudio.prototype;});
 const page=await context.newPage(),checks=[],errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(baseURL)&&r.status()>=400)failed.push({url:r.url(),status:r.status()});});
 try{
  await page.goto(new URL('index.html',baseURL).href,{waitUntil:'domcontentloaded',timeout:45000});await login(page);await page.locator('#learningModuleLinks').waitFor();assert.equal(await page.locator('#lessonGrid .lesson-card').count(),15);assert.equal(await page.locator('#learningModuleLinks a').count(),5);checks.push('published homepage renders 15 lessons and all five new module links');
  await page.locator('#learningContinue').click();await page.waitForURL('**/learning.html?**');await page.locator('[data-qid]').first().waitFor();const bank=await page.evaluate(()=>window.HSK1_NEW_BANK);assert.equal(bank.length,15);assert.equal(bank.reduce((n,L)=>n+['choice','sort','translation','listening'].reduce((m,k)=>m+L[k].length,0),0),300);assert.equal(await page.locator('[data-stage="sort"]').isDisabled(),true);
  for(let i=0;i<5;i++){const q=bank[0].choice[i];await page.locator(`[data-qid="${q.id}"] [data-option="${i===0?(q.answer+1)%4:q.answer}"]`).click();}await page.locator('[data-testid="submit-group"]').click();assert.match(await page.locator('[data-testid="current-score"]').innerText(),/^4/);assert.equal(await page.locator('[data-stage="sort"]').isDisabled(),true);const first=bank[0].choice[0];await page.locator(`[data-qid="${first.id}"] [data-option="${first.answer}"]`).click();await page.locator('[data-testid="correct-group"]').click();assert.equal(await page.locator('[data-stage="sort"]').isEnabled(),true);assert.match(await page.locator('[data-testid="first-score"]').innerText(),/4\/5/);checks.push('live 300-question bank loaded; normal submission and correction unlock sort while preserving first 4/5');await page.screenshot({path:path.join(out,'live-homework-desktop.png'),fullPage:false});
  await page.goto(new URL('learning.html?mode=listening&lesson=1',baseURL).href,{waitUntil:'domcontentloaded'});await page.locator('#listeningRate').selectOption('0.65');const q=bank[0].listening[0];assert.ok(!(await page.locator(`[data-qid="${q.id}"]`).innerText()).includes(q.transcript));await page.locator(`[data-play="${q.id}"]`).click();await page.waitForFunction(start=>{const a=window.__testAudioInstances[0];return a&&!a.paused&&a.currentTime>start+.04;},q.audio.start,{timeout:20000});assert.equal(await page.evaluate(()=>window.__testAudioInstances[0].playbackRate),.65);await page.waitForFunction(end=>{const a=window.__testAudioInstances[0];return a.paused&&Math.abs(a.currentTime-end)<.12;},q.audio.end,{timeout:20000});checks.push('published original MP3 actually plays at 0.65× and stops at the mapped segment boundary');
  await page.goto(new URL('learning.html?mode=vocab',baseURL).href,{waitUntil:'domcontentloaded'});await page.locator('[data-lv-action="none"]').click();for(const id of [1,3,5])await page.locator(`[data-testid="vocab-lesson-${id}"]`).check();await page.locator('[data-testid="vocab-start"]').click();assert.equal(await page.locator('[data-testid="vocab-card"]').count(),1);assert.deepEqual(await page.evaluate(()=>window.HSKLearn.state.preferences.vocab.lessons),[1,3,5]);checks.push('published mixed vocabulary combines selected lessons 1, 3 and 5');
  await page.setViewportSize({width:390,height:844});for(const mode of ['homework','listening','vocab','review','progress']){await page.goto(new URL(`learning.html?mode=${mode}&lesson=9`,baseURL).href,{waitUntil:'domcontentloaded'});await page.locator('#learningMain h1').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`mobile overflow: ${mode}`);await page.screenshot({path:path.join(out,`live-${mode}-mobile.png`),fullPage:false});}checks.push('all five published modules render on 390px viewport without page overflow');
 }catch(e){errors.push(e.stack);throw e;}finally{await browser.close();if(local)await local.close();const report={baseURL,isolatedContext:true,normalPasswordEntry:true,passed:errors.length===0&&failed.length===0,checks,errors,failed};fs.writeFileSync(path.join(out,'live-smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
 if(errors.length||failed.length)process.exitCode=1;
})().catch(e=>{console.error(e.message);process.exit(1);});
