import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {observeNativeMedia,attachNativeMedia} from './media-observer.ts';
test.afterEach(async({page},info)=>{await attachNativeMedia(page,info)});
const lesson=JSON.parse(readFileSync(new URL('../../content/hsk2/lesson-01.json',import.meta.url),'utf8'));
async function login(page:any,hash=''){await page.goto('./?level=2'+hash);const gate=page.locator('#class-password');if(await gate.count()){await gate.fill(process.env.HSK_TEST_PASSWORD!);await page.locator('.auth-card button').click()}await expect(page.locator('.auth-gate')).toHaveCount(0);await expect(page.locator('main h1')).toBeVisible()}
test('normal login, real original audio and course content survive history/refresh',async({page})=>{await observeNativeMedia(page);await login(page);await page.locator('.lesson-open').first().click();await expect(page.locator('.text-section')).toHaveCount(4);await page.locator('.text-section .audio-control button').first().click();await expect(page.locator('.player-bar')).toBeVisible();await expect(page.locator('.player-bar')).toHaveAttribute('data-state','playing');await expect(page.locator('.player-bar>span')).toContainText('1-1');await page.waitForTimeout(1500);await expect(page.locator('.player-bar>span')).not.toContainText('0.0s');await page.locator('nav.feature-nav a[data-view=practice]').click();await expect(page.locator('.player-bar')).toBeHidden();await page.goBack();await expect(page.locator('.text-section')).toHaveCount(4);await page.reload();await expect(page.locator('.text-section')).toHaveCount(4)});
for(const width of [320,390,768,1440])test(`mixed cards independent flips, exact fronts, safe paging at ${width}`,async({page})=>{await page.setViewportSize({width,height:900});await login(page,'#view=practice');await page.locator('.practice-setup button').click();const cards=page.locator('.mixed-flip');const count=width<700?1:width<1050?4:6;await expect(cards).toHaveCount(Math.min(count,lesson.vocabulary.length));await expect(cards.first()).toHaveAttribute('data-face','front');await expect(cards.first().locator('.card-pinyin,.card-meaning')).toHaveCount(0);await cards.first().click();await expect(cards.first()).toHaveAttribute('data-face','back');await page.screenshot({path:`test-results/pilot-cards-${width}-back.png`,fullPage:true});if(count>1)await expect(cards.nth(1)).toHaveAttribute('data-face','front');await page.locator('.mixed-pager button').last().click();await expect(cards.first()).toHaveAttribute('data-face','front');await page.locator('.mixed-pager button').first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/pilot-cards-${width}.png`,fullPage:true});await page.locator('.lesson-selection summary').click();await page.screenshot({path:`test-results/pilot-cards-${width}-selection.png`,fullPage:true})});
test('manual Chinese composition and submitted receipts preserve exact text and first/latest',async({page})=>{await login(page,'#view=homework&lesson=1&part=writing');const inputs=page.locator('textarea');for(let i=0;i<5;i++){const input=inputs.nth(i);await input.dispatchEvent('compositionstart');await input.fill(`  我是学生${i}。\n中文第二行  `);await input.dispatchEvent('compositionend')}await page.locator('#assignment button[type=submit]').click();await expect(page.locator('#receipt')).toContainText('等待老师查看');expect(await page.locator('#receipt .submitted-answer').first().textContent()).toBe('  我是学生0。\n中文第二行  ');await page.reload();expect(await page.locator('#receipt .submitted-answer').first().textContent()).toBe('  我是学生0。\n中文第二行  ');const firstId=await page.locator('#receipt').getAttribute('data-latest-id');await page.getByRole('button',{name:'重新作答（保留记录）'}).click();await expect(page.locator('textarea').first()).toHaveValue('');await expect(page.locator('textarea').first()).toBeEnabled();for(let i=0;i<5;i++)await page.locator('textarea').nth(i).fill('新的答案。');await page.locator('#assignment button[type=submit]').click();await expect(page.locator('#receipt')).not.toHaveAttribute('data-latest-id',firstId!);await page.locator('#receipt select').selectOption('first');expect(await page.locator('#receipt .submitted-answer').first().textContent()).toBe('  我是学生0。\n中文第二行  ');await page.locator('#receipt select').selectOption('latest');await expect(page.locator('#receipt .submitted-answer').first()).toHaveText('新的答案。')});
test('homework choice submits a real score while legacy nonempty data is untouched',async({page})=>{await page.addInitScript(()=>{localStorage.setItem('hsk2_ranteacher_progress_v1','{"1":{"score":9}}');localStorage.setItem('hsk3_ranteacher_progress_v1','{"20":{"score":8}}');localStorage.setItem('ran_hsk1_modular_v1','{"sentinel":1}')});await login(page,'#view=homework&lesson=1&part=vocabGrammar');for(const q of lesson.homework.filter((q:any)=>q.part==='vocabGrammar'))await page.locator(`input[name="${q.id}"][value="${q.answer}"]`).check();await page.locator('#assignment button[type=submit]').click();await expect(page.locator('#receipt')).toContainText('10/10');const data=await page.evaluate(()=>({h2:localStorage.getItem('hsk2_ranteacher_progress_v1'),h3:localStorage.getItem('hsk3_ranteacher_progress_v1'),h1:localStorage.getItem('ran_hsk1_modular_v1')}));expect(data).toEqual({h2:'{"1":{"score":9}}',h3:'{"20":{"score":8}}',h1:'{"sentinel":1}'});await page.locator('nav.feature-nav a[data-view=progress]').click();await expect(page.locator('.data-panel').last()).toContainText('"score":9')});
test('manual public payload contains no model answers or solution keys',async()=>{for(const q of lesson.homework.filter((q:any)=>q.part==='writing'))for(const key of ['answer','solution','modelAnswer','explanation','options','tokens'])expect(q).not.toHaveProperty(key)});

for (const number of [1, 2, 3]) test(`pilot lesson ${number} completes every homework part with isolated exact receipts`, async ({page}) => {
 const source=JSON.parse(readFileSync(new URL(`../../content/hsk2/lesson-${String(number).padStart(2,'0')}.json`,import.meta.url),'utf8'));
 await login(page,`#view=homework&lesson=${number}&part=vocabGrammar`);
 for(const part of ['vocabGrammar','ordering','listening','translationChoice','writing']){
  await page.goto(`./?level=2#view=homework&lesson=${number}&part=${part}`);
  const questions=source.homework.filter((q:any)=>q.part===part);
  await expect(page.locator('#assignment fieldset')).toHaveCount(questions.length);
  for(const [index,q] of questions.entries()){
   const field=page.locator(`[data-question-id="${q.id}"]`);
   if(part==='writing')await field.locator('textarea').fill(`独立手写答案 ${number}-${index}\n第二行`);
   else if(part==='ordering')for(const n of q.answer)await field.locator('.ordering-tokens button').nth(n).click();
   else await field.locator(`input[value="${q.answer}"]`).check();
  }
  if(part==='listening')await expect(page.locator('#assignment .audio-control button')).toHaveCount(5);
  await page.locator('#assignment button[type=submit]').click();
  await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');
  await expect(page.locator('#receipt')).toContainText(part==='writing'?'等待老师查看':`${questions.length}/${questions.length}`);
 }
 const data=await page.evaluate(()=>JSON.parse(localStorage.getItem('ran_hsk2_fltrp_2026_v1')!).data);
 const records=Object.entries(data.homework).filter(([key])=>key.startsWith(`hsk2-fltrp-2026:l${String(number).padStart(2,'0')}:`));
 expect(records).toHaveLength(5);
 expect(records.reduce((sum,[,record]:any)=>sum+(record.latest.correct??0),0)).toBe(25);
 const writing=(data.homework[`hsk2-fltrp-2026:l${String(number).padStart(2,'0')}:writing`]).latest;
 expect(writing.correct).toBeNull();expect(writing.total).toBe(5);
});
