import type {test as Test,expect as Expect,Page} from '@playwright/test';
import {readFileSync,writeFileSync} from 'node:fs';
import {createCompatibility} from '../../src/services/storage/compatibility.ts';
import {getHomework30Bank} from '../../src/services/content/homework30.ts';
import {homework30Group,submitHomework30,restartHomework30} from '../../src/domain/homework30/engine.ts';
import {getSourceLesson} from '../../src/services/source-activities/content.ts';
const json=(name:string)=>JSON.parse(readFileSync(new URL('../../content/'+name,import.meta.url),'utf8'));
const compat=createCompatibility(json('stage2-bank.json'),json('stage3-catalog.json'),json('textbook.json'));
const sourceKey='ran_hsk1_textbook_source_v1',primaryKey='ran_hsk1_modular_v1',legacyKey='ran_hsk1_stage2_v3';
const stamp=1791093600000,firstId='hsk1-original-2026-l04-p018-warmup-01';
const firstVersion=getSourceLesson(4)!.activities.find(a=>a.id===firstId)!.version;
function oldData(){const d=compat.blank(),lesson=getHomework30Bank()[0];for(let run=0;run<2;run++){homework30Group(d.homework30!,1,'choice').draft=Object.fromEntries(lesson.choice.map(q=>[q.id,run?0:q.answer]));if(!submitHomework30(d.homework30!,lesson,'choice',stamp+run).ok)throw Error('Invalid synthetic seed');restartHomework30(d.homework30!,1,'choice',stamp+run+1);}homework30Group(d.homework30!,1,'choice').draft={[lesson.choice[0].id]:1};d.legacyRaw={[legacyKey]:' { "synthetic": "legacy byte sample" } '};return compat.validate(d);}
async function seed(page:Page){const raw=JSON.stringify({app:'hsk1-modular',schema:1,revision:9,updatedAt:stamp,data:oldData(),recovery:null});await page.addInitScript(({raw,primaryKey,legacyKey})=>{sessionStorage.setItem('hsk_portal_unlocked_v2','1');if(!localStorage.getItem(primaryKey))localStorage.setItem(primaryKey,raw);if(!localStorage.getItem(legacyKey))localStorage.setItem(legacyKey,' { "synthetic": "legacy byte sample" } ');},{raw,primaryKey,legacyKey});}
const pilot=(page:Page)=>page.locator('[data-hsk1-source-pilot="4"]');
const first=(page:Page)=>pilot(page).locator(`[data-activity-id="${firstId}"]`);
async function captureSourceParts(page:Page,host:string,width:number,expect:typeof Expect){
 const base=`test-results/${host}-hsk1-source-l04-${width}`,parts:any[]=[];
 // Each visible intro/control block is captured in full, not just the first viewport.
 for(const [i,child] of (await pilot(page).locator(':scope > *').all()).entries()){
  if(await child.evaluate(e=>e.hasAttribute('data-source-numbers')||e.classList.contains('source-activity-grid')))break;
  if(!await child.isVisible())continue;const file=base+`-header-${i}.png`;await child.screenshot({path:file});parts.push({file,kind:'complete-header-block',tag:await child.evaluate(e=>e.tagName)});
 }
 for(const [i,card] of (await pilot(page).locator('.activity-card').all()).entries()){const file=base+`-activity-${String(i+1).padStart(2,'0')}.png`;await card.screenshot({path:file});parts.push({file,kind:'activity',activityId:(await card.getAttribute('data-activity-id'))!});}
 const numbers=pilot(page).locator('[data-source-numbers]');await numbers.screenshot({path:base+'-numbers-overview.png'});parts.push({file:base+'-numbers-overview.png',kind:'complete-number-section-overview'});
 for(const [tableIndex,scroll] of (await numbers.locator('.source-table-scroll').all()).entries()){
  const geometry=await scroll.evaluate(e=>({clientWidth:e.clientWidth,scrollWidth:e.scrollWidth,max:e.scrollWidth-e.clientWidth}));expect(geometry.clientWidth).toBeGreaterThan(0);
  if(geometry.max>1){
   await scroll.evaluate(e=>e.scrollLeft=0);await scroll.focus();for(let i=0;i<40;i++)await scroll.press('ArrowRight',{delay:20});
   await expect.poll(()=>scroll.evaluate(e=>{const last=e.querySelector('tr')!.lastElementChild!.getBoundingClientRect(),box=e.getBoundingClientRect();return e.scrollLeft>0&&last.right<=box.right+1})).toBe(true);
  }
  const starts=[0],step=Math.max(1,Math.floor(geometry.clientWidth*.75));for(let x=step;x<geometry.max;x+=step)starts.push(x);if(geometry.max>0)starts.push(geometry.max);
  let covered=0;for(const [partIndex,x]of starts.entries()){
   await scroll.evaluate((e,x)=>e.scrollLeft=x,x);const position=await scroll.evaluate(e=>({left:e.scrollLeft,width:e.clientWidth,scrollWidth:e.scrollWidth}));expect(position.left).toBeLessThanOrEqual(covered+1);covered=Math.max(covered,position.left+position.width);
   const file=base+`-table-${tableIndex}-part-${partIndex}.png`;await scroll.screenshot({path:file});parts.push({file,kind:'overlapping-number-table-slice',tableIndex,scrollLeft:position.left,maxScroll:geometry.max,clientWidth:position.width,scrollWidth:position.scrollWidth});
  }expect(covered).toBeGreaterThanOrEqual(geometry.scrollWidth-1);
 }
 const bonus=pilot(page).locator('.source-bonus');await bonus.screenshot({path:base+'-bonus.png'});parts.push({file:base+'-bonus.png',kind:'bonus'});expect(parts.filter(p=>p.kind==='activity')).toHaveLength(36);expect(new Set(parts.filter(p=>p.activityId).map(p=>p.activityId)).size).toBe(36);writeFileSync(base+'-parts.json',JSON.stringify({host,width,fullSourceActivities:36,parts},null,2));
}
export function sourcePilotCases(route:string,hostName:string,test:typeof Test,expect:typeof Expect){
async function ready(page:Page,route:string){await page.goto(route);await expect(page.locator('[data-hsk1-source-pilot="4"]')).toBeVisible();await expect(page.locator('#reading-save-status')).toHaveAttribute('data-state','saved');}
async function submitted(page:Page,value='D'){const c=first(page);await c.locator('select').selectOption(value);await c.getByRole('button',{name:'保存并查看反馈'}).click();await expect(c.locator('.activity-feedback')).toContainText('参考答案');await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');}
 test.beforeEach(async({page})=>seed(page));
 for(const width of [320,390,768,1440])test(`${hostName} HSK1 source L4 reviewed source structure at ${width}`,async({page})=>{await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,route);await expect(pilot(page).locator('.activity-card')).toHaveCount(36);await expect(pilot(page).locator('[data-source-field]')).toHaveCount(27);await expect(pilot(page).locator('img')).toHaveCount(13);await expect(pilot(page).locator('.activity-feedback')).not.toContainText(['参考答案']);for(const img of await pilot(page).locator('img').all()){await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);}await pilot(page).locator('[data-source-numbers] summary').click();await expect(pilot(page).locator('[data-number-table="0-99"] td')).toHaveCount(100);await expect(pilot(page).locator('[data-number-table="0-99"] td[aria-label]')).toHaveCount(64);await expect(pilot(page).locator('.source-bonus')).toContainText('原视频尚未取得');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);await captureSourceParts(page,hostName,width,expect);});
 test(`${hostName} HSK1 source save export reset import reload and history preserve nonempty old bytes`,async({page})=>{await ready(page,route);const before=await page.evaluate(({primaryKey,legacyKey})=>({primary:localStorage.getItem(primaryKey),legacy:localStorage.getItem(legacyKey)}),{primaryKey,legacyKey});await submitted(page);await submitted(page,'A');await expect(first(page).locator('.source-history summary')).toContainText('2次');const [download]=await Promise.all([page.waitForEvent('download'),pilot(page).locator('[data-source-export]').click()]);const path=await download.path();if(!path)throw Error('No downloaded backup');const bytes=readFileSync(path);expect(JSON.parse(bytes.toString()).app).toBe('hsk1-textbook-source-backup');await pilot(page).getByRole('button',{name:'预览清空原版活动'}).click();await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await expect(first(page).locator('select')).toHaveValue('');await expect(first(page).locator('.activity-feedback')).toBeEmpty();await pilot(page).locator('#source-import-file').setInputFiles({name:'source.json',mimeType:'application/json',buffer:bytes});await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await expect(first(page).locator('select')).toHaveValue('A');await expect(first(page).locator('.source-history summary')).toContainText('2次');const after=await page.evaluate(({primaryKey,legacyKey})=>({primary:localStorage.getItem(primaryKey),legacy:localStorage.getItem(legacyKey)}),{primaryKey,legacyKey});expect(after).toEqual(before);await page.reload();await expect(first(page).locator('select')).toHaveValue('A');await expect(first(page).locator('.source-history summary')).toContainText('2次');});
 test(`${hostName} HSK1 source quota failure hides answers and exports unsaved input`,async({page})=>{await page.addInitScript(key=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw new DOMException('test quota','QuotaExceededError');return set.call(this,k,v);};},sourceKey);await ready(page,route);await first(page).locator('select').selectOption('D');await first(page).getByRole('button',{name:'保存并查看反馈'}).click();await expect(first(page).locator('.activity-feedback')).toContainText('尚未确认保存');await expect(first(page).locator('.activity-feedback')).not.toContainText('参考答案：');expect(await page.evaluate(key=>localStorage.getItem(key),sourceKey)).toBeNull();const [download]=await Promise.all([page.waitForEvent('download'),pilot(page).locator('[data-source-export]').click()]);const path=await download.path();if(!path)throw Error('No download');expect(JSON.parse(readFileSync(path,'utf8')).data.records[firstId+'@'+firstVersion].draft.values['blank-1']).toBe('D');});
 test(`${hostName} HSK1 source delayed save cannot reveal a changed or closed answer`,async({page})=>{
  await ready(page,route);const hold=()=>page.evaluate(async()=>{await new Promise<void>(ready=>{void navigator.locks.request('ran-hsk1-textbook-source-write',async()=>{ready();await new Promise<void>(release=>(window as any).__releaseSource=release)})})}),release=()=>page.evaluate(()=>(window as any).__releaseSource());
  await hold();await first(page).locator('select').selectOption('D');await first(page).getByRole('button',{name:'保存并查看反馈'}).click();await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saving');await first(page).locator('select').selectOption('A');await release();await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');await expect(first(page).locator('.activity-feedback')).toBeEmpty();
  await hold();await pilot(page).getByRole('button',{name:'预览清空原版活动'}).click();await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saving');await pilot(page).getByRole('button',{name:'取消',exact:false}).click();await release();await expect(first(page).locator('select')).toHaveValue('A');await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');
  const row=await page.evaluate(({sourceKey,firstId,firstVersion})=>JSON.parse(localStorage.getItem(sourceKey)!).data.records[firstId+'@'+firstVersion],{sourceKey,firstId,firstVersion});expect(row.draft.values['blank-1']).toBe('A');expect(row.history).toHaveLength(0);
 });
 test(`${hostName} HSK1 source open tasks remain ungraded and IME invalidates pending preview`,async({page})=>{await ready(page,route);const open=pilot(page).locator('[data-kind="picture-description"]').first();await open.locator('input').first().fill('七口人');await open.getByRole('button',{name:'保存并查看反馈'}).click();await expect(open.locator('.activity-feedback')).toContainText('不计分');await expect(open.locator('.activity-feedback')).not.toContainText('参考答案');await pilot(page).getByRole('button',{name:'预览清空原版活动'}).click();await open.locator('input').first().dispatchEvent('compositionstart');await open.locator('input').first().fill('尚在组词');await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await expect(pilot(page).locator('.source-preview')).toBeHidden();await open.locator('input').first().dispatchEvent('compositionend');await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');await expect(open.locator('input').first()).toHaveValue('尚在组词');});
 test(`${hostName} HSK1 source older-tab conflict preserves newer saved answers`,async({page})=>{await ready(page,route);const other=await page.context().newPage();await other.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1'));await ready(other,route);await submitted(page,'D');await other.waitForTimeout(30);await first(other).locator('select').selectOption('A');await first(other).getByRole('button',{name:'保存并查看反馈'}).click();await expect(pilot(other).locator('[data-source-save-status]')).toHaveAttribute('data-state','conflict');await expect(first(other).locator('.activity-feedback')).not.toContainText('参考答案：');expect(await page.evaluate(({sourceKey,firstId,firstVersion})=>JSON.parse(localStorage.getItem(sourceKey)!).data.records[firstId+'@'+firstVersion].draft.values['blank-1'],{sourceKey,firstId,firstVersion})).toBe('D');await other.close();});
 test(`${hostName} HSK1 source pending journal blocks mutation without touching old bytes`,async({page})=>{await page.addInitScript(()=>localStorage.setItem('ran_hsk1_source_pair_journal_v1','unresolved'));await page.goto(route);await expect(pilot(page)).toBeVisible();const raw=await page.evaluate(key=>localStorage.getItem(key),primaryKey);await first(page).locator('select').selectOption('D');await first(page).getByRole('button',{name:'保存并查看反馈'}).click();await expect(first(page).locator('.activity-feedback')).toContainText('尚未确认保存');expect(await page.evaluate(key=>localStorage.getItem(key),sourceKey)).toBeNull();expect(await page.evaluate(key=>localStorage.getItem(key),primaryKey)).toBe(raw);});
 test(`${hostName} HSK1 source IME start cancels a lock-waiting submission until an explicit retry`,async({page})=>{
  await ready(page,route);await first(page).locator('select').selectOption('D');await first(page).getByRole('button',{name:'保存并查看反馈'}).click();await expect(first(page).locator('.activity-feedback')).toContainText('参考答案');
  const prior=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).data.records,sourceKey),primary=await page.evaluate(key=>localStorage.getItem(key),primaryKey),open=pilot(page).locator('[data-kind="picture-description"]').first(),input=open.locator('input').first();await input.fill('六口人');await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');
  const id=(await open.getAttribute('data-activity-id'))+'@'+(await open.getAttribute('data-activity-version'));
  await expect.poll(()=>page.evaluate(({key,id})=>JSON.parse(localStorage.getItem(key)!).data.records[id]?.history.length,{key:sourceKey,id})).toBe(0);
  await page.evaluate(async()=>{await new Promise<void>(ready=>{void navigator.locks.request('ran-hsk1-textbook-source-write',async()=>{ready();await new Promise<void>(release=>(window as any).__releaseImeSource=release)})})});
  await open.getByRole('button',{name:'保存并查看反馈'}).click();await input.dispatchEvent('compositionstart');await page.evaluate(()=>(window as any).__releaseImeSource());await expect(open.getByRole('button',{name:'保存并查看反馈'})).toBeEnabled();await expect(open.locator('.activity-feedback')).toBeEmpty();await input.dispatchEvent('compositionend');await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');
  expect(await page.evaluate(({key,id})=>JSON.parse(localStorage.getItem(key)!).data.records[id].history.length,{key:sourceKey,id})).toBe(0);await expect(input).toHaveValue('六口人');
  await open.getByRole('button',{name:'保存并查看反馈'}).click();await expect(open.locator('.activity-feedback')).toContainText('不计分');expect(await page.evaluate(({key,id})=>JSON.parse(localStorage.getItem(key)!).data.records[id].history.length,{key:sourceKey,id})).toBe(1);
  for(const[key,record]of Object.entries(prior))expect(await page.evaluate(({storage,key})=>JSON.parse(localStorage.getItem(storage)!).data.records[key],{storage:sourceKey,key})).toEqual(record);expect(await page.evaluate(key=>localStorage.getItem(key),primaryKey)).toBe(primary);
 });

}
