import type {test as Test,expect as Expect,Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {createCompatibility} from '../../src/services/storage/compatibility.ts';
import {getHomework30Bank} from '../../src/services/content/homework30.ts';
import {homework30Group,submitHomework30,restartHomework30} from '../../src/domain/homework30/engine.ts';
const json=(name:string)=>JSON.parse(readFileSync(new URL('../../content/'+name,import.meta.url),'utf8'));
const compat=createCompatibility(json('stage2-bank.json'),json('stage3-catalog.json'),json('textbook.json'));
const sourceKey='ran_hsk1_textbook_source_v1',primaryKey='ran_hsk1_modular_v1',legacyKey='ran_hsk1_stage2_v3';
const stamp=1791093600000,firstId='hsk1-original-2026-l04-p018-warmup-01';
function oldData(){const d=compat.blank(),lesson=getHomework30Bank()[0];for(let run=0;run<2;run++){homework30Group(d.homework30!,1,'choice').draft=Object.fromEntries(lesson.choice.map(q=>[q.id,run?0:q.answer]));if(!submitHomework30(d.homework30!,lesson,'choice',stamp+run).ok)throw Error('Invalid synthetic seed');restartHomework30(d.homework30!,1,'choice',stamp+run+1);}homework30Group(d.homework30!,1,'choice').draft={[lesson.choice[0].id]:1};d.legacyRaw={[legacyKey]:' { "synthetic": "legacy byte sample" } '};return compat.validate(d);}
async function seed(page:Page){const raw=JSON.stringify({app:'hsk1-modular',schema:1,revision:9,updatedAt:stamp,data:oldData(),recovery:null});await page.addInitScript(({raw,primaryKey,legacyKey})=>{sessionStorage.setItem('hsk_portal_unlocked_v2','1');if(!localStorage.getItem(primaryKey))localStorage.setItem(primaryKey,raw);if(!localStorage.getItem(legacyKey))localStorage.setItem(legacyKey,' { "synthetic": "legacy byte sample" } ');},{raw,primaryKey,legacyKey});}
const pilot=(page:Page)=>page.locator('[data-hsk1-source-pilot="4"]');
const first=(page:Page)=>pilot(page).locator(`[data-activity-id="${firstId}"]`);
export function sourcePilotCases(route:string,hostName:string,test:typeof Test,expect:typeof Expect){
async function ready(page:Page,route:string){await page.goto(route);await expect(page.locator('[data-hsk1-source-pilot="4"]')).toBeVisible();await expect(page.locator('#reading-save-status')).toHaveAttribute('data-state','saved');}
async function submitted(page:Page,value='D'){const c=first(page);await c.locator('select').selectOption(value);await c.getByRole('button',{name:'保存并查看反馈'}).click();await expect(c.locator('.activity-feedback')).toContainText('参考答案');await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');}
 test.beforeEach(async({page})=>seed(page));
 for(const width of [320,390,768,1440])test(`${hostName} HSK1 source L4 reviewed source structure at ${width}`,async({page})=>{await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,route);await expect(pilot(page).locator('.activity-card')).toHaveCount(21);await expect(pilot(page).locator('[data-source-field]')).toHaveCount(24);await expect(pilot(page).locator('img')).toHaveCount(10);await expect(pilot(page).locator('.activity-feedback')).not.toContainText(['参考答案']);for(const img of await pilot(page).locator('img').all()){await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true);}await pilot(page).locator('[data-source-numbers] summary').click();await expect(pilot(page).locator('[data-number-table="0-99"] td')).toHaveCount(100);await expect(pilot(page).locator('[data-number-table="0-99"] td[aria-label]')).toHaveCount(64);await expect(pilot(page).locator('.source-bonus')).toContainText('原视频尚未取得');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:`test-results/${hostName}-hsk1-source-l04-${width}.png`,fullPage:true});});
 test(`${hostName} HSK1 source save export reset import reload and history preserve nonempty old bytes`,async({page})=>{await ready(page,route);const before=await page.evaluate(({primaryKey,legacyKey})=>({primary:localStorage.getItem(primaryKey),legacy:localStorage.getItem(legacyKey)}),{primaryKey,legacyKey});await submitted(page);await submitted(page,'A');await expect(first(page).locator('.source-history summary')).toContainText('2次');const [download]=await Promise.all([page.waitForEvent('download'),pilot(page).locator('[data-source-export]').click()]);const path=await download.path();if(!path)throw Error('No downloaded backup');const bytes=readFileSync(path);expect(JSON.parse(bytes.toString()).app).toBe('hsk1-textbook-source-backup');await pilot(page).getByRole('button',{name:'预览清空原版活动'}).click();await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await expect(first(page).locator('select')).toHaveValue('');await expect(first(page).locator('.activity-feedback')).toBeEmpty();await pilot(page).locator('#source-import-file').setInputFiles({name:'source.json',mimeType:'application/json',buffer:bytes});await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await expect(first(page).locator('select')).toHaveValue('A');await expect(first(page).locator('.source-history summary')).toContainText('2次');const after=await page.evaluate(({primaryKey,legacyKey})=>({primary:localStorage.getItem(primaryKey),legacy:localStorage.getItem(legacyKey)}),{primaryKey,legacyKey});expect(after).toEqual(before);await page.reload();await expect(first(page).locator('select')).toHaveValue('A');await expect(first(page).locator('.source-history summary')).toContainText('2次');});
 test(`${hostName} HSK1 source quota failure hides answers and exports unsaved input`,async({page})=>{await page.addInitScript(key=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw new DOMException('test quota','QuotaExceededError');return set.call(this,k,v);};},sourceKey);await ready(page,route);await first(page).locator('select').selectOption('D');await first(page).getByRole('button',{name:'保存并查看反馈'}).click();await expect(first(page).locator('.activity-feedback')).toContainText('尚未确认保存');await expect(first(page).locator('.activity-feedback')).not.toContainText('参考答案：');expect(await page.evaluate(key=>localStorage.getItem(key),sourceKey)).toBeNull();const [download]=await Promise.all([page.waitForEvent('download'),pilot(page).locator('[data-source-export]').click()]);const path=await download.path();if(!path)throw Error('No download');expect(JSON.parse(readFileSync(path,'utf8')).data.records[firstId+'@source-v2'].draft.values['blank-1']).toBe('D');});
 test(`${hostName} HSK1 source delayed save cannot reveal a changed or closed answer`,async({page})=>{await page.addInitScript(()=>{const real=navigator.locks.request.bind(navigator.locks);(window as any).__holdSource=true;Object.defineProperty(navigator.locks,'request',{value:(name:string,...args:any[])=>name==='ran-hsk1-textbook-source-write'?real(name,async lock=>{if((window as any).__holdSource)await new Promise<void>(resolve=>{(window as any).__releaseSource=resolve;});return args[args.length-1](lock);}):real(name,...args as [any])});});await ready(page,route);await first(page).locator('select').selectOption('D');await first(page).getByRole('button',{name:'保存并查看反馈'}).click();await first(page).locator('select').selectOption('A');await page.evaluate(()=>{(window as any).__holdSource=false;(window as any).__releaseSource();});await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');await expect(first(page).locator('.activity-feedback')).toBeEmpty();await page.evaluate(()=>{(window as any).__holdSource=true;});await pilot(page).getByRole('button',{name:'预览清空原版活动'}).click();await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await pilot(page).getByRole('button',{name:'取消',exact:false}).click();await page.evaluate(()=>{(window as any).__releaseSource();});await expect(first(page).locator('select')).toHaveValue('A');});
 test(`${hostName} HSK1 source open tasks remain ungraded and IME invalidates pending preview`,async({page})=>{await ready(page,route);const open=pilot(page).locator('[data-kind="picture-description"]').first();await open.locator('input').first().fill('七口人');await open.getByRole('button',{name:'保存并查看反馈'}).click();await expect(open.locator('.activity-feedback')).toContainText('不计分');await expect(open.locator('.activity-feedback')).not.toContainText('参考答案');await pilot(page).getByRole('button',{name:'预览清空原版活动'}).click();await open.locator('input').first().dispatchEvent('compositionstart');await open.locator('input').first().fill('尚在组词');await pilot(page).getByRole('button',{name:'确认替换原版活动'}).click();await expect(pilot(page).locator('.source-preview')).toBeHidden();await open.locator('input').first().dispatchEvent('compositionend');await expect(pilot(page).locator('[data-source-save-status]')).toHaveAttribute('data-state','saved');await expect(open.locator('input').first()).toHaveValue('尚在组词');});
 test(`${hostName} HSK1 source older-tab conflict preserves newer saved answers`,async({page})=>{await ready(page,route);const other=await page.context().newPage();await ready(other,route);await submitted(page,'D');await other.waitForTimeout(30);await first(other).locator('select').selectOption('A');await first(other).getByRole('button',{name:'保存并查看反馈'}).click();await expect(pilot(other).locator('[data-source-save-status]')).toHaveAttribute('data-state','conflict');await expect(first(other).locator('.activity-feedback')).not.toContainText('参考答案：');expect(await page.evaluate(({sourceKey,firstId})=>JSON.parse(localStorage.getItem(sourceKey)!).data.records[firstId+'@source-v2'].draft.values['blank-1'],{sourceKey,firstId})).toBe('D');await other.close();});
 test(`${hostName} HSK1 source pending journal blocks mutation without touching old bytes`,async({page})=>{await page.addInitScript(()=>localStorage.setItem('ran_hsk1_source_pair_journal_v1','unresolved'));await page.goto(route);await expect(pilot(page)).toBeVisible();const raw=await page.evaluate(key=>localStorage.getItem(key),primaryKey);await first(page).locator('select').selectOption('D');await first(page).getByRole('button',{name:'保存并查看反馈'}).click();await expect(first(page).locator('.activity-feedback')).toContainText('尚未确认保存');expect(await page.evaluate(key=>localStorage.getItem(key),sourceKey)).toBeNull();expect(await page.evaluate(key=>localStorage.getItem(key),primaryKey)).toBe(raw);});
}
