import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {sourceLesson} from '../src/services/source-activities/content.ts';
import {blankSourceData,validateSourceData,editSourceDraft} from '../src/services/source-activities/state.ts';
import {createSourceStore,createSourceSession,SOURCE_STORAGE_KEY,SOURCE_JOURNAL_KEY} from '../src/services/source-activities/store.ts';
import {createStore,STORAGE_KEY} from '../src/services/storage/index.ts';
import {createCompatibility} from '../src/services/storage/compatibility.ts';
import {getHomework30Bank} from '../src/services/content/homework30.ts';
import {homework30Group,submitHomework30,restartHomework30} from '../src/domain/homework30/engine.ts';
const read=name=>JSON.parse(fs.readFileSync(new URL('../content/'+name,import.meta.url),'utf8'));
const compatibility=createCompatibility(read('stage2-bank.json'),read('stage3-catalog.json'),read('textbook.json'));
const stamp=1791093600000;const a=sourceLesson.activities[0],key=a.id+'@'+a.version;
function memory(){const values=new Map(),writes=[];return {values,writes,getItem:k=>values.get(k)??null,setItem(k,v){writes.push(k);values.set(k,v);}}}
const lock=async task=>task();const make=(storage,overrides={})=>createSourceStore({storage,lock,now:()=>stamp,...overrides});
function nonemptyPrimary(){const d=compatibility.blank(),lesson=getHomework30Bank()[0];for(let run=0;run<2;run++){const group=homework30Group(d.homework30,1,'choice');group.draft=Object.fromEntries(lesson.choice.map(q=>[q.id,run?0:q.answer]));assert.equal(submitHomework30(d.homework30,lesson,'choice',stamp+run).ok,true);restartHomework30(d.homework30,1,'choice',stamp+run+1);}homework30Group(d.homework30,1,'choice').draft={[lesson.choice[0].id]:1};d.legacyRaw={ran_hsk1_stage2_v3:' { "synthetic": "old byte-for-byte receipt" } '};return compatibility.validate(d);}
function seed(storage){const data=nonemptyPrimary(),raw=JSON.stringify({app:'hsk1-modular',schema:1,revision:9,updatedAt:stamp,data,recovery:null});storage.values.set(STORAGE_KEY,raw);storage.values.set('legacy-synthetic',' \n { "old":"keep exact bytes" } \n');return raw;}
test('L4 source sidecar locks original cardinality, answers, pinyin, source pages and ungraded tasks',()=>{
 const kinds=sourceLesson.activities.reduce((r,a)=>(r[a.kind]=(r[a.kind]??0)+1,r),{});assert.deepEqual(kinds,{'image-match':6,'listening-choice':4,'word-bank-cloze':4,'picture-description':4,'open-dialogue-completion':2,'pair-work':1});
 assert.equal(sourceLesson.activities.flatMap(a=>a.fields).length,24);
 for(const a of sourceLesson.activities){assert.equal(a.lesson,4);assert.equal(a.source.pdfPage,a.source.printedPage+15);assert.ok(a.instruction.zh&&a.instruction.vi&&a.prompt.zh&&a.prompt.vi);for(const f of a.fields){if(f.assessment==='answer-key'){assert.ok(f.options.some(o=>o.id===f.answer));assert.equal(f.answerSource.sha256,sourceLesson.answerBookSHA256);assert.ok(f.options.every(o=>o.py&&o.vi));}else{assert.equal(f.assessment,'ungraded');assert.equal(f.answer,undefined);assert.equal(f.answerSource,undefined);}}}
 assert.deepEqual(sourceLesson.activities.filter(a=>a.kind==='image-match').map(a=>a.fields[0].answer),['D','A','C','F','E','B']);assert.deepEqual(sourceLesson.activities.filter(a=>a.kind==='listening-choice').map(a=>a.fields[0].answer),['A','B','B','B']);assert.deepEqual(sourceLesson.activities.filter(a=>a.kind==='word-bank-cloze').flatMap(a=>a.fields.map(f=>f.answer)),['B','D','A','C','E']);
 assert.deepEqual(sourceLesson.activities.filter(a=>a.audio).map(a=>a.audio.sceneId),['textbook-l04-text-2','textbook-l04-text-2','textbook-l04-text-3','textbook-l04-text-3']);assert.ok(sourceLesson.activities.filter(a=>a.audio).every(a=>a.pinyin&&a.audio.verifiedByListening===false));assert.equal(sourceLesson.bonus.payload,null);assert.equal(sourceLesson.bonus.availability,'unavailable');
});
test('numeric tables preserve all original sparse grid positions, six large numbers and 二/两',()=>{const n=sourceLesson.numberTables;assert.deepEqual(n.grid.map(r=>r.length),Array(10).fill(10));assert.deepEqual(n.grid.flat().filter(Boolean).map(c=>c.number),[0,1,2,3,4,5,6,7,8,9,10,11,19,20,22,28,30,33,37,40,44,46,50,55,60,64,66,70,73,77,80,82,88,90,91,99]);assert.equal(n.grid.flat().filter(c=>c===null).length,64);assert.deepEqual(n.higher.map(c=>c.number),[100,208,999,1000,1528,9999]);assert.deepEqual(n.two.map(c=>c.zh),['十二','二十二','一百二十二','两个人','两口人','两本书']);});
test('ten original schematic SVGs have explicit source-cell mappings and no external or active payloads',()=>{assert.equal(sourceLesson.figures.length,10);for(const f of sourceLesson.figures){assert.equal(f.kind,'original-schematic');assert.equal(f.source.pdfPage,f.source.printedPage+15);assert.ok(f.alt.zh&&f.alt.vi&&f.note.zh&&f.note.vi);const svg=fs.readFileSync(new URL('../content/source-activities/'+f.file,import.meta.url),'utf8');assert.equal(createHash('sha256').update(svg).digest('hex'),f.sha256);assert.match(svg,/viewBox="0 0 360 220"/);assert.doesNotMatch(svg,/<script|<image|href=|onload=|foreignObject/i);}});
test('all five frozen HSK1 source banks are byte-identical',()=>{for(const [name,sha] of Object.entries({'textbook.json':'5079b381a30d5d7785db5ee93d17b1ad71380a53633146001150c874f27558d7','homework30-bank.json':'efc0fd1c3bbbead479e8d610da9ea7c802d7cf3edb553942edc2d7dce54c9c5d','stage2-bank.json':'bfd70d38b319362cd14e0da533c0c90a268a7f90b243cfffef23ef6549177ae3','stage3-catalog.json':'35a15efbf9cc80c8e4ccb51d154ca8d906b970b13acabb0cc179a64423162913','legacy-exercises.json':'84b0e7784c06da7b89f224db71d1cb122685d26e184ee41892237d1b2fdd735c'}))assert.equal(createHash('sha256').update(fs.readFileSync(new URL('../content/'+name,import.meta.url))).digest('hex'),sha);});
test('source save/export/reload/history/reset/restore preserve nonempty primary and legacy exact bytes and old tabs still write',async()=>{
 const storage=memory(),primaryRaw=seed(storage),legacyRaw=storage.values.get('legacy-synthetic'),old=createStore({storage,blank:compatibility.blank,validate:compatibility.validate,lock,now:()=>stamp+100});const store=make(storage),session=createSourceSession(store,()=>stamp);
 assert.equal((await session.submit(a,{'blank-1':'D'})).ok,true);assert.equal((await session.submit(a,{'blank-1':'A'})).ok,true);const backup=store.exportBackup(),reload=make(storage);assert.equal(reload.snapshot().data.records[key].history.length,2);assert.equal(reload.snapshot().data.records[key].history[0].values['blank-1'],'D');assert.equal(reload.snapshot().data.records[key].draft.values['blank-1'],'A');
 assert.equal((await store.confirm(store.previewReplacement(blankSourceData(),'reset'))).ok,true);assert.equal(Object.keys(store.snapshot().data.records).length,0);assert.equal((await store.restore()).ok,true);assert.equal(store.snapshot().data.records[key].history.length,2);assert.equal((await store.confirm(store.previewBackup(backup))).ok,true);
 assert.equal(storage.values.get(STORAGE_KEY),primaryRaw);assert.equal(storage.values.get('legacy-synthetic'),legacyRaw);assert.ok(storage.writes.every(k=>k===SOURCE_STORAGE_KEY));assert.deepEqual(compatibility.validate(JSON.parse(primaryRaw).data),old.snapshot().data);old.edit(d=>d.homework.profile.name='Old program still works');assert.equal((await old.save()).ok,true);assert.equal(make(storage).snapshot().data.records[key].history.length,2);session.dispose();
});
test('older activity versions survive catalogue changes as inert context and independent histories',async()=>{const data=blankSourceData(),old={...a,version:'source-old',prompt:{zh:'旧题 <script>alert(1)</script>',vi:'Đề cũ'}};editSourceDraft(data,old,{'blank-1':'old free text'},stamp);const row=data.records[old.id+'@source-old'];row.history.push({id:'old-1',at:stamp,values:{'blank-1':'<img src=x onerror=alert(1)>'}});const storage=memory(),store=make(storage);assert.equal((await store.confirm(store.previewReplacement(data,'import'))).ok,true);assert.deepEqual(make(storage).snapshot().data,data);assert.throws(()=>editSourceDraft(data,{...old,prompt:a.prompt},{'blank-1':'B'},stamp+1),/版本/);});
test('source validation rejects malformed domains, duplicate history, unknown fields and wrong edition',()=>{const valid=blankSourceData();editSourceDraft(valid,a,{'blank-1':'D'},stamp);for(const mutate of [v=>v.schema=2,v=>v.edition='hsk3',v=>v.extra={},v=>v.records[key].draft.values.invented='x',v=>v.records[key].history=[{id:'x',at:stamp,values:{}},{id:'x',at:stamp,values:{}}],v=>v.records[key].context.source.pdfPage='33',v=>v.records[key].context.fields[0].answer='Z']){const v=structuredClone(valid);mutate(v);assert.throws(()=>validateSourceData(v));}const store=make(memory());assert.throws(()=>store.previewBackup(JSON.stringify({app:'hsk1-modular-backup',schema:1,exportedAt:stamp,data:valid})));assert.throws(()=>store.previewBackup(JSON.stringify({app:'hsk1-textbook-source-backup',schema:1,exportedAt:stamp,data:null})));});
test('source quota failure retains exportable draft, confirms no saved reference and leaves old primary intact',async()=>{const storage=memory(),primary=seed(storage);storage.setItem=()=>{throw new DOMException('full','QuotaExceededError')};const store=make(storage),session=createSourceSession(store,()=>stamp);const result=await session.submit(a,{'blank-1':'D'});assert.equal(result.ok,false);assert.equal(store.snapshot().status,'unsaved');assert.equal(storage.values.get(STORAGE_KEY),primary);assert.equal(storage.values.has(SOURCE_STORAGE_KEY),false);assert.equal(JSON.parse(store.exportBackup()).data.records[key].draft.values['blank-1'],'D');session.dispose();});
test('source write-then-throw needs exact readback; a newer third value is never overwritten',async()=>{const storage=memory(),put=storage.setItem;storage.setItem=(k,v)=>{put(k,v);throw Error('after write');};let store=make(storage);store.edit(d=>editSourceDraft(d,a,{'blank-1':'D'},stamp));assert.equal((await store.save()).ok,true);const before=storage.values.get(SOURCE_STORAGE_KEY);store=make(storage);store.edit(d=>editSourceDraft(d,a,{'blank-1':'A'},stamp));storage.setItem=(k,v)=>{put(k,v+' ')};assert.equal((await store.save()).ok,false);assert.equal(store.snapshot().status,'conflict');assert.notEqual(storage.values.get(SOURCE_STORAGE_KEY),before);assert.ok(storage.values.get(SOURCE_STORAGE_KEY).endsWith(' '));});
test('source missing locks, unreadable storage and unresolved pair journal fail closed',async()=>{for(const scenario of ['locks','read','journal']){const storage=memory();if(scenario==='read')storage.getItem=()=>{throw Error('denied')};if(scenario==='journal')storage.values.set(SOURCE_JOURNAL_KEY,'unresolved or corrupt');const store=make(storage,scenario==='locks'?{lock:undefined}:{});store.edit(d=>editSourceDraft(d,a,{'blank-1':'D'},stamp));assert.equal((await store.save()).ok,false);assert.equal(storage.writes.length,0);assert.ok(store.exportBackup().includes('blank-1'));}});
test('source stale preview, close while waiting, source tab conflict and ordinary old import never clear source',async()=>{const storage=memory();seed(storage);const first=make(storage),second=make(storage);first.edit(d=>editSourceDraft(d,a,{'blank-1':'D'},stamp));assert.equal((await first.save()).ok,true);second.edit(d=>editSourceDraft(d,a,{'blank-1':'A'},stamp));assert.equal((await second.save()).code,'conflict');const p=first.previewReplacement(blankSourceData(),'reset');first.edit(d=>editSourceDraft(d,a,{'blank-1':'B'},stamp));assert.equal((await first.confirm(p)).code,'stale-preview');await first.save();const original=storage.values.get(SOURCE_STORAGE_KEY);let release;const barrier=new Promise(r=>release=r),held=make(storage,{lock:async task=>{await barrier;return task();}}),cancel=new AbortController();const pending=held.confirm(held.previewReplacement(blankSourceData(),'reset'),cancel.signal);cancel.abort();release();assert.equal((await pending).code,'cancelled');assert.equal(storage.values.get(SOURCE_STORAGE_KEY),original);const old=createStore({storage,blank:compatibility.blank,validate:compatibility.validate,lock,now:()=>stamp});assert.equal((await old.confirm(old.previewBackup(old.exportBackup()))).ok,true);assert.equal(storage.values.get(SOURCE_STORAGE_KEY),original);});
test('failed direct submission never enters history through later ordinary draft flush',async()=>{const storage=memory(),write=storage.setItem;let fail=true;storage.setItem=(k,v)=>{if(fail)throw new DOMException('full','QuotaExceededError');write(k,v);};const store=make(storage),session=createSourceSession(store,()=>stamp);const result=await session.submit(a,{'blank-1':'D'});assert.equal(result.ok,false);assert.equal(result.submissionId,null);assert.equal(store.snapshot().data.records[key].history.length,0);assert.equal(store.snapshot().data.records[key].draft.values['blank-1'],'D');fail=false;session.edit(a,{'blank-1':'A'});assert.equal((await session.flush()).ok,true);const loaded=make(storage);assert.equal(loaded.snapshot().data.records[key].history.length,0);assert.equal(loaded.snapshot().data.records[key].draft.values['blank-1'],'A');session.dispose();});
test('same-version answer assessment input or reference change cannot silently rewrite historical meaning',()=>{const d=blankSourceData();editSourceDraft(d,a,{'blank-1':'D'},stamp);for(const mutate of [v=>v.fields[0].answer='A',v=>v.fields[0].assessment='ungraded',v=>v.fields[0].input='text',v=>v.fields[0].answerSource.pdfPage=2,v=>v.fields[0].reference={zh:'新参考',vi:'Gợi ý mới'},v=>v.figureSHA256='0'.repeat(64)]){const changed=structuredClone(a);mutate(changed);assert.throws(()=>editSourceDraft(d,changed,{'blank-1':'D'},stamp+1),/版本/);}assert.deepEqual(validateSourceData(d),d);});
test('source timestamps are valid JavaScript dates, never merely safe integers',()=>{const d=blankSourceData();editSourceDraft(d,a,{'blank-1':'D'},stamp);d.records[key].history=[{id:'dated',at:stamp,values:{'blank-1':'D'}}];for(const where of ['draft','history']){const invalid=structuredClone(d);if(where==='draft')invalid.records[key].draft.updatedAt=Number.MAX_SAFE_INTEGER;else invalid.records[key].history[0].at=Number.MAX_SAFE_INTEGER;assert.throws(()=>validateSourceData(invalid));}d.records[key].history[0].at=8640000000000000;assert.doesNotThrow(()=>new Date(validateSourceData(d).records[key].history[0].at).toISOString());});
test('single-domain submission candidate rejects edits and raw changes while waiting, preserves existing recovery',async()=>{const storage=memory(),initial=make(storage);initial.edit(d=>editSourceDraft(d,a,{'blank-1':'D'},stamp));await initial.save();await initial.confirm(initial.previewReplacement(blankSourceData(),'reset'));const recovery=JSON.parse(storage.values.get(SOURCE_STORAGE_KEY)).recovery;const session=createSourceSession(initial,()=>stamp);assert.equal((await session.submit(a,{'blank-1':'A'})).ok,true);assert.deepEqual(JSON.parse(storage.values.get(SOURCE_STORAGE_KEY)).recovery,recovery);session.dispose();for(const scenario of ['edit','raw','dispose','abort']){let release;const barrier=new Promise(r=>release=r),store=make(storage,{lock:async task=>{await barrier;return task();}});const candidate=store.snapshot().data;candidate.records[key].history.push({id:'not-committed-'+scenario,at:stamp,values:{'blank-1':'B'}});const abort=new AbortController(),pending=store.saveCandidate(candidate,abort.signal),before=storage.values.get(SOURCE_STORAGE_KEY);if(scenario==='edit')store.edit(d=>editSourceDraft(d,a,{'blank-1':'C'},stamp));if(scenario==='raw')storage.values.set(SOURCE_STORAGE_KEY,before+' ');if(scenario==='dispose')store.dispose();if(scenario==='abort')abort.abort();release();assert.equal((await pending).ok,false);assert.equal(storage.values.get(SOURCE_STORAGE_KEY),scenario==='raw'?before+' ':before);assert.equal(store.snapshot().data.records[key].history.some(h=>h.id==='not-committed-'+scenario),false);}});
test('independent editorial corrections preserve six-person source, neutral image metadata, printed tones and non-aligned Vietnamese glosses',()=>{const family=sourceLesson.activities.find(a=>a.id.endsWith('picture-01'));assert.equal(family.fields[0].reference.zh,'六口人');assert.equal(family.fields[0].reference.vi,'sáu người');const svg=fs.readFileSync(new URL('../content/source-activities/figures/picture-01.svg',import.meta.url),'utf8');assert.equal((svg.match(/<g transform="translate\(/g)??[]).length,6);const warm=sourceLesson.figures.find(f=>f.id==='warmup-03');assert.equal(warm.alt.zh,'课桌后有三个人，其中两人举手。');assert.doesNotMatch(warm.alt.vi,/học sinh/i);for(const a of sourceLesson.activities.filter(a=>a.kind==='image-match'))assert.equal(a.fields[0].options.find(o=>o.zh==='学生').py,'xuéshēng');assert.match(sourceLesson.activities.find(a=>a.id.endsWith('listen-text2-01')).pinyin,/yí gè/);assert.deepEqual(sourceLesson.activities.find(a=>a.id.endsWith('listen-text3-01')).fields[0].options.map(o=>o.py),['yí gè','liǎng gè','sān gè']);assert.equal(sourceLesson.numberTables.two[3].py,'liǎng gè rén');for(const ending of ['cloze-02','cloze-04']){const a=sourceLesson.activities.find(a=>a.id.endsWith(ending));assert.doesNotMatch(a.prompt.vi,/＿＿/);assert.match(a.prompt.vi,/không tương ứng từng từ/);}});

test('IME start during a locked source submission cancels history while retaining old submissions and draft',async()=>{
 const storage=memory();let hold=false,release;const gate=new Promise(r=>release=r);const store=make(storage,{lock:async task=>{if(hold)await gate;return task()}}),session=createSourceSession(store,()=>stamp),open=sourceLesson.activities.find(a=>a.kind==='picture-description'),values=Object.fromEntries(open.fields.map(f=>[f.id,'六口人'])),openKey=open.id+'@'+open.version;
 assert.equal((await session.submit(a,{[a.fields[0].id]:a.fields[0].answer})).ok,true);const old=structuredClone(store.snapshot().data.records[key]);session.edit(open,values);await session.flush();hold=true;const pending=session.submit(open,values);session.setComposing(open.id,true);hold=false;release();assert.equal((await pending).ok,false);assert.equal(store.snapshot().data.records[openKey].history.length,0);assert.equal((await session.submit(open,values)).code,'composing');session.setComposing(open.id,false);await session.flush();assert.equal(JSON.parse(storage.getItem(SOURCE_STORAGE_KEY)).data.records[openKey].history.length,0);assert.deepEqual(store.snapshot().data.records[key],old);assert.equal((await session.submit(open,values)).ok,true);assert.equal(store.snapshot().data.records[openKey].history.length,1);assert.deepEqual(store.snapshot().data.records[key],old);session.dispose();
});
