"""Seven original-source localized observations with explicit per-ID decisions."""
import hashlib,importlib.util,json,pathlib,subprocess
import numpy as np
from scipy.linalg import solve_toeplitz
from scipy.signal import lfilter
ROOT=pathlib.Path(__file__).resolve().parents[2]
BASE=ROOT/'course-app/docs/final-quality-20261006/audio-hsk2/closure-followup'
OUT=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-hsk2-localized'
REPORT=ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk2-paired-full-01.json'
ORDINALS=[139,140,142,152,156,158,159]
FORMANT_SCOPES={142:[5.08,5.14,5.2,5.25],152:[30.7,30.76,30.82,30.88,30.94],156:[16.62,16.67,16.71,16.75,16.78],158:[13.02,13.08,13.14,13.2,13.25]}
NOTES={
139:'The original selected two-syllable utterance includes the brief unaspirated onset around 15.08 followed by the high-i-like nucleus through 15.29, then the n-like transition and central/e-like voiced body through 15.60. There is no leading B/Bi letter substitution in the runtime text: actual small B諾 and medium 皮諾 predictions are retained. Original full medium and independent CTC both locate 笔呢; the printed parent explicitly contains Bǐ ne?. The complete utterance and both quiet margins are present, and neither adjacent question nor answer enters this crop.',
140:'The original complete 你洗得真快啊 utterance is present within 27.6599375–29.3800625. In the displayed original spectrum the short xi-like second syllable has a high-front i-like body before the de-like central vowel transition; its word identity is supported by the preceding source dialogue about 洗手/洗完. Actual small 你洗得真快呀! and medium 你写得真快啊! remain unchanged. The final ai-like vowel passes into the final particle with a connected glide: canonical printed a! and the actual small-model ya! glyph observation are distinguished, not silently rewritten as identical transcripts. This source-frame decision retains the original recording and printed lesson, and does not certify every phoneme or tone.',
142:'The complete original sentence and boundary buffers are present, but its last dian/nasal tail does not provide an unambiguous independently identifiable rhotic phase in this localized spectrum. Small retains 儿 while medium, whole source and CTC omit it. This is not evidence that the original lacks 儿; the unresolved rhotic identity remains held rather than approved by printed script or a single prediction.',
152:'The entire original two-clause utterance is inside 29.5999375–34.30. The dian tail around 30.75–31.03 has a continuing vowel/resonance transition before the genuine silence preceding the next clause, rather than a cut at a model token endpoint. Original spectrum and actual LPC candidates show the upper resonance descending toward about 2.3–2.6 kHz during this tail; the fixed CTC native transcript retains 点儿. These independent localized cues, original printed diǎnr and the complete source/crop extent support retention of this single original utterance. The two Whisper outputs and whole-source omission of 儿 remain explicitly recorded and are not treated as proof of absence. The unrelated 因/阴 script observation in the crop is resolved using the pinned printed next clause about 阴天下雪, not a new audio token.',
156:'The complete utterance encloses the dian tail and following ba as separate connected source phases. After the dian body around 16.54–16.69, original spectrum and LPC show a short lowered upper resonance around 16.71–16.78 (roughly 2.3–2.7 kHz) before the ba-like release/body after 16.82. The native CTC retains 点儿吧. With actual printed yìdiǎnr ba and the complete source-frame/neighbor review, these concrete original cues support this source utterance despite the retained Whisper/whole-source omission of 儿. No standalone extra 儿 syllable is asserted, and no full phoneme/tone certificate is claimed.',
158:'The complete original utterance retains the zhe/r-like connected interval around 13.05–13.28 before the distinct duo-like onset after 13.3. The original localized spectrum has a low upper resonance near 1.83–1.86 kHz through 13.14–13.25; actual LPC reproduces that band. This localized original cue and native CTC 在这儿 distinguish the source-linked rhotic transition from relying on the printed character alone. Both Whisper and whole-source omission of 儿 remain unchanged. All surrounding sentence phases and original quiet margins are inside the crop, with neither neighboring source line included.',
159:'The name at the beginning has a complete high-front i-like first body around .69–.83 and an f-like frication followed by the ei-like second body around .85–1.2. The whole unprompted source retains 一飞, while small 义非, medium 易飞 and CTC 一菲 retain their different original glyph observations. The printed original source Yīfēi identifies the character spelling and named source occurrence; spelling is not inferred by silently substituting homophones, and this source-frame review does not certify first-syllable tone. The entire following utterance and final nasal/release lie inside the fixed crop through 5.86, with no adjacent source speech included.'}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def checked(r):
 p=ROOT/r['file'];assert sha(p)==r['sha256'];return json.loads(p.read_text())
def load(name,file):
 s=importlib.util.spec_from_file_location(name,pathlib.Path(__file__).with_name(file));m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 OUT.mkdir(parents=True,exist_ok=True);support=load('localized_support','review-decisions.py');syllable=load('localized_syllable','review-syllable-evidence.py');facts=json.loads((BASE/'current173-source-frame-facts-v2.json').read_text())['targets'];localized=json.loads((BASE/'localized-sentence-phases.json').read_text())['targets'];review=json.loads(REPORT.read_text())['targets'];observations=[];decisions=[]
 for ordinal in ORDINALS:
  f=facts[ordinal];r=next(x for x in review if x['id']==f['id'] and x['sourceSampleRange16k']==f['sourceSampleRange16k']);loc=next(x for x in localized if x['poolOrdinal']==ordinal);s,e=r['sourceSampleRange16k'];p=ROOT/'course-app/public'/r['sourceTrack'];assert sha(p)==r['sourceSHA256'];b=subprocess.run(['ffmpeg','-nostdin','-v','error','-threads','1','-i',str(p),'-ac','1','-ar','16000','-f','f32le','-'],capture_output=True,check=True).stdout;assert hashlib.sha256(b).hexdigest()==r['sourcePCM_SHA256'];assert hashlib.sha256(b[s*4:e*4]).hexdigest()==r['cropPCM_SHA256'];a,z=loc['localizedPlotScope16k'];assert hashlib.sha256(b[a*4:z*4]).hexdigest()==loc['localizedPCM_SHA256'];assert sha(ROOT/loc['plotEvidence']['file'])==loc['plotEvidence']['sha256']
  canonical=r['canonicalSource'];obj=syllable.pointer(checked(canonical),canonical['sourceJSONPointer']);assert obj['zh']==canonical['parentZH'] and obj['py']==canonical['sourcePinyin'];models=[]
  for m in r['rawModelEvidence']:
   raw=checked(m);support.unprompted(raw);assert raw['sourceSampleRange16k']==[s,e] and raw['cropPCM_SHA256']==r['cropPCM_SHA256'] and raw['originalSourceSHA256']==r['sourceSHA256'];assert ''.join(x['text'] for x in raw['rawSegments'])==m['rawTranscript'];models.append({'file':m['file'],'sha256':m['sha256'],'unalteredRawTranscript':m['rawTranscript'],'retainedHolds':m['holds']})
  whole=[]
  for w in f['wholeSourceUnpromptedEvidence']:
   raw=checked(w);support.unprompted(raw);assert raw.get('cropPCM_SHA256',raw.get('track',{}).get('pcm',{}).get('sha256'))==r['sourcePCM_SHA256'];assert ''.join(x['text'] for x in raw['rawSegments'])==w['wholeSourceTranscript'];whole.append({'file':w['file'],'sha256':w['sha256'],'unalteredRawTranscript':w['wholeSourceTranscript']})
  ctc=f['independentCTCActualCropEvidence'];raw=checked(ctc);assert raw['rawText']==ctc['rawText'] and raw['cropPCM_SHA256']==r['cropPCM_SHA256'] and raw['expectedTextPromptUsed'] is False;assert json.loads(raw['rawResultString'])==raw['rawResult'];pcm=np.frombuffer(b,dtype='<f4');formants=[]
  for t in FORMANT_SCOPES.get(ordinal,[]):
   frame=[int((t-.015)*16000),int((t+.015)*16000)];x=pcm[frame[0]:frame[1]:2];x=lfilter([1,-.97],[1],x)*np.hamming(len(x));ac=np.correlate(x,x,'full')[len(x)-1:len(x)+18];co=np.r_[1,solve_toeplitz(ac[:18],-ac[1:19])];roots=np.roots(co);roots=roots[roots.imag>0];freq=np.angle(roots)*8000/(2*np.pi);bw=-np.log(abs(roots))*8000/np.pi;formants.append({'originalSourceFrames':frame,'centerSeconds':t,'actualLPCResonanceCandidatesHzBandwidthHz':sorted([round(float(v)),round(float(w))] for v,w in zip(freq,bw) if 100<v<3500 and 0<w<500),'notAnAutomaticRhoticOrToneClassification':True})
  obs={'id':r['id'],'sourceTrack':r['sourceTrack'],'sourceSHA256':r['sourceSHA256'],'sourcePCM_SHA256':r['sourcePCM_SHA256'],'sourceSampleRange16k':[s,e],'cropPCM_SHA256':r['cropPCM_SHA256'],'canonicalSource':canonical,'actualOriginalPlotEvidence':loc['plotEvidence'],'actualWhisperBindings':models,'actualWholeSourceEvidence':whole,'actualCTCEvidence':{'file':ctc['file'],'sha256':ctc['sha256'],'unalteredRawTranscript':ctc['rawText']},'actualLocalizedLPCObservations':formants,'actualLPCCalculation':{'sourceSampleRate':16000,'analysisSampleRate':8000,'windowFrames':480,'preemphasis':.97,'hammingWindow':True,'order':18,'formantCandidatesAreNotCertifiedPhonemes':True},'explicitIndependentDecision':'hold-unresolved-rhotic-identity' if ordinal==142 else 'recommend-accept-source-bound-complete-original-utterance','rationale':NOTES[ordinal],'humanListening':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False};observations.append(obs)
  d={'id':r['id'],'sourceSampleRange16k':[s,e],'decision':'hold' if ordinal==142 else 'accept','sourceContextChecked':True,'acknowledgedFlags':r['flags'],'rationale':NOTES[ordinal],'humanListening':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False}
  if ordinal!=142:
   proof={k:r[k] for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};proof.update({'sourceText':r['sourceZH'],'sourcePinyin':r['sourcePinyin'],'wholeSourceGroupUnpromptedASRReviewed':True,'sourceOrderChecked':True,'neighborSpeechExcluded':True,'actualCropBoundariesChecked':True,'phoneticEquivalenceIsAuxiliaryOnly':True,'sourceGroupEvidence':{'file':whole[0]['file'],'sha256':whole[0]['sha256']},'rawDifferences':{'pure':models,'whole':whole,'CTC':obs['actualCTCEvidence']},'explanation':NOTES[ordinal]});d.update({'resolvedTextHolds':sorted(set(r['holds']) & support.TEXT_REVIEW_HOLDS),'resolvedSourceHolds':sorted(set(r['holds']) & support.SOURCE_REVIEW_HOLDS),'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[],'sourceContextEvidence':proof});support.contextual_decision(r,d,ROOT)
  decisions.append(d)
 p=OUT/'fresh-original-localized-source-observations.json';p.write_text(json.dumps({'schemaVersion':1,'producer':ref(pathlib.Path(__file__)),'originalLocalizedInput':ref(BASE/'localized-sentence-phases.json'),'records':observations,'automaticApproval':False},ensure_ascii=False,indent=2)+'\n');out=OUT/'seven-localized-independent-decisions.json';out.write_text(json.dumps({'schemaVersion':1,'reviewReportSHA256':sha(REPORT),'actualOriginalSourceObservations':ref(p),'decisions':decisions,'counts':{'acceptRecommendations':6,'heldRhoticIdentity':1},'runtimeApproved':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps(ref(out)));print('recommendations 6; held 1; no runtime approval')
if __name__=='__main__':main()
