"""Materialize root's explicit decisions after the actual original plots were read."""
import hashlib,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[2]
OUT=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-two-fixed-sources'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def main():
 observations=OUT/'fresh-two-fixed-original-source-observations.json';records=json.loads(observations.read_text())['records']
 for f in records:
  report=ROOT/f['reviewReport']['file'];assert sha(report)==f['reviewReport']['sha256'];r=next(x for x in json.loads(report.read_text())['targets'] if x['id']==f['id'] and x['sourceSampleRange16k']==f['sourceSampleRange16k']);identity={k:r[k] for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};identity['sourceText']=r['sourceZH'];d={'id':r['id'],'sourceSampleRange16k':r['sourceSampleRange16k'],'decision':'accept','sourceContextChecked':True,'acknowledgedFlags':r['flags'],'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False}
  if r['id'].startswith('v-'):
   explanation='The independently viewed original full 9-2 recording has two complete recorded 那个 readings, not four. Both show the low nasal onset, open stable/descending a-like vowel, and independent short g/e final inside the printed source-head window between 家 and 外边. The selected first original reading is complete at 11.22–12.07 with quiet edges, containing the real low initial nasal before the vowel and the full weak final around 11.84–11.96. Both real recorded variants are compatible with the printed nàge alternative; printed nàge / nèige remains unchanged. No unrecorded nèige alternative or tone certificate is asserted. Actual pure 納克/NOG and supplemental CTC 那个 are all retained; neither the model glyphs nor speaker gender determines pronunciation.'
   proof={**identity,'sourcePinyin':r['sourcePinyin'],'wholeSourceGroupUnpromptedASRReviewed':True,'sourceOrderChecked':True,'neighborSpeechExcluded':True,'actualCropBoundariesChecked':True,'phoneticEquivalenceIsAuxiliaryOnly':True,'originalRepeatedReadingsChecked':True,'sourceGroupEvidence':f['originalWholeSourceEvidence'][0],'originalPrintedSource':f['originalPrintedSource'],'independentOriginalSourceObservations':ref(observations),'originalReadingFacts':f['sourceFact'],'rawDifferences':[{'model':x['file'],'raw':x['unalteredRawTranscript'],'retained':True} for x in f['actualWhisperBindings']],'selectedCompleteOriginalReadingFrames16k':[181280,191360],'actualOriginalReadingCount':2,'selectedLegalRecordedAlternative':'nàge-compatible original source reading','unrecordedAlternativeClaim':False,'pronunciationToneCertified':False,'explanation':explanation};d.update({'rationale':explanation,'sourceContextEvidence':proof,'resolvedTextHolds':r['holds'],'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[]});name='nage-complete-recorded-variant-independent-decision.json'
  else:
   onset='The first b-like release and complete open a body begin around 17.23, after the real quiet lead-in. The following aspirated/front frication around 17.43–17.55 and full i/an body/nasal tail around 17.56–17.72 are present. The second b release around 17.74 and a vowel continue through 17.87 before the 17.90 cut.'
   final='All three original bā/qiān/bā syllable bodies, continuous transitions and final decay are preserved. The previous 真不便宜 ends before 16.55, well before the 16.86 cut; there is no later lexical speech in the selected source tail. The four actual edge windows are quiet. Both pure Whisper snapshots and the separately verified native CTC retain exactly 八千八; the original full-source 8800 spelling is retained as a separate context observation and is never converted to approve this crop.'
   wave=OUT/(r['candidateId']+'-independent-waveform-observation.json');wave.write_text(json.dumps({**identity,'plots':[{'id':r['id'],'sourceSampleRange16k':r['sourceSampleRange16k'],'cropPCM_SHA256':r['cropPCM_SHA256'],**f['actualSourcePlot']}]},ensure_ascii=False,indent=2)+'\n')
   numeric={**identity,'category':'single-fixed-original-three-syllable-numeral-utterance','completeOriginalNumeralUtteranceIndependentlyReviewed':True,'allThreePrintedSyllablesPresentInSourceOrder':True,'noDigitOrAlternateNumberConversion':True,'originalSyllableComponents16k':[{'originalPrintedPinyin':'bā','sourceSampleRange16k':[275360,278720],'onsetRimeAndFinalExplanation':'Complete first original b release plus a vowel/decay inside the first original 17.21–17.42 phase.'},{'originalPrintedPinyin':'qiān','sourceSampleRange16k':[278720,283584],'onsetRimeAndFinalExplanation':'Actual front frication then voiced i/an and full nasal tail precede the final b release, preserving the connected 17.42–17.724 phase.'},{'originalPrintedPinyin':'bā','sourceSampleRange16k':[283584,286080],'onsetRimeAndFinalExplanation':'Final real b-like release and complete a body/decay occur inside 17.724–17.88, before the quiet cut.'}],'independentOriginalSourceObservations':ref(observations),'explanation':onset+' '+final}
   proof={**identity,'category':'triple-literal-noSpeech-proxy-review','independentFixedNumericUtteranceReviewEvidence':numeric,'independentlyVerifiedCTCSupplementalEvidence':ref(ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk2-current173-independent-ctc-source-frame-review-01.json'),'waveformObservation':ref(wave),'actualSyllableFeatureEvidence':f['actualSyllableFeatureEvidence'],'selectedCompleteOriginalReadingFrames16k':[273760,285600],'independentlyReviewedNeighborLimits16k':[264640,297216],'originalPrintedSource':{k:f['originalPrintedSource'][k] for k in ['file','sha256','sourceJSONPointer']},'sourceUtteranceEvidence':{'canonicalSourceId':r['canonicalSource']['sourceId'],'sentenceOrdinal':2,'parentZH':r['canonicalSource']['parentZH'],'actualUtteranceFrames16k':[273760,285600],'previousActualSpeechFrames16k':[251680,264640],'followingActualSpeechFrames16k':None,'completeOriginalUtteranceIndependentlyReviewed':True,'wholeSourceEvidence':f['originalWholeSourceEvidence']},'completeOriginalOnsetRimeAndFinalReviewed':True,'neighborPhonemesExcluded':True,'sourceOrderChecked':True,'originalPrintedPronunciationChecked':True,'allASRWarningsRetained':True,'noSyntheticPadding':True,'phonemeIdentityUnknown':False,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False,'onsetExplanation':onset,'rimeAndFinalExplanation':final,'originalReadingExplanation':'Actual freshly decoded original source and exact three-syllable crop, printed second sentence Bā qiān bā, all original raw transcripts and concrete three original speech phases were independently read; no numeric/letter conversion, synthetic padding or inferred tone certification.','explanation':onset+' '+final};d.update({'rationale':onset+' '+final,'tripleLiteralNoSpeechDecisionEvidence':proof,'resolvedTextHolds':[],'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':r['holds']});name='ba-qian-ba-fixed-original-utterance-independent-decision.json'
  p=OUT/name;p.write_text(json.dumps({'schemaVersion':1,'reviewReportSHA256':sha(report),'independentOriginalSourceObservations':ref(observations),'producer':ref(pathlib.Path(__file__)),'decisions':[d],'automaticApproval':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps(ref(p)))
if __name__=='__main__':main()
