"""Two source-context decisions and two complete original utterance proposals."""
import copy,hashlib,importlib.util,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[2]
OUT=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-hsk2-four-final'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def module(name,file):
 s=importlib.util.spec_from_file_location(name,pathlib.Path(__file__).with_name(file));m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 support=module('four_final_context','review-decisions.py');features=module('four_final_features','review-syllable-evidence.py');fresh_path=OUT/'fresh-four-final-original-source-observations-v1.json';fresh=json.loads(fresh_path.read_text())['records'];previous_path=ROOT/'course-app/docs/final-quality-20261006/audio-context-peer-hsk2-rhotic/combined24-original-core-r-recording-explicit-decisions.json';previous=json.loads(previous_path.read_text())['decisions'];report=ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk2-paired-full-01.json';rows=json.loads(report.read_text())['targets'];ordinary=[];proposals=[]
 explanations={
 130:'The original complete sentence retains both shu-like frication and rounded high-vowel bodies around 20.64–20.98, then the two separate f-like high-frequency onsets and u bodies around 21.00–21.44, followed by the short centralized de before 睡一觉. These four actual source syllables are in the exact printed shūshūfúfú de reduplication in the full dialogue. Small 叔叔夫夫的, medium 舒舒服服地 and CTC 舒舒服服的 remain their actual predictions; 的/地 are the specific publisher grammar spelling of this /de/ occurrence, not an audible global character substitution. The entire 明天不上学 / 他们说要…睡一觉 / 让我们…起床 sequence and final chuang nasal/release through about25.38 are retained. The prior independently reviewed localized 晚点儿 source r variant is incorporated unchanged, without asserting a tone certificate.',
 145:'The original first name has the complete front release/frication around16.42–16.49, ia-like body through16.63, then a separately connected rounded/high-front entry and e-like vowel movement through16.90 before the real pause. The complete two-syllable printed Jiāyuè/家月 source name in this dialogue and its earlier occurrence is present, followed by the complete 你想不想吃点儿东西 question. Small 佳玉, medium 佳月 and CTC 佳悦 are retained as different decoder spellings. Actual name movement and whole source order, rather than a general yu/yue replacement or inferred tone, establish the exact source occurrence. The independently signed connected 点儿 cue and final 西 release before19.18 are retained; neither previous answer nor the following 吃点儿吧 enters this crop.',
 146:'The actual original utterance begins with the full ch-like frication/i body around20.50–20.78, then the separate dian body with the connected descending upper-resonance tail through21.14 before the independent ba onset around21.20. The full source preserves 身体 / 不舒服时 / 更要 / 好好 / 吃饭 in order, with all voiced bodies and the final fan nasal/release before24.70. The original lower vowel bands and localized LPC descending upper band before ba support the source-bound diǎnr interval; the source is not cut at the decoder 点 endpoint. The preceding question ends before19.18 and the following 吃点什么呢 starts after26.15, both excluded. Every existing no-speech probability and omission of 儿 remains unchanged. This complete original physical review supports this exact utterance diagnostic only, not a general word no-speech exception.',
 157:'The original sentence preserves the full aspirated t-like onset near5.77–5.86, open a body through6.05 and complete connected 告诉我 / 是在网上买的 sequence. Original Tā is bound to the printed 她 and preceding 安妮 at this exact source occurrence; audio does not distinguish the gender character from decoder 他. After the genuine internal pause, 比我的本子 / 贵一点儿 retain complete bodies, the connected centralized dian late tail through10.82 and final decay before10.85. The independent localized spectrum/LPC has a continuing upper-resonance movement toward about2.56–2.70kHz before genuine quiet, not a following word. The previous source clause ends around4.9 and the following 我们班同学 begins after11.6, outside the crop. The original two-model no-speech diagnostic, raw 他 and omitted 儿 spellings stay recorded and are reviewed only for this complete printed-source utterance.'}
 for f in fresh:
  o=f['poolOrdinal'];r=next(x for x in rows if x['id']==f['id'] and x['sourceSampleRange16k']==f['sourceSampleRange16k']);old=next(x for x in previous if x['id']==r['id'] and x['sourceSampleRange16k']==r['sourceSampleRange16k']);context=copy.deepcopy(old.get('sourceContextEvidence',old.get('unapprovedOriginalSourceContextEvidence')));context.update({'sourcePinyin':r['canonicalSource']['sourcePinyin'],'originalPrintedSource':{k:r['canonicalSource'][k] for k in ['file','sha256','sourceJSONPointer']},'freshOriginalSourceVerification':ref(fresh_path),'previousIndependentSourceRimeReview':ref(previous_path),'explanation':explanations[o]+' '+old['rationale']});decision={'id':r['id'],'candidateId':r['candidateId'],'sourceSampleRange16k':r['sourceSampleRange16k'],'decision':'accept','sourceContextChecked':True,'acknowledgedFlags':r['flags'],'rationale':explanations[o],'sourceContextEvidence':context,'resolvedTextHolds':sorted(set(r['holds'])&support.TEXT_REVIEW_HOLDS),'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[],'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False}
  if o in [130,145]:
   support.contextual_decision(r,decision,ROOT);ordinary.append(decision);continue
  pcm=support.original_pcm(ROOT,r);s,e=r['sourceSampleRange16k'];identity={k:r[k] for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};identity['sourceText']=r['sourceZH'];bins=features.features(pcm,s,e);feature_path=OUT/(str(o)+'-fresh-actual-original-feature-bins.json');feature_path.write_text(json.dumps({**identity,'featureBins':bins,'featureBinsSHA256':features.feature_sha(bins),'actualOriginalPCMUnchanged':True,'method':'32ms real original windows at 5ms hops; no tone certificate'},ensure_ascii=False,indent=2)+'\n');wave_path=OUT/(str(o)+'-fresh-original-waveform-observation.json');wave_path.write_text(json.dumps({**identity,'producerEvidence':ref(pathlib.Path(__file__)),'plots':[{**ref(ROOT/f['freshOriginalUtteranceAndNamePlot']['file']),'id':r['id'],'sourceSampleRange16k':[s,e],'cropPCM_SHA256':r['cropPCM_SHA256']}],'actualOriginalSourceAndCorePlotsIndependentlyRead':True},ensure_ascii=False,indent=2)+'\n')
  marks=[s,e];limits=[s,e];neighbor=([255040,306880],[418400,432000]) if o==146 else ([44800,78400],[186400,222400]);source=r['canonicalSource'];physical={**identity,'category':'fixed-complete-original-utterance-source-physical-review','originalPrintedSource':{k:source[k] for k in ['file','sha256','sourceJSONPointer']},'sourceUtteranceEvidence':{'canonicalSourceId':source['sourceId'],'sentenceOrdinal':source['sentenceOrdinal'],'parentZH':source['parentZH'],'actualUtteranceFrames16k':marks,'previousActualSpeechFrames16k':neighbor[0],'followingActualSpeechFrames16k':neighbor[1],'adjacentSpeechFramesAreConservativeOriginalSourceEnvelopesNotCharacterAlignment':True,'completeOriginalUtteranceIndependentlyReviewed':True,'wholeSourceEvidence':[{'file':x['file'],'sha256':x['sha256']} for x in f['actualWholeSourceRawEvidence']]},'waveformObservation':ref(wave_path),'actualSyllableFeatureEvidence':ref(feature_path),'independentlyVerifiedCTCSupplementalEvidence':ref(ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk2-current173-independent-ctc-source-frame-review-01.json'),'selectedCompleteOriginalReadingFrames16k':marks,'independentlyReviewedNeighborLimits16k':limits,'completeOriginalOnsetRimeAndFinalReviewed':True,'neighborPhonemesExcluded':True,'sourceOrderChecked':True,'originalPrintedPronunciationChecked':True,'allASRWarningsRetained':True,'noSyntheticPadding':True,'phonemeIdentityUnknown':False,'onsetExplanation':explanations[o],'rimeAndFinalExplanation':old['rationale'],'originalReadingExplanation':'Actual freshly decoded original source, canonical printed text/pinyin, complete original source/crop spectrum and unchanged two-model native/CTC bytes were independently checked. No synthetic padding, ASR timestamp repair or automatic certification.','explanation':explanations[o],'previousIndependentLocalizedReview':ref(previous_path),'freshWholeSourceIndependentVerification':ref(fresh_path),'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False};decision.update({'decision':'hold-until-exact-utterance-registry-and-central-independent-approval','actualOriginalUtteranceSourcePhysicalEvidence':physical,'retainedDecoderHolds':sorted(set(r['holds'])&support.DECODER_DIAGNOSTIC_HOLDS),'actualUnmodifiedTwoModelRawWhitelist':[{k:x[k] for k in ['file','sha256','modelRepository','modelRevision','rawTranscript']} for x in r['rawModelEvidence']],'actualUnmodifiedCTCRawWhitelist':f['actualCTCRawEvidence'],'productionApproved':False});proposals.append(decision)
 for name,items in [('two-final-source-context-independent-decisions.json',ordinary),('two-fixed-original-utterance-independent-physical-proposals.json',proposals)]:
  p=OUT/name;p.write_text(json.dumps({'schemaVersion':1,'reviewReportSHA256':sha(report),'producerEvidence':ref(pathlib.Path(__file__)),'actualFreshOriginalSourceVerification':ref(fresh_path),'decisions':items,'automaticApproval':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps({**ref(p),'actualDecisions':len(items)}))
if __name__=='__main__':main()
