"""Two explicit original vowel decisions after actual source/control plots were read."""
import hashlib,importlib.util,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[2]
BASE=ROOT/'course-app/docs/final-quality-20261006/audio-hsk1/remaining14-original-reading-contrast'
OUT=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-hsk1-vowel-controls'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def checked(r):
 p=pathlib.Path(r['file']);p=p if p.is_absolute() else ROOT/p
 assert sha(p)==r['sha256'];return json.loads(p.read_text())
def module(name,file):
 s=importlib.util.spec_from_file_location(name,pathlib.Path(__file__).with_name(file));m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 OUT.mkdir(parents=True,exist_ok=True);support=module('two_vowels_context','review-decisions.py');features=module('two_vowels_features','review-syllable-evidence.py')
 proposal_path=BASE/'actual-reading-components-and-source-proposals-01.json';proposal=json.loads(proposal_path.read_text());fine_path=BASE/'ne-and-yu-actual-vowel-resonance-observations.json';fine=json.loads(fine_path.read_text());rain_path=BASE/'yu-and-original-xiayu-same-source-comparison.json';rain=json.loads(rain_path.read_text())
 for group in fine['comparisons']:
  plot=group['actualVowelPlot'];assert sha(ROOT/plot['file'])==plot['sha256']
 assert sha(ROOT/rain['actualPlot']['file'])==rain['actualPlot']['sha256'];checked(rain['exactOriginalWholeSourceUnpromptedRaw']);control=rain['printedControlWord'];control_path=ROOT/control['sourceLessonFile'];assert sha(control_path)==control['sourceLessonSHA256'];assert features.pointer(json.loads(control_path.read_text()),control['sourceJSONPointer'])=='下雨';assert features.pointer(json.loads(control_path.read_text()),control['sourceJSONPointer'].rsplit('/',1)[0])['py']==control['sourcePinyin']
 report=ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk1-paired-full-03.json';rows=json.loads(report.read_text())['targets'];decisions=[];observations=[]
 descriptions={
 'v-l04-lex-dcf66dcd60-s1':'The original first nasal lead at 3.335–3.370, sustained vowel at 3.370–3.475 and natural release through 3.535 are complete. The actual first nucleus retains persistent broad bands near 0.7–0.9 kHz and 1.4 kHz. In the independently accepted original 呢/ne at lesson 7 the first nucleus has corresponding sustained central bands; the two second readings also show corresponding approximately 0.9–1.0 and 1.8–1.9 kHz bands. This concrete source comparison resolves the isolated decoder open-vowel spelling as a source-context prediction; it is not a speaker match, certified formant identification or tone certificate. The exact printed 呢/ne head is between 妹妹 and 女儿 in the full original source, with one complete first reading and no neighboring syllable.',
 'v-l12-lex-8995b89799-s1':'The first original 雨/yǔ reading preserves its rounded/high-front entry at 13.280–13.305, the complete high/front nucleus through 13.795 and natural tail through 13.900. Its weak/creaky middle belongs to that single syllable and is not another repetition. The actual same original 12-2 track contains the printed 下雨/xià yǔ head before 了 and 雨: its first 雨 body around 8.67–9.20 and second around 10.08–10.80 retain the corresponding weak/creaky high-front nucleus and approximately 2.3–2.6 kHz resonance region seen in both isolated original 雨 readings. This same-source, printed-head and full-source comparison establishes the retained source syllable; a model’s long whole-word timestamp is not used as its phoneme boundary. No neighboring 有点儿 is included, and no certified vowel/formant/tone identity is claimed.'}
 for id,explanation in descriptions.items():
  target=next(t for t in proposal['targets'] if t['id']==id);v=next(z for z in target['variants'] if z['selectedOriginalRepetition']==1);r=next(z for z in rows if z['id']==id and z['sourceSampleRange16k']==v['sourceSampleRange16k']);s,e=r['sourceSampleRange16k'];pcm=support.original_pcm(ROOT,r);assert hashlib.sha256(pcm[s*4:e*4]).hexdigest()==r['cropPCM_SHA256'];printed=v['originalCatalogPrintedObject'];obj=features.pointer(checked(printed),printed['sourceJSONPointer']);assert obj['id']==id and obj['zh']==r['sourceZH'] and obj['py']==r['sourcePinyin'];assert v['allFourActualQuietWindows'] is True
  for m in v['actualWhisperRaw']:
   raw=checked(m);support.unprompted(raw);assert raw['sourceSampleRange16k']==[s,e] and raw['cropPCM_SHA256']==r['cropPCM_SHA256'];assert ''.join(q['text'] for q in raw['rawSegments'])==m['rawTranscript']
  ctc=checked(v['actualIndependentCTCRaw']);assert ctc['cropPCM_SHA256']==r['cropPCM_SHA256'] and ctc['expectedTextPromptUsed'] is False
  whole=checked(v['wholeSourceEvidence']);support.unprompted(whole);assert whole.get('cropPCM_SHA256',whole.get('track',{}).get('pcm',{}).get('sha256'))==r['sourcePCM_SHA256'];assert not set(r['holds'])&support.DECODER_DIAGNOSTIC_HOLDS
  identity={k:r[k] for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};identity['sourceText']=r['sourceZH']
  context={**identity,'sourcePinyin':r['sourcePinyin'],'wholeSourceGroupUnpromptedASRReviewed':True,'sourceOrderChecked':True,'neighborSpeechExcluded':True,'actualCropBoundariesChecked':True,'phoneticEquivalenceIsAuxiliaryOnly':True,'originalRepeatedReadingsChecked':True,'sourceGroupEvidence':v['wholeSourceEvidence'],'originalPrintedSource':printed,'actualSourceComparisonEvidence':ref(fine_path),'sameOriginalRainControlEvidence':ref(rain_path) if r['sourceZH']=='雨' else None,'actualWaveformObservation':v['actualWaveformObservation'],'originalSourcePhases':v['actualComponentTransitionProposals'],'supplementalCTCEvidence':v['actualIndependentCTCRaw'],'rawDifferences':[{'model':m['file'],'unalteredRawTranscript':m['rawTranscript']} for m in v['actualWhisperRaw']],'explanation':explanation}
  holds=set(r['holds']);assert holds<=support.TEXT_REVIEW_HOLDS
  decision={'id':id,'sourceSampleRange16k':[s,e],'decision':'accept','sourceContextChecked':True,'rationale':explanation,'acknowledgedFlags':r['flags'],'resolvedTextHolds':sorted(holds),'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[],'sourceContextEvidence':context,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False};support.contextual_decision(r,decision,ROOT);decisions.append(decision);observations.append({'id':id,'sourceSampleRange16k':[s,e],'cropPCM_SHA256':r['cropPCM_SHA256'],'actualOriginalSourceAndControlPlotsRead':True,'independentConcreteSourceExplanation':explanation})
 out=OUT/'two-original-vowel-control-explicit-independent-decisions.json';out.write_text(json.dumps({'schemaVersion':1,'reviewReportSHA256':sha(report),'producerEvidence':ref(pathlib.Path(__file__)),'actualSourceProposal':ref(proposal_path),'actualSourceVowelComparison':ref(fine_path),'actualSameSourceRainControl':ref(rain_path),'originalSourceObservations':observations,'decisions':decisions,'automaticApproval':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps({**ref(out),'actualExplicitDecisions':len(decisions)}))
if __name__=='__main__':main()
