"""Record the root peer's actual source-spectrum observations, never autoapprove."""
import hashlib,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[2]
BASE=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-numerals'
NOTES={
'一':('hold-repair-onset','At the newly displayed actual 2.98–3.17 transition, the first periodic cycle starts around 3.038–3.040. The current 3.045 boundary crosses that first cycle. A proposed 3.035 start must retain the entire original onset and receive new actual-crop inference; the current crop is not approved.'),
'二':('recommend-complete-original-physical-reading','The selected er-like body around 17.66–17.85 and its rhotic tail are inside the actual 17.63–17.855 crop. The following shi-like frication starts after that boundary. The printed original 半斤二十个 supplies this occurrence and its actual èr, distinct from canonical source inference or a numeral digit conversion.'),
'三':('recommend-complete-original-physical-reading','The selected source 苹果三块五一斤 has an s-like frication around 13.03–13.14 and an/an-nasal-like body through about 13.30. The 13.005–13.311 boundaries retain these phases before the following kuai-like onset. Printed sān identifies this actual occurrence; no tone certificate is asserted.'),
'四':('recommend-complete-original-physical-reading','The original tongue-twister printed 四是四，十是十 contains the selected si-like complete reading. Its s-like frication around 1.73–1.90 and apical vowel through about 2.13 remain inside 1.50–2.14. The following shi-like onset is after the selected body, rather than another reading of 四 inserted by a model.'),
'五':('recommend-complete-original-physical-reading','The selected source 这些五块钱一个 has a separate low-frequency u-like body beginning about 12.423 and ending near 12.62, all inside 12.402–12.625. The prior syllable decays before the cut and the following kuai-like onset begins later, around 12.67. Printed wǔ and unchanged original context identify the source reading.'),
'六':('hold-repair-previous-syllable','Fresh 1.24–1.44 source-transition spectrum shows a continuing high-i-like phase from preceding 期 through about 1.348. The current 1.315 boundary includes part of it. The l-like transition into the liu-like body appears around 1.35. A proposed 1.345 start must be checked as a genuine new crop, keeping the complete following tail through the existing 1.80 end.'),
'八':('recommend-complete-original-physical-reading','At the original utterance 身高有一米八 the ba-like attack around 19.60 and complete a-like vowel decay before 19.82 are enclosed by 19.55–19.95. Both neighboring utterance bodies remain outside. Original printed bā is verified separately from model spelling.'),
'九':('recommend-complete-original-physical-reading','This is the actual printed 九个小时 / jiǔ gè xiǎo shí occurrence. A j-like release/frication around 5.36–5.45 passes into the iu-like vowel and tail, which decays before the 5.745 end. The next ge-like attack is after 5.76. The earlier summary neighbor 年 was incorrect and is not used in this decision.'),
'十':('recommend-complete-physical-reading-voicing-proxy-still-separate','The corrected actual 3.40–3.985 crop retains the sh-like frication around 3.58–3.75 and the entire following apical vowel through about 3.98. The source is the printed 四是四，十是十 tongue-twister. Its visible periodic nucleus extends approximately 3.75–3.98. The true existing seven-bin F0-gated result stays unchanged; an independent fixed-source alternative measured-spectrum gate is still required, not a fabricated ten-bin claim.'),
'百':('physical-reading-observed-voicing-proxy-not-yet-approved','The source 这件一百元 has a b-like release at about 4.31 followed by a moving ai-like vowel body through about 4.48, within the actual 4.265–4.485 crop, before the following yuan-like transition. The vowel has irregular cycles. The actual F0-gated three-bin result remains insufficient for the existing automatic proxy. Observed complete spelling/context and vowel alone must not be mislabeled as passing that numerical gate.'),
'千':('hold-repair-following-syllable','The actual source says 几千年 / jǐ qiān nián. After the q-like frication and ian body the nasal tail around 45.865–45.928 declines, but the waveform grows again into the following nian onset around 45.94. The current 45.944 boundary intersects that transition. A proposed 45.925 end must be checked as a genuine new crop; the current boundary is not certified.'),
'两':('recommend-complete-original-physical-reading','The original source is 我们下午两点见吧 / wǒ men xià wǔ liǎng diǎn jiàn ba. The complete liang-like onset and vowel are present after about 12.37. The ng-like low nasal band decays through about 12.657, followed by the low-amplitude closure through about 12.683. The current 12.674 cut lies after the nasal decay and before the following dian release near 12.69, retaining the target tail while excluding the next vowel. This is a source-frame decision and not tone certification.'),
'零':('hold-repair-onset','The printed original is the telephone code ending in 0, not literal Chinese pinyin; its code interpretation remains explicitly separate. In the fresh 10.52–10.70 spectrum the preceding jiu-like tail falls before the l-like constriction/transition around 10.584–10.590, followed by the ling-like strong i body around 10.60. The current 10.590 start may omit the beginning of the l transition. A proposed 10.5825 start requires new actual-crop inference and physical boundary verification; the old crop stays held.')}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def main():
 p=BASE/'fresh-original-source-transition-observations.json';x=json.loads(p.read_text());records=[]
 for r in x['records']:
  decision,note=NOTES[r['sourceZH']];records.append({k:r[k] for k in ['id','sourceZH','sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']});records[-1].update({'producerFacts':r['producerFacts'],'independentPhysicalRecommendation':decision,'explanation':note,'actualOriginalWaveformAndSpectrumReadByRoot':True,'originalPrintedSourceAndPinyinChecked':True,'rawModelDiagnosticsUnchanged':True,'runtimeApproved':False,'humanListening':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False})
 out=BASE/'explicit-independent-physical-recommendations.json';out.write_text(json.dumps({'schemaVersion':1,'producer':ref(pathlib.Path(__file__)),'freshSourceObservations':ref(p),'records':records,'automaticPrecisionApproval':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps(ref(out)))
if __name__=='__main__':main()
