"""Independent actual-source review of four explicitly printed alternatives."""
import hashlib,importlib.util,json,pathlib,subprocess
ROOT=pathlib.Path(__file__).resolve().parents[2]
BASE=ROOT/'course-app/docs/final-quality-20261006/audio-hsk1/four-alternative-original-reading-observations'
OUT=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-four-alternatives'
REPORT=ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk1-paired-full-03.json'
NOTES={
'谁':'The four actual source readings have two distinct vowel-transition classes repeated within each source voice: original readings 1/3 show a lower resonance beginning near 1.7–1.8 kHz, while 2/4 begin nearer 1.1 kHz then rise. This is an original within-voice vowel contrast and does not infer a pronunciation from the speaker identity. The selected middle readings 2 and 3 include the complete sh-like onsets and both full vowel tails, separated by genuine original silence. They retain the ui-like then ei-like source classes corresponding to the two explicitly printed legal forms shuí and shéi. Printed shéi / shuí stays unchanged; vowel-class order is stated separately and no certified tone/order claim is made. Actual small 水谁, medium 谁 and CTC 谁谁 are retained, including model repetition suppression and the 水 glyph observation, rather than rewritten into agreement.',
'里':'The actual original four readings are short-long-short-long: about 5.45–5.63, 6.85–7.44, 8.34–8.58 and 9.43–10.20. Each original voice contains the same short/long contrast. The selected middle two retain the entire long l/i body and then the entire short l/i body, with their quiet margins and no other lexical head. This explicitly printed li / lǐ alternative unit retains two original contrasting legal readings rather than two arbitrary repetitions of an ordinary word. The observed long→short order is distinct from the unchanged printed slash order; it is not presented as tone certification.',
'边':'The original source contains the actual short-long-short-long contrast around 3.73–3.87, 4.90–5.34, 6.13–6.33 and 7.34–7.89. The current middle-two crop retains both complete b-like releases, i/an vowel bodies and nasal decays of one long and one short original reading. The previous first reading and following fourth reading remain outside. This is the explicitly printed bian / biān alternative source unit; long→short recording order is distinguished from the printed order. Original 编编/other glyph predictions remain as recorded; neither their spelling nor an F0 estimate certifies the source tones.',
'上':'The actual source contrast is short-long-short-long around 3.33–3.55, 4.58–5.08, 5.81–6.09 and 7.03–7.71. Both selected middle source readings have complete sh-like frication, a-like vowel and ng-like decay, with the third shorter body and the second longer body both inside the fixed original crop. No first/fourth reading or adjacent lexical head is included. The source explicitly prints shang / shàng, so the original contrasting pair is a bounded alternative unit for this exact source ID. Long→short recording order is separate from the printed slash order. Single model tokens that suppress repeated readings remain unchanged; no tone or speaker-native certificate is asserted.'}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def checked(r):
 p=ROOT/r['file'];assert sha(p)==r['sha256'];return json.loads(p.read_text())
def main():
 OUT.mkdir(parents=True,exist_ok=True);spec=importlib.util.spec_from_file_location('root_alternatives_support',pathlib.Path(__file__).with_name('review-decisions.py'));support=importlib.util.module_from_spec(spec);spec.loader.exec_module(support);source=json.loads((BASE/'current-middle-two-source-model-index-v2.json').read_text());rows=json.loads(REPORT.read_text())['targets'];observations=[];decisions=[]
 for f in source['targets']:
  r=next(t for t in rows if t['id']==f['id'] and t['sourceSampleRange16k']==f['sourceSampleRange16k']);assert r['expectedReadingCount']==2 and r['clipUnit']=='alternative-original-pronunciations';s,e=r['sourceSampleRange16k'];pcm=support.original_pcm(ROOT,r);assert hashlib.sha256(pcm).hexdigest()==r['sourcePCM_SHA256'] and hashlib.sha256(pcm[s*4:e*4]).hexdigest()==r['cropPCM_SHA256']
  canonical=r['canonicalSource'];obj=checked(canonical)
  for k in canonical['sourceJSONPointer'].split('/')[1:]:obj=obj[int(k)] if isinstance(obj,list) else obj[k]
  assert obj['zh']==r['sourceZH'] and obj['py']==r['sourcePinyin'];printed=f['originalTeachingSourceDeclaration'];teaching=checked(printed)
  for k in printed['sourceJSONPointer'].split('/')[1:]:teaching=teaching[int(k)] if isinstance(teaching,list) else teaching[k]
  assert teaching['zh']==r['sourceZH'] and teaching['py']==r['sourcePinyin'];actual_plot=ROOT/f['actualFourReadingPlot']['file'];assert sha(actual_plot)==f['actualFourReadingPlot']['sha256'];models=[]
  for raw_ref in f['actualCropModelEvidence'].values():
   raw=checked(raw_ref);support.unprompted(raw);assert raw['sourceSampleRange16k']==[s,e] and raw['cropPCM_SHA256']==r['cropPCM_SHA256'] and raw['originalSourceSHA256']==r['sourceSHA256'];assert ''.join(q['text'] for q in raw['rawSegments'])==raw_ref['rawTranscript'];models.append({'file':raw_ref['file'],'sha256':raw_ref['sha256'],'unalteredRawTranscript':raw_ref['rawTranscript']})
  whole=checked(f['originalSourceRawEvidence']);support.unprompted(whole);assert whole.get('cropPCM_SHA256',whole.get('track',{}).get('pcm',{}).get('sha256'))==r['sourcePCM_SHA256'];ctc=checked(f['independentCTCSupplementalEvidence']);assert ctc['cropPCM_SHA256']==r['cropPCM_SHA256'] and ctc['expectedTextPromptUsed'] is False and ctc['modelSHA256']=='c71f0ce00bec95b07744e116345e33d8cbbe08cef896382cf907bf4b51a2cd51';assert ctc['rawText']==f['independentCTCSupplementalEvidence']['rawText'];assert json.loads(ctc['rawResultString'])==ctc['rawResult']
  note=NOTES[r['sourceZH']];proof={k:r[k] for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};proof.update({'sourceText':r['sourceZH'],'sourcePinyin':r['sourcePinyin'],'wholeSourceGroupUnpromptedASRReviewed':True,'sourceOrderChecked':True,'neighborSpeechExcluded':True,'actualCropBoundariesChecked':True,'phoneticEquivalenceIsAuxiliaryOnly':True,'originalRepeatedReadingsChecked':True,'sourceGroupEvidence':{'file':f['originalSourceRawEvidence']['file'],'sha256':f['originalSourceRawEvidence']['sha256']},'rawDifferences':{'pure':models,'wholeUnalteredText':''.join(q['text'] for q in whole['rawSegments']),'CTCUnalteredText':ctc['rawText']},'explicitPrintedAlternativeSource':printed,'actualFourReadingPlot':f['actualFourReadingPlot'],'selectedOriginalReadingOrdinals':[2,3],'actualReadingCount':2,'recordedAcousticClassOrder':['ui-like','ei-like'] if r['sourceZH']=='谁' else ['long','short'],'printedSlashOrderUnchanged':True,'pronunciationToneCertified':False,'recordedPronunciationOrderCertified':False,'explanation':note})
  if r['sourceZH']=='谁':proof['withinOriginalVoiceVowelComparisonEvidence']=ref(BASE/'who-four-original-vowel-resonance-observations.json')
  d={'id':r['id'],'sourceSampleRange16k':[s,e],'decision':'accept','sourceContextChecked':True,'acknowledgedFlags':r['flags'],'resolvedTextHolds':sorted(set(r['holds'])&support.TEXT_REVIEW_HOLDS),'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[],'sourceContextEvidence':proof,'rationale':note,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False};support.contextual_decision(r,d,ROOT);decisions.append(d);observations.append({k:r[k] for k in ['id','sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']});observations[-1].update({'freshSourceBytesChecked':True,'actualFourReadingsAndSelectedOriginalTwoIndependentlyInspected':True,'canonicalPrintedAlternatives':r['sourcePinyin'],'allActualModelDiagnosticsUnchanged':True})
 p=OUT/'four-printed-alternatives-independent-decisions.json';p.write_text(json.dumps({'schemaVersion':1,'producer':ref(pathlib.Path(__file__)),'reviewReportSHA256':sha(REPORT),'producerSourceModelIndex':ref(BASE/'current-middle-two-source-model-index-v2.json'),'freshSourceObservations':observations,'decisions':decisions,'automaticApproval':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps(ref(p)))
if __name__=='__main__':main()
