"""Bind five independently inspected nonnumeric utterances to original bytes."""
import hashlib,importlib.util,json,math,pathlib,subprocess
import numpy as np
ROOT=pathlib.Path(__file__).resolve().parents[2]
BASE=ROOT/'course-app/docs/final-quality-20261006/audio-hsk2/closure-followup'
OUT=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-hsk2-sentences'
REPORT=ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk2-paired-full-01.json'
CTC=ROOT/'course-app/docs/final-quality-20261006/audio-review/hsk2-current173-independent-ctc-source-frame-review-01.json'
ORDINALS=[128,131,132,144,154]
NOTES={
128:('The initial h-like friction and ua body begin after the quiet lead-in around 20.5; all following wo/men/de/jia bodies are visible inside the crop.','The last jia-like vowel and decay finish before 21.52. The following 有爸爸 utterance begins around 22.1, outside this crop.'),
131:('The initial uo-like onset/body starts around 18.0 after the 17.52 cut. The complete continuous source utterance passes through its internal consonant/vowel transitions to 一起玩.','The final uan-like body/nasal decay is present around 20.1–20.24, before the 20.28 end; the next response starts beyond 21.1.'),
132:('The initial uo-like speech begins around 9.2 after the 9.02 cut. Both clauses are complete; the real pause between the clauses around 11.3–11.7 remains inside the same printed sentence.','The final qi/u-like frication and voiced body of 踢球 decay before 15.35; the next question starts beyond 16.0, outside the crop.'),
144:('The initial aspirated t-like release and ou body around 5.6 are inside the 5.42 cut; the following hai/teng/ma transitions remain within this four-syllable child utterance.','The final ma-like vowel and decay finish around 6.4 before the 6.50 cut. Prior 怎么样了 speech ends before the cut and the following response starts near 7.6.'),
154:('The initial h-like friction and en body near 5.0 follow the 4.68 cut. 很漂亮 and 多少钱一个 are both inside the printed source line, including its original pause around 5.8–6.6.','The final ge-like syllable body and release decay finish before the 7.72 end. Following 比我们 speech starts later than 9.0; no preceding question speech is included.')}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def module(name,file):
 s=importlib.util.spec_from_file_location(name,pathlib.Path(__file__).with_name(file));m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def checked(r):
 p=ROOT/r['file'];assert sha(p)==r['sha256'];return json.loads(p.read_text())
def main():
 OUT.mkdir(parents=True,exist_ok=True);support=module('root_h2_support','review-decisions.py');syllable=module('root_h2_features','review-syllable-evidence.py');triple=module('root_h2_triple','review-triple-literal.py')
 facts=json.loads((BASE/'current173-source-frame-facts-v2.json').read_text())['targets'];review=json.loads(REPORT.read_text())['targets'];features=json.loads((BASE/'actual-sentence-feature-observation-index.json').read_text())['targets'];pages=json.loads((BASE/'current-triple-sentences-source-plot-index.json').read_text())['pages'];ctc=json.loads(CTC.read_text());assert ctc['status']=='independent-CTC-bytes-source-frames-verified-not-approved'
 outputs=[];pcm_cache={}
 for ordinal in ORDINALS:
  f=facts[ordinal];matches=[r for r in review if r['id']==f['id'] and r['sourceSampleRange16k']==f['sourceSampleRange16k'] and r['cropPCM_SHA256']==f['cropPCM_SHA256']];assert len(matches)==1;r=matches[0];s,e=r['sourceSampleRange16k'];track=r['sourceTrack']
  if track not in pcm_cache:
   p=ROOT/'course-app/public'/track;assert sha(p)==r['sourceSHA256'];pcm_cache[track]=subprocess.run(['ffmpeg','-nostdin','-v','error','-threads','1','-i',str(p),'-ac','1','-ar','16000','-f','f32le','-'],capture_output=True,check=True).stdout
  pcm=pcm_cache[track];assert hashlib.sha256(pcm).hexdigest()==r['sourcePCM_SHA256'];assert hashlib.sha256(pcm[s*4:e*4]).hexdigest()==r['cropPCM_SHA256']
  original=r['canonicalSource'];obj=syllable.pointer(checked(original),original['sourceJSONPointer']);assert obj['zh']==original['parentZH'] and obj['py']==original['sourcePinyin']
  for m in r['rawModelEvidence']:
   raw=checked(m);support.unprompted(raw);assert raw['sourceSampleRange16k']==[s,e] and raw['cropPCM_SHA256']==r['cropPCM_SHA256'];assert ''.join(x['text'] for x in raw['rawSegments'])==m['rawTranscript'];assert triple.literal(m['rawTranscript'])==triple.literal(r['sourceZH'])
  co=[x for x in ctc['observations'] if x['id']==r['id'] and x['sourceSampleRange16k']==[s,e] and x['cropPCM_SHA256']==r['cropPCM_SHA256']];assert len(co)==1;raw=checked(co[0]['rawEvidence']);assert raw['rawText']==co[0]['rawText'] and triple.literal(raw['rawText'])==triple.literal(r['sourceZH']);assert raw['expectedTextPromptUsed'] is False
  for w in f['wholeSourceUnpromptedEvidence']:
   raw=checked(w);support.unprompted(raw);assert raw.get('cropPCM_SHA256',raw.get('track',{}).get('pcm',{}).get('sha256'))==r['sourcePCM_SHA256'];assert ''.join(x['text'] for x in raw['rawSegments'])==w['wholeSourceTranscript']
  feat=[x for x in features if x['id']==r['id'] and x['cropPCM_SHA256']==r['cropPCM_SHA256']];assert len(feat)==1;fr=checked(feat[0]);bins=syllable.features(pcm,s,e);assert fr['featureBins']==bins and fr['featureBinsSHA256']==syllable.feature_sha(bins)
  page=[p for p in pages if any(x['id']==r['id'] and x['sourceSampleRange16k']==[s,e] and x['cropPCM_SHA256']==r['cropPCM_SHA256'] for x in p['targets'])];assert len(page)==1;checked_plot=ROOT/page[0]['file'];assert sha(checked_plot)==page[0]['sha256']
  wp=OUT/(r['candidateId']+'-waveform-observation.json');wp.write_text(json.dumps({'sourceTrack':track,'sourceSHA256':r['sourceSHA256'],'sourcePCM_SHA256':r['sourcePCM_SHA256'],'plots':[{'id':r['id'],'sourceSampleRange16k':[s,e],'cropPCM_SHA256':r['cropPCM_SHA256'],**ref(checked_plot)}]},indent=2)+'\n')
  regions=f['originalSpeechLikeRegionsAroundActualCrop'];previous=[x['sourceFrames'] for x in regions if x['sourceFrames'][1]<=s];following=[x['sourceFrames'] for x in regions if x['sourceFrames'][0]>=e];prev=max(previous,key=lambda z:z[1]) if previous else None;nxt=min(following,key=lambda z:z[0]) if following else None;limits=[prev[1] if prev else 0,nxt[0] if nxt else len(pcm)//4]
  onset,final=NOTES[ordinal];proof={k:r[k] for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};proof.update({'category':'triple-literal-noSpeech-proxy-review','sourceText':r['sourceZH'],'independentlyVerifiedCTCSupplementalEvidence':ref(CTC),'waveformObservation':ref(wp),'actualSyllableFeatureEvidence':ref(ROOT/feat[0]['file']),'selectedCompleteOriginalReadingFrames16k':[s,e],'independentlyReviewedNeighborLimits16k':limits,'originalPrintedSource':{**ref(ROOT/original['file']),'sourceJSONPointer':original['sourceJSONPointer']},'sourceUtteranceEvidence':{'canonicalSourceId':original['sourceId'],'sentenceOrdinal':original['sentenceOrdinal'],'parentZH':original['parentZH'],'actualUtteranceFrames16k':[s,e],'previousActualSpeechFrames16k':prev,'followingActualSpeechFrames16k':nxt,'completeOriginalUtteranceIndependentlyReviewed':True,'wholeSourceEvidence':[{'file':x['file'],'sha256':x['sha256']} for x in f['wholeSourceUnpromptedEvidence']]},'completeOriginalOnsetRimeAndFinalReviewed':True,'neighborPhonemesExcluded':True,'sourceOrderChecked':True,'originalPrintedPronunciationChecked':True,'allASRWarningsRetained':True,'noSyntheticPadding':True,'phonemeIdentityUnknown':False,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False,'onsetExplanation':onset,'rimeAndFinalExplanation':final,'originalReadingExplanation':'Independently inspected actual source and crop waveform/spectrum, fresh original PCM and exact crop hash, complete printed parent line and sentence ordinal, actual unprompted full-source context and all three unchanged pure-crop native transcripts. Parent printed pinyin is preserved separately from the initially empty child pinyin metadata.','explanation':'The entire single original nonnumeric utterance and its complete quiet margins were inspected. All three native actual-crop lexical observations agree after punctuation/whitespace only. Whisper no-speech probabilities and low-word flags remain unchanged; this fixed-source decision explains that statistical proxy using the observed real complete voiced original utterance.'})
  d={'id':r['id'],'sourceSampleRange16k':[s,e],'decision':'accept','sourceContextChecked':True,'acknowledgedFlags':r['flags'],'rationale':onset+' '+final,'humanListening':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'tripleLiteralNoSpeechDecisionEvidence':proof};triple.validate(r,d,ROOT,support);outputs.append(d)
 p=OUT/'five-nonnumeric-sentence-independent-decisions.json';p.write_text(json.dumps({'schemaVersion':1,'reviewReportSHA256':sha(REPORT),'producer':ref(pathlib.Path(__file__)),'independentOriginalTracksFreshDecoded':len(pcm_cache),'originalSourceFactEvidence':ref(BASE/'current173-source-frame-facts-v2.json'),'actualPlotIndexEvidence':ref(BASE/'current-triple-sentences-source-plot-index.json'),'decisions':outputs,'automaticApproval':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps(ref(p)));print('actual independent peer decisions',len(outputs))
if __name__=='__main__':main()
