"""Review five complete original source recordings and disclose phonetic uncertainty."""
import hashlib, importlib.util, json, pathlib, subprocess
import numpy as np
ROOT=pathlib.Path(__file__).resolve().parents[2]
BASE=ROOT/'course-app/docs/final-quality-20261006/audio-hsk2/remaining-word30-source-closure'
OUT=ROOT/'course-app/docs/final-quality-20261006/audio-root-peer-hsk2-five-recording-variants'
PHASES={
 '等':'The complete first original reading has a short initial release around17.88, the strong body17.90–18.15, sustained weak original nasal/final continuation18.15–18.34 and weak terminal release18.34–18.47. The entire final lies inside17.75–18.59. The preceding reading ends before17.20 and the second original reading begins after19.00. The weak final is preserved without replacing it with either retained 到 or 大恩 prediction.',
 '着':'The complete first original reading lies between the original second 动 region and the second 着 reading. Original initial noise near9.605 leads to a separate voiced body9.64–9.78 and finite original decay through about9.89, within9.52–10.09. The next repetition starts after10.45. The unchanged 真 prediction is not substituted for the actual source recording; exact e/en phone classification remains uncertified.',
 '进':'The complete first original head begins with the actual frication around0.61–0.73, followed by the separate original body0.74–1.01 and nasal/final decay1.01–1.26 inside0.55–1.32. Its second original reading starts after1.71. The exact j/q and in/ing/ian classification suggested by differing decoders is not certified; all original onset and final source samples remain present.',
 '楼':'The complete second original head follows the first reading, whose foreground ends before7.55. The second original lateral/gliding entry around7.99–8.08 continues through the complete original vowel8.08–8.49, its original offglide8.52–8.63 and finite decay through about8.73, inside7.86–8.76. No third/neighboring word enters this cut. The retained 喽/老 predictions do not establish an ou/ao equivalence or a certified replacement pronunciation.',
 '路':'The complete first original head is after the preceding full original word and before its own second reading. Its original entry near12.285 leads to the sustained original rounded body12.30–12.56 and finite release through about12.73, inside12.11–12.89. The preceding foreground ends before11.80 and the next original reading starts after13.29. The l/n and u/uo distinction suggested by LOOL/喏 is not uniquely certified; no onset, vowel or original final is synthesized or substituted.',
}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':p.relative_to(ROOT).as_posix(),'sha256':sha(p)}
def main():
 s=importlib.util.spec_from_file_location('five_recording_context',pathlib.Path(__file__).with_name('review-decisions.py'));support=importlib.util.module_from_spec(s);s.loader.exec_module(support)
 s=importlib.util.spec_from_file_location('five_printed_pointer',pathlib.Path(__file__).with_name('review-syllable-evidence.py'));feature=importlib.util.module_from_spec(s);s.loader.exec_module(feature)
 source=BASE/'five-unclassified-printed-versus-original-recording-complete-source-review-index-v1.json';assert sha(source)=='36d8491a6989de8f3abf058a2ac1b63c20d4e784118a54996d67e4ac5461a60f'
 OUT.mkdir(exist_ok=True);groups={};notes=[]
 for t in json.loads(source.read_text())['targets']:
  rp=ROOT/'course-app/docs/final-quality-20261006/audio-review'/('hsk2-six-second-source-paired-01.json' if t['sourceText']=='楼' else 'hsk2-ten-existing-source-paired-01.json')
  matches=[r for r in json.loads(rp.read_text())['targets'] if r['id']==t['id'] and r['candidateId']==t['candidateId'] and r['sourceSampleRange16k']==t['sourceSampleRange16k']];assert len(matches)==1;r=matches[0];support.actual_identity(r,t,'original-recording-variant');assert set(r['holds'])<=support.TEXT_REVIEW_HOLDS
  pcm=support.original_pcm(ROOT,r);a,b=r['sourceSampleRange16k'];assert hashlib.sha256(pcm[a*4:b*4]).hexdigest()==r['cropPCM_SHA256'];v=np.frombuffer(pcm,dtype='<f4')
  for x,y in [(a-320,a),(a,a+320),(b-320,b),(b,b+320)]:
   assert 0<=x<y<=len(v) and 20*np.log10(max(np.sqrt(np.mean(v[x:y].astype('f8')**2)),1e-12))<=-45
  c=t['canonicalPrintedSource'];book=json.loads(support.actual_file(ROOT,c).read_text());obj=feature.pointer(book,c['sourceJSONPointer']);assert obj['id']==r['id'] and obj['zh']==r['sourceZH'] and obj['py']==r['sourcePinyin'];assert r['sourceTrack'].endswith('/'+obj['audioTrack']+'.mp3')
  for k in ['sourceFactsEvidence','actualFeatureEvidence','actualLocalSourceCropSpectrumEvidence','actualWholeSourceSpectrumEvidence']:support.actual_file(ROOT,t[k])
  wholes=[]
  for rr in t['actualWholeSourceRawEvidence']:
   raw=json.loads(support.actual_file(ROOT,rr).read_text());support.unprompted(raw);assert raw.get('cropPCM_SHA256',raw.get('track',{}).get('pcm',{}).get('sha256'))==r['sourcePCM_SHA256'];assert ''.join(z['text'] for z in raw['rawSegments'])==rr['wholeSourceTranscript'];wholes.append({'file':rr['file'],'sha256':rr['sha256']})
  assert wholes
  for rr in r['rawModelEvidence']:
   raw=json.loads(support.actual_file(ROOT,rr).read_text());support.unprompted(raw);assert raw['sourceSampleRange16k']==[a,b] and raw['cropPCM_SHA256']==r['cropPCM_SHA256'];assert ''.join(z['text'] for z in raw['rawSegments'])==rr['rawTranscript']
  cc=t['actualPureCTCAuxiliaryRawEvidence'];ctc=json.loads(support.actual_file(ROOT,cc).read_text());assert ctc['cropPCM_SHA256']==r['cropPCM_SHA256'] and ctc['expectedTextPromptUsed'] is False and ctc['rawText']==cc['rawText'] and json.loads(ctc['rawResultString'])==ctc['rawResult']
  py=r['sourcePinyin'];note={'zh':f'本段保留原录音读法，请结合教材拼音 {py} 辨听。','vi':f'Đoạn này giữ cách đọc của bản ghi âm gốc; hãy đối chiếu với phiên âm {py} trong giáo trình.'}
  explanation=PHASES[r['sourceZH']]+' Root actually viewed the three actual local source/crop spectrum sheets and the three complete-original-source sheets. Exact source-book head/pinyin, original two-reading order and complete actual spatial body/final were independently reviewed. This is a disclosed complete original recording variant with unresolved unique predicted phone classification, accompanied by a bilingual source/frame-bound student note. The recording is not asserted to certify every canonical phone, tone or the decoder alternatives. Textbook text/pinyin/expected answers and all raw predictions/timestamps/flags remain unchanged. No human listening, native-speaker or device certification is asserted.'
  identity={k:r[k] for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};identity['sourceText']=r['sourceZH']
  proof={**identity,'sourcePinyin':py,'wholeSourceGroupUnpromptedASRReviewed':True,'sourceOrderChecked':True,'neighborSpeechExcluded':True,'actualCropBoundariesChecked':True,'phoneticEquivalenceIsAuxiliaryOnly':True,'originalRepeatedReadingsChecked':True,'sourceGroupEvidence':wholes[0],'originalPrintedSource':{**{k:c[k] for k in ['file','sha256']},'sourceJSONPointer':c['sourceJSONPointer']},'actualOriginalSourceFacts':ref(source),'actualLocalSourceSpectrum':t['actualLocalSourceCropSpectrumEvidence'],'actualWholeSourceSpectrum':t['actualWholeSourceSpectrumEvidence'],'actualPhoneClassificationUnknown':True,'recordingVariantDisclosed':True,'recordingNote':note,'rawDifferences':[{'file':z['file'],'sha256':z['sha256'],'unalteredRawTranscript':z['rawTranscript']} for z in r['rawModelEvidence']],'explanation':explanation}
  d={'id':r['id'],'sourceSampleRange16k':[a,b],'decision':'accept','sourceContextChecked':True,'acknowledgedFlags':r['flags'],'rationale':explanation,'resolvedTextHolds':r['holds'],'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[],'sourceContextEvidence':proof,'recordingVariantScope':'complete-original-source-head-with-uncertified-unique-predicted-phone-classification','recordingNote':note,'requiredStudentVisibleRecordingNote':True,'uniquePredictedPhoneClassificationCertified':False,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False};support.contextual_decision(r,d,ROOT);groups.setdefault(rp,[]).append(d)
  notes.append({**{k:t[k] for k in ['id','candidateId','sourceText','sourcePinyin','sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']},'proposedRecordingNoteZH':note['zh'],'proposedRecordingNoteVI':note['vi'],'actualPhoneClassificationUnknown':True,'canonicalSourceAndAnswersUnchanged':True,'independentlyReviewedSourceVariant':True,'actualIndependentSourceFacts':ref(source)})
 for rp,decisions in groups.items():
  dp=OUT/(rp.stem+'-five-recording-variant-decisions.json');op=OUT/(rp.stem+'-five-recording-variant-approved.json')
  dp.write_text(json.dumps({'schemaVersion':1,'reviewReportSHA256':sha(rp),'independentReviewScript':ref(pathlib.Path(__file__)),'actualIndependentSourceFacts':ref(source),'decisions':decisions,'automaticApproval':False},ensure_ascii=False,indent=2)+'\n')
  subprocess.run(['python',str(ROOT/'tools/final-quality-20261006/review-decisions.py'),'--repo-root',str(ROOT),'--report',str(rp),'--decisions',str(dp),'--target-catalog',str(ROOT/'course-app/content/audio-precision-targets-20261006.json'),'--output',str(op)],check=True);print(json.dumps({**ref(op),'actualCount':len(decisions)}))
 npth=OUT/'five-complete-original-source-recording-variant-student-note-proposal.json';npth.write_text(json.dumps({'schemaVersion':1,'targets':notes,'automaticPrecisionApproval':False,'independentSourceReviewScript':ref(pathlib.Path(__file__))},ensure_ascii=False,indent=2)+'\n');print(json.dumps(ref(npth)))
if __name__=='__main__':main()
