/* Additive, single-lesson pilot; other lessons retain their existing assignments. */
(function(){
  'use strict';
  const bank=window.HSK1_PILOT9,E=window.HSK1_PILOT_ENGINE;
  if(!bank||!E)return;
  const KEY='hsk1_lesson9_pilot_progress_v1';
  const h=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fold=x=>String(x||'').normalize('NFD').replace(/\p{M}/gu,'').toLowerCase().replace(/đ/g,'d');
  let state=E.empty(bank),storageWarning='',activeGroup=0,activeAudio=null,audioFrame=0;
  let search='',wordFilter='all',revealed=new Set(),wordList=[],reviewAnswers={},reviewResults={};
  const tokenOrders=new Map();
  try{const raw=localStorage.getItem(KEY);if(raw)state=E.restore(bank,JSON.parse(raw));}catch(e){storageWarning='Không đọc được tiến độ cũ. Dữ liệu cũ vẫn còn; hãy xuất bản sao nếu cần. Phiên này bắt đầu với tiến độ mới.';}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageWarning='';}catch(e){storageWarning='Trình duyệt không lưu được tiến độ. Hãy xuất tệp trước khi đóng trang.';}document.querySelectorAll('.p9-save-note').forEach(el=>el.textContent=storageWarning||'Tự lưu trên trình duyệt này. Xuất tệp để chuyển sang thiết bị khác.');}
  function stopAudio(){if(activeAudio)activeAudio.pause();document.querySelectorAll('audio[data-p9-listening]').forEach(a=>{a.pause();a.remove();});cancelAnimationFrame(audioFrame);activeAudio=null;document.querySelectorAll('[data-p9-action="play"]').forEach(b=>{b.textContent='▶ Nghe audio';b.removeAttribute('data-p9-playing');});}
  function scoreText(s){return `${s.correct}/${s.total} đúng${s.review?` · ${s.review} chờ đối chiếu`:''}`;}
  function toolbar(){return `<div class="p9-toolbar"><button data-p9-action="export">Xuất tiến độ</button><button data-p9-action="import">Nhập tiến độ</button><input type="file" accept="application/json,.json" data-p9-import hidden><a href="#" data-p9-action="review">Ôn câu cần luyện →</a></div><p class="p9-save-note">${h(storageWarning||'Tự lưu trên trình duyệt này. Xuất tệp để chuyển sang thiết bị khác.')}</p>`;}
  function dashboard(){const recent=E.totals(bank,state),first=E.totals(bank,state,'first'),best=E.totals(bank,state,'best');
    return `<div class="p9-lead"><div class="p9-kicker">Bài 9 · Bài tập theo giáo trình</div><h2>30 câu, học từng bước</h2><p>Hoàn thành đủ 5 câu rồi nộp để mở nhóm tiếp theo. Xem giải thích trước khi tiếp tục. Bạn có thể học lại một nhóm; điểm lần đầu được giữ riêng.</p><div class="p9-summary"><div class="p9-stat"><strong>${recent.groups}/6</strong><span>Nhóm đã nộp · ${recent.total}/30 câu</span></div><div class="p9-stat"><strong>${first.correct}/${first.total}</strong><span>Lần đầu</span><small>${first.review?first.review+' câu chờ đối chiếu':'Số câu đúng / đã nộp'}</small></div><div class="p9-stat"><strong>${recent.correct}/${recent.total}</strong><span>Gần nhất</span><small>${recent.incorrect} sai · ${recent.review} chờ đối chiếu</small></div><div class="p9-stat"><strong>${best.correct}/${best.total}</strong><span>Tốt nhất từng nhóm</span><small>Cộng điểm cao nhất của mỗi nhóm</small></div></div><progress max="30" value="${recent.total}" aria-label="Số câu đã nộp"></progress><p class="p9-muted">${recent.groups===6?'Đã hoàn thành 30/30 câu. Tiếp tục ôn các câu sai hoặc chờ đối chiếu.':'Còn '+(30-recent.total)+' câu chưa nộp.'} Điểm cao sau khi làm lại không thay thế điểm lần đầu.</p>${toolbar()}</div>`;
  }
  function nav(){return `<nav class="p9-group-nav" aria-label="Sáu nhóm bài tập">${bank.groups.map((g,i)=>{const s=state.groups[g.id],list=s?.attempts||[],open=E.unlocked(bank,state,i);return `<button class="p9-group-btn" data-p9-action="group" data-index="${i}" ${open?'':'disabled'} ${i===activeGroup?'aria-current="step"':''}><span class="p9-group-number">${list.length?'✓':open?i+1:'🔒'}</span><span>${h(g.title)}<small>${list.length?scoreText(list[list.length-1]):open?'5 câu · Sẵn sàng':'Nộp nhóm '+i+' để mở'}</small></span></button>`;}).join('')}</nav>`;}
  function lastAttempt(g){const s=E.groupState(state,g.id);return s.editing===false?s.attempts[s.attempts.length-1]:null;}
  function randomTokens(q,g){const s=E.groupState(state,g.id),key=q.id+':'+s.attemptCount;
    if(!tokenOrders.has(key)){const a=q.tokens.map((_,i)=>i);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}if(q.accepted.some(x=>E.normalize(x)===E.normalize(a.map(i=>q.tokens[i]).join(''))))a.push(a.shift());tokenOrders.set(key,a);}
    return tokenOrders.get(key);
  }
  function audioHtml(q){return `<div class="p9-audio-row"><button class="p9-primary" data-p9-action="play" data-qid="${q.id}">▶ Nghe audio</button><label>Tốc độ <select data-p9-speed data-qid="${q.id}" aria-label="Tốc độ audio câu ${q.id}"><option value="1">1×</option><option value="0.8">0,8×</option></select></label><span data-p9-audio-status="${q.id}" aria-live="polite">Audio giáo trình · ${Math.ceil(q.audio.end-q.audio.start)} giây</span></div>`;}
  function answerDisplay(q,a){return q.type==='order'?Array.isArray(a)?a.map(i=>q.tokens[i]).join(''):'' :String(a??'');}
  function feedback(q,result,answer){if(!result)return '';
    const good=result.status==='correct',pending=result.status==='review';
    const label=good?'✓ Đúng':pending?'? Chờ đối chiếu':'Cần luyện lại';
    const model=q.answer||q.accepted[0];
    return `<div class="p9-feedback ${pending?'p9-review':good?'':'p9-bad'}"><strong>${label}</strong><div>Đáp án của bạn: ${h(answerDisplay(q,answer))}</div>${q.audio?`<div class="p9-model">${h(q.transcript)}</div><p>${h(q.pinyin)}</p>`:''}<div class="p9-model">${q.audio?'Nghĩa đúng: ':'Đáp án tham khảo: '}${h(model)}</div>${result.why?`<p>${h(result.why)}</p>`:''}<p><b>Giải thích:</b> ${h(q.explain)}</p>${q.type==='order'&&q.accepted.length>1?`<p>Cũng đúng: ${q.accepted.slice(1).map(h).join(' / ')}</p>`:''}<small>Đối chiếu giáo trình p.${q.source.page} · ${q.source.kind==='adapted'?'Câu hỏi chuyển thể':'Giáo trình'}</small></div>`;
  }
  function questionHtml(q,i,g,review=false){const attempt=review?null:lastAttempt(g),s=E.groupState(state,g.id);
    const a=review?reviewAnswers[q.id]:attempt?attempt.answers[q.id]:s.draft[q.id];
    const result=review?reviewResults[q.id]:attempt?.results.find(x=>x.id===q.id),checked=!!result;
    let content='';
    if(q.audio)content+=audioHtml(q);
    if(q.type==='choice')content+=`<div class="p9-options">${q.options.map((o,n)=>`<button class="p9-option ${checked&&o===q.answer?'p9-correct':''} ${checked&&o===a&&o!==q.answer?'p9-wrong':''}" data-p9-action="answer" data-qid="${q.id}" data-option="${n}" aria-pressed="${o===a}" ${checked?'disabled':''}><b>${String.fromCharCode(65+n)}</b><span>${h(o)}</span></button>`).join('')}</div>`;
    else if(q.type==='order'){const chosen=Array.isArray(a)?a:[];content+=`<div class="p9-order-answer" aria-label="Câu đã sắp xếp">${chosen.length?chosen.map(n=>`<button data-p9-action="remove-token" data-qid="${q.id}" data-token="${n}" ${checked?'disabled':''} aria-label="Bỏ ${h(q.tokens[n])} khỏi câu">${h(q.tokens[n])}</button>`).join(''):'<span class="p9-muted">Chạm thẻ bên dưới để tạo câu…</span>'}</div><div class="p9-tokens">${randomTokens(q,g).map(n=>`<button data-p9-action="token" data-qid="${q.id}" data-token="${n}" ${checked||chosen.includes(n)?'disabled':''}>${h(q.tokens[n])}</button>`).join('')}</div>`;}
    else content+=`<textarea class="p9-input" data-p9-input data-qid="${q.id}" maxlength="240" lang="zh-CN" aria-label="Viết bản dịch tiếng Trung câu ${i+1}" placeholder="Viết câu bằng chữ Hán…" ${checked?'disabled':''}>${h(a||'')}</textarea><small>Nhập chữ Hán; không chấm lỗi dấu câu hoặc khoảng trắng.</small>`;
    if(review&&!checked)content+=`<div class="p9-actions"><button data-p9-action="check-review" data-qid="${q.id}">Kiểm tra câu này</button></div>`;
    return `<article class="p9-q" data-p9-q="${q.id}" ${review?'data-p9-review="1"':''}><div class="p9-q-meta"><span>Câu ${i+1}/5 · ${h(g.zh)}</span><span>Giáo trình p.${q.source.page}</span></div><h4>${h(q.prompt)}</h4>${q.stem?`<div class="p9-stem" lang="zh-CN">${h(q.stem)}</div>`:''}${content}${feedback(q,result,a)}</article>`;
  }
  function groupHtml(g){const index=bank.groups.indexOf(g);
    if(!E.unlocked(bank,state,index))return `<div class="p9-empty">🔒 Nộp đủ nhóm ${index} (${h(bank.groups[index-1]?.title)}) để mở nhóm này. <button data-p9-action="group" data-index="${index-1}">Về nhóm trước</button></div>`;
    const attempt=lastAttempt(g),s=E.groupState(state,g.id);
    const recent=s.attempts[s.attempts.length-1];
    return `<div class="p9-group-intro"><div class="p9-kicker">Nhóm ${index+1}/6 · ${h(g.zh)}</div><h3>${h(g.title)}</h3><p>${h(g.intro)}</p>${!attempt&&recent?`<p class="p9-inline-note">Đang làm lại. Lần đầu: ${scoreText(s.attempts[0])}; gần nhất: ${scoreText(recent)}. Đáp án và giải thích sẽ hiện sau khi nộp lại.</p>`:''}</div>${g.passage?`<div class="p9-passage" lang="zh-CN">${g.passage.map(h).join('<br>')}</div>`:''}${g.questions.map((q,i)=>questionHtml(q,i,g)).join('')}<p class="p9-error" role="alert" data-p9-error="${g.id}"></p>${attempt?`<div class="p9-result" aria-live="polite"><b>Kết quả: ${scoreText(attempt)}</b><div>${attempt.incorrect} sai · ${attempt.review} chờ đối chiếu · ${attempt.review?'Điểm đang chờ xác nhận':'Điểm '+Math.round(attempt.correct/5*100)+'/100'}</div><small>Lần đầu: ${scoreText(s.attempts[0])} · Đã nộp ${s.attemptCount} lần</small></div><div class="p9-actions"><button data-p9-action="retry" data-group="${g.id}">Làm lại nhóm này</button>${index<5?`<button class="p9-primary" data-p9-action="group" data-index="${index+1}">Nhóm tiếp theo →</button>`:`<button class="p9-primary" data-p9-action="review">Ôn câu cần luyện →</button>`}</div>`:`<div class="p9-actions"><button class="p9-primary" data-p9-action="submit" data-group="${g.id}">Nộp 5 câu & xem giải thích</button></div>`}`;
  }
  function renderHomework(){const root=document.getElementById('pilot9Homework');if(!root)return;root.innerHTML=dashboard()+nav()+`<div data-p9-panel="practice">${groupHtml(bank.groups[activeGroup])}</div>`+speaking();}
  function renderListening(){const root=document.getElementById('pilot9Listening');if(!root)return;root.innerHTML=`<div class="p9-lead"><div class="p9-kicker">Bài 9 · Audio gốc</div><h2>Nghe tiếng Trung, hiểu bằng tiếng Việt</h2><p>5 câu nghe dùng audio gốc từ gói giáo trình. Đây là cùng nhóm 3 trong bài tập: nộp ở đây cũng được lưu ở mục Bài tập, chỉ tính 5 câu một lần.</p><p class="p9-muted">Chữ Hán, pinyin và giải thích hiện sau khi nộp. Hoàn thành nhóm 1–2 trước để mở nhóm nghe.</p></div><div data-p9-panel="listening">${groupHtml(bank.groups[2])}</div>`;}
  function speaking(){if(E.totals(bank,state).groups<6)return '';return `<div class="p9-speaking"><div class="p9-kicker">Vận dụng · Không tính vào 30 câu</div><h3>Nói về một ngày của bạn</h3><p>Trong một phút, nói 3 câu: bạn học ở đâu và lúc nào; trước trường có gì; một hoạt động ban ngày của bạn. Nói lại lần hai với ít gợi ý hơn.</p><p lang="zh-CN">我明天上午在____学习。<br>学校前边有____。<br>我白天在家里____。</p><small>Tự nghe lại hoặc nói với giáo viên. Hoạt động này không được tự chấm điểm phát âm.</small></div>`;}
  function renderWords(){const root=document.getElementById('pilot9Vocab');if(!root)return;
    wordList=E.mergedWords(window.HSK1_LESSONS,state.selectedLessons);
    const items=wordList.filter(w=>{const saved=state.words[w.key],match=!search||[w.zh,w.py,w.vn].some(x=>fold(x).includes(fold(search)));return match&&(wordFilter==='all'||wordFilter==='unknown'&&!saved?.known||wordFilter==='known'&&saved?.known||wordFilter==='due'&&(!saved||saved.due<=Date.now()));});
    const known=wordList.filter(w=>state.words[w.key]?.known).length;
    root.innerHTML=`<div class="p9-lead"><div class="p9-kicker">Từ vựng · Ôn cùng nhiều bài</div><h2>Chọn bài để ôn chung</h2><p>Nhìn chữ Hán và thử nhớ nghĩa trước khi mở thẻ. Từ trùng chữ, cách đọc và nghĩa được gộp; những nghĩa khác nhau được giữ riêng.</p><p><b>${wordList.length}</b> thẻ · ${known} đã nhớ · ${wordList.length-known} cần học</p></div><div class="p9-picker"><b>Chọn một hoặc nhiều bài:</b><div class="p9-lesson-checks">${window.HSK1_LESSONS.map(l=>`<label><input type="checkbox" data-p9-lesson="${l.id}" ${state.selectedLessons.includes(l.id)?'checked':''}>Bài ${l.id}</label>`).join('')}</div><div class="p9-toolbar"><button data-p9-action="preset" data-lessons="7,8,9">Ôn bài 7–9</button><button data-p9-action="preset" data-lessons="9">Chỉ bài 9</button><button data-p9-action="preset" data-lessons="">Bỏ chọn</button></div></div><div class="p9-toolbar"><input class="p9-search" data-p9-search aria-label="Tìm từ vựng" placeholder="Tìm chữ Hán, pinyin hoặc nghĩa Việt…" value="${h(search)}"><select class="p9-filter" data-p9-filter aria-label="Lọc thẻ"><option value="all" ${wordFilter==='all'?'selected':''}>Tất cả</option><option value="unknown" ${wordFilter==='unknown'?'selected':''}>Cần học</option><option value="known" ${wordFilter==='known'?'selected':''}>Đã nhớ</option><option value="due" ${wordFilter==='due'?'selected':''}>Đến hạn ôn</option></select></div><p class="p9-muted">Hiện ${items.length} thẻ. Bấm “Đã nhớ” để lên lịch ôn sau 1, 3, 7, rồi 14 ngày qua các lần ôn. “Cần học” đưa thẻ về lượt ôn hiện tại.</p><div class="p9-word-grid">${items.map(w=>{const n=wordList.indexOf(w),open=revealed.has(w.key),saved=state.words[w.key];return `<article class="p9-word ${saved?.known?'p9-known':''}" data-p9-word="${n}"><small>Bài ${w.lessons.join(', ')}${saved?.known?' · Đã nhớ':''}</small><div class="p9-word-zh" lang="zh-CN">${h(w.zh)}</div><div class="p9-word-detail">${open?`<b>${h(w.py)}</b><span>${h(w.vn)}</span>`:'<span class="p9-muted">Bạn nhớ nghĩa và cách đọc?</span>'}</div><div class="p9-word-actions"><button data-p9-action="reveal" data-word="${n}" aria-expanded="${open}">${open?'Ẩn nghĩa':'Mở nghĩa'}</button><button data-p9-action="vocab-audio" data-word="${n}">Nghe từ</button><button data-p9-action="known" data-word="${n}" ${open?'':'disabled'}>Đã nhớ</button><button data-p9-action="unknown" data-word="${n}" ${open?'':'disabled'}>Cần học</button></div><small>${saved?.known?'Ôn lại: '+new Date(saved.due).toLocaleDateString('vi-VN'):''}</small></article>`;}).join('')||'<div class="p9-empty">'+(state.selectedLessons.length?'Không có thẻ phù hợp.':'Chọn ít nhất một bài để hiện thẻ.')+'</div>'}</div>`;
  }
  function neededQuestions(){return bank.groups.flatMap(g=>{const attempts=state.groups[g.id]?.attempts||[];const a=attempts[attempts.length-1];if(!a)return [];return g.questions.filter(q=>a.results.find(r=>r.id===q.id)?.status!=='correct').map(q=>({g,q,a}));});}
  function renderReview(){const root=document.getElementById('pilot9Review');if(!root)return;const items=neededQuestions();root.innerHTML=`<div class="p9-lead"><div class="p9-kicker">Bài 9 · Ôn có mục tiêu</div><h2>Câu cần luyện & câu chờ đối chiếu</h2><p>${items.length} câu từ lần nộp gần nhất. Ôn ở đây không thay đổi điểm bài tập. Muốn cập nhật điểm gần nhất, làm lại và nộp cả nhóm.</p>${toolbar()}</div>${items.length?items.map(({g,q,a})=>`<div class="p9-review-card"><p class="p9-muted">${h(g.title)} · Lần nộp: ${a.results.find(r=>r.id===q.id)?.status==='review'?'Chờ đối chiếu':'Cần luyện'}</p><p>Lần trước: ${h(answerDisplay(q,a.answers[q.id]))}</p>${questionHtml(q,g.questions.indexOf(q),g,true)}</div>`).join(''):'<div class="p9-empty">Chưa có câu cần luyện. Hoàn thành bài tập để xem kết quả ở đây.</div>'}`;}
  function renderAll(){renderHomework();renderListening();renderReview();renderCompletion();}
  function renderCompletion(){const card=document.querySelector('.complete-card');if(!card)return;const s=E.totals(bank,state);card.innerHTML=`<div><h3>Bài tập bài 9: ${s.total}/30 câu đã nộp</h3><p>${s.groups===6?'Đã hoàn thành 6 nhóm. Câu chờ đối chiếu vẫn cần giáo viên kiểm tra.':'Hoàn thành bằng cách nộp lần lượt 6 nhóm bài tập.'}</p></div><span class="chip">${s.groups}/6 nhóm</span>`;}
  function navigate(index){if(!Number.isInteger(index)||index<0||index>=6||!E.unlocked(bank,state,index))return;stopAudio();activeGroup=index;showSection('practice');renderAll();document.getElementById('pilot9Homework')?.scrollIntoView({behavior:'smooth',block:'start'});}
  function locate(qid){for(const g of bank.groups){const q=g.questions.find(x=>x.id===qid);if(q)return {g,q};}return null;}
  async function play(q,button){const statuses=()=>document.querySelectorAll(`[data-p9-audio-status="${q.id}"]`);if(activeAudio?.dataset.p9Listening===q.id){stopAudio();statuses().forEach(x=>x.textContent='Đã dừng. Bấm để nghe lại từ đầu đoạn.');return;}stopAudio();window.HSK1_OFFICIAL_AUDIO?.stop();document.querySelectorAll('audio').forEach(a=>a.pause());window.speechSynthesis?.cancel();const audio=new Audio('audio/'+q.audio.file);audio.hidden=true;audio.dataset.p9Listening=q.id;button.closest('.p9-audio-row').appendChild(audio);activeAudio=audio;const rate=button.closest('.p9-audio-row').querySelector('[data-p9-speed]').value;audio.playbackRate=Number(rate)||1;
    try{await new Promise((resolve,reject)=>{audio.addEventListener('loadedmetadata',resolve,{once:true});audio.addEventListener('error',reject,{once:true});audio.load();});if(activeAudio!==audio)return;audio.currentTime=q.audio.start;await audio.play();statuses().forEach(x=>x.textContent='Đang phát audio giáo trình…');
      button.textContent='❚❚ Dừng audio';button.dataset.p9Playing='1';let last=-1;
      const tick=()=>{if(activeAudio!==audio)return;if(audio.currentTime>=q.audio.end){audio.pause();audio.currentTime=q.audio.end;activeAudio=null;button.textContent='▶ Nghe audio';button.removeAttribute('data-p9-playing');statuses().forEach(x=>x.textContent='Đã nghe xong. Có thể nghe lại.');return;}const elapsed=Math.floor(audio.currentTime-q.audio.start);if(elapsed!==last){last=elapsed;statuses().forEach(x=>x.textContent=`Đang phát: ${Math.max(0,elapsed)}/${Math.ceil(q.audio.end-q.audio.start)} giây`);}audioFrame=requestAnimationFrame(tick);};audioFrame=requestAnimationFrame(tick);
    }catch(e){if(activeAudio===audio)stopAudio();statuses().forEach(x=>x.textContent='Không phát được audio. Kiểm tra kết nối rồi thử lại.');}
  }
  function exportFile(){const data={...state,exportedAt:new Date().toISOString(),note:'Progress on this browser; translation review items are not verified teacher grades.'};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='hsk1-bai9-tien-do.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function reportError(groupId,msg,missing=[]){document.querySelectorAll(`[data-p9-error="${groupId}"]`).forEach(x=>x.textContent=msg);document.querySelectorAll('[data-p9-q]').forEach(x=>x.classList.toggle('p9-missing',missing.includes(x.dataset.p9Q)));const target=[...document.querySelectorAll(`[data-p9-q="${missing[0]}"]`)].find(x=>x.offsetParent!==null);target?.scrollIntoView({behavior:'smooth',block:'center'});}
  function bind(){document.addEventListener('click',async event=>{const b=event.target.closest('[data-p9-action]');if(!b||!b.closest('.p9')||b.disabled)return;event.preventDefault();const action=b.dataset.p9Action;
      if(action==='group'){navigate(Number(b.dataset.index));return;}
      if(action==='review'){stopAudio();showSection('review');renderReview();return;}
      if(action==='export'){exportFile();return;}
      if(action==='import'){b.closest('.p9').querySelector('[data-p9-import]').click();return;}
      if(action==='preset'){state.selectedLessons=b.dataset.lessons?b.dataset.lessons.split(',').map(Number):[];revealed.clear();save();renderWords();return;}
      if(['reveal','known','unknown','vocab-audio'].includes(action)){const w=wordList[Number(b.dataset.word)];if(!w)return;if(action==='reveal'){revealed.has(w.key)?revealed.delete(w.key):revealed.add(w.key);}else if(action==='vocab-audio'){stopAudio();const layer=window.HSK1_OFFICIAL_AUDIO;try{if(!layer?.ready)throw Error('not ready');layer.playVocab(w.zh,w.lessons[0]);}catch(e){toast('Audio chưa sẵn sàng. Hãy thử lại.');}return;}else{E.markWord(state,w.key,action==='known');save();}renderWords();return;}
      if(action==='retry'){stopAudio();E.retry(state,b.dataset.group);save();renderAll();return;}
      if(action==='submit'){const result=E.submit(bank,state,b.dataset.group);if(!result.ok){reportError(b.dataset.group,'Chưa nộp: hãy hoàn thành đủ 5 câu. Câu dịch cần chữ Hán, không dùng pinyin.',result.missing||[]);return;}stopAudio();save();renderAll();document.querySelector(`[data-p9-panel] .p9-result`)?.scrollIntoView({behavior:'smooth',block:'center'});return;}
      const found=locate(b.dataset.qid);if(!found)return;const {g,q}=found;
      if(action==='play'){await play(q,b);return;}
      const inReview=!!b.closest('[data-p9-review]');
      if(!inReview&&(!E.unlocked(bank,state,bank.groups.indexOf(g))||lastAttempt(g)))return;
      const answers=inReview?reviewAnswers:E.groupState(state,g.id).draft;
      if(inReview&&reviewResults[q.id])return;
      if(action==='answer'){answers[q.id]=q.options[Number(b.dataset.option)];if(!inReview)save();const card=b.closest('[data-p9-q]');card.querySelectorAll('[data-p9-action="answer"]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));return;}
      if(action==='token'||action==='remove-token'){const a=Array.isArray(answers[q.id])?[...answers[q.id]]:[],n=Number(b.dataset.token);if(action==='token'&&!a.includes(n))a.push(n);if(action==='remove-token'&&a.includes(n))a.splice(a.indexOf(n),1);answers[q.id]=a;if(!inReview)save();const card=b.closest('[data-p9-q]');const panel=card.parentElement;card.outerHTML=questionHtml(q,g.questions.indexOf(q),g,inReview);panel.querySelector(`[data-p9-q="${q.id}"] [data-p9-action="${action==='token'?'remove-token':'token'}"][data-token="${n}"]`)?.focus();return;}
      if(action==='check-review'){const r=E.grade(q,answers[q.id]);if(r.status==='missing'){toast('Hoàn thành câu trả lời trước khi kiểm tra.');return;}reviewResults[q.id]=r;renderReview();}
    });
    document.addEventListener('input',e=>{const el=e.target;if(el.matches('[data-p9-input]')){const found=locate(el.dataset.qid);if(!found)return;const inReview=!!el.closest('[data-p9-review]');if(inReview)reviewAnswers[found.q.id]=el.value;else if(!lastAttempt(found.g)){E.groupState(state,found.g.id).draft[found.q.id]=el.value;save();}}
      if(el.matches('[data-p9-search]')){search=el.value;const start=el.selectionStart;renderWords();const next=document.querySelector('[data-p9-search]');next.focus();next.setSelectionRange(start,start);}
    });
    document.addEventListener('change',async e=>{const el=e.target;if(el.matches('[data-p9-speed]')&&activeAudio?.dataset.p9Listening===el.dataset.qid)activeAudio.playbackRate=Number(el.value)||1;if(el.matches('[data-p9-lesson]')){state.selectedLessons=[...document.querySelectorAll('[data-p9-lesson]:checked')].map(x=>Number(x.dataset.p9Lesson));revealed.clear();save();renderWords();}
      if(el.matches('[data-p9-filter]')){wordFilter=el.value;renderWords();}
      if(el.matches('[data-p9-import]')){const file=el.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Tệp quá lớn.');const fresh=E.restore(bank,JSON.parse(await file.text()));if(E.totals(bank,state).groups&&!confirm('Thay tiến độ bài 9 trên trình duyệt này bằng tệp đã chọn?'))return;stopAudio();state=fresh;if(!E.unlocked(bank,state,activeGroup))activeGroup=0;save();renderWords();renderAll();toast('Đã nhập tiến độ bài 9.');}catch(error){toast('Không nhập được: '+error.message);}finally{el.value='';}}
    });
    document.addEventListener('click',e=>{if(e.target.closest('.section-tab'))stopAudio();});
    window.addEventListener('pagehide',stopAudio);
  }
  function home(){const grid=document.getElementById('lessonGrid');if(!grid)return;const link=grid.querySelector('a[href="lesson.html?id=9&sec=vocab"]');const card=link?.closest('.lesson-card');if(!card)return;const s=E.totals(bank,state);const tag=document.createElement('div');tag.className='p9-home-tag';tag.innerHTML=`Bài tập bài 9 · ${s.total}/30 câu đã nộp · <a href="lesson.html?id=9&sec=practice">Mở 6 nhóm bài tập →</a>`;card.appendChild(tag);const bar=card.querySelector('.mini-progress i');if(bar)bar.style.width=(s.total/30*100)+'%';}
  function mount(){if(document.getElementById('lessonGrid')){home();return;}if(Number(new URL(location.href).searchParams.get('id'))!==9||!document.getElementById('practice'))return;
    document.getElementById('practice').innerHTML='<div class="p9" id="pilot9Homework"></div>';
    document.getElementById('vocab').innerHTML='<div class="p9" id="pilot9Vocab"></div>';
    for(const [name,title] of [['listening','Nghe hiểu'],['review','Ôn câu cần luyện']]){if(!secOrder.includes(name))secOrder.push(name);secNames[name]=title;const section=document.createElement('section');section.id=name;section.className='content-section';section.innerHTML=`<div class="p9" id="${name==='listening'?'pilot9Listening':'pilot9Review'}"></div>`;document.getElementById('practice').after(section);document.querySelectorAll('.top-section-tabs,.mobile-section-tabs .section-tabs').forEach(nav=>{const b=document.createElement('button');b.type='button';b.className='section-tab';b.dataset.sec=name;b.textContent=title;nav.appendChild(b);});}
    document.querySelectorAll('.section-tab[data-sec="practice"]').forEach(b=>b.textContent='Bài tập · 30 câu');
    const chip=document.querySelector('.open-access-chip');if(chip)chip.textContent='Bài 9: tự do xem nội dung học; 6 nhóm bài tập mở lần lượt sau khi nộp.';
    const sec=new URL(location.href).searchParams.get('sec');if(['listening','review'].includes(sec))showSection(sec,false);
    bind();renderWords();renderAll();
    window.__HSK1_PILOT9_DIAGNOSTICS={version:bank.version,questions:bank.groups.reduce((n,g)=>n+g.questions.length,0),groups:bank.groups.length,lesson:9,storageKey:KEY};
  }
  if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
