import type {Track} from './types.ts';
export interface VerifiedSegment{track:string;start:number;end:number;sourceText:string;unit?:string;verification:{status:string;method:string;humanListening:boolean};subsegments?:string[];parentLineId?:string}
export interface SegmentData{schemaVersion:number;tracks:Record<string,{sourceHash:string;duration:number;containerDuration?:number}>;words:Record<string,VerifiedSegment>;lines:Record<string,VerifiedSegment>;subsegments:Record<string,VerifiedSegment>;unresolved:unknown[]}
export function validateSegments(value:SegmentData,tracks:readonly Track[]):SegmentData{
 if(!value||value.schemaVersion!==1||!value.tracks||!value.words||!value.lines||!value.subsegments||!Array.isArray(value.unresolved))throw Error('Invalid original-audio segment manifest');
 const sources=new Map(tracks.map(t=>[t.file,t]));for(const [file,declared]of Object.entries(value.tracks)){const source=sources.get(file);if(!source||source.sha256!==declared.sourceHash||Math.abs(source.duration-(declared.containerDuration??declared.duration))>.06||!Number.isFinite(declared.duration)||declared.duration<=0)throw Error('Segment source hash or duration mismatch: '+file)}
 for(const kind of ['words','lines','subsegments'] as const)for(const [id,s]of Object.entries(value[kind])){const source=sources.get(s.track);if(!source||!value.tracks[s.track]||s.verification?.status!=='verified'||!s.sourceText?.trim()||!Number.isFinite(s.start)||!Number.isFinite(s.end)||s.start<0||s.end<=s.start||s.end>source.duration+.05||!id.startsWith(`hsk${source.level}-fltrp-2026:l${String(source.lesson).padStart(2,'0')}:`)||source.kind!==(kind==='words'?'vocab':'text'))throw Error('Invalid, foreign or unverified original-audio range: '+id)}
 for(const [id,line]of Object.entries(value.lines))if(line.subsegments){let previous=line.start;for(const subId of line.subsegments){const s=value.subsegments[subId];if(!s||s.parentLineId!==id||s.track!==line.track||s.start<previous-.025||s.end>line.end+.025)throw Error('Invalid sentence boundary: '+subId);previous=s.end}if(line.subsegments.map(sub=>value.subsegments[sub]!.sourceText).join('').replace(/\s/g,'')!==line.sourceText.replace(/\s/g,''))throw Error('Sentence fragments do not preserve source text: '+id)}
 return structuredClone(value);
}
