import type {Track} from './types.ts';
export interface Verification {status:string;method:string;contentMatch?:string;observedTranscript?:string;humanListening:boolean;devicePlaybackCertified?:boolean;pronunciationToneCertified?:boolean}
export interface GuardedSentenceEvidence {sampleRate:number;sourceSampleRange:[number,number];sourcePCM_SHA256:string;cropPCM_SHA256:string;reviewReportSHA256:string;lowProbabilityFlagsRetained:boolean;observationGlyphMapping:Record<string,string>;rawModelEvidence:{model:string;file:string;sha256:string;rawTranscript:string;minimumRawProbability:number;rawLowProbabilityWordsBelow0_5:{start:number;end:number;word:string;probability:number}[]}[]}
export interface VerifiedSegment {track:string;sourceHash?:string;start:number;end:number;sourceText:string;sourcePinyin?:string;unit?:string;repetition?:number;verification:Verification;subsegments?:string[];parentLineId?:string;sentenceNumber?:number;guardedEvidence?:GuardedSentenceEvidence}
export interface UnresolvedSegment {id:string;kind:string;track:string;sourceHash?:string;sourceText:string;sourcePinyin?:string;status:string;fallback:string}
export interface SegmentData {humanListening?:boolean;devicePlaybackCertified?:boolean;pronunciationToneCertified?:boolean;schemaVersion:number;scope?:{levels:number[];lessons:number[]};tracks:Record<string,{sourceHash:string;duration:number;containerDuration?:number}>;words:Record<string,VerifiedSegment>;lines:Record<string,VerifiedSegment>;subsegments:Record<string,VerifiedSegment>;unresolved:UnresolvedSegment[]}
interface SourceBinding {level:number;lesson:number;track:string;sourceText:string;sourcePinyin:string;sentences?:{id:string;sourceText:string;sourcePinyin:string}[]}
interface RangeBinding {kind:string;track:string;start:number;end:number;unit?:string;repetition:number|null;parentLineId:string|null;method:string;contentMatch?:string;observedTranscript:string|null}
export interface SegmentAuthority {schemaVersion:number;tracks:Record<string,{sourceHash:string;decodedDuration:number;containerDuration:number}>;lessons:Record<string,{level:number;number:number;courseId:string}>;words:Record<string,SourceBinding>;lines:Record<string,SourceBinding>;ranges:Record<string,RangeBinding>}
export interface ReviewedSentenceSubset extends SegmentData {coverageMode:'reviewed-sentence-subset';review:{file:string;sha256:string};acceptedRuntimeFragmentIds:string[]}
export interface ReviewedSentenceAuthority {schemaVersion:number;coverageMode:'reviewed-sentence-subset';review:{file:string;sha256:string};acceptedRuntimeFragmentIds:string[];tracks:SegmentAuthority['tracks'];fragments:Record<string,{kind:'lines'|'subsegments';level:number;lesson:number;sourceParent?:{id:string;sourceText:string;sourcePinyin:string;sentences:{id:string;sourceText:string;sourcePinyin:string}[]};segment:VerifiedSegment}>}
function fail(message:string):never{throw Error('Invalid original-audio manifest: '+message)}
const sameSet=(actual:string[],expected:string[])=>actual.length===expected.length&&new Set(actual).size===actual.length&&actual.every(x=>expected.includes(x));
// These two exact source-frame gates are the complete scope of the independent
// post-crop review. They do not authorize a whole lesson, parent turn, or word.
const reviewedSentenceReport='76c0d3571f5ea0ce1c2d40de7baeffe3a58155ee6782a27636d99865c761501c';
const reviewedSentenceGates:Record<string,{kind:'lines'|'subsegments';frames:[number,number];parent:string|null;ordinal:number}>={
 'hsk2-fltrp-2026:l04:text2:line3':{kind:'lines',frames:[159680,197921],parent:null,ordinal:1},
 'hsk2-fltrp-2026:l05:text2:line8:sentence2':{kind:'subsegments',frames:[572480,614240],parent:'hsk2-fltrp-2026:l05:text2:line8',ordinal:2},
};
function canonicalJSON(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonicalJSON).join(',')+']';if(value&&typeof value==='object')return '{'+Object.entries(value).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([key,item])=>JSON.stringify(key)+':'+canonicalJSON(item)).join(',')+'}';return JSON.stringify(value)??''}
// Pin the complete accepted source/evidence snapshot, not merely two mutually
// agreeing JSON files. This checksum includes low-probability raw observations.
const reviewedSentenceAuthoritySHA256='5fde9de3374e597ecd7cffaf84223288f51ad6d1c48c41c109374cdefcb4869b';
export async function validateReviewedSentenceSubset(value:ReviewedSentenceSubset,tracks:readonly Track[],authority:ReviewedSentenceAuthority):Promise<SegmentData> {
 const ids=Object.keys(reviewedSentenceGates);
 if(!value||value.schemaVersion!==1||value.coverageMode!=='reviewed-sentence-subset'||authority?.schemaVersion!==1||authority.coverageMode!==value.coverageMode||!value.tracks||!value.words||!value.lines||!value.subsegments||!Array.isArray(value.unresolved)||Object.keys(value.words).length||value.unresolved.length)fail('reviewed sentence subset shape');
 const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonicalJSON(authority)));if([...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')!==reviewedSentenceAuthoritySHA256)fail('reviewed sentence subset frozen authority checksum');
 if(value.review?.sha256!==reviewedSentenceReport||authority.review?.sha256!==reviewedSentenceReport||value.review.file!==authority.review.file||!sameSet(value.acceptedRuntimeFragmentIds??[],ids)||!sameSet(authority.acceptedRuntimeFragmentIds??[],ids)||!sameSet(Object.keys(authority.fragments??{}),ids)||!sameSet([...Object.keys(value.lines),...Object.keys(value.subsegments)],ids))fail('reviewed sentence subset authority or exact two IDs');
 if(JSON.stringify(value.scope)!==JSON.stringify({levels:[2],lessons:[4,5]}))fail('reviewed sentence subset scope');
 for(const key of ['humanListening','devicePlaybackCertified','pronunciationToneCertified'] as const)if(value[key]!==false)fail('reviewed sentence subset certification '+key);
 const sources=new Map(tracks.map(t=>[t.file,t]));
 const expectedTracks=ids.map(id=>authority.fragments[id]!.segment.track);
 if(!sameSet(Object.keys(value.tracks),expectedTracks)||!sameSet(Object.keys(authority.tracks??{}),expectedTracks))fail('reviewed sentence subset source tracks');
 for(const [file,declared]of Object.entries(value.tracks)){const source=sources.get(file),approved=authority.tracks[file];if(!source||source.kind!=='text'||!approved||source.sha256!==declared.sourceHash||declared.sourceHash!==approved.sourceHash||declared.duration!==approved.decodedDuration||declared.containerDuration!==approved.containerDuration||Math.abs(source.duration-approved.containerDuration)>.06)fail('reviewed sentence subset source hash/duration '+file)}
 for(const id of ids){const gate=reviewedSentenceGates[id]!,binding=authority.fragments[id]!,s=value[gate.kind][id],source=sources.get(s?.track);
  if(!s||binding.kind!==gate.kind||binding.level!==2||binding.lesson!==(gate.kind==='lines'?4:5)||source?.level!==binding.level||source.lesson!==binding.lesson||JSON.stringify(s)!==JSON.stringify(binding.segment))fail('reviewed sentence subset source/evidence binding '+id);
  const evidence=s.guardedEvidence,verification=s.verification;
  if(s.sourceHash!==source.sha256||s.unit!=='sentence'||s.repetition!==undefined||s.subsegments!==undefined||s.sentenceNumber!==gate.ordinal||(s.parentLineId??null)!==gate.parent||s.start!==gate.frames[0]/16000||s.end!==gate.frames[1]/16000||s.end>value.tracks[s.track]!.duration||verification?.status!=='verified'||verification.method!=='independently-reviewed-unprompted-dual-model-crop+source-frame-guards'||verification.contentMatch!=='exact-CJK-after-review-scoped-five-glyph-observation-normalization'||verification.humanListening!==false||verification.devicePlaybackCertified!==false||verification.pronunciationToneCertified!==false)fail('reviewed sentence subset range/unit/certification '+id);
  if(!evidence||evidence.sampleRate!==16000||JSON.stringify(evidence.sourceSampleRange)!==JSON.stringify(gate.frames)||evidence.reviewReportSHA256!==reviewedSentenceReport||evidence.lowProbabilityFlagsRetained!==true||!/^([a-f0-9]{64})$/.test(evidence.sourcePCM_SHA256)||!/^([a-f0-9]{64})$/.test(evidence.cropPCM_SHA256)||!sameSet(evidence.rawModelEvidence.map(e=>e.model),['small','medium'])||evidence.rawModelEvidence.some(e=>!/^([a-f0-9]{64})$/.test(e.sha256)||e.minimumRawProbability<0||e.minimumRawProbability>1))fail('reviewed sentence subset frame/raw evidence '+id);
  if(gate.parent){const parent=binding.sourceParent,part=parent?.sentences[gate.ordinal-1];if(!parent||parent.id!==gate.parent||parent.sentences.length!==2||part?.id!==id||part.sourceText!==s.sourceText||part.sourcePinyin!==s.sourcePinyin||gate.parent in value.lines||parent.sentences[0]!.id in value.subsegments)fail('reviewed sentence subset parent/sibling/ordinal '+id)}else if(binding.sourceParent)fail('reviewed sentence subset unexpected parent '+id);
 }
 return structuredClone(value);
}
export function validateSegments(value:SegmentData,tracks:readonly Track[],authority:SegmentAuthority):SegmentData {
 if(!value||value.schemaVersion!==1||!value.tracks||!value.words||!value.lines||!value.subsegments||!Array.isArray(value.unresolved)||authority?.schemaVersion!==1)fail('shape or source/range authority missing');
 for(const key of ['humanListening','devicePlaybackCertified','pronunciationToneCertified'] as const)if(key in value&&value[key]!==false)fail('unsupported root certification '+key);
 const scope=value.scope;if(!scope||!Array.isArray(scope.levels)||!scope.levels.length||!scope.levels.every(n=>n===2||n===3)||new Set(scope.levels).size!==scope.levels.length||!Array.isArray(scope.lessons)||!scope.lessons.length||!scope.lessons.every(n=>Number.isInteger(n)&&n>0)||new Set(scope.lessons).size!==scope.lessons.length)fail('scope');
 const inScope=(s:{level:number;lesson:number})=>scope.levels.includes(s.level)&&scope.lessons.includes(s.lesson);
 for(const level of scope.levels)for(const n of scope.lessons){const id=`hsk${level}-fltrp-2026:l${String(n).padStart(2,'0')}`;if(!authority.lessons[id]||authority.lessons[id].level!==level||authority.lessons[id].number!==n)fail('unreviewed lesson scope '+id)}
 const sources=new Map(tracks.map(t=>[t.file,t]));if(!sameSet(Object.keys(value.tracks),tracks.filter(inScope).map(t=>t.file)))fail('missing or extra source tracks');
 for(const [file,declared]of Object.entries(value.tracks)){const source=sources.get(file);if(!source||!inScope(source)||!authority.tracks?.[file]||declared.duration!==authority.tracks[file].decodedDuration||(declared.containerDuration??declared.duration)!==authority.tracks[file].containerDuration||declared.sourceHash!==authority.tracks[file].sourceHash||source.sha256!==declared.sourceHash||Math.abs(source.duration-(declared.containerDuration??declared.duration))>.06||!Number.isFinite(declared.duration)||declared.duration<=0)fail('source hash/duration '+file)}
 const expectedWords=Object.entries(authority.words).filter(([,s])=>inScope(s)),expectedLines=Object.entries(authority.lines).filter(([,s])=>inScope(s));
 const unresolvedIds=value.unresolved.map(s=>s.id);if(!sameSet([...Object.keys(value.words),...unresolvedIds],expectedWords.map(([id])=>id)))fail('word/unresolved partition');if(!sameSet(Object.keys(value.lines),expectedLines.map(([id])=>id)))fail('source-line coverage');
 const children=new Map<string,{parent:string;source:SourceBinding}>();
 for(const [id,binding]of expectedLines){const parts=binding.sentences??[];if(!parts.length)fail('missing actual sentence definition '+id);if(parts.length>1)for(const p of parts)children.set(p.id,{parent:id,source:{...binding,sourceText:p.sourceText,sourcePinyin:p.sourcePinyin}})}
 if(!sameSet(Object.keys(value.subsegments),[...children.keys()]))fail('missing or orphan actual sentences');
 function sourceCheck(id:string,s:{track:string;sourceHash?:string;sourceText:string;sourcePinyin?:string},binding:SourceBinding|undefined){const track=sources.get(s.track);if(!binding||!track||!inScope(track)||s.track!==binding.track||s.sourceHash!==track.sha256||s.sourceText!==binding.sourceText||s.sourcePinyin!==binding.sourcePinyin)fail('source identity, text, pinyin or track '+id)}
 for(const item of value.unresolved){sourceCheck(item.id,item,authority.words[item.id]);if('start' in item||'end' in item||item.kind!=='word'||item.status!=='pending'||item.fallback!=='whole-source-vocabulary-track-with-explicit-label'||item.id in value.words)fail('unresolved word '+item.id)}
 for(const kind of ['words','lines','subsegments'] as const)for(const [id,s]of Object.entries(value[kind])){
  const binding=kind==='words'?authority.words[id]:kind==='lines'?authority.lines[id]:children.get(id)?.source;sourceCheck(id,s,binding);
  const original=sources.get(s.track)!,approved=authority.ranges[id];if(!approved||approved.kind!==kind||approved.track!==s.track||approved.start!==s.start||approved.end!==s.end||approved.unit!==s.unit||approved.repetition!==(s.repetition??null)||approved.parentLineId!==(s.parentLineId??null)||approved.method!==s.verification?.method||approved.contentMatch!==s.verification?.contentMatch||approved.observedTranscript!==(s.verification?.observedTranscript??null))fail('unreviewed timing/evidence binding '+id);
  if(s.verification.status!=='verified'||s.verification.humanListening!==false||s.verification.devicePlaybackCertified!==false||s.verification.pronunciationToneCertified!==false||!Number.isFinite(s.start)||!Number.isFinite(s.end)||s.start<0||s.end<=s.start||s.end>Math.min(original.duration+.05,value.tracks[s.track]!.duration+.025)||original.kind!==(kind==='words'?'vocab':'text'))fail('range or unsupported certification '+id);
  if(kind==='words'&&(s.unit!=='single-original-pronunciation'||![1,2].includes(s.repetition??0)||s.subsegments||s.parentLineId))fail('single pronunciation '+id);
 }
 for(const [id,binding]of expectedLines){const line=value.lines[id]!,parts=binding.sentences!;if(parts.length===1){if(line.unit!=='sentence'||line.subsegments?.length)fail('single-sentence labeling '+id)}else{if(!['source-paragraph','source-multi-sentence-line','dialogue-turn'].includes(line.unit??'')||!sameSet(line.subsegments??[],parts.map(p=>p.id))||(line.subsegments??[]).some((s,i)=>s!==parts[i]!.id))fail('multi-sentence labeling/order '+id);let previous=line.start;for(const p of parts){const child=value.subsegments[p.id]!;if(child.unit!=='sentence'||child.parentLineId!==id||child.track!==line.track||child.start<previous-.025||child.end>line.end+.025||child.subsegments?.length)fail('child relationship/boundary '+p.id);previous=child.end}}
 }
 for(const file of Object.keys(value.tracks)){const lines=Object.values(value.lines).filter(s=>s.track===file).sort((a,b)=>a.start-b.start);for(let i=1;i<lines.length;i++)if(lines[i]!.start<lines[i-1]!.end-.025)fail('source lines overlap '+file)}
 return structuredClone(value);
}

export function mergeSegmentData(values:readonly SegmentData[]):SegmentData {
 const combined:SegmentData={schemaVersion:1,tracks:{},words:{},lines:{},subsegments:{},unresolved:[]};
 for(const value of values){for(const [file,track]of Object.entries(value.tracks)){if(combined.tracks[file]&&JSON.stringify(combined.tracks[file])!==JSON.stringify(track))fail('conflicting duplicate source track '+file);combined.tracks[file]=track}
  for(const kind of ['words','lines','subsegments'] as const)for(const [id,s]of Object.entries(value[kind])){if(combined.words[id]||combined.lines[id]||combined.subsegments[id]||combined.unresolved.some(s=>s.id===id))fail('duplicate segment across manifests '+id);combined[kind][id]=s}
  for(const item of value.unresolved){if(combined.words[item.id]||combined.lines[item.id]||combined.subsegments[item.id]||combined.unresolved.some(s=>s.id===item.id))fail('duplicate unresolved identity '+item.id);combined.unresolved.push(item)}
 }
 return combined;
}
