import {el,button,copy,download} from './dom.ts';
import type {Level} from './router.ts';
export interface BackupProvider{level:Level;edition:string;status():string;export():string;original():string|null;preview(text:string):{data:unknown;confirm(signal:AbortSignal):Promise<{ok:boolean;code:string}>}}
const count=(v:unknown)=>v&&typeof v==='object'?Object.keys(v).length:0;
export function summarizeBackup(data:unknown,level:Level):string{if(!data||typeof data!=='object')return '—';const d=data as Record<string,unknown>;if(level===1){const r=d.reading as Record<string,unknown>|undefined;return `HSK 1 · 教材记录 ${count(r?.modules)} · 旧版原始存档 ${count(d.legacyRaw)}`};return `HSK ${level} · 教材分部 ${count(d.reading)} · 作业 ${count(d.homework)} · 听力 ${count(d.listening)} · 教材练习 ${count(d.activities)}`}
export function openBackupPanel(providers:BackupProvider[],legacy:Record<string,string|null>,onApplied:()=>void){
 const controller=new AbortController(),dialog=el('dialog',undefined,'word-dialog backup-dialog'),body=el('div'),close=button(copy('关闭','Đóng'),()=>dialog.close());body.append(close);const title=el('h2',copy('学习记录备份','Sao lưu dữ liệu học tập'));title.id='unified-backup-title';dialog.setAttribute('aria-labelledby',title.id);body.append(title,el('p',copy('记录只保存在浏览器中。换设备前请下载备份；可逐级预览并恢复。','Dữ liệu chỉ lưu trong trình duyệt. Tải bản sao lưu trước khi đổi thiết bị; có thể xem trước và khôi phục từng cấp.')));
 const message=el('p');message.setAttribute('role','status');message.setAttribute('aria-live','polite');body.append(message);
 for(const p of providers){const card=el('section',undefined,'backup-course-summary');card.append(el('h3',`HSK ${p.level} · ${p.edition}`),el('p',summarizeBackup(JSON.parse(p.export()).data,p.level)),el('p',copy(`保存状态：${p.status()}`,`Trạng thái lưu: ${p.status()}`)));body.append(card)}
 body.append(button(copy('下载全部三级备份','Tải bản sao lưu cả 3 cấp'),()=>{try{const payload={app:'hsk123-unified-backup',schema:1,exportedAt:Date.now(),courses:providers.map(p=>({level:p.level,edition:p.edition,status:p.status(),backup:JSON.parse(p.export()),unreadableOriginal:p.original()})),legacyReadonly:legacy};download(`hsk123-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2));message.replaceChildren(el('span',copy('已生成下载。请保存文件并确认设备能打开。','Đã tạo tệp tải xuống. Hãy lưu và kiểm tra tệp trên thiết bị.')))}catch(e){message.textContent=String(e)}},'primary'));
 const label=el('label',copy('选择备份文件','Chọn tệp sao lưu')),file=el('input');file.type='file';file.accept='.json,application/json';file.id='unified-backup-file';label.htmlFor=file.id;const previews=el('section');body.append(label,file,previews);
 file.onchange=async()=>{const chosen=file.files?.[0];if(!chosen)return;previews.replaceChildren();try{if(chosen.size>32*1024*1024)throw Error('备份超过32MB · Tệp sao lưu vượt 32MB');const value=JSON.parse(await chosen.text());if(controller.signal.aborted)return;let candidates:{level:Level;backup:unknown}[]=[];if(value.app==='hsk123-unified-backup'&&value.schema===1&&Array.isArray(value.courses))candidates=value.courses;else{const inner=value.current??value,provider=providers.find(p=>JSON.parse(p.export()).app===inner.app);if(!provider)throw Error('无法识别课程或版本 · Không nhận diện được cấp hoặc phiên bản');candidates=[{level:provider.level,backup:inner}]}
  const seen=new Set<number>();for(const item of candidates){if(seen.has(item.level))throw Error('重复课程 · Cấp học bị trùng');seen.add(item.level);const provider=providers.find(p=>p.level===item.level);if(!provider)throw Error('不支持的课程 · Cấp học không được hỗ trợ');const pending=provider.preview(JSON.stringify(item.backup));const panel=el('section',undefined,'backup-preview');panel.append(el('h3',`HSK ${provider.level} · ${provider.edition}`),el('p',summarizeBackup(pending.data,provider.level)),el('p',copy(`将只替换HSK ${provider.level}当前版本的记录。其他级别和全部旧版原始记录保留；替换前记录可在本级进度页恢复。`,`Chỉ thay dữ liệu phiên bản hiện tại HSK ${provider.level}. Giữ nguyên cấp khác và dữ liệu gốc bản cũ; có thể khôi phục dữ liệu trước khi thay trong trang tiến độ của cấp này.`)));const confirm=button(copy(`确认恢复HSK ${provider.level}`,`Xác nhận khôi phục HSK ${provider.level}`),async()=>{if(confirm.disabled)return;confirm.disabled=true;const result=await pending.confirm(controller.signal);if(controller.signal.aborted)return;if(result.ok){message.replaceChildren(el('span',copy(`HSK ${provider.level}已恢复`,`Đã khôi phục HSK ${provider.level}`)));panel.replaceChildren(el('p',copy('恢复完成；再次更改前请重新选择文件并预览。','Khôi phục hoàn tất; chọn lại tệp và xem trước trước khi thay đổi tiếp.')));onApplied()}else{message.replaceChildren(el('span',copy('恢复未完成，可能有其他修改。请重新选择文件预览；当前记录没有被此操作替换。','Chưa khôi phục; có thể có thay đổi khác. Chọn lại tệp để xem trước; thao tác này chưa thay dữ liệu hiện tại.')))}});panel.append(confirm);previews.append(panel)}
 }catch(e){previews.replaceChildren();message.textContent=e instanceof Error?e.message:String(e)}};
 dialog.append(body);document.body.append(dialog);dialog.addEventListener('close',()=>{controller.abort();dialog.remove()},{once:true});dialog.showModal();close.focus();return()=>dialog.close();
}
