import {test,expect} from '@playwright/test';
import {sourcePilotCases} from '../../../hsk1-app/tests/browser/source-pilot-cases.ts';
sourcePilotCases('/#view=lesson&level=1&lesson=4&section=practice','unified',test,expect);
import {sourcePairCases} from '../../../hsk1-app/tests/browser/source-pair-cases.ts';
sourcePairCases('/#view=lesson&level=1&lesson=4&section=practice','/#view=progress&level=1&lesson=4','unified',test,expect);
test('unified full three-course schema2 roundtrip includes nonempty HSK1 source domain',async({page})=>{
  await page.goto('/#view=lesson&level=1&lesson=4&section=practice');const card=page.locator('[data-hsk1-source-pilot] .activity-card').first();await card.locator('select').selectOption('D');await card.getByRole('button',{name:'保存并查看反馈'}).click();await expect(card.locator('.activity-feedback')).toContainText('参考答案');
  await page.getByRole('button',{name:'统一备份与恢复'}).click();const dialog=page.getByRole('dialog',{name:'学习记录备份'});await expect(dialog).toBeVisible();const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载全部三级备份'}).click()]);const path=await download.path();if(!path)throw Error('Missing unified full backup');const {readFileSync}=await import('node:fs');const bytes=readFileSync(path),backup=JSON.parse(bytes.toString());expect(backup.schema).toBe(2);expect(backup.courses.map((c:any)=>c.level)).toEqual([1,2,3]);expect(backup.courses[0].domains.map((d:any)=>d.name)).toEqual(['primary','textbook-source']);expect(Object.keys(backup.courses[0].domains[1].backup.data.records)).toHaveLength(1);expect(backup.courses[0].domains[0].backup.data.homework30.lessons['1'].choice.history).toHaveLength(2);
  const original=await page.evaluate(()=>localStorage.getItem('ran_hsk1_textbook_source_v1'));await dialog.locator('#unified-backup-file').setInputFiles({name:'all-three.json',mimeType:'application/json',buffer:bytes});await expect(dialog.locator('.backup-preview')).toHaveCount(3);await dialog.getByRole('button',{name:'确认恢复HSK 1'}).click();await expect(dialog).toContainText('HSK 1已恢复');expect(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('ran_hsk1_textbook_source_v1')!).data.records).length)).toBe(1);await expect(page.locator('#reading-save-status')).toHaveAttribute('data-state','saved');const primaryOnly=backup.courses[0].domains[0].backup;const currentSource=await page.evaluate(()=>localStorage.getItem('ran_hsk1_textbook_source_v1'));await dialog.locator('#unified-backup-file').setInputFiles({name:'primary-old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(primaryOnly))});await expect(dialog.locator('.backup-preview')).toContainText('当前教材练习记录全部保留');await dialog.getByRole('button',{name:'确认恢复HSK 1'}).click();await expect(dialog).toContainText('HSK 1已恢复');expect(await page.evaluate(()=>localStorage.getItem('ran_hsk1_textbook_source_v1'))).toBe(currentSource);expect(JSON.parse(currentSource!).data).toEqual(JSON.parse(original!).data);
});
