import {test,expect} from '@playwright/test';
import raw16 from '../../content/hsk3/lesson-16.json' with {type:'json'};import raw17 from '../../content/hsk3/lesson-17.json' with {type:'json'};import raw18 from '../../content/hsk3/lesson-18.json' with {type:'json'};
import type {Lesson} from '../../src/types.ts';import {activityReady,expectLessonReady,openLesson,singleAnswerFields,sourceActivity,submitIncomplete,submitSaved,type LessonFixture} from './lesson-ready.ts';
const lesson16=raw16 as unknown as Lesson & LessonFixture,lesson17=raw17 as unknown as Lesson & LessonFixture,lesson18=raw18 as unknown as Lesson & LessonFixture;
test.beforeEach(async({page})=>page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const optionalValue of ['', '虚构续问：公园什么时候开放？'])test(`HSK3 lesson16 explicit optional continuation ${optionalValue?'filled':'empty'} survives submission reload export and restore`,async({page})=>{
 await page.setViewportSize({width:390,height:900});await openLesson(page,lesson16,'practice');const a=sourceActivity(lesson16,'classroom'),g=await activityReady(page,a),inputs=g.locator('textarea');await expect(inputs).toHaveCount(4);const marker=g.locator('.optional-field-note');await expect(marker).toHaveCount(1);expect(await marker.evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThanOrEqual(14);await expect(marker).toContainText('可选，可留空');await expect(marker).toContainText('Tùy chọn, có thể để trống');await expect(marker.locator('..')).toHaveAttribute('for',a.fields[3].id);
 for(let i=0;i<2;i++)await inputs.nth(i).fill(`虚构动物的回答${i+1}`);if(optionalValue)await inputs.nth(3).fill(optionalValue);await submitIncomplete(page,a);await inputs.nth(2).fill('虚构动物的回答3');await submitSaved(page,lesson16,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await expect(inputs.nth(3)).toHaveValue(optionalValue);await page.reload();await expectLessonReady(page,lesson16,'practice');await activityReady(page,a);await expect(inputs.nth(3)).toHaveValue(optionalValue);
 const saved=await page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id],a.id);expect(saved.checkedAt).toBeGreaterThan(0);
 await page.getByRole('button',{name:'统一备份与恢复'}).click();const dialog=page.getByRole('dialog',{name:'学习记录备份'});const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载全部三级备份'}).click()]);const file=await download.path();if(!file)throw Error('No backup download');const {readFileSync}=await import('node:fs'),bytes=readFileSync(file),backup=JSON.parse(bytes.toString());expect(backup.courses.find((x:{level:number})=>x.level===3).backup.data.activities[a.id]).toEqual(saved);await dialog.getByRole('button',{name:'关闭',exact:false}).click();
 await inputs.nth(3).fill('备份后修改的虚构内容');await expect(g.locator('.activity-feedback')).toBeEmpty();await expect.poll(()=>page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id].checkedAt,a.id)).toBeNull();await page.getByRole('button',{name:'统一备份与恢复'}).click();await dialog.locator('#unified-backup-file').setInputFiles({name:'optional-continuation.json',mimeType:'application/json',buffer:bytes});await expect(dialog.locator('.backup-preview')).toHaveCount(3);await dialog.getByRole('button',{name:'确认恢复HSK 3'}).click();await expect(dialog).toContainText('HSK 3已恢复');await dialog.getByRole('button',{name:'关闭',exact:false}).click();await openLesson(page,lesson16,'practice');await activityReady(page,a);await expect(inputs.nth(3)).toHaveValue(optionalValue);for(let i=0;i<3;i++)await expect(inputs.nth(i)).toHaveValue(`虚构动物的回答${i+1}`);expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id],a.id)).toEqual(saved);await page.reload();await expectLessonReady(page,lesson16,'practice');await expect(inputs.nth(3)).toHaveValue(optionalValue);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id],a.id)).toEqual(saved);
});
for(const width of [320,390,768,1440])for(const lesson of [lesson16,lesson17,lesson18])test(`HSK3 lesson ${lesson.number} final-unit source views and every manifest identity at ${width}`,async({page})=>{
 const errors:string[]=[],seen=new Set<string>(),figures=new Set<string>();page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});
 for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
  await openLesson(page,lesson,section,scene);if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(seen.has(id)).toBe(false);seen.add(id);await activityReady(page,lesson.activities.find(a=>a.id===id)!)}for(const id of await page.locator('main figure[data-illustration-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.illustrationId!))){expect(figures.has(id),id+' rendered more than once').toBe(false);figures.add(id)}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true)}
  if(section==='overview'){await expect((await activityReady(page,sourceActivity(lesson,'objectives'))).locator('input[type=checkbox]')).toHaveCount(lesson.number===17?3:4);const matching=await activityReady(page,sourceActivity(lesson,'warmup1-matching'));await expect(matching.locator('select')).toHaveCount(lesson.number===16?5:6);await expect(matching.locator('img')).toHaveCount(lesson.number===16?1:6)}
  if(section==='text'){await expect((await activityReady(page,sourceActivity(lesson,`text${scene}-reading`))).locator('textarea')).toHaveCount(3);await expect(page.locator('main img')).toHaveCount(lesson.number===16&&scene===2?0:1)}
  if(section==='practice'){const counts=lesson.number===16?[4,3,2]:lesson.number===17?[5,3,4]:[4,4,4];for(const[i,count]of counts.entries()){const g=await activityReady(page,sourceActivity(lesson,`picture${i+1}`));await expect(g.locator('input')).toHaveCount(count);await expect(g.locator('img')).toHaveCount(1)}const g=await activityReady(page,sourceActivity(lesson,'classroom'));await expect(g.locator('textarea')).toHaveCount(lesson.number===16?4:lesson.number===17?3:1);await expect(g.locator('img')).toHaveCount(lesson.number===17?1:0)}
  if(section==='culture'){await expect(page.locator('main audio,main video')).toHaveCount(0);await expect(page.locator('main img')).toHaveCount(lesson.number===16?1:0);if(lesson.number===18){const g=await activityReady(page,sourceActivity(lesson,'review-grammar'));await expect(g.locator('tbody tr')).toHaveCount(12);await expect(g.locator('input[type=checkbox]')).toHaveCount(24)}else await expect(page.locator('[data-activity-id*=review-]')).toHaveCount(0)}
  if([390,1440].includes(width)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk3-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
 }
 expect([...seen].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect([...figures].sort()).toEqual(lesson.illustrationManifest.map(f=>f.id).sort());expect(errors).toEqual([]);
});
for(const lesson of [lesson16,lesson17,lesson18])test(`HSK3 lesson${lesson.number} final-unit matching and word banks keep exact official keys`,async({page})=>{
 const keys=lesson.number===16?['EDABC','BACED','EBADC']:lesson.number===17?['EDCFBA','ABECD','CAEDB']:['CBDAFE','ADBCE','DCEBA'];for(const[i,[section,suffix]]of[['overview','warmup1-matching'],['practice','words-bank1'],['practice','words-bank2']].entries()){await openLesson(page,lesson,section);const a=sourceActivity(lesson,suffix),g=await activityReady(page,a),fields=singleAnswerFields(a);expect(fields.map(f=>f.answer.charAt(0)).join('')).toBe(keys[i]);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitIncomplete(page,a);for(const f of fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct')).toHaveCount(fields.length)}await page.reload();await expectLessonReady(page,lesson,'practice');await expect(page.locator('[data-activity-id*=words-bank] .feedback-correct')).toHaveCount(10);
});
for(const lesson of [lesson16,lesson17,lesson18])test(`HSK3 lesson${lesson.number} all final-unit grammar and picture references are delayed and non-unique`,async({page})=>{
 for(const section of ['grammar','practice']){await openLesson(page,lesson,section);const activities=lesson.activities.filter(a=>section==='grammar'?/:grammar\d+-practice\d+$/.test(a.id):/:picture\d+$/.test(a.id));for(const a of activities){const g=await activityReady(page,a);await expect(g.locator('.activity-feedback')).toBeEmpty();for(const[i,f]of a.fields.entries())await page.locator(`[id="${f.id}"]`).fill(`自拟表达${i+1}`);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);for(const f of a.fields)await expect(g.locator('.activity-feedback')).toContainText(f.referenceAnswer!.vi)}await page.reload();await expectLessonReady(page,lesson,section);for(const a of activities)for(const[i,f]of a.fields.entries())await expect(page.locator(`[id="${f.id}"]`)).toHaveValue(`自拟表达${i+1}`)}
});
test('HSK3 lesson17 seven-expression support panel is attached once to three durable open responses',async({page})=>{
 await page.setViewportSize({width:320,height:900});await openLesson(page,lesson17,'practice');const a=sourceActivity(lesson17,'classroom'),g=await activityReady(page,a);await expect(g.locator('img')).toHaveCount(1);await expect(g.locator('textarea')).toHaveCount(3);await g.screenshot({path:'test-results/unified-hsk3-lesson17-emotions-320.png'});for(let i=0;i<3;i++)await g.locator('textarea').nth(i).fill(`虚构情绪情境${i+1}`);await submitSaved(page,lesson17,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expectLessonReady(page,lesson17,'practice');await activityReady(page,a);for(let i=0;i<3;i++)await expect(g.locator('textarea').nth(i)).toHaveValue(`虚构情绪情境${i+1}`);
});
test('HSK3 lesson18 actual 刚才 and 刚刚 groups preserve examples and context-dependent practice stays ungraded',async({page})=>{
 await openLesson(page,lesson18,'grammar');const presentation=lesson18.grammarPresentations![0],grammar=lesson18.grammar.find(g=>g.id===presentation.grammarId)!,section=page.locator('.lesson-section.grammar').nth(lesson18.grammar.indexOf(grammar));await expect(section.locator('.grammar-explanation-group')).toHaveCount(2);await expect(section.locator('.example')).toHaveCount(4);for(const[i,group]of presentation.groups.entries()){const panel=section.locator('.grammar-explanation-group').nth(i);await expect(panel).toContainText(group.explanation.vi);for(const[j,k]of group.exampleIndices.entries())await expect(panel.locator('.example .chinese-line').nth(j)).toHaveText(grammar.examples[k].zh)}for(const i of [1,2,3]){const a=sourceActivity(lesson18,`grammar2-practice${i}`),g=await activityReady(page,a);await expect(g.locator('.activity-feedback')).toBeEmpty();await expect(g).not.toContainText('此处参考用');await expect(g).not.toContainText('Ở đây gợi ý dùng');await g.locator('input').fill('刚才');await submitSaved(page,lesson18,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await expect(g.locator('.activity-feedback')).toContainText('不是唯一答案')}
});
test('HSK3 lesson18 final source review keeps twelve rows and twenty-four independently saved choices',async({page})=>{
 await page.setViewportSize({width:320,height:900});await openLesson(page,lesson18,'culture');const a=sourceActivity(lesson18,'review-grammar'),g=await activityReady(page,a),checks=g.locator('input[type=checkbox]');await expect(g.locator('tbody tr')).toHaveCount(12);await expect(checks).toHaveCount(24);for(let i=0;i<24;i++)await checks.nth(i).setChecked(i%5===2);await submitSaved(page,lesson18,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expectLessonReady(page,lesson18,'culture');await activityReady(page,a);for(let i=0;i<24;i++)expect(await checks.nth(i).isChecked()).toBe(i%5===2);await g.screenshot({path:'test-results/unified-hsk3-lesson18-review-320.png'});
});
test('HSK3 lesson18 feedback-only explanation is absent from unsubmitted DOM and save failures then clears after edit and reset',async({page})=>{
 await openLesson(page,lesson18,'grammar');const a=sourceActivity(lesson18,'grammar2-practice3'),data=lesson18.activities.find(x=>x.id===a.id)!,g=await activityReady(page,a),note=data.feedbackNote!;expect(note.zh).toContain('此处参考用');await expect(g.locator('.activity-feedback-note')).toHaveCount(0);await expect(g).not.toContainText(note.zh);await expect(g).not.toContainText(note.vi);await g.locator('input').fill('刚才');await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');
 await page.evaluate(()=>{const w=window as typeof window & {savedSet?:typeof Storage.prototype.setItem};w.savedSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ran_hsk3_fltrp_2026_v1')throw new DOMException('Synthetic full storage','QuotaExceededError');return w.savedSet!.call(this,k,v)}});await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-problem','true');await expect(g.locator('.activity-feedback-note')).toHaveCount(0);await expect(g).not.toContainText(note.zh);await expect(g).not.toContainText(note.vi);await page.evaluate(()=>{Storage.prototype.setItem=(window as typeof window & {savedSet:typeof Storage.prototype.setItem}).savedSet});
 await submitSaved(page,lesson18,a);await expect(g.locator('.activity-feedback-note')).toHaveCount(1);await expect(g.locator('.activity-feedback-note')).toContainText(note.zh);await expect(g.locator('.activity-feedback-note')).toContainText(note.vi);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expectLessonReady(page,lesson18,'grammar');await activityReady(page,a);await expect(g.locator('.activity-feedback-note')).toContainText(note.zh);await g.locator('input').fill('刚刚');await expect(g.locator('.activity-feedback-note')).toHaveCount(0);await expect(g).not.toContainText(note.zh);await submitSaved(page,lesson18,a);await expect(g.locator('.activity-feedback-note')).toHaveCount(1);
 await page.goto('/#view=progress&level=3');await page.getByRole('button',{name:'仅重置本版学习记录'}).click();await page.getByRole('button',{name:'确认重置本版'}).click();await expect.poll(()=>page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id],a.id)).toBeUndefined();await openLesson(page,lesson18,'grammar');await activityReady(page,a);await expect(g.locator('input')).toHaveValue('');await expect(g.locator('.activity-feedback-note')).toHaveCount(0);await expect(g).not.toContainText(note.zh);await expect(g).not.toContainText(note.vi);
});
