import {test, expect} from '@playwright/test';
import raw8 from '../../content/hsk3/lesson-08.json' with {type:'json'};
import raw9 from '../../content/hsk3/lesson-09.json' with {type:'json'};
import type {Lesson} from '../../src/types.ts';
import {activityReady, expectLessonReady, openLesson, singleAnswerFields, sourceActivity, submitIncomplete, submitSaved, type LessonFixture} from './lesson-ready.ts';
const lesson8=raw8 as unknown as Lesson & LessonFixture, lesson9=raw9 as unknown as Lesson & LessonFixture;
test.beforeEach(async ({page}) => page.addInitScript(() => sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const width of [320,390,768,1440])for(const lesson of [lesson8,lesson9]){
 test(`HSK3 lesson ${lesson.number} source-specific textbook views at ${width}`,async({page})=>{
  const errors:string[]=[],seen=new Set<string>();page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});
  for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
   await openLesson(page,lesson,section,scene);if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');
   for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(seen.has(id)).toBe(false);seen.add(id);await activityReady(page,lesson.activities.find(a=>a.id===id)!)}
   expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
   for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true)}
   if(section==='overview'){await expect((await activityReady(page,sourceActivity(lesson,'objectives'))).locator('input[type=checkbox]')).toHaveCount(3);const g=await activityReady(page,sourceActivity(lesson,'warmup1-matching'));await expect(g.locator('select')).toHaveCount(6);await expect(g.locator('img')).toHaveCount(6)}
   if(section==='text'){await expect(page.locator('main img')).toHaveCount((lesson.number===8&&scene===3)||(lesson.number===9&&scene===4)?0:1);await expect((await activityReady(page,sourceActivity(lesson,`text${scene}-reading`))).locator('textarea')).toHaveCount(3);const listen=await activityReady(page,sourceActivity(lesson,`text${scene}-listening`));await expect(listen.locator('select')).toHaveCount(2);await expect(listen).toContainText('先听2遍')}
   if(section==='practice')for(const[i,count]of(lesson.number===8?[3,3,3]:[4,3,3]).entries()){const g=await activityReady(page,sourceActivity(lesson,`picture-dialogue${i+1}`));await expect(g.locator('input[type=text]')).toHaveCount(count);await expect(g.locator('img')).toHaveCount(1)}
   if(section==='culture'){if(lesson.number===8){await expect(page.locator('main')).toContainText('在中国看病');await expect(page.locator('main img')).toHaveCount(1);await expect(page.locator('main video,main audio')).toHaveCount(0)}else{await expect(page.locator('main img,main video,main audio')).toHaveCount(0);await expect((await activityReady(page,sourceActivity(lesson,'review-grammar'))).locator('input[type=checkbox]')).toHaveCount(22)}}
   if([390,1440].includes(width)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk3-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
  }
  expect([...seen].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect(errors).toEqual([]);
 });
}
for(const lesson of [lesson8,lesson9]){
 test(`HSK3 lesson${lesson.number} official source banks grade without revealing before submit`,async({page})=>{
  await openLesson(page,lesson,'practice');
  const expected=lesson.number===8?[['关心','得','方法','开','种'],['以后','突然','注意','其他','差不多']]:[['参加','球场','成绩','影响','世界'],['几乎','主要','只是','受到','得到']];
  for(const bank of [1,2]){const a=sourceActivity(lesson,`comprehensive-words${bank}`),g=await activityReady(page,a),fields=singleAnswerFields(a);expect(fields.map(f=>f.answer)).toEqual(expected[bank-1]);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitIncomplete(page,a);for(const f of fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct')).toHaveCount(5)}
  if(lesson.number===9){await expect(page.locator('main')).toContainText('在那儿做运动');await expect(page.locator('main')).toContainText('他们以前每年都是第一名');await expect(page.locator('main')).not.toContainText('在那里做运动');await expect(page.locator('main')).not.toContainText('他们以前年年都是第一名')}
  await page.reload();await expectLessonReady(page,lesson,'practice');await expect(page.locator('[data-activity-id*=comprehensive-words] .feedback-correct')).toHaveCount(10);
 });
 test(`HSK3 lesson${lesson.number} picture dialogue independent blanks persist as ungraded references`,async({page})=>{
  await openLesson(page,lesson,'practice');
  for(const[i,count]of(lesson.number===8?[3,3,3]:[4,3,3]).entries()){const a=sourceActivity(lesson,`picture-dialogue${i+1}`),g=await activityReady(page,a);await g.locator('input').first().fill('自拟表达');await submitIncomplete(page,a);for(let j=0;j<count;j++)await g.locator('input').nth(j).fill(`自拟表达${i+1}-${j+1}`);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0)}
  await page.reload();await expectLessonReady(page,lesson,'practice');for(const[i,count]of(lesson.number===8?[3,3,3]:[4,3,3]).entries()){const g=await activityReady(page,sourceActivity(lesson,`picture-dialogue${i+1}`));for(let j=0;j<count;j++)await expect(g.locator('input').nth(j)).toHaveValue(`自拟表达${i+1}-${j+1}`)}
 });
}
test('HSK3 lesson9 eleven-row review preserves twenty-two checks and two separate vocabulary fields',async({page})=>{
 await page.setViewportSize({width:320,height:900});await openLesson(page,lesson9,'culture');const ga=sourceActivity(lesson9,'review-grammar'),va=sourceActivity(lesson9,'review-vocabulary'),ea=sourceActivity(lesson9,'review-effort');const g=await activityReady(page,ga),v=await activityReady(page,va),e=await activityReady(page,ea);await expect(g.locator('tbody tr')).toHaveCount(11);await expect(g.locator('input')).toHaveCount(22);await expect(v.locator('textarea')).toHaveCount(2);
 for(let i=0;i<22;i++)await g.locator('input').nth(i).setChecked([0,3,20].includes(i));await v.locator('textarea').nth(0).fill('参加、比赛');await v.locator('textarea').nth(1).fill('得分');await e.locator('textarea').fill('继续练习表达目的');await submitSaved(page,lesson9,ga);await submitSaved(page,lesson9,va);await submitSaved(page,lesson9,ea);
 await page.reload();await expectLessonReady(page,lesson9,'culture');await activityReady(page,ga);for(let i=0;i<22;i++)if([0,3,20].includes(i))await expect(g.locator('input').nth(i)).toBeChecked();else await expect(g.locator('input').nth(i)).not.toBeChecked();await expect(v.locator('textarea').nth(0)).toHaveValue('参加、比赛');await expect(v.locator('textarea').nth(1)).toHaveValue('得分');await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);
});
test('HSK3 lesson9 potential complement third dialogue keeps both independent responses',async({page})=>{
 await openLesson(page,lesson9,'grammar');const a=sourceActivity(lesson9,'grammar2-practice3'),g=await activityReady(page,a);await expect(g.locator('input')).toHaveCount(2);await g.locator('input').first().fill('听得懂');await submitIncomplete(page,a);await g.locator('input').nth(1).fill('听不懂');await submitSaved(page,lesson9,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expectLessonReady(page,lesson9,'grammar');await activityReady(page,a);await expect(g.locator('input').first()).toHaveValue('听得懂');await expect(g.locator('input').nth(1)).toHaveValue('听不懂');
});
for(const lesson of [lesson8,lesson9])test(`HSK3 lesson${lesson.number} six picture matching choices preserve correct wrong and edited responses`,async({page})=>{
 await openLesson(page,lesson,'overview');const a=sourceActivity(lesson,'warmup1-matching'),g=await activityReady(page,a),fields=singleAnswerFields(a);expect(fields.map(f=>f.answer.charAt(0))).toEqual(lesson.number===8?['D','C','F','A','B','E']:['B','D','A','F','E','C']);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitIncomplete(page,a);for(const f of fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct')).toHaveCount(6);
 await page.locator(`[id="${fields[0].id}"]`).selectOption(fields[1].answer);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct')).toHaveCount(5);await expect(g.locator('.feedback-retry')).toHaveCount(1);await page.reload();await expectLessonReady(page,lesson,'overview');await activityReady(page,a);await expect(g.locator('.feedback-retry')).toHaveCount(1);await expect(page.locator(`[id="${fields[0].id}"]`)).toHaveValue(fields[1].answer);
});
for(const lesson of [lesson8,lesson9])test(`HSK3 lesson${lesson.number} reading references remain hidden until submission and never string grade`,async({page})=>{
 await openLesson(page,lesson,'text',1);const a=sourceActivity(lesson,'text1-reading'),g=await activityReady(page,a),source=lesson.activities.find(x=>x.id===a.id)!;expect(source.fields).toHaveLength(3);
 for(const f of source.fields){expect(f.assessment).toBe('reference');expect(f.answer).toBeUndefined();expect(f.referenceAnswer?.zh).toBeTruthy();expect(f.referenceAnswer?.vi).toBeTruthy();await expect(g.getByText(f.referenceAnswer!.zh,{exact:true})).toHaveCount(0);await expect(g.getByText(f.referenceAnswer!.vi,{exact:true})).toHaveCount(0)}
 await expect(g.locator('.activity-feedback')).toBeEmpty();await g.locator('textarea').first().fill('我想用自己的话来回答。');await submitIncomplete(page,a);for(let i=1;i<3;i++)await g.locator('textarea').nth(i).fill(`用自己的话说明课文内容${i}`);await submitSaved(page,lesson,a);
 await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await expect(g.locator('.activity-feedback')).toContainText('不是唯一答案');for(const f of source.fields){await expect(g.locator('.activity-feedback')).toContainText(f.referenceAnswer!.zh);await expect(g.locator('.activity-feedback')).toContainText(f.referenceAnswer!.vi)}
 await page.reload();await expectLessonReady(page,lesson,'text',1);await activityReady(page,a);await expect(g.locator('.activity-feedback')).toContainText(source.fields[0].referenceAnswer!.zh);await g.locator('textarea').first().fill('修改我的读后回答');await expect(g.locator('.activity-feedback')).toBeEmpty();
});
test('HSK3 prior fallback responses remain safe read-only history through backup restore and never prefill new scores',async({page})=>{
 const lesson=lesson8,q=lesson.texts[0].questions[2],warm=lesson.warmup[0],grammar=lesson.grammar[0],section=lesson.sections.find(s=>s.kind==='practice')!;
 const attack='<img src=x onerror="window.__archiveExecuted=true"><script>window.__archiveExecuted=true</script>';
 const make=(id:string,value:string,checkedAt:number|null=123)=>({[id]:{values:{[id+(id===q.id?':answer':':response')]:value},checkedAt,updatedAt:124}});
 const old={...make(q.id,attack),...make(warm.id+':0','旧图片答案',null),...make(grammar.id+':practice1','旧语法答案'),...make(section.id+':block1','旧练习答案\n保留换行')};
 await openLesson(page,lesson,'overview');await page.evaluate(old=>{const key='ran_hsk3_fltrp_2026_v1',value=JSON.parse(localStorage.getItem(key)!);value.data.activities=old;localStorage.setItem(key,JSON.stringify(value))},old);await page.reload();await expectLessonReady(page,lesson,'overview');const history=page.locator('.previous-activity-records');await expect(history).not.toHaveAttribute('open','');await history.locator('summary').click();await expect(history.locator('[data-previous-activity-id]')).toHaveCount(4);await expect(history).toContainText(attack);await expect(history).toContainText('课文1');await expect(history).toContainText('教材第');await expect(history).toContainText('当时未提交');await expect(history.locator('img,script,input,textarea,select,.feedback-correct,.feedback-retry')).toHaveCount(0);expect(await page.evaluate(()=>(window as unknown as {__archiveExecuted?:boolean}).__archiveExecuted)).toBeUndefined();
 for(const width of [320,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.evaluate(()=>{const panel=document.querySelector('.previous-activity-records')!,nav=document.querySelector('.textbook-tabs')!;scrollTo(0,panel.getBoundingClientRect().top+scrollY-nav.getBoundingClientRect().height-12)});await expect.poll(()=>history.locator('summary').evaluate(node=>node.getBoundingClientRect().top>=document.querySelector('.textbook-tabs')!.getBoundingClientRect().bottom)).toBe(true);await page.screenshot({path:`test-results/unified-hsk3-lesson8-history-viewport-${width}.png`});await history.screenshot({path:`test-results/unified-hsk3-lesson8-history-${width}.png`})}
 const warmup=await activityReady(page,sourceActivity(lesson,'warmup1-matching'));for(const control of await warmup.locator('select').all())await expect(control).toHaveValue('');await expect(warmup.locator('.activity-feedback')).toBeEmpty();
 await openLesson(page,lesson,'text',1);const reading=await activityReady(page,sourceActivity(lesson,'text1-reading'));for(const control of await reading.locator('textarea').all())await expect(control).toHaveValue('');await expect(reading.locator('.activity-feedback')).toBeEmpty();
 await page.getByRole('button',{name:'统一备份与恢复'}).click();const dialog=page.getByRole('dialog',{name:'学习记录备份'});const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载全部三级备份'}).click()]);const file=await download.path();if(!file)throw Error('No backup download');const {readFileSync}=await import('node:fs'),bytes=readFileSync(file),backup=JSON.parse(bytes.toString());expect(backup.courses.find((x:{level:number})=>x.level===3).backup.data.activities).toEqual(old);await dialog.getByRole('button',{name:'关闭',exact:false}).click();
 await page.evaluate(id=>{const key='ran_hsk3_fltrp_2026_v1',v=JSON.parse(localStorage.getItem(key)!);v.data.activities[id].values[id+':answer']='changed after backup';localStorage.setItem(key,JSON.stringify(v))},q.id);await page.reload();await expectLessonReady(page,lesson,'text',1);await page.getByRole('button',{name:'统一备份与恢复'}).click();await dialog.locator('input[type=file]').setInputFiles({name:'historical-responses.json',mimeType:'application/json',buffer:bytes});await expect(dialog.locator('.backup-preview')).toHaveCount(3);await dialog.getByRole('button',{name:'确认恢复HSK 3'}).click();await expect(dialog).toContainText('HSK 3已恢复');await dialog.getByRole('button',{name:'关闭',exact:false}).click();await openLesson(page,lesson,'overview');await expect(history).not.toHaveAttribute('open','');await history.locator('summary').click();await expect(history).toContainText(attack);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities)).toEqual(old);await page.reload();await expectLessonReady(page,lesson,'overview');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities)).toEqual(old);
});
