import {test,expect} from '@playwright/test';
import lesson2 from '../../content/hsk3/lesson-02.json' with {type:'json'};
import lesson3 from '../../content/hsk3/lesson-03.json' with {type:'json'};
test.beforeEach(async({page})=>page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const width of [320,390,768,1440])for(const lesson of [lesson2,lesson3])test(`HSK3 lesson ${lesson.number} reviewed textbook sections at ${width}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.setViewportSize({width,height:900});const ids=new Set<string>();
 for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
  await page.goto(`/#view=lesson&level=3&lesson=${lesson.number}&section=${section}&scene=${scene}`);await expect(page.locator('main h1')).toContainText(lesson.title.zh);await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');
  for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(ids.has(id),`duplicate visible activity ${id}`).toBe(false);ids.add(id)}
  const overflow=await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('body *')].map(el=>({tag:el.tagName,className:el.className,left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right})).filter(el=>el.right>innerWidth+1).slice(0,30)}));expect(overflow.documentWidth,JSON.stringify({lesson:lesson.number,section,scene,...overflow})).toBeLessThanOrEqual(overflow.width+1);
  for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((node:HTMLImageElement)=>node.complete&&node.naturalWidth>0)).toBe(true)}
  if(section==='practice'){const hints=page.locator('.picture-editorial-hints'),sources=lesson.sections.filter(s=>['practice','activity'].includes(s.kind)).map(s=>s.blocks.filter(b=>b.source.provenance==='supplemental'&&/^图片描述/.test(b.zh))).filter(blocks=>blocks.length);expect(sources.map(blocks=>blocks.length)).toEqual(lesson.number===2?[2,1]:[1]);await expect(hints).toHaveCount(sources.length);for(const[i,blocks]of sources.entries()){const group=hints.nth(i);await expect(group).not.toHaveAttribute('open','');await expect(group.locator('p')).toHaveCount(blocks.length);for(const paragraph of await group.locator('p').all())await expect(paragraph).toBeHidden();expect(await group.evaluate((node,index)=>{const selector=index===0?'[data-activity-id*="picture-dialogue"]':'[data-activity-id$="classroom-group"]';const cards=[...document.querySelectorAll(selector)];return cards.length===(index===0?3:1)&&cards.every(card=>!!(card.compareDocumentPosition(node)&Node.DOCUMENT_POSITION_FOLLOWING))},i)).toBe(true);await group.locator('summary').click();for(const[j,b]of blocks.entries()){await expect(group.locator('p').nth(j)).toBeVisible();await expect(group.locator('p').nth(j)).toContainText(b.zh);await expect(group.locator('p').nth(j)).toContainText(b.vi)}await group.locator('summary').click();await expect(group.locator('p').first()).toBeHidden()}}
  if(section==='overview'&&lesson.number===3){await expect(page.locator('[data-activity-id$=warmup1-matching] img')).toHaveCount(6);await expect(page.locator('[data-activity-id$=warmup1-matching] select')).toHaveCount(6)}
  if(section==='practice'&&lesson.number===3){const pictures=page.locator('[data-activity-id*=picture-dialogue]');for(const[i,count]of [4,3,4].entries()){await expect(pictures.nth(i).locator('input')).toHaveCount(count);await expect(pictures.nth(i).locator('img')).toHaveCount(1)}}
  if(section==='text'){const reading=page.locator(`[data-activity-id$=text${scene}-reading]`),listening=page.locator(`[data-activity-id$=text${scene}-listening]`);await expect(reading.locator('textarea')).toHaveCount(3);await expect(listening.locator('select')).toHaveCount(2);await expect(page.locator('main img')).toHaveCount(lesson.number===2&&scene===3?0:1)}
  if(section==='overview'&&lesson.number===2){await expect(page.locator('.activity-menu-sections > section')).toHaveCount(4);await expect(page.locator('.activity-menu select')).toHaveCount(5);const boxes=await page.locator('.activity-menu-section').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right}}));expect(boxes[0].y).toBeCloseTo(boxes[1].y,0);expect(boxes[2].y).toBeCloseTo(boxes[3].y,0);expect(boxes[0].x).toBeLessThan(boxes[1].x);expect(boxes[2].y).toBeGreaterThan(boxes[0].y)}
  if(section==='practice'&&lesson.number===2){const gallery=page.locator('.activity-support-figures');await expect(gallery.locator('img')).toHaveCount(3);const boxes=await gallery.locator('figure').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y}}));if(width<641){expect(boxes[1].y).toBeGreaterThan(boxes[0].y);expect(boxes[2].y).toBeGreaterThan(boxes[1].y)}else{expect(boxes[0].y).toBeCloseTo(boxes[1].y,0);expect(boxes[1].y).toBeCloseTo(boxes[2].y,0)}}
  if((width===390||width===1440)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk3-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
 }
 expect([...ids].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect(errors).toEqual([]);
});

test('HSK3 lesson2 source menu keeps five distinct blanks and exact fixed quadrant foods',async({page})=>{
 test.setTimeout(60000);
 await page.goto('/#view=lesson&level=2&lesson=15&section=overview');const otherGroup=page.locator('[data-activity-id$=warmup2-frequency]');for(const[i,v]of ['七','八','九'].entries())await otherGroup.locator('input').nth(i).fill(v);await otherGroup.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ran_hsk2_fltrp_2026_v1')!).data.activities['hsk2-fltrp-2026:l15:activity:warmup2-frequency'].values['hsk2-fltrp-2026:l15:field:warmup2-frequency1'])).toBe('七');
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=3&lesson=2&section=overview');const g=page.locator('[data-activity-id$=warmup1-menu]'),menu=g.locator('.activity-menu'),blocks=menu.locator('.activity-menu-section');await expect(menu).toHaveAttribute('role','group');await expect(menu.locator('.activity-menu-title select')).toHaveCount(1);await expect(blocks.nth(0)).toContainText('羊（yáng）肉');await expect(blocks.nth(1)).toContainText('冰激凌（bīngjīlíng）');await expect(blocks.nth(2)).toContainText('饺子');await expect(blocks.nth(3)).toContainText('奶茶');await expect(blocks.nth(2).locator('select')).toHaveCount(0);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);
 const fields=lesson2.activities.find(a=>a.id.endsWith('warmup1-menu'))!.fields;expect(fields.map(f=>f.answer)).toEqual(['菜单','鸡肉','蛋糕','饮料','绿茶']);for(const f of fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer as string);await menu.locator('select').first().focus();await page.keyboard.press('Tab');await expect(blocks.nth(0).locator('select')).toBeFocused();await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-correct')).toHaveCount(5);await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();for(const f of fields)await expect(page.locator(`[id="${f.id}"]`)).toHaveValue(f.answer as string);await page.locator(`[id="${fields[3].id}"]`).selectOption('菜单');await expect(g.locator('.activity-feedback')).toBeEmpty();await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-retry')).toHaveCount(1);await expect(g.locator('.feedback-correct')).toHaveCount(4);await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(page.locator(`[id="${fields[3].id}"]`)).toHaveValue('菜单');for(const[i,f]of fields.entries())if(i!==3)await expect(page.locator(`[id="${f.id}"]`)).toHaveValue(f.answer as string);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 const key='ran_hsk3_fltrp_2026_v1',activity=lesson2.activities.find(a=>a.menu)!.id;const other=await page.evaluate(()=>localStorage.getItem('ran_hsk2_fltrp_2026_v1'));expect(other).not.toBeNull();expect(JSON.parse(other!).data.activities['hsk2-fltrp-2026:l15:activity:warmup2-frequency'].values['hsk2-fltrp-2026:l15:field:warmup2-frequency1']).toBe('七');await page.evaluate(key=>{const w=window as any;w.__menuLockHeld=false;void navigator.locks.request(key+'-write',async()=>{w.__menuLockHeld=true;await new Promise<void>(resolve=>w.__releaseMenuLock=resolve)})},key);await expect.poll(()=>page.evaluate(()=>(window as any).__menuLockHeld)).toBe(true);await page.locator(`[id="${fields[3].id}"]`).selectOption('饮料');await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saving');await page.locator(`[id="${fields[0].id}"]`).selectOption('绿茶');await expect(g.locator('.activity-feedback')).toBeEmpty();await page.evaluate(()=>(window as any).__releaseMenuLock());await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await expect(g.locator('.activity-feedback')).toBeEmpty();await expect.poll(()=>page.evaluate(({key,activity})=>JSON.parse(localStorage.getItem(key)!).data.activities[activity].checkedAt,{key,activity})).toBe(null);await page.reload();await expect(g.locator('.activity-feedback')).toBeEmpty();await expect(page.locator(`[id="${fields[0].id}"]`)).toHaveValue('绿茶');await expect(page.locator(`[id="${fields[3].id}"]`)).toHaveValue('饮料');expect(await page.evaluate(()=>localStorage.getItem('ran_hsk2_fltrp_2026_v1'))).toBe(other);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-retry')).toHaveCount(1);await expect(g.locator('.feedback-correct')).toHaveCount(4);test.info().annotations.push({type:'delayed-submit-stage',description:'Real HSK3 Web Lock delay; edit invalidated pending answer feedback and checkedAt; durable reload preserved all values and other-course data'});
});

test('HSK3 lesson2 group support scenes zoom without duplicating picture fields and retain plan',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/#view=lesson&level=3&lesson=2&section=practice');const group=page.locator('[data-activity-id$=classroom-group]'),gallery=group.locator('.activity-support-figures');await expect(gallery.locator('img')).toHaveCount(3);await expect(group.locator('textarea')).toHaveCount(1);const imageIds=await page.locator('main figure').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.illustrationId));expect(new Set(imageIds).size).toBe(imageIds.length);const zoom=gallery.getByRole('button',{name:'放大查看示意图 · Phóng to hình minh họa'}).nth(1);await zoom.focus();await page.keyboard.press('Enter');const modal=page.getByRole('dialog',{name:'查看示意图 · Xem hình minh họa'});await expect(modal).toBeVisible();await expect(modal.locator('img')).toHaveCount(1);await page.keyboard.press('Escape');await expect(modal).toHaveCount(0);await expect(zoom).toBeFocused();await group.locator('textarea').fill('我们比较在外面吃饭、点外卖和在家做饭。');await group.getByRole('button',{name:'提交并查看反馈'}).click();await expect(group).toContainText('这是开放任务');await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(group.locator('textarea')).toHaveValue('我们比较在外面吃饭、点外卖和在家做饭。');await expect(group.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);const pictures=page.locator('[data-activity-id*="picture-dialogue"]');await expect(pictures).toHaveCount(3);for(const[i,count]of [3,3,4].entries()){await expect(pictures.nth(i).locator('input')).toHaveCount(count);await expect(pictures.nth(i).locator('img')).toHaveCount(1)}await page.goto('/#view=lesson&level=3&lesson=2&section=text&scene=1');const reading=page.locator('[data-activity-id$=text1-reading]');for(const input of await reading.locator('textarea').all())await input.fill('参考回答');await reading.getByRole('button',{name:'提交并查看反馈'}).click();await expect(reading).toContainText('对话没有说王一雪');await expect(reading.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);
});

test('HSK3 lesson3 two word banks retain textbook and answer page splits',async({page})=>{
 await page.goto('/#view=lesson&level=3&lesson=3&section=practice');for(const [index,values]of [['关','办','挺','还','才'],['打扫','环境','听说','搬家','需要']].entries()){const g=page.locator(`[data-activity-id$=comprehensive-words${index+1}]`);const activity=lesson3.activities.find(a=>a.id.endsWith('comprehensive-words'+(index+1)))!;expect(activity.fields.map(f=>f.answer)).toEqual(values);for(const f of activity.fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer as string);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-correct')).toHaveCount(5);if(index===0){await expect(g).toContainText('PDF第4页');await expect(g).toContainText('PDF第5页')}else{await expect(g).toContainText('教材第25、26页');await expect(g).toContainText('PDF第5页')}}await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(page.locator('[data-activity-id*=comprehensive-words] .feedback-correct')).toHaveCount(10);const group=page.locator('[data-activity-id$=classroom-group]');await expect(group.locator('textarea')).toHaveCount(5);for(const[i,ta]of (await group.locator('textarea').all()).entries())await ta.fill('个人回答'+i);await group.getByRole('button',{name:'提交并查看反馈'}).click();await expect(group).toContainText('这是开放任务');await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(group.locator('textarea').nth(4)).toHaveValue('个人回答4');await expect(group.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);
});

test('HSK3 lesson3 reflection keeps vocabulary categories eighteen checks and effort across pages',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=3&lesson=3&section=culture');const vocab=page.locator('[data-activity-id$=review-vocabulary]'),grammar=page.locator('[data-activity-id$=review-grammar]'),effort=page.locator('[data-activity-id$=review-effort]');await expect(vocab.locator('textarea')).toHaveCount(2);await expect(vocab).toContainText('教材第27页');await expect(grammar.locator('tbody tr')).toHaveCount(9);await expect(grammar.locator('input')).toHaveCount(18);await expect(grammar).toContainText('教材第28页');await vocab.locator('textarea').nth(0).fill('搬、箱子');await vocab.locator('textarea').nth(1).fill('需要');await grammar.locator('input').nth(0).check();await grammar.locator('input').nth(3).check();await effort.locator('textarea').fill('练习比较就和才');await effort.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(vocab.locator('textarea').nth(0)).toHaveValue('搬、箱子');await expect(vocab.locator('textarea').nth(1)).toHaveValue('需要');await expect(grammar.locator('input').nth(0)).toBeChecked();await expect(grammar.locator('input').nth(1)).not.toBeChecked();await expect(grammar.locator('input').nth(2)).not.toBeChecked();await expect(grammar.locator('input').nth(3)).toBeChecked();await expect(effort.locator('textarea')).toHaveValue('练习比较就和才');await expect(page.locator('main img')).toHaveCount(1);await expect(page.locator('main video,main audio')).toHaveCount(0);await expect(page.locator('main')).toContainText('3-1');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
