import {test,expect} from '@playwright/test';
import raw10 from '../../content/hsk3/lesson-10.json' with {type:'json'};import raw11 from '../../content/hsk3/lesson-11.json' with {type:'json'};
import type {Lesson} from '../../src/types.ts';import {activityReady,expectLessonReady,openLesson,singleAnswerFields,sourceActivity,submitIncomplete,submitSaved,type LessonFixture} from './lesson-ready.ts';
const lesson10=raw10 as unknown as Lesson & LessonFixture,lesson11=raw11 as unknown as Lesson & LessonFixture;
test.beforeEach(async({page})=>page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const width of [320,390,768,1440])for(const lesson of [lesson10,lesson11])test(`HSK3 lesson ${lesson.number} source-specific textbook views at ${width}`,async({page})=>{
 const errors:string[]=[],seen=new Set<string>();page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});
 for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
  await openLesson(page,lesson,section,scene);if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');
  for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(seen.has(id)).toBe(false);seen.add(id);await activityReady(page,lesson.activities.find(a=>a.id===id)!)}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true)}
  if(section==='overview'){await expect((await activityReady(page,sourceActivity(lesson,'objectives'))).locator('input[type=checkbox]')).toHaveCount(lesson.number===10?4:3);const g=await activityReady(page,sourceActivity(lesson,'warmup1-matching'));await expect(g.locator('select')).toHaveCount(6);await expect(g.locator('img')).toHaveCount(6)}
  if(section==='text'){await expect(page.locator('main img')).toHaveCount(1);const reading=await activityReady(page,sourceActivity(lesson,`text${scene}-reading`));await expect(reading.locator('textarea')).toHaveCount(lesson.number===10&&scene===4?2:3);await expect(reading.locator('input[type=checkbox]')).toHaveCount(lesson.number===10&&scene===4?1:0);await expect((await activityReady(page,sourceActivity(lesson,`text${scene}-listening`)))).toContainText('先听2遍')}
  if(section==='practice'){for(const[i,count]of(lesson.number===10?[3,3,3]:[3,4,4]).entries()){const g=await activityReady(page,sourceActivity(lesson,`picture-dialogue${i+1}`));await expect(g.locator('input')).toHaveCount(count);await expect(g.locator('img')).toHaveCount(1)}await expect((await activityReady(page,sourceActivity(lesson,'classroom-group'))).locator('textarea')).toHaveCount(8)}
  if(section==='culture'){await expect(page.locator('main img')).toHaveCount(lesson.number===10?1:0);await expect(page.locator('main audio,main video')).toHaveCount(0);await expect(page.locator('[data-activity-id*=review-]')).toHaveCount(0);if(lesson.number===10)await expect(page.locator('main')).toContainText('10-1')}
  if([390,1440].includes(width)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk3-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
 }
 expect([...seen].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect(errors).toEqual([]);
});
for(const lesson of [lesson10,lesson11])test(`HSK3 lesson${lesson.number} official matching and two word banks retain independent source keys`,async({page})=>{
 for(const[section,suffix,keys]of[['overview','warmup1-matching',lesson.number===10?'BEDAFC':'ACEDBF'],['practice','comprehensive-words1',lesson.number===10?'ACEDB':'CADBE'],['practice','comprehensive-words2',lesson.number===10?'DCBEA':'DBAEC']]){await openLesson(page,lesson,section);const a=sourceActivity(lesson,suffix),g=await activityReady(page,a),fields=singleAnswerFields(a);expect(fields.map(f=>f.answer.charAt(0)).join('')).toBe(keys);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitIncomplete(page,a);for(const f of fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct')).toHaveCount(fields.length)}
 await page.reload();await expectLessonReady(page,lesson,'practice');await expect(page.locator('[data-activity-id*=comprehensive-words] .feedback-correct')).toHaveCount(10);
});
test('HSK3 lesson10 education comparison preserves optional reading marker and distinct reference versus personal responses',async({page})=>{
 await page.setViewportSize({width:320,height:900});await openLesson(page,lesson10,'text',4);const a=sourceActivity(lesson10,'text4-reading'),g=await activityReady(page,a);await expect(g.locator('input[type=checkbox]')).not.toBeChecked();await expect(g.locator('textarea')).toHaveCount(2);await expect(g.locator('.activity-feedback')).toBeEmpty();await g.locator('textarea').nth(0).fill('按课文转述升学阶段');await submitIncomplete(page,a);await g.locator('textarea').nth(1).fill('以虚构国家为例比较学制');await submitSaved(page,lesson10,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await expect(g.locator('.activity-feedback')).toContainText('不是唯一答案');await expect(g.locator('.activity-feedback')).toContainText('这是开放任务');await expect(g.locator('input[type=checkbox]')).not.toBeChecked();await page.reload();await expectLessonReady(page,lesson10,'text',4);await activityReady(page,a);await expect(g.locator('textarea').nth(0)).toHaveValue('按课文转述升学阶段');await expect(g.locator('textarea').nth(1)).toHaveValue('以虚构国家为例比较学制');await expect(g.locator('input[type=checkbox]')).not.toBeChecked();await g.locator('input[type=checkbox]').check();await expect(g.locator('.activity-feedback')).toBeEmpty();
});
for(const lesson of [lesson10,lesson11])test(`HSK3 lesson${lesson.number} four-person source activity retains eight open notes without correctness grading`,async({page})=>{
 await openLesson(page,lesson,'practice');const a=sourceActivity(lesson,'classroom-group'),g=await activityReady(page,a);await expect(g.locator('textarea')).toHaveCount(8);await g.locator('textarea').first().fill('虚构小组第1项');await submitIncomplete(page,a);for(let i=1;i<8;i++)await g.locator('textarea').nth(i).fill(`虚构小组第${i+1}项`);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await expect(g).toContainText('这是开放任务');await page.reload();await expectLessonReady(page,lesson,'practice');await activityReady(page,a);for(let i=0;i<8;i++)await expect(g.locator('textarea').nth(i)).toHaveValue(`虚构小组第${i+1}项`);
});
test('HSK3 lesson11 repaired Vietnamese grammar and email references are delayed non-unique feedback',async({page})=>{
 await openLesson(page,lesson11,'grammar');for(const suffix of ['grammar3-practice1','grammar3-practice3']){const a=sourceActivity(lesson11,suffix),g=await activityReady(page,a),data=lesson11.activities.find(x=>x.id===a.id)!;await expect(g).toContainText(data.title.vi);await expect(g).not.toContainText('phải đem');await expect(g).not.toContainText('Tôi làm ______');await expect(g.locator('.activity-feedback')).toBeEmpty();await g.locator('input').fill('用自己的表达');await submitSaved(page,lesson11,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await expect(g.locator('.activity-feedback')).toContainText(data.fields[0].referenceAnswer!.vi)}
 await openLesson(page,lesson11,'practice');const a=sourceActivity(lesson11,'picture-dialogue3'),g=await activityReady(page,a);await expect(g).not.toContainText('tôi đem mấy lá');for(let i=0;i<4;i++)await g.locator('input').nth(i).fill(`自拟回答${i}`);await submitSaved(page,lesson11,a);await expect(g.locator('.activity-feedback')).toContainText('gửi xong mấy email này rồi sẽ đến ngay');await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);
});
test('HSK3 lesson10 repaired picture dialogues preserve natural Vietnamese blank order and all nine fields',async({page})=>{
 await openLesson(page,lesson10,'practice');for(let i=1;i<=3;i++){const a=sourceActivity(lesson10,`picture-dialogue${i}`),g=await activityReady(page,a),data=lesson10.activities.find(x=>x.id===a.id)!;await expect(g.locator('input')).toHaveCount(3);await expect(g).not.toContainText('tôi đem ______');await expect(g.locator('.activity-feedback')).toBeEmpty();for(let j=0;j<3;j++)await g.locator('input').nth(j).fill(`自己的回答${i}-${j}`);await submitSaved(page,lesson10,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);for(const f of data.fields)await expect(g.locator('.activity-feedback')).toContainText(f.referenceAnswer!.vi)}await page.reload();await expectLessonReady(page,lesson10,'practice');for(let i=1;i<=3;i++){const g=await activityReady(page,sourceActivity(lesson10,`picture-dialogue${i}`));for(let j=0;j<3;j++)await expect(g.locator('input').nth(j)).toHaveValue(`自己的回答${i}-${j}`)}
});
test('HSK3 lesson10 and11 grouped source grammar retains each original example exactly once',async({page})=>{
 for(const lesson of [lesson10,lesson11]){await openLesson(page,lesson,'grammar');const presentation=lesson.grammarPresentations![0],grammar=lesson.grammar.find(g=>g.id===presentation.grammarId)!,index=lesson.grammar.indexOf(grammar),section=page.locator('.lesson-section.grammar').nth(index);await expect(section.locator('.grammar-explanation-group')).toHaveCount(lesson.number===10?3:2);await expect(section.locator('.example')).toHaveCount(grammar.examples.length);for(const[i,group]of presentation.groups.entries()){const panel=section.locator('.grammar-explanation-group').nth(i);await expect(panel).toContainText(group.explanation.zh);await expect(panel).toContainText(group.explanation.vi);for(const[j,k]of group.exampleIndices.entries())await expect(panel.locator('.example .chinese-line').nth(j)).toHaveText(grammar.examples[k].zh)}}
});
