import {test,expect} from '@playwright/test';
import raw13 from '../../content/hsk3/lesson-13.json' with {type:'json'};
import raw12 from '../../content/hsk3/lesson-12.json' with {type:'json'};
import type {Lesson} from '../../src/types.ts';
import {activityReady,expectLessonReady,openLesson,sourceActivity,singleAnswerFields,submitIncomplete,submitSaved,type LessonFixture} from './lesson-ready.ts';
const lesson12=raw12 as unknown as Lesson & LessonFixture,lesson13=raw13 as unknown as Lesson & LessonFixture;
test.beforeEach(async({page})=>page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const optionalValue of ['', '虚构续问：公园什么时候开放？'])test(`HSK3 lesson12 explicit optional continuation ${optionalValue?'filled':'empty'} survives submission reload export and restore`,async({page})=>{
 await page.setViewportSize({width:390,height:900});await openLesson(page,lesson12,'practice');const a=sourceActivity(lesson12,'classroom-discussion'),g=await activityReady(page,a),inputs=g.locator('textarea');await expect(inputs).toHaveCount(7);const marker=g.locator('.optional-field-note');await expect(marker).toHaveCount(1);expect(await marker.evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThanOrEqual(14);await expect(marker).toContainText('可选，可留空');await expect(marker).toContainText('Tùy chọn, có thể để trống');await expect(marker.locator('..')).toHaveAttribute('for',a.fields[6].id);
 for(let i=0;i<5;i++)await inputs.nth(i).fill(`虚构城市的回答${i+1}`);if(optionalValue)await inputs.nth(6).fill(optionalValue);await submitIncomplete(page,a);await inputs.nth(5).fill('虚构城市的回答6');await submitSaved(page,lesson12,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await expect(inputs.nth(6)).toHaveValue(optionalValue);await page.reload();await expectLessonReady(page,lesson12,'practice');await activityReady(page,a);await expect(inputs.nth(6)).toHaveValue(optionalValue);
 const saved=await page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id],a.id);expect(saved.checkedAt).toBeGreaterThan(0);
 await page.getByRole('button',{name:'统一备份与恢复'}).click();const dialog=page.getByRole('dialog',{name:'学习记录备份'});const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载全部三级备份'}).click()]);const file=await download.path();if(!file)throw Error('No backup download');const {readFileSync}=await import('node:fs'),bytes=readFileSync(file),backup=JSON.parse(bytes.toString());expect(backup.courses.find((x:{level:number})=>x.level===3).backup.data.activities[a.id]).toEqual(saved);await dialog.getByRole('button',{name:'关闭',exact:false}).click();
 await inputs.nth(6).fill('备份后修改的虚构内容');await expect(g.locator('.activity-feedback')).toBeEmpty();await expect.poll(()=>page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id].checkedAt,a.id)).toBeNull();await page.getByRole('button',{name:'统一备份与恢复'}).click();await dialog.locator('#unified-backup-file').setInputFiles({name:'optional-continuation.json',mimeType:'application/json',buffer:bytes});await expect(dialog.locator('.backup-preview')).toHaveCount(3);await dialog.getByRole('button',{name:'确认恢复HSK 3'}).click();await expect(dialog).toContainText('HSK 3已恢复');await dialog.getByRole('button',{name:'关闭',exact:false}).click();await openLesson(page,lesson12,'practice');await activityReady(page,a);await expect(inputs.nth(6)).toHaveValue(optionalValue);for(let i=0;i<6;i++)await expect(inputs.nth(i)).toHaveValue(`虚构城市的回答${i+1}`);expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id],a.id)).toEqual(saved);await page.reload();await expectLessonReady(page,lesson12,'practice');await expect(inputs.nth(6)).toHaveValue(optionalValue);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')!).data.activities[id],a.id)).toEqual(saved);
});
for(const width of [320,390,768,1440])for(const lesson of [lesson12,lesson13])test(`HSK3 lesson ${lesson.number} source-specific textbook views at ${width}`,async({page})=>{
 const errors:string[]=[],seen=new Set<string>(),figures=new Set<string>();page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});
 for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
  await openLesson(page,lesson,section,scene);if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(seen.has(id)).toBe(false);seen.add(id);await activityReady(page,lesson.activities.find(a=>a.id===id)!)}for(const id of await page.locator('main figure[data-illustration-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.illustrationId!))){expect(figures.has(id)).toBe(false);figures.add(id)}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true)}
  if(section==='overview'){await expect((await activityReady(page,sourceActivity(lesson,'objectives'))).locator('input[type=checkbox]')).toHaveCount(lesson.number===12?4:3);await expect((await activityReady(page,sourceActivity(lesson,'warmup1-matching'))).locator('img')).toHaveCount(6)}
  if(section==='text'){await expect((await activityReady(page,sourceActivity(lesson,`text${scene}-reading`))).locator('textarea')).toHaveCount(3);await expect((await activityReady(page,sourceActivity(lesson,`text${scene}-listening`)))).toContainText('先听2遍');await expect(page.locator('main img')).toHaveCount(scene===4?0:1)}
  if(section==='practice'){for(const[i,count]of(lesson.number===12?[5,3,3]:[3,3,4]).entries()){const g=await activityReady(page,sourceActivity(lesson,`picture${i+1}`));await expect(g.locator('input')).toHaveCount(count);await expect(g.locator('img')).toHaveCount(1)}await expect((await activityReady(page,sourceActivity(lesson,'classroom-discussion'))).locator('textarea')).toHaveCount(lesson.number===12?7:4)}
  if(section==='culture'){await expect(page.locator('main audio,main video')).toHaveCount(0);if(lesson.number===12){const review=await activityReady(page,sourceActivity(lesson,'review-grammar'));await expect(review.locator('input[type=checkbox]')).toHaveCount(22);await expect(review.locator('tbody tr')).toHaveCount(11)}else{await expect(page.locator('[data-activity-id*=review-]')).toHaveCount(0);await expect(page.locator('main img')).toHaveCount(0)}}
  if([390,1440].includes(width)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk3-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
 }
 expect([...seen].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect([...figures].sort()).toEqual(lesson.illustrationManifest.map(f=>f.id).sort());expect(errors).toEqual([]);
});
for(const lesson of [lesson12,lesson13])test(`HSK3 lesson${lesson.number} official matching and cross-page word banks retain independent keys`,async({page})=>{
 for(const[section,suffix,keys]of[['overview','warmup1-matching',lesson.number===12?'BCEFAD':'BECFAD'],['practice','words-bank1',lesson.number===12?'AECDB':'EACDB'],['practice','words-bank2',lesson.number===12?'DABCE':'BDCEA']]){await openLesson(page,lesson,section);const a=sourceActivity(lesson,suffix),g=await activityReady(page,a),fields=singleAnswerFields(a);expect(fields.map(f=>f.answer.charAt(0)).join('')).toBe(keys);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitIncomplete(page,a);for(const f of fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct')).toHaveCount(fields.length)}await page.reload();await expectLessonReady(page,lesson,'practice');await expect(page.locator('[data-activity-id*=words-bank] .feedback-correct')).toHaveCount(10);
});
for(const lesson of [lesson12,lesson13])test(`HSK3 lesson${lesson.number} reading references are delayed non-unique feedback in all four texts`,async({page})=>{
 for(const scene of [1,2,3,4]){await openLesson(page,lesson,'text',scene);const a=sourceActivity(lesson,`text${scene}-reading`),g=await activityReady(page,a),data=lesson.activities.find(x=>x.id===a.id)!;await expect(g.locator('.activity-feedback')).toBeEmpty();for(let i=0;i<3;i++)await g.locator('textarea').nth(i).fill(`自拟课文${scene}回答${i+1}`);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);for(const f of data.fields)await expect(g.locator('.activity-feedback')).toContainText(f.referenceAnswer!.vi);await page.reload();await expectLessonReady(page,lesson,'text',scene);await activityReady(page,a);for(let i=0;i<3;i++)await expect(g.locator('textarea').nth(i)).toHaveValue(`自拟课文${scene}回答${i+1}`)}
});
test('HSK3 lesson13 nine grammar frames retain eleven independent answers and multi-blank completion guards',async({page})=>{
 await openLesson(page,lesson13,'grammar');const activities=lesson13.activities.filter(a=>/:grammar\d+-practice\d+$/.test(a.id));expect(activities).toHaveLength(9);expect(activities.flatMap(a=>a.fields)).toHaveLength(11);for(const a of activities){const g=await activityReady(page,a);await expect(g.locator('.activity-feedback')).toBeEmpty();if(a.fields.length===2){await g.locator('input').first().fill('第一分句');await submitIncomplete(page,a)}for(const[i,f]of a.fields.entries())await page.locator(`[id="${f.id}"]`).fill(`自拟表达${a.id}-${i}`);await submitSaved(page,lesson13,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0)}await page.reload();await expectLessonReady(page,lesson13,'grammar');for(const a of activities)for(const[i,f]of a.fields.entries())await expect(page.locator(`[id="${f.id}"]`)).toHaveValue(`自拟表达${a.id}-${i}`);
});
test('HSK3 lesson12 cross-page review retains twenty-two distinct optional checks and two source groups for 就',async({page})=>{
 await page.setViewportSize({width:320,height:900});await openLesson(page,lesson12,'culture');const a=sourceActivity(lesson12,'review-grammar'),g=await activityReady(page,a),checks=g.locator('input[type=checkbox]');await expect(checks).toHaveCount(22);for(let i=0;i<22;i++)await checks.nth(i).setChecked(i%3===0);await submitSaved(page,lesson12,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expectLessonReady(page,lesson12,'culture');await activityReady(page,a);for(let i=0;i<22;i++)expect(await checks.nth(i).isChecked()).toBe(i%3===0);await g.screenshot({path:'test-results/unified-hsk3-lesson12-review-320.png'});
 await openLesson(page,lesson12,'grammar');const presentation=lesson12.grammarPresentations![0],grammar=lesson12.grammar.find(x=>x.id===presentation.grammarId)!,section=page.locator('.lesson-section.grammar').nth(lesson12.grammar.indexOf(grammar));await expect(section.locator('.grammar-explanation-group')).toHaveCount(2);await expect(section.locator('.example')).toHaveCount(4);for(const[i,group]of presentation.groups.entries()){const panel=section.locator('.grammar-explanation-group').nth(i);await expect(panel).toContainText(group.explanation.vi);for(const[j,k]of group.exampleIndices.entries())await expect(panel.locator('.example .chinese-line').nth(j)).toHaveText(grammar.examples[k].zh)}
});
