import {test,expect} from '@playwright/test';
import raw14 from '../../content/hsk3/lesson-14.json' with {type:'json'};import raw15 from '../../content/hsk3/lesson-15.json' with {type:'json'};
import type {Lesson} from '../../src/types.ts';import {activityReady,expectLessonReady,openLesson,singleAnswerFields,sourceActivity,submitIncomplete,submitSaved,type LessonFixture} from './lesson-ready.ts';
const lesson14=raw14 as unknown as Lesson & LessonFixture,lesson15=raw15 as unknown as Lesson & LessonFixture;
test.beforeEach(async({page})=>page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const width of [320,390,768,1440])for(const lesson of [lesson14,lesson15])test(`HSK3 lesson ${lesson.number} source-specific views render every distinct manifest identity once at ${width}`,async({page})=>{
 const errors:string[]=[],seen=new Set<string>(),figures=new Set<string>();page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});
 for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
  await openLesson(page,lesson,section,scene);if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(seen.has(id)).toBe(false);seen.add(id);await activityReady(page,lesson.activities.find(a=>a.id===id)!)}for(const id of await page.locator('main figure[data-illustration-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.illustrationId!))){expect(figures.has(id),id+' displayed more than once').toBe(false);figures.add(id)}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true)}
  if(section==='overview'){await expect((await activityReady(page,sourceActivity(lesson,'objectives'))).locator('input[type=checkbox]')).toHaveCount(lesson.number===14?3:4);await expect((await activityReady(page,sourceActivity(lesson,'warmup1-matching'))).locator('img')).toHaveCount(6)}
  if(section==='text'){await expect((await activityReady(page,sourceActivity(lesson,`text${scene}-reading`))).locator('textarea')).toHaveCount(3);await expect(page.locator('main img')).toHaveCount(1)}
  if(section==='practice'){for(const[i,count]of(lesson.number===14?[3,3,3]:[3,3,2]).entries()){const g=await activityReady(page,sourceActivity(lesson,`picture${i+1}`));await expect(g.locator('input')).toHaveCount(count);await expect(g.locator('img')).toHaveCount(1)}if(lesson.number===15){const g=await activityReady(page,sourceActivity(lesson,'classroom-cities'));await expect(g.locator('img')).toHaveCount(4);await expect(g.locator('textarea')).toHaveCount(1)}else await expect((await activityReady(page,sourceActivity(lesson,'classroom-unlucky-day'))).locator('textarea')).toHaveCount(4)}
  if(section==='culture'){await expect(page.locator('main audio,main video')).toHaveCount(0);if(lesson.number===15){await expect((await activityReady(page,sourceActivity(lesson,'review-grammar'))).locator('input[type=checkbox]')).toHaveCount(20);await expect(page.locator('main img')).toHaveCount(1)}else await expect(page.locator('[data-activity-id],main img')).toHaveCount(0)}
  if([390,1440].includes(width)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk3-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
 }
 expect([...seen].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect([...figures].sort()).toEqual(lesson.illustrationManifest.map(f=>f.id).sort());expect(errors).toEqual([]);
});
for(const lesson of [lesson14,lesson15])test(`HSK3 lesson${lesson.number} reviewed matching and word-bank keys remain official`,async({page})=>{
 for(const[section,suffix,keys]of[['overview','warmup1-matching',lesson.number===14?'FACDBE':'FEBADC'],['practice','words-bank1',lesson.number===14?'CABDE':'BDCEA'],['practice','words-bank2',lesson.number===14?'CEDBA':'EBCDA']]){await openLesson(page,lesson,section);const a=sourceActivity(lesson,suffix),g=await activityReady(page,a),fields=singleAnswerFields(a);expect(fields.map(f=>f.answer.charAt(0)).join('')).toBe(keys);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitIncomplete(page,a);for(const f of fields)await page.locator(`[id="${f.id}"]`).selectOption(f.answer);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct')).toHaveCount(fields.length)}await page.reload();await expectLessonReady(page,lesson,'practice');await expect(page.locator('[data-activity-id*=words-bank] .feedback-correct')).toHaveCount(10);
});
test('HSK3 lesson15 overlapping Nanjing answers A and B are both non-unique saved selections',async({page})=>{
 await openLesson(page,lesson15,'text',2);const a=sourceActivity(lesson15,'text2-listening'),data=lesson15.activities.find(x=>x.id===a.id)!,g=await activityReady(page,a);expect(data.fields.map(f=>f.assessment)).toEqual(['official','reference']);await expect(g.locator('.activity-feedback')).toBeEmpty();await g.locator('select').first().selectOption(data.fields[0].answer as string);await submitIncomplete(page,a);
 for(const choice of [1,0]){await g.locator('select').nth(1).selectOption(data.fields[1].options![choice].zh);await expect(g.locator('.activity-feedback')).toBeEmpty();await submitSaved(page,lesson15,a);await expect(g.locator('.feedback-correct')).toHaveCount(1);await expect(g.locator('.feedback-retry')).toHaveCount(0);await expect(g.locator('.activity-feedback')).toContainText('不作唯一答案判分');await expect(g.locator('.activity-feedback')).toContainText(data.fields[1].referenceAnswer!.vi);await page.reload();await expectLessonReady(page,lesson15,'text',2);await activityReady(page,a);await expect(g.locator('select').nth(1)).toHaveValue(data.fields[1].options![choice].zh);await expect(g.locator('.feedback-correct')).toHaveCount(1)}
});
for(const width of [320,390])test(`HSK3 lesson15 four named cities stay in their own activity before its response at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await openLesson(page,lesson15,'practice');const a=sourceActivity(lesson15,'classroom-cities'),g=await activityReady(page,a),ids=lesson15.activities.find(x=>x.id===a.id)!.illustrationIds!;expect(ids).toHaveLength(4);await expect(g.locator('figure')).toHaveCount(4);for(const image of await g.locator('img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((i:HTMLImageElement)=>i.complete&&i.naturalWidth>0)).toBe(true)}expect(await g.locator('figure').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.illustrationId))).toEqual(ids);for(const id of ids)await expect(page.locator(`[data-illustration-id="${id}"]`)).toHaveCount(1);expect(await g.evaluate(el=>{const figures=[...el.querySelectorAll('figure')],input=el.querySelector('textarea')!;return figures.every(f=>Boolean(f.compareDocumentPosition(input)&Node.DOCUMENT_POSITION_FOLLOWING)&&f.getBoundingClientRect().bottom<=input.getBoundingClientRect().top)})).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await g.screenshot({path:`test-results/unified-hsk3-lesson15-four-cities-${width}.png`});await g.locator('textarea').fill('虚构旅行计划：我最喜欢南京，因为想了解它的历史。');await submitSaved(page,lesson15,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expectLessonReady(page,lesson15,'practice');await activityReady(page,a);await expect(g.locator('textarea')).toHaveValue('虚构旅行计划：我最喜欢南京，因为想了解它的历史。');
});
test('HSK3 lesson14 borrowing translation and four source blank rows keep their intended roles',async({page})=>{
 await openLesson(page,lesson14,'text',2);const listen=await activityReady(page,sourceActivity(lesson14,'text2-listening'));await expect(listen.locator('select').nth(1)).toContainText('Mượn sách của Lý Văn');await expect(listen.locator('select').nth(1)).not.toContainText('Nhờ Lý Văn mượn sách');await openLesson(page,lesson14,'practice');const a=sourceActivity(lesson14,'classroom-unlucky-day'),g=await activityReady(page,a);await expect(g.locator('textarea')).toHaveCount(4);await expect(g).toContainText('买的水果被我忘在超市了');await expect(g).toContainText('图书馆借的书被我丢了');for(let i=0;i<4;i++)await g.locator('textarea').nth(i).fill(`虚构事件${i+3}`);await submitSaved(page,lesson14,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expectLessonReady(page,lesson14,'practice');await activityReady(page,a);for(let i=0;i<4;i++)await expect(g.locator('textarea').nth(i)).toHaveValue(`虚构事件${i+3}`);
});
test('HSK3 lesson15 review has ten independent understand-use pairs and cross-page grammar remains one explanation',async({page})=>{
 await page.setViewportSize({width:320,height:900});await openLesson(page,lesson15,'culture');const a=sourceActivity(lesson15,'review-grammar'),g=await activityReady(page,a),checks=g.locator('input[type=checkbox]');await expect(g.locator('tbody tr')).toHaveCount(10);await expect(checks).toHaveCount(20);for(let i=0;i<20;i++)await checks.nth(i).setChecked(i%4===1);await submitSaved(page,lesson15,a);await page.reload();await expectLessonReady(page,lesson15,'culture');await activityReady(page,a);for(let i=0;i<20;i++)expect(await checks.nth(i).isChecked()).toBe(i%4===1);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await openLesson(page,lesson15,'grammar');const grammar=page.locator('.lesson-section.grammar').nth(1);await expect(grammar.locator('.grammar-explanation-group')).toHaveCount(0);await expect(grammar).toContainText(lesson15.grammarSourceExplanations![1].explanation.vi);
});
for(const lesson of [lesson14,lesson15])test(`HSK3 lesson${lesson.number} every grammar and picture reference field saves independently without unique grading`,async({page})=>{
 for(const section of ['grammar','practice']){await openLesson(page,lesson,section);const activities=lesson.activities.filter(a=>section==='grammar'?/:grammar\d+-practice\d+$/.test(a.id):/:picture\d+$/.test(a.id));for(const a of activities){const g=await activityReady(page,a);await expect(g.locator('.activity-feedback')).toBeEmpty();for(const[i,f]of a.fields.entries())await page.locator(`[id="${f.id}"]`).fill(`自拟回答${i+1}`);await submitSaved(page,lesson,a);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);for(const f of a.fields)await expect(g.locator('.activity-feedback')).toContainText(f.referenceAnswer!.vi)}await page.reload();await expectLessonReady(page,lesson,section);for(const a of activities)for(const[i,f]of a.fields.entries())await expect(page.locator(`[id="${f.id}"]`)).toHaveValue(`自拟回答${i+1}`)}
});
