import {test,expect} from '@playwright/test';
import lesson2 from '../../content/hsk2/lesson-02.json' with {type:'json'};
import lesson3 from '../../content/hsk2/lesson-03.json' with {type:'json'};
import lesson4 from '../../content/hsk2/lesson-04.json' with {type:'json'};
import lesson5 from '../../content/hsk2/lesson-05.json' with {type:'json'};
import lesson6 from '../../content/hsk2/lesson-06.json' with {type:'json'};
import lesson7 from '../../content/hsk2/lesson-07.json' with {type:'json'};
import lesson8 from '../../content/hsk2/lesson-08.json' with {type:'json'};
import lesson9 from '../../content/hsk2/lesson-09.json' with {type:'json'};
import lesson10 from '../../content/hsk2/lesson-10.json' with {type:'json'};
import lesson11 from '../../content/hsk2/lesson-11.json' with {type:'json'};
import lesson12 from '../../content/hsk2/lesson-12.json' with {type:'json'};
import lesson13 from '../../content/hsk2/lesson-13.json' with {type:'json'};
import lesson14 from '../../content/hsk2/lesson-14.json' with {type:'json'};
import lesson15 from '../../content/hsk2/lesson-15.json' with {type:'json'};
test.beforeEach(async({page})=>page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const width of [320,390,768,1440])for(const lesson of [lesson2,lesson3,lesson4,lesson5,lesson6,lesson7,lesson8,lesson9,lesson10,lesson11,lesson12,lesson13,lesson14,lesson15])test(`HSK2 lesson ${lesson.number} reviewed textbook sections at ${width}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.setViewportSize({width,height:900});const ids=new Set<string>();
 for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
  await page.goto(`/#view=lesson&level=2&lesson=${lesson.number}&section=${section}&scene=${scene}`);await expect(page.locator('main h1')).toContainText(lesson.title.zh);await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');
  for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(ids.has(id),`duplicate visible activity ${id}`).toBe(false);ids.add(id)}
  const overflow=await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('body *')].map(el=>({tag:el.tagName,className:el.className,left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right,position:getComputedStyle(el).position})).filter(el=>el.right>innerWidth+1).slice(0,30)}));expect(overflow.documentWidth,JSON.stringify({lesson:lesson.number,section,scene,...overflow})).toBeLessThanOrEqual(overflow.width+1);
  for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((node:HTMLImageElement)=>node.complete&&node.naturalWidth>0)).toBe(true)}
  if(section==='practice'){const hints=page.locator('.picture-editorial-hints');await expect(hints).toHaveCount(1);await expect(hints).not.toHaveAttribute('open','');await expect(hints.locator('p').first()).toBeHidden();const follows=await hints.evaluate(node=>{const cards=[...document.querySelectorAll('[data-activity-id*="picture-dialogue"]')];return cards.length===4&&cards.every(card=>!!(card.compareDocumentPosition(node)&Node.DOCUMENT_POSITION_FOLLOWING))});expect(follows).toBe(true)}
  if(section==='overview'&&lesson.number===4){const table=page.locator('.self-assessment-matrix');await expect(table.locator('tbody tr')).toHaveCount(3);await expect(table.locator('input[type=checkbox]')).toHaveCount(9);await expect(table.locator('thead th').first()).toContainText('动词');for(const word of ['包子','饺子','面条儿','绿茶','红茶','花茶','中国','法国','泰国'])await expect(table).toContainText(word)}
  if(section==='overview'&&lesson.number===2){const scroll=page.locator('.matrix-scroll');await expect(scroll).toHaveCSS('position','relative');const table=page.locator('.self-assessment-matrix');await expect(table.locator('thead th')).toHaveCount(4);await expect(table.locator('tbody select')).toHaveCount(3);await expect(table).toContainText('方式1');await expect(table).toContainText('方式2')}
  if(section==='practice'&&lesson.number===4){const group=page.locator('[data-activity-id$=comprehensive-words]');await expect(group.locator('.activity-field .source-note')).toHaveCount(5);await expect(group.locator('.activity-field .source-note').nth(2)).toContainText('36');await expect(group.locator(':scope > .source-note')).toContainText('35、36')}
  if(section==='practice'&&lesson.number===5)await expect(page.locator('[data-activity-id$=picture-dialogue1] .task-note')).not.toContainText('十点');
  if(section==='culture'&&lesson.number===3){const table=page.locator('[data-activity-id$=review-grammar] .self-assessment-matrix');await expect(table.locator('tbody tr')).toHaveCount(9);await expect(table.locator('tbody input[type=checkbox]')).toHaveCount(18);await expect(table.locator('thead th')).toHaveCount(3);expect(await table.evaluate(node=>node.getBoundingClientRect().right<=innerWidth+1)).toBe(true)}
  if([10,11].includes(lesson.number)&&section==='text'&&scene===4)await expect(page.locator('main img')).toHaveCount(0);
  if(lesson.number===10&&section==='culture'){const body=page.locator('.textbook-body');await expect(body.getByRole('heading',{name:'小语助力：“呢”'})).toBeVisible();await expect(body.getByText('这里“呢”表示提醒或深究的语气。',{exact:true})).toBeVisible();await expect(body.getByText('Ở đây 呢 thể hiện ngữ khí nhắc hỏi hoặc hỏi sâu thêm.',{exact:true})).toBeVisible();await expect(body.locator('.source-note').filter({hasText:'教材第85页'})).toBeVisible();expect(lesson.sections.find(s=>s.kind==='tip')!.source).toMatchObject({pdfPage:100,printedPage:85,provenance:'textbook'});await expect(body).not.toContainText('本课没有单独的拓展');await expect(body.locator('img,video')).toHaveCount(0)}
  if(lesson.number===13&&section==='text'&&[1,2,4].includes(scene))await expect(page.locator('main img')).toHaveCount(0);
  if(lesson.number===14&&section==='text'&&scene===4)await expect(page.locator('main img')).toHaveCount(0);
  if(lesson.number===15&&section==='text'&&[2,4].includes(scene))await expect(page.locator('main img')).toHaveCount(0);
  if(lesson.number===12&&section==='text'&&scene===4)await expect(page.locator('main img')).toHaveCount(1);
  if((width===390||width===1440)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk2-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
 }
 expect([...ids].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect(errors).toEqual([]);
});
test('review matrix keeps two columns independent across refresh and scoped backup restore',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/#view=lesson&level=2&lesson=3&section=culture');let checks=page.locator('[data-activity-id$=review-grammar] .self-assessment-matrix tbody input');await checks.nth(0).check();await checks.nth(3).check();await checks.nth(1).uncheck();await checks.nth(2).uncheck();await page.locator('[data-activity-id$=review-grammar]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();checks=page.locator('[data-activity-id$=review-grammar] .self-assessment-matrix tbody input');await expect(checks.nth(0)).toBeChecked();await expect(checks.nth(3)).toBeChecked();await expect(checks.nth(1)).not.toBeChecked();await expect(checks.nth(2)).not.toBeChecked();
 await page.getByRole('button',{name:'统一备份与恢复'}).click();const dialog=page.getByRole('dialog',{name:'学习记录备份'});const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载全部三级备份'}).click()]);const path=await download.path();if(!path)throw Error('Missing backup');const {readFileSync}=await import('node:fs');const bytes=readFileSync(path);await dialog.getByRole('button',{name:'关闭',exact:false}).click();await checks.nth(0).uncheck();await checks.nth(3).uncheck();await page.locator('[data-activity-id$=review-grammar]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.getByRole('button',{name:'统一备份与恢复'}).click();await dialog.locator('input[type=file]').setInputFiles({name:'matrix-backup.json',mimeType:'application/json',buffer:bytes});await dialog.getByRole('button',{name:'确认恢复HSK 2'}).click();await expect(dialog).toContainText('HSK 2已恢复');await dialog.getByRole('button',{name:'关闭',exact:false}).click();await expect(checks.nth(0)).toBeChecked();await expect(checks.nth(3)).toBeChecked();await expect(checks.nth(1)).not.toBeChecked();await expect(checks.nth(2)).not.toBeChecked();
});

test('source survey tables preserve independent travel text, single preferences and multiple experiences',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=1&section=overview');let table=page.locator('[data-activity-id$=travel-survey] table');await expect(table.locator('thead th')).toHaveCount(3);for(const [i,value]of ['上周六','和朋友','坐火车'].entries())await table.locator('input').nth(i).fill(value);await page.locator('[data-activity-id$=travel-survey]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('input').nth(0)).toHaveValue('上周六');await expect(table.locator('input').nth(1)).toHaveValue('和朋友');await expect(table.locator('input').nth(2)).toHaveValue('坐火车');
 await page.goto('/#view=lesson&level=2&lesson=2&section=overview');table=page.locator('[data-activity-id$=warmup-preferences] table');await table.locator('select').nth(0).selectOption('坐飞机去');await table.locator('select').nth(1).selectOption('回家做饭');await table.locator('select').nth(2).selectOption('去看电影');await page.locator('[data-activity-id$=warmup-preferences]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('select').nth(0)).toHaveValue('坐飞机去');await expect(table.locator('select').nth(1)).toHaveValue('回家做饭');await expect(table.locator('select').nth(2)).toHaveValue('去看电影');
 await page.goto('/#view=lesson&level=2&lesson=4&section=overview');table=page.locator('[data-activity-id$=warmup-experiences] table');await table.locator('input').nth(0).check();await table.locator('input').nth(1).check();await table.locator('input').nth(4).check();await page.locator('[data-activity-id$=warmup-experiences]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('input').nth(0)).toBeChecked();await expect(table.locator('input').nth(1)).toBeChecked();await expect(table.locator('input').nth(2)).not.toBeChecked();await expect(table.locator('input').nth(4)).toBeChecked();
});

test('lesson3 original two-row vocabulary reflection retains independent free text',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=3&section=culture');
 const activity=page.locator('[data-activity-id$=review-vocabulary]'),table=activity.locator('table');
 await expect(table.locator('thead th')).toHaveCount(2);await expect(table.locator('tbody tr')).toHaveCount(2);await expect(table.locator('textarea')).toHaveCount(2);await table.locator('textarea').nth(0).fill('生日、已经');await table.locator('textarea').nth(1).fill('准备');
 await activity.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('textarea').nth(0)).toHaveValue('生日、已经');await expect(table.locator('textarea').nth(1)).toHaveValue('准备');await expect(activity).not.toContainText('正确率');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

test('lesson6 reflection preserves two free-text categories and independent understand/use checkboxes',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=6&section=culture');const vocab=page.locator('[data-activity-id$=review-vocabulary]'),grammar=page.locator('[data-activity-id$=review-grammar]');
 await expect(vocab.locator('table tbody tr')).toHaveCount(2);await expect(grammar.locator('table tbody tr')).toHaveCount(9);await expect(grammar.locator('input[type=checkbox]')).toHaveCount(18);await expect(grammar.locator('.activity-field .source-note')).toHaveCount(0);await expect(grammar.locator(':scope > .source-note')).toContainText('55');
 await vocab.locator('textarea').nth(0).fill('画笔、舒服');await vocab.locator('textarea').nth(1).fill('快乐');await grammar.locator('input').nth(0).check();await grammar.locator('input').nth(3).check();await grammar.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(vocab.locator('textarea').nth(0)).toHaveValue('画笔、舒服');await expect(vocab.locator('textarea').nth(1)).toHaveValue('快乐');await expect(grammar.locator('input').nth(0)).toBeChecked();await expect(grammar.locator('input').nth(1)).not.toBeChecked();await expect(grammar.locator('input').nth(3)).toBeChecked();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('lesson7 source surveys keep three sequences and two complete group records on narrow screens',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=7&section=overview');const sequence=page.locator('[data-activity-id$=warmup2-sequences]');await expect(sequence.locator('table thead th')).toHaveCount(2);await expect(sequence.locator('table tbody tr')).toHaveCount(3);for(const [i,value]of ['去上课','去打篮球','做饭'].entries())await sequence.locator('input').nth(i).fill(value);await sequence.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(sequence.locator('input').nth(0)).toHaveValue('去上课');await expect(sequence.locator('input').nth(2)).toHaveValue('做饭');
 await page.goto('/#view=lesson&level=2&lesson=7&section=practice');const group=page.locator('[data-activity-id$=group-survey]'),scroll=group.locator('.matrix-scroll');await expect(group.locator('thead th')).toHaveCount(5);await expect(group.locator('tbody tr')).toHaveCount(2);const values=['安妮','游泳','练习游泳','还可以','李文','篮球','打篮球','很好'];for(const [i,v]of values.entries())await group.locator('input').nth(i).fill(v);await group.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();for(const [i,v]of values.entries())await expect(group.locator('input').nth(i)).toHaveValue(v);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(await scroll.evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);await scroll.focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>scroll.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);
});

test('lesson9 headerless source comparison keeps all eight personal responses and original units',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=9&section=overview');const activity=page.locator('[data-activity-id$=warmup2-personal]'),table=activity.locator('table');await expect(table.locator('tbody tr')).toHaveCount(4);await expect(table.locator('thead')).toHaveClass('matrix-hidden-head');await expect(table.locator('input')).toHaveCount(4);await expect(table.locator('select')).toHaveCount(4);
 for(const label of ['今天（℃）','昨天（℃）','咖啡（每杯）','奶茶（每杯）','包子（非常、很、不）好吃','饺子（非常、很、不）好吃','看电视（非常、很、没）有意思','看电影（非常、很、没）有意思'])await expect(activity.locator('.matrix-visible-label').filter({hasText:label})).toBeVisible();
 for(const [i,value]of ['30','27','25000 VND','30000 VND'].entries())await table.locator('input').nth(i).fill(value);for(const [i,value]of ['非常','不','没','很'].entries())await table.locator('select').nth(i).selectOption(value);await activity.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();for(const [i,value]of ['30','27','25000 VND','30000 VND'].entries())await expect(table.locator('input').nth(i)).toHaveValue(value);for(const [i,value]of ['非常','不','没','很'].entries())await expect(table.locator('select').nth(i)).toHaveValue(value);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(activity.locator('.activity-field .source-note')).toHaveCount(0);await expect(activity.locator(':scope > .source-note')).toContainText('73');
 const scroll=activity.locator('.matrix-scroll');await scroll.focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>scroll.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);
});
test('lesson9 two vocabulary reflections and both grammar-check dimensions survive reload',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=9&section=culture');const vocab=page.locator('[data-activity-id$=review-vocabulary]'),grammar=page.locator('[data-activity-id$=review-grammar]');await expect(vocab.locator('table tbody tr')).toHaveCount(2);await expect(grammar.locator('table tbody tr')).toHaveCount(9);await expect(grammar.locator('input[type=checkbox]')).toHaveCount(18);await vocab.locator('textarea').nth(0).fill('旁边、咖啡');await vocab.locator('textarea').nth(1).fill('那么');await grammar.locator('input').nth(0).check();await grammar.locator('input').nth(17).check();await grammar.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(vocab.locator('textarea').nth(0)).toHaveValue('旁边、咖啡');await expect(vocab.locator('textarea').nth(1)).toHaveValue('那么');await expect(grammar.locator('input').nth(0)).toBeChecked();await expect(grammar.locator('input').nth(1)).not.toBeChecked();await expect(grammar.locator('input').nth(17)).toBeChecked();await expect(grammar.locator('.activity-field .source-note')).toHaveCount(0);await expect(grammar.locator(':scope > .source-note')).toContainText('83');
});

test('lesson10 open responses and all seven source picture blanks persist without exact grading',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=10&section=overview');const open=page.locator('[data-activity-id$=warmup2-personal]');await expect(open.locator('textarea')).toHaveCount(3);for(const [i,value]of ['我想学中文。','我喜欢做菜。','我准备好了。'].entries())await open.locator('textarea').nth(i).fill(value);await open.getByRole('button',{name:'提交并查看反馈'}).click();await expect(open).toContainText('这是开放任务');await expect(open.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expect(open.locator('textarea').nth(2)).toHaveValue('我准备好了。');
 await page.goto('/#view=lesson&level=2&lesson=10&section=practice');const groups=page.locator('[data-activity-id*="picture-dialogue"]');await expect(groups).toHaveCount(4);const values=[['还是'],['水果','洗完'],['快要','了'],['就要','了']];for(const [i,row]of values.entries()){const g=groups.nth(i);await expect(g.locator('input')).toHaveCount(row.length);for(const[j,value]of row.entries())await g.locator('input').nth(j).fill(value);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g).toContainText('不是唯一答案');await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0)}await page.reload();for(const[i,row]of values.entries())for(const[j,value]of row.entries())await expect(groups.nth(i).locator('input').nth(j)).toHaveValue(value);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('lesson10 official answers retain split answer pages and clear stale feedback after edit',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=10&section=text&scene=3');const g=page.locator('[data-activity-id$=text3-listening]');await expect(g.locator('select')).toHaveCount(2);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await g.locator('select').nth(0).selectOption('比上次好');await g.locator('select').nth(1).selectOption('做菜');await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-correct')).toHaveCount(2);await expect(g).toContainText('PDF第13页');await expect(g).toContainText('PDF第14页');const wrong='很不好';await g.locator('select').nth(0).selectOption(wrong);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-retry')).toHaveCount(1);await expect(g.locator('.feedback-correct')).toHaveCount(1);await page.reload();await expect(g.locator('.feedback-retry')).toHaveCount(1);
});
test('lesson11 second picture warmup preserves four open descriptions and separate culture resource status',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/#view=lesson&level=2&lesson=11&section=overview');const g=page.locator('[data-activity-id$=warmup2-pictures]');await expect(g.locator('input')).toHaveCount(4);await expect(g.locator('img')).toHaveCount(4);for(const[i,value]of ['下雪','听音乐','开门','拿水瓶'].entries())await g.locator('input').nth(i).fill(value);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g).toContainText('不是唯一答案');await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expect(g.locator('input').nth(3)).toHaveValue('拿水瓶');await page.goto('/#view=lesson&level=2&lesson=11&section=culture');await expect(page.locator('main')).toContainText('没有这个视频');await expect(page.locator('main')).toContainText('11-1');await expect(page.locator('main video, main audio')).toHaveCount(0);await expect(page.locator('main img')).toHaveCount(1);
});

test('lesson12 four-person survey keeps three names in headers and twelve independent responses',async({page})=>{
 test.setTimeout(60000);
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=12&section=overview');const g=page.locator('[data-activity-id$=warmup2-survey]'),table=g.locator('table'),head=table.locator('thead'),body=table.locator('tbody');await expect(head.locator('th')).toHaveCount(5);await expect(head.locator('input')).toHaveCount(3);await expect(body.locator('tr')).toHaveCount(3);await expect(body.locator('input')).toHaveCount(12);await expect(table).toHaveAttribute('data-header-inputs','true');await head.locator('input').first().focus();await page.keyboard.press('Tab');await expect(head.locator('input').nth(1)).toBeFocused();await page.keyboard.press('Tab');await expect(head.locator('input').nth(2)).toBeFocused();const names=['A同学','B同学','C同学'];for(const[i,v]of names.entries())await head.locator('input').nth(i).fill(v);const values=['六点','七点','八点','九点','十点','十一点','十二点','十点半','快','不快','很快','慢'];for(const[i,v]of values.entries())await body.locator('input').nth(i).fill(v);await g.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();for(const[i,v]of values.entries())await expect(body.locator('input').nth(i)).toHaveValue(v);for(const[i,v]of names.entries())await expect(head.locator('input').nth(i)).toHaveValue(v);await head.locator('input').nth(1).fill('B昵称');await expect(g.locator('.activity-feedback')).toBeEmpty();await g.getByRole('button',{name:'保存本次记录'}).click();await expect(g.locator('.activity-feedback')).toContainText('这是开放任务');await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ran_hsk2_fltrp_2026_v1')!).data.activities['hsk2-fltrp-2026:l12:activity:warmup2-survey'].values['hsk2-fltrp-2026:l12:field:warmup2-nameB'])).toBe('B昵称');await page.reload();await expect(head.locator('input').nth(1)).toHaveValue('B昵称');for(const[i,v]of values.entries())await expect(body.locator('input').nth(i)).toHaveValue(v);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const scroll=g.locator('.matrix-scroll');await scroll.focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>scroll.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await verifyRapidLessonSaveLifecycle(page);for(const[i,v]of values.entries())await expect(body.locator('input').nth(i)).toHaveValue(v);await expect(head.locator('input').nth(0)).toHaveValue('A同学');await expect(head.locator('input').nth(2)).toHaveValue('C同学');
});
test('lesson12 official word keys span answer pages while review dimensions stay independent',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=12&section=practice');const words=page.locator('[data-activity-id$=comprehensive-words]');for(const[i,value]of ['好','外面','事情','从小','正'].entries())await words.locator('select').nth(i).selectOption(value);await words.getByRole('button',{name:'提交并查看反馈'}).click();await expect(words.locator('.feedback-correct')).toHaveCount(5);await expect(words).toContainText('PDF第16页');await expect(words).toContainText('PDF第17页');await page.goto('/#view=lesson&level=2&lesson=12&section=culture');const grammar=page.locator('[data-activity-id$=review-grammar]'),vocab=page.locator('[data-activity-id$=review-vocabulary]');await expect(grammar.locator('tbody tr')).toHaveCount(9);await expect(grammar.locator('input')).toHaveCount(18);await vocab.locator('textarea').nth(0).fill('晴、楼');await vocab.locator('textarea').nth(1).fill('从小');await grammar.locator('input').nth(1).check();await grammar.locator('input').nth(16).check();await grammar.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await expect(grammar.locator('.activity-feedback')).toContainText('已记录你的自评');await page.reload();await expect(grammar.locator('input').nth(0)).not.toBeChecked();await expect(grammar.locator('input').nth(1)).toBeChecked();await expect(grammar.locator('input').nth(16)).toBeChecked();await expect(grammar.locator('input').nth(17)).not.toBeChecked();await expect(vocab.locator('textarea').nth(0)).toHaveValue('晴、楼');
});
test('lesson13 coffee guess and five comparison blanks remain nonunique and persist separately',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=13&section=culture');const tip=page.locator('[data-activity-id$=tip-coffee-cup]');await expect(tip).toHaveCount(1);await expect(tip.locator('.activity-feedback')).toBeEmpty();await tip.locator('textarea').fill('喝咖啡用的杯子');await tip.getByRole('button',{name:'提交并查看反馈'}).click();await expect(tip).toContainText('不是唯一答案');await expect(tip.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);await page.reload();await expect(tip.locator('textarea')).toHaveValue('喝咖啡用的杯子');await page.goto('/#view=lesson&level=2&lesson=13&section=grammar');const values=[['比','长一点儿'],['比','便宜一点儿'],['比我的重一点儿']];for(const[i,row]of values.entries()){const g=page.locator(`[data-activity-id$=grammar3-practice${i+1}]`);await expect(g.locator('input')).toHaveCount(row.length);for(const[j,value]of row.entries())await g.locator('input').nth(j).fill(value);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g).toContainText('不是唯一答案');await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0)}await page.reload();for(const[i,row]of values.entries())for(const[j,value]of row.entries())await expect(page.locator(`[data-activity-id$=grammar3-practice${i+1}] input`).nth(j)).toHaveValue(value);
});

test('lesson13 original ambiguous-key explanation appears only after feedback and survives reload',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/#view=lesson&level=2&lesson=13&section=text&scene=4');const g=page.locator('[data-activity-id$=text4-listening]'),note=g.locator('.question-editorial-note');await expect(note).toHaveCount(0);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(note).toHaveCount(0);await g.locator('select').nth(0).selectOption('正确');await g.locator('select').nth(1).selectOption('正确');await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(note).toHaveCount(1);await expect(note).toContainText('不能据此断定她没有送花');await expect(note).toContainText('không thể suy ra cô ấy không tặng hoa');await expect(note).toContainText('教材第119页');await expect(g.locator('.feedback-retry')).toHaveCount(1);await g.locator('select').nth(1).selectOption('错误');await expect(note).toHaveCount(0);await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g.locator('.feedback-correct')).toHaveCount(2);await expect(note).toHaveCount(1);await page.reload();await expect(note).toHaveCount(1);await expect(note).toContainText('教材第119页');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

// Hold the real browser Web Lock, rather than adding a blind timeout or faking success.
async function verifyRapidLessonSaveLifecycle(page:import('@playwright/test').Page){
 const key='ran_hsk2_fltrp_2026_v1',activity='hsk2-fltrp-2026:l12:activity:warmup2-survey',field='hsk2-fltrp-2026:l12:field:warmup2-nameB';
 const g=page.locator('[data-activity-id$=warmup2-survey]'),input=g.locator('thead input').nth(1),status=page.locator('.save-status');
 const stored=()=>page.evaluate(({key,activity,field})=>JSON.parse(localStorage.getItem(key)!).data.activities[activity].values[field],{key,activity,field});
 async function hold(){await expect(status).toHaveAttribute('data-status','saved');await page.evaluate(key=>{const w=window as any;w.__saveLockHeld=false;void navigator.locks.request(key+'-write',async()=>{w.__saveLockHeld=true;await new Promise<void>(resolve=>w.__releaseSaveLock=resolve)})},key);await expect.poll(()=>page.evaluate(()=>(window as any).__saveLockHeld)).toBe(true)}
 async function release(){await page.evaluate(()=>(window as any).__releaseSaveLock());}
 async function editAndSave(value:string){await input.fill(value);await g.getByRole('button',{name:'保存本次记录'}).click();await expect(status).toHaveAttribute('data-status','saving');await expect(status).toContainText('正在保存');await expect(status).toContainText('Đang lưu')}
 async function saved(value:string){await expect(status).toHaveAttribute('data-status','saved');await expect.poll(stored).toBe(value)}
 // Actual page-initiated refresh invokes the browser beforeunload prompt; cancel it.
 await hold();await editAndSave('B刷新待保存');expect(await stored()).not.toBe('B刷新待保存');const dialogPromise=page.waitForEvent('dialog');await page.evaluate(()=>{setTimeout(()=>location.reload(),0)});const dialog=await dialogPromise;expect(dialog.type()).toBe('beforeunload');await dialog.dismiss();await expect(input).toHaveValue('B刷新待保存');await expect(status).toHaveAttribute('data-status','saving');await release();await saved('B刷新待保存');await page.reload();await expect(input).toHaveValue('B刷新待保存');test.info().annotations.push({type:'rapid-save-stage',description:'Native refresh prompt cancelled; edited value retained and durable after release'});
 // Switching levels must wait for the pending native lock and retain the edited value.
 const otherHomework=await page.evaluate(()=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')??'{"data":{"homework":{}}}').data.homework);
 await hold();await editAndSave('B切级待保存');await page.locator('.level-switch a[data-level="3"]').click();await expect(g).toBeVisible();await expect(input).toHaveValue('B切级待保存');await expect(status).toHaveAttribute('data-status','saving');await release();await expect(page.locator('.level-switch a[data-level="3"]')).toHaveAttribute('aria-current','true');await expect.poll(stored).toBe('B切级待保存');await page.locator('.level-switch a[data-level="2"]').click();await expect(input).toHaveValue('B切级待保存');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ran_hsk3_fltrp_2026_v1')??'{"data":{"homework":{}}}').data.homework)).toEqual(otherHomework);test.info().annotations.push({type:'rapid-save-stage',description:'Delayed level switch retained source-course edit and other-course homework'});
 // Browser Back/Forward during a pending same-course edit uses the same save barrier.
 await page.locator('.textbook-tabs a[href*="section=grammar"]').click();await expect(page.locator('.textbook-module')).toHaveAttribute('data-section','grammar');await page.locator('.textbook-tabs a[href*="section=overview"]').click();await expect(input).toBeVisible();await hold();await editAndSave('B返回待保存');await page.evaluate(()=>history.back());await expect(g).toBeVisible();await expect(input).toHaveValue('B返回待保存');await expect(status).toHaveAttribute('data-status','saving');await release();await expect(page.locator('.textbook-module')).toHaveAttribute('data-section','grammar');await expect.poll(stored).toBe('B返回待保存');await page.evaluate(()=>history.forward());await expect(input).toHaveValue('B返回待保存');test.info().annotations.push({type:'rapid-save-stage',description:'Back/Forward completed only after durable save; edited value restored'});
 // A real failed Storage write stays visibly unsaved, blocks a level change, and can retry.
 await page.evaluate(key=>{const w=window as any;w.__originalStorageSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw new DOMException('Simulated full storage','QuotaExceededError');return w.__originalStorageSet.call(this,k,v)}},key);await input.fill('B失败后重试');await g.getByRole('button',{name:'保存本次记录'}).click();await expect(status).toHaveAttribute('data-problem','true');await expect(page.locator('.global-message')).toContainText('未确认保存');await expect(input).toHaveValue('B失败后重试');expect(await stored()).toBe('B返回待保存');await page.locator('.level-switch a[data-level="3"]').click();await expect(status).toHaveAttribute('data-status','unsaved');await expect(status).toHaveAttribute('data-problem','true');await expect(status).toContainText('Bộ nhớ đã đầy');await expect(g).toBeVisible();await expect(page.locator('.level-switch a[data-level="2"]')).toHaveAttribute('aria-current','true');await expect(input).toHaveValue('B失败后重试');expect(await stored()).toBe('B返回待保存');const guard=await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented});expect(guard).toBe(true);test.info().annotations.push({type:'rapid-save-stage',description:'Failed write visibly unsaved; rejected level navigation settled before quota restoration'});await page.evaluate(()=>{Storage.prototype.setItem=(window as any).__originalStorageSet});await g.getByRole('button',{name:'保存本次记录'}).click();await saved('B失败后重试');await page.reload();await expect(input).toHaveValue('B失败后重试');
}


test('lesson14 two picture warmups retain eight scenes and word-choice split textbook pages',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=14&section=overview');const first=page.locator('[data-activity-id$=warmup1-matching]'),second=page.locator('[data-activity-id$=warmup2-descriptions]');await expect(first.locator('img')).toHaveCount(4);await expect(second.locator('img')).toHaveCount(4);await expect(second.locator('textarea')).toHaveCount(4);for(const[i,v]of ['做饭','买东西','坐飞机','看电影'].entries())await second.locator('textarea').nth(i).fill(v);await second.getByRole('button',{name:'提交并查看反馈'}).click();await expect(second).toContainText('不是唯一答案');await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(second.locator('textarea').nth(3)).toHaveValue('看电影');await expect(second.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);
 await page.goto('/#view=lesson&level=2&lesson=14&section=grammar');const grammar=lesson14.grammar[2];for(const example of grammar.examples)await expect(page.locator('main')).toContainText(example.zh);expect(grammar.examples.length).toBe(6);await expect(page.locator('[data-activity-id^="hsk2-fltrp-2026:l14:activity:grammar"] input')).toHaveCount(9);
 await page.goto('/#view=lesson&level=2&lesson=14&section=practice');const words=page.locator('[data-activity-id$=comprehensive-words]');for(const[i,v]of ['眼睛','过年','跳舞','姓','位'].entries())await words.locator('select').nth(i).selectOption(v);await words.getByRole('button',{name:'提交并查看反馈'}).click();await expect(words.locator('.feedback-correct')).toHaveCount(5);for(const[i,pg]of [128,128,128,128,129].entries())await expect(words.locator('.activity-field .source-note').nth(i)).toContainText(String(pg));await expect(words).toContainText('PDF第19页');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

test('lesson15 frequency table keeps source blank corner fixed times and three durable counts',async({page})=>{
 await page.setViewportSize({width:320,height:900});await page.goto('/#view=lesson&level=2&lesson=15&section=overview');const g=page.locator('[data-activity-id$=warmup2-frequency]'),table=g.locator('table');await expect(table.locator('thead th')).toHaveCount(3);await expect(table.locator('thead th').first()).toHaveText('');await expect(table.locator('thead th').nth(1)).toContainText('时间');await expect(table.locator('thead th').nth(2)).toContainText('次数');await expect(table.locator('caption')).toContainText('根据自己的实际情况');await expect(table.locator('input')).toHaveCount(3);for(const[i,v]of ['一个星期','一个月','一年'].entries()){await expect(table.locator('tbody tr').nth(i)).toContainText(v);await expect(table.locator('tbody tr').nth(i).locator('input')).toHaveCount(1);await expect(table.locator('tbody tr').nth(i)).toContainText('lần')}const values=['三','两','一'];for(const[i,v]of values.entries())await table.locator('input').nth(i).fill(v);await table.locator('input').first().focus();await page.keyboard.press('Tab');await expect(table.locator('input').nth(1)).toBeFocused();await g.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await expect(g).toContainText('这是开放任务');await page.reload();for(const[i,v]of values.entries())await expect(table.locator('input').nth(i)).toHaveValue(v);await table.locator('input').nth(1).fill('四');await expect(g.locator('.activity-feedback')).toBeEmpty();await g.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('input').nth(1)).toHaveValue('四');await expect(table.locator('input').nth(0)).toHaveValue('三');await expect(g.locator('.feedback-correct,.feedback-retry')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

test('lesson15 cross-page review keeps eighteen independent checks and unavailable culture video',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/#view=lesson&level=2&lesson=15&section=culture');const g=page.locator('[data-activity-id$=review-grammar]'),v=page.locator('[data-activity-id$=review-vocabulary]'),effort=page.locator('[data-activity-id$=review-effort]');await expect(g.locator('tbody tr')).toHaveCount(9);await expect(g.locator('input')).toHaveCount(18);for(let i=0;i<9;i++){const notes=g.locator('tbody tr').nth(i).locator('.source-note');await expect(notes).toHaveCount(1);await expect(g.locator('tbody tr').nth(i).locator('th .matrix-row-source')).toHaveCount(1);await expect(g.locator('tbody tr').nth(i).locator('td .source-note')).toHaveCount(0);await expect(notes).toContainText(i<4?'139':'140')}await v.locator('textarea').nth(0).fill('门票、机票');await v.locator('textarea').nth(1).fill('好像');await g.locator('input').nth(1).check();await g.locator('input').nth(16).check();await effort.locator('textarea').fill('练习说数量');await effort.getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(g.locator('input').nth(0)).not.toBeChecked();await expect(g.locator('input').nth(1)).toBeChecked();await expect(g.locator('input').nth(16)).toBeChecked();await expect(g.locator('input').nth(17)).not.toBeChecked();await expect(v.locator('textarea').nth(1)).toHaveValue('好像');await expect(effort.locator('textarea')).toHaveValue('练习说数量');await expect(page.locator('main img')).toHaveCount(1);await expect(page.locator('main video,main audio')).toHaveCount(0);await expect(page.locator('main')).toContainText('视频编号15-1');await expect(page.locator('main')).toContainText('不是当前入境资格或旅行建议');await expect(page.locator('main')).toContainText('没有对应视频');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});

test('lesson15 reversed Vietnamese blank labels and split answer pages preserve their bindings',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=15&section=practice');const g=page.locator('[data-activity-id$=picture-dialogue3]');await expect(g).toContainText('______ [ô 2] này đến ______ [ô 1]');await expect(g.locator('input')).toHaveCount(2);await g.locator('input').nth(0).fill('机场');await g.locator('input').nth(1).fill('路');await g.getByRole('button',{name:'提交并查看反馈'}).click();await expect(g).toContainText('不是唯一答案');await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(g.locator('input').nth(0)).toHaveValue('机场');await expect(g.locator('input').nth(1)).toHaveValue('路');const words=page.locator('[data-activity-id$=comprehensive-words]');for(const[i,v]of ['鸟','门票','出国','机票','姓名'].entries())await words.locator('select').nth(i).selectOption(v);await words.getByRole('button',{name:'提交并查看反馈'}).click();await expect(words.locator('.feedback-correct')).toHaveCount(5);await expect(words).toContainText('PDF第20页');await expect(words).toContainText('PDF第21页');await page.goto('/#view=lesson&level=2&lesson=9&section=vocab');const word=page.locator('[data-word-id="hsk2-fltrp-2026:l09:word02"]');await expect(page.locator('main')).toContainText('pángbiān');expect(lesson9.vocabulary.find(w=>w.id.endsWith(':word02'))!.py).toBe('pángbiān');expect(JSON.stringify(lesson9.texts)).toContain('Pángbian');
});
