import {test,expect} from '@playwright/test';
import lesson2 from '../../content/hsk2/lesson-02.json' with {type:'json'};
import lesson3 from '../../content/hsk2/lesson-03.json' with {type:'json'};
import lesson4 from '../../content/hsk2/lesson-04.json' with {type:'json'};
import lesson5 from '../../content/hsk2/lesson-05.json' with {type:'json'};
test.beforeEach(async({page})=>page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1')));
for(const width of [320,390,768,1440])for(const lesson of [lesson2,lesson3,lesson4,lesson5])test(`HSK2 lesson ${lesson.number} reviewed textbook sections at ${width}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.setViewportSize({width,height:900});const ids=new Set<string>();
 for(const section of ['overview','vocab','text','grammar','hanzi','practice','culture'])for(const scene of section==='text'?[1,2,3,4]:[1]){
  await page.goto(`/#view=lesson&level=2&lesson=${lesson.number}&section=${section}&scene=${scene}`);await expect(page.locator('main h1')).toContainText(lesson.title.zh);await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');
  for(const id of await page.locator('[data-activity-id]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.activityId!))){expect(ids.has(id),`duplicate visible activity ${id}`).toBe(false);ids.add(id)}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  for(const image of await page.locator('main img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate((node:HTMLImageElement)=>node.complete&&node.naturalWidth>0)).toBe(true)}
  if(section==='practice'){const hints=page.locator('.picture-editorial-hints');await expect(hints).toHaveCount(1);await expect(hints).not.toHaveAttribute('open','');await expect(hints.locator('p').first()).toBeHidden();const follows=await hints.evaluate(node=>{const cards=[...document.querySelectorAll('[data-activity-id*="picture-dialogue"]')];return cards.length===4&&cards.every(card=>!!(card.compareDocumentPosition(node)&Node.DOCUMENT_POSITION_FOLLOWING))});expect(follows).toBe(true)}
  if(section==='overview'&&lesson.number===4){const table=page.locator('.self-assessment-matrix');await expect(table.locator('tbody tr')).toHaveCount(3);await expect(table.locator('input[type=checkbox]')).toHaveCount(9);await expect(table.locator('thead th').first()).toContainText('动词');for(const word of ['包子','饺子','面条儿','绿茶','红茶','花茶','中国','法国','泰国'])await expect(table).toContainText(word)}
  if(section==='overview'&&lesson.number===2){const table=page.locator('.self-assessment-matrix');await expect(table.locator('thead th')).toHaveCount(4);await expect(table.locator('tbody select')).toHaveCount(3);await expect(table).toContainText('方式1');await expect(table).toContainText('方式2')}
  if(section==='practice'&&lesson.number===4){const group=page.locator('[data-activity-id$=comprehensive-words]');await expect(group.locator('.activity-field .source-note')).toHaveCount(5);await expect(group.locator('.activity-field .source-note').nth(2)).toContainText('36');await expect(group.locator(':scope > .source-note')).toContainText('35、36')}
  if(section==='practice'&&lesson.number===5)await expect(page.locator('[data-activity-id$=picture-dialogue1] .task-note')).not.toContainText('十点');
  if(section==='culture'&&lesson.number===3){const table=page.locator('.self-assessment-matrix');await expect(table.locator('tbody tr')).toHaveCount(9);await expect(table.locator('tbody input[type=checkbox]')).toHaveCount(18);await expect(table.locator('thead th')).toHaveCount(3);expect(await table.evaluate(node=>node.getBoundingClientRect().right<=innerWidth+1)).toBe(true)}
  if((width===390||width===1440)&&scene===1){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`test-results/unified-hsk2-lesson${lesson.number}-${section}-${width}.png`,fullPage:true})}
 }
 expect([...ids].sort()).toEqual(lesson.activities.map(a=>a.id).sort());expect(errors).toEqual([]);
});
test('review matrix keeps two columns independent across refresh and scoped backup restore',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/#view=lesson&level=2&lesson=3&section=culture');let checks=page.locator('.self-assessment-matrix tbody input');await checks.nth(0).check();await checks.nth(3).check();await checks.nth(1).uncheck();await checks.nth(2).uncheck();await page.locator('[data-activity-id$=review-grammar]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();checks=page.locator('.self-assessment-matrix tbody input');await expect(checks.nth(0)).toBeChecked();await expect(checks.nth(3)).toBeChecked();await expect(checks.nth(1)).not.toBeChecked();await expect(checks.nth(2)).not.toBeChecked();
 await page.getByRole('button',{name:'统一备份与恢复'}).click();const dialog=page.getByRole('dialog',{name:'学习记录备份'});const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载全部三级备份'}).click()]);const path=await download.path();if(!path)throw Error('Missing backup');const {readFileSync}=await import('node:fs');const bytes=readFileSync(path);await dialog.getByRole('button',{name:'关闭',exact:false}).click();await checks.nth(0).uncheck();await checks.nth(3).uncheck();await page.locator('[data-activity-id$=review-grammar]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.getByRole('button',{name:'统一备份与恢复'}).click();await dialog.locator('input[type=file]').setInputFiles({name:'matrix-backup.json',mimeType:'application/json',buffer:bytes});await dialog.getByRole('button',{name:'确认恢复HSK 2'}).click();await expect(dialog).toContainText('HSK 2已恢复');await dialog.getByRole('button',{name:'关闭',exact:false}).click();await expect(checks.nth(0)).toBeChecked();await expect(checks.nth(3)).toBeChecked();await expect(checks.nth(1)).not.toBeChecked();await expect(checks.nth(2)).not.toBeChecked();
});

test('source survey tables preserve independent travel text, single preferences and multiple experiences',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=1&section=overview');let table=page.locator('[data-activity-id$=travel-survey] table');await expect(table.locator('thead th')).toHaveCount(3);for(const [i,value]of ['上周六','和朋友','坐火车'].entries())await table.locator('input').nth(i).fill(value);await page.locator('[data-activity-id$=travel-survey]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('input').nth(0)).toHaveValue('上周六');await expect(table.locator('input').nth(1)).toHaveValue('和朋友');await expect(table.locator('input').nth(2)).toHaveValue('坐火车');
 await page.goto('/#view=lesson&level=2&lesson=2&section=overview');table=page.locator('[data-activity-id$=warmup-preferences] table');await table.locator('select').nth(0).selectOption('坐飞机去');await table.locator('select').nth(1).selectOption('回家做饭');await table.locator('select').nth(2).selectOption('去看电影');await page.locator('[data-activity-id$=warmup-preferences]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('select').nth(0)).toHaveValue('坐飞机去');await expect(table.locator('select').nth(1)).toHaveValue('回家做饭');await expect(table.locator('select').nth(2)).toHaveValue('去看电影');
 await page.goto('/#view=lesson&level=2&lesson=4&section=overview');table=page.locator('[data-activity-id$=warmup-experiences] table');await table.locator('input').nth(0).check();await table.locator('input').nth(1).check();await table.locator('input').nth(4).check();await page.locator('[data-activity-id$=warmup-experiences]').getByRole('button',{name:'保存本次记录'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.reload();await expect(table.locator('input').nth(0)).toBeChecked();await expect(table.locator('input').nth(1)).toBeChecked();await expect(table.locator('input').nth(2)).not.toBeChecked();await expect(table.locator('input').nth(4)).toBeChecked();
});
