import {test,expect} from '@playwright/test';
import segments from '../../content/audio-segments-pilot.json' with {type:'json'};
import {observeNativeMedia,attachNativeMedia} from '../browser/media-observer';
test.beforeEach(async({page})=>{await page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1'));await observeNativeMedia(page)});
test.afterEach(async({page},info)=>attachNativeMedia(page,info));
for(const level of [2,3]){
 const words=Object.entries(segments.words).filter(([id])=>id.startsWith(`hsk${level}`));
 for(let begin=0;begin<words.length;begin+=8)test(`HSK ${level} original word clips ${begin+1}–${Math.min(words.length,begin+8)} end at verified boundaries`,async({page})=>{
  test.setTimeout(90000);await page.goto(`/#view=lesson&level=${level}&lesson=1&section=vocab`);
  for(const [id,s]of words.slice(begin,begin+8)){await page.locator(`[data-word-id="${id}"] .word-open`).click();const dialog=page.getByRole('dialog',{name:s.sourceText,exact:true});await expect(dialog).toBeVisible();await page.evaluate(()=>(window as any).__hskNativeEvents=[]);await dialog.getByRole('button',{name:'播放单词原音'}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__hskNativeEvents.some((e:any)=>e.event==='playing'))).toBe(true);await expect(page.locator('.player-bar')).toHaveAttribute('data-state','ended',{timeout:20000});const events=await page.evaluate(()=>(window as any).__hskNativeEvents as any[]);expect(events.some(e=>String(e.source).endsWith(s.track))).toBe(true);const startAt=events.findIndex(e=>e.event==='playing'&&String(e.source).endsWith(s.track));const times=events.slice(startAt).filter(e=>String(e.source).endsWith(s.track)&&(e.event==='playing'||e.event==='pause'||e.event==='timeupdate')).map(e=>Number(e.time));expect(Math.min(...times)).toBeGreaterThanOrEqual(s.start-.08);expect(Math.max(...times)).toBeLessThanOrEqual(s.end+.16);await dialog.getByRole('button',{name:'关闭',exact:false}).click()}
 });
}
test('multi-sentence source uses separate genuine sentence controls and HSK1 scenes preserve URL',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=1&section=text&scene=4');await expect(page.locator('.sentence-audio button')).toHaveCount(3);await page.locator('.sentence-audio button').nth(1).click();await expect.poll(()=>page.evaluate(()=>(window as any).__hskNativeEvents.some((e:any)=>e.event==='playing'))).toBe(true);await expect(page.locator('.player-bar')).toHaveAttribute('data-state','ended',{timeout:15000});await page.locator('.level-switch a[data-level="1"]').click();await page.setViewportSize({width:390,height:900});await page.goto('/#view=lesson&level=1&lesson=1&section=text&scene=2');await expect(page.locator('#scene-select')).toHaveValue('1');await page.locator('#scene-select').selectOption('2');await expect(page).toHaveURL(/scene=3/);await page.reload();await expect(page.locator('#scene-select')).toHaveValue('2');
});
test('pending short word never advertises a verified standalone original clip',async({page})=>{await page.goto('/#view=lesson&level=2&lesson=1&section=vocab');await page.locator('[data-word-id="hsk2-fltrp-2026:l01:word04"] .word-open').click();const dialog=page.getByRole('dialog',{name:'接',exact:true});await expect(dialog.getByRole('button',{name:'播放单词原音'})).toHaveCount(0);await expect(dialog).toContainText('独立原音尚待核验');await expect(dialog.getByRole('button',{name:'听所在生词组原音'})).toBeVisible()});
test('supplemental illustration zoom closes by Escape and restores the opener',async({page})=>{await page.goto('/#view=lesson&level=3&lesson=1&section=text');const opener=page.locator('.illustration-zoom').first();await opener.click();await expect(page.getByRole('dialog',{name:'查看示意图'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'查看示意图'})).toHaveCount(0);await expect(opener).toBeFocused()});
test('all three levels load licensed handwriting, animate, practice and reset',async({page})=>{
 test.setTimeout(120000);for(const [level,character]of [[1,'你'],[2,'鸭'],[3,'瘦']] as const){await page.goto(`/#view=lesson&level=${level}&lesson=1&section=hanzi`);await page.locator(`[data-hanzi-char="${character}"]`).click();const panel=page.locator('[data-hanzi-mode]');await expect(panel).toHaveAttribute('data-hanzi-mode','display');await expect(page.locator('[data-hanzi-canvas] svg')).toBeVisible();await page.locator('[data-hanzi-action=animate]').click();await expect(panel).toHaveAttribute('data-hanzi-mode','animation');await expect(panel).toHaveAttribute('data-hanzi-mode','display',{timeout:45000});await page.locator('[data-hanzi-action=practice]').click();await expect(panel).toHaveAttribute('data-hanzi-mode','practice');await page.locator('[data-hanzi-action=reset]').click();await expect(panel).toHaveAttribute('data-hanzi-mode','display');}
});
