import {test,expect} from '@playwright/test';
import subset from '../../content/audio-segments-hsk2-reviewed-sentences.json' with {type:'json'};
import {observeNativeMedia,attachNativeMedia} from '../browser/media-observer';
test.beforeEach(async({page})=>{await page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1'));await observeNativeMedia(page)});
test.afterEach(async({page},info)=>attachNativeMedia(page,info));
for(const [id,segment]of [...Object.entries(subset.lines),...Object.entries(subset.subsegments)])test(`guarded source-frame ${id} plays its exact original range and retains fallback`,async({page},info)=>{
 const lesson=id.includes(':l04:')?4:5;await page.goto(`/#view=lesson&level=2&lesson=${lesson}&section=text&scene=2`);
 await expect(page.locator('[data-audio-segment]')).toHaveCount(1);const button=page.locator(`[data-audio-segment="${id}"]`);await expect(button).toContainText(lesson===5?'第2句原音':'本句原音');await expect(button).toContainText(lesson===5?'Âm thanh câu 2':'Nghe câu gốc');
 await expect(page.locator('.audio-control small').first()).toContainText('完整课文原音');if(lesson===5){await expect(page.locator('[data-audio-segment="hsk2-fltrp-2026:l05:text2:line8"]')).toHaveCount(0);await expect(page.locator('[data-audio-segment$="sentence1"]')).toHaveCount(0)}
 await button.click();await expect(page.locator('.player-bar')).toHaveAttribute('data-state','playing');await expect(page.locator('.player-bar')).toHaveAttribute('data-state','ended',{timeout:20000});
 const events=await page.evaluate(()=>(window as unknown as {__hskNativeEvents:Record<string,unknown>[]}).__hskNativeEvents);const times=events.filter(e=>String(e.source).endsWith(segment.track)&&!e.muted&&!e.seeking&&['playing','pause','timeupdate','seeked','volumechange'].includes(String(e.event))).map(e=>Number(e.time));expect(times.length).toBeGreaterThan(0);expect(Math.min(...times)).toBeGreaterThanOrEqual(segment.start-.08);expect(Math.max(...times)).toBeLessThanOrEqual(segment.end+.16);
 await info.attach(id,{body:Buffer.from(JSON.stringify({id,start:segment.start,end:segment.end,frames:segment.guardedEvidence.sourceSampleRange,events})),contentType:'application/json'});
 await button.click();await expect(page.locator('.player-bar')).toHaveAttribute('data-state','playing');await page.locator('.player-bar input[type=range]').evaluate((input:HTMLInputElement)=>{input.value='999';input.dispatchEvent(new Event('input',{bubbles:true}))});await expect(page.locator('.player-bar')).toHaveAttribute('data-state','ended');
 await button.click();await expect(page.locator('.player-bar')).toHaveAttribute('data-state','playing');await page.locator('.player-bar').getByRole('button',{name:/停止/}).click();await expect(page.locator('.player-bar')).toHaveAttribute('data-state','idle');
 await button.click();await expect(page.locator('.player-bar')).toHaveAttribute('data-state','playing');await page.evaluate(()=>{location.hash='#view=lesson&level=2&lesson=6&section=text&scene=1'});await expect(page.locator('#lesson-select')).toHaveValue('6');await expect(page.locator('.player-bar')).toHaveAttribute('data-state','idle');await page.goBack();await expect(button).toBeVisible();await expect(button).toContainText(lesson===5?'第2句原音':'本句原音');await expect(button).toContainText(lesson===5?'Âm thanh câu 2':'Nghe câu gốc');
});
test('whole-track color retains its honest pending independent-word label',async({page})=>{await page.goto('/#view=lesson&level=2&lesson=4&section=vocab');await page.locator('[data-word-id="hsk2-fltrp-2026:l04:word16"] .word-open').click();const dialog=page.getByRole('dialog',{name:'颜色',exact:true});await expect(dialog.getByRole('button',{name:'播放单词原音'})).toHaveCount(0);await expect(dialog).toContainText('独立原音尚待核验');await expect(dialog.getByRole('button',{name:'听所在生词组原音'})).toBeVisible()});
test('failed new checksum leaves legacy accepted clips and new whole-track fallback available',async({page})=>{
 await page.addInitScript(()=>{crypto.subtle.digest=async()=>new Uint8Array(32).buffer});
 await page.goto('/#view=lesson&level=2&lesson=4&section=text&scene=2');await expect(page.locator('.chinese-line')).toHaveCount(6);await expect(page.locator('[data-audio-segment]')).toHaveCount(0);await expect(page.locator('.audio-control small').first()).toContainText('完整课文原音');
 await page.goto('/#view=lesson&level=2&lesson=1&section=vocab');await page.locator('[data-word-id="hsk2-fltrp-2026:l01:word01"] .word-open').click();await expect(page.getByRole('dialog').getByRole('button',{name:'播放单词原音'})).toBeVisible();
});
