import {test,expect} from '@playwright/test';
import lesson from '../../content/hsk2/lesson-01.json' with {type:'json'};
test.beforeEach(async({page})=>{await page.addInitScript(()=>sessionStorage.setItem('hsk_portal_unlocked_v2','1'))});
for(const width of [320,390,768,1440])for(const level of [1,2,3])test(`shared classroom HSK${level} viewport ${width}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});
 for(const section of level===1?['vocab','text','grammar','hanzi','practice']:['overview','vocab','text','grammar','hanzi','practice','culture']){await page.goto(`/#view=lesson&level=${level}&lesson=1&section=${section}`);await expect(page.locator('main h1').first()).toBeVisible();if(level===1)await expect(page.locator('main')).toHaveAttribute('data-module-state','ready');await expect(page.locator('main')).not.toContainText('暂时无法打开');if(level!==1)await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');if(section==='hanzi')await expect(page.locator('[data-hanzi-mode]')).toHaveAttribute('data-hanzi-mode','display');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(width===390||width===1440){for(const img of await page.locator('main img').all()){await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate((node:HTMLImageElement)=>node.complete&&node.naturalWidth>0)).toBe(true)}await page.evaluate(()=>window.scrollTo(0,0));}if(width===390||width===1440)await page.screenshot({path:`test-results/unified-hsk${level}-${section}-${width}.png`,fullPage:true})}
 expect(errors).toEqual([]);
});
test('one shell switches levels without reload and keeps nonempty drafts isolated',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('hsk3_ranteacher_progress_v1','{"20":{"score":8}}');(window as any).__documentMarker=crypto.randomUUID()});
 await page.goto('/#view=homework&level=2&lesson=1&part=writing');const marker=await page.evaluate(()=>(window as any).__documentMarker);await page.locator('textarea').first().fill('二级草稿保存');await page.locator('.level-switch a[data-level="3"]').click();await page.locator('.feature-nav a[data-view="homework"]').click();await page.locator('.subnav a').filter({hasText:'越译中手写'}).click();await page.locator('textarea').first().fill('三级不同草稿');await page.locator('.level-switch a[data-level="1"]').click();await expect(page.locator('#home-module')).toBeVisible();await page.locator('.level-switch a[data-level="2"]').click();await expect(page.locator('textarea').first()).toHaveValue('二级草稿保存');expect(await page.evaluate(()=>(window as any).__documentMarker)).toBe(marker);expect(await page.evaluate(()=>localStorage.getItem('hsk3_ranteacher_progress_v1'))).toBe('{"20":{"score":8}}');await page.reload();await expect(page.locator('textarea').first()).toHaveValue('二级草稿保存');
});
test('textbook answers save, check, survive scene changes and reload without altering homework',async({page})=>{
 await page.goto('/#view=lesson&level=2&lesson=1&section=text');const activity=page.locator('[data-activity-id="hsk2-fltrp-2026:l01:activity:text1-listening"]');await activity.locator('select').nth(0).selectOption('王一雪');await activity.locator('select').nth(1).selectOption('王一雪');await activity.getByRole('button',{name:'提交并查看反馈'}).click();await expect(activity).toContainText('回答正确');await page.locator('.scene-tabs a').nth(1).click();await page.locator('.scene-tabs a').first().click();await expect(activity.locator('select').first()).toHaveValue('王一雪');await page.reload();await expect(activity.locator('select').first()).toHaveValue('王一雪');expect(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('ran_hsk2_fltrp_2026_v1')!).data.homework).length)).toBe(0);
});
test('homework receipts store immutable questions and scores',async({page})=>{
 await page.goto('/#view=homework&level=2&lesson=1');for(const q of lesson.homework.filter(q=>q.part==='vocabGrammar'))await page.locator(`input[name="${q.id}"][value="${q.answer}"]`).check();await page.locator('#assignment button[type=submit]').click();await expect(page.locator('#receipt')).toContainText('10/10');const attempt=await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('ran_hsk2_fltrp_2026_v1')!).data.homework)[0] as any);expect(attempt.latest.questions).toHaveLength(10);expect(attempt.latest.contentRevision).toMatch(/^q1-/);
});
test('portal shows all three levels and retains HSK4 and legacy courses',async({page})=>{await page.setViewportSize({width:390,height:900});await page.goto('/#view=portal&level=2');await expect(page.locator('.level-grid .level-card')).toHaveCount(3);await expect(page.locator('.level-grid')).toContainText('18课');await page.locator('details.data-panel summary').click();await expect(page.locator('details.data-panel')).toContainText('HSK 4');await expect(page.locator('details.data-panel')).toContainText('20课');await page.screenshot({path:'test-results/unified-portal-390.png',fullPage:true})});
test('shared backup exports all three course identities and restores only the selected level',async({page})=>{
 await page.goto('/#view=progress&level=2');await page.locator('#profile-name').fill('Before backup');await page.locator('.data-panel').getByRole('button',{name:'重试保存'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.getByRole('button',{name:'统一备份与恢复'}).click();const dialog=page.getByRole('dialog',{name:'学习记录备份'});await expect(dialog).toBeVisible();await expect(dialog.locator('.backup-course-summary')).toHaveCount(3);const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载全部三级备份'}).click()]);const path=await download.path();if(!path)throw Error('Backup file missing');const {readFileSync}=await import('node:fs');const bytes=readFileSync(path);const backup=JSON.parse(bytes.toString());expect(backup.courses.map((c:any)=>c.level)).toEqual([1,2,3]);expect(backup.courses[1].backup.data.profile.name).toBe('Before backup');await dialog.getByRole('button',{name:'关闭',exact:false}).click();await page.locator('#profile-name').fill('After backup');await page.locator('.data-panel').getByRole('button',{name:'重试保存'}).click();await expect(page.locator('.save-status')).toHaveAttribute('data-status','saved');await page.getByRole('button',{name:'统一备份与恢复'}).click();await dialog.locator('input[type=file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:bytes});await expect(dialog.locator('.backup-preview')).toHaveCount(3);await dialog.getByRole('button',{name:'确认恢复HSK 2'}).click();await expect(dialog).toContainText('HSK 2已恢复');await dialog.getByRole('button',{name:'关闭',exact:false}).click();await expect(page.locator('#profile-name')).toHaveValue('Before backup');
});
