import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {verifyActivities} from '../tools/verify-activities.mjs';
const source=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-01.json',import.meta.url)));
function matrix(){const l=structuredClone(source),a=l.activities.find(a=>a.kind==='self-assessment');a.fields=a.fields.slice(0,2);a.matrix={columns:[{zh:'理解',vi:'Đã hiểu'},{zh:'会用',vi:'Biết sử dụng'}],rows:[{prompt:{zh:'示例语法',vi:'Ví dụ ngữ pháp'},fieldIds:a.fields.map(f=>f.id)}]};return {l,a}}
test('existing pilot activities and a separately bound self-assessment matrix are structurally sound',()=>{assert.deepEqual(verifyActivities(source),[]);assert.deepEqual(verifyActivities(matrix().l),[])});
test('matrix cannot drop, repeat, misorder dimensions or bind non-checkbox answers',()=>{for(const mutate of [a=>a.matrix.rows[0].fieldIds.pop(),a=>a.matrix.rows[0].fieldIds[1]=a.fields[0].id,a=>a.fields[1].input='textarea',a=>a.matrix.columns.pop(),a=>a.matrix.rows[0].prompt.vi='']){const {l,a}=matrix();mutate(a);assert.ok(verifyActivities(l).length)}});
test('editorial references never acquire automatic grading answers or unrelated picture IDs',()=>{for(const mutate of [f=>f.answer='自动判错',f=>f.illustrationId='foreign-image']){const l=structuredClone(source);mutate(l.activities.flatMap(a=>a.fields).find(f=>f.assessment==='reference'));assert.ok(verifyActivities(l).length)}});

test('source surveys retain text/select/checkbox matrix bindings and reject mismatched context columns',()=>{for(const n of [1,2,4]){const l=JSON.parse(fs.readFileSync(new URL(`../content/hsk2/lesson-0${n}.json`,import.meta.url)));assert.deepEqual(verifyActivities(l),[]);const a=l.activities.find(a=>a.kind==='survey'&&a.matrix);assert.ok(a);if(a.matrix.contextHeaders?.length){a.matrix.rows[0].contextCells.pop();assert.ok(verifyActivities(l).length)}else{a.matrix.rows[0].cellLabels.pop();assert.ok(verifyActivities(l).length)}}});
test('cross-page activities reject unrelated or inconsistent per-field source pages',()=>{for(const mutate of [f=>f.source.pdfPage=999,f=>f.source.printedPage=1]){const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-04.json',import.meta.url)));mutate(l.activities.find(a=>a.id.endsWith('comprehensive-words')).fields[2]);assert.ok(verifyActivities(l).length)}});

test('every approved instructional illustration exists with its reviewed bytes and no external source',async()=>{
 const {createHash}=await import('node:crypto');let count=0;
 for(const level of [2,3])for(const name of fs.readdirSync(new URL(`../content/hsk${level}/`,import.meta.url)).filter(n=>/^lesson-\d\d\.json$/.test(n))){const lesson=JSON.parse(fs.readFileSync(new URL(`../content/hsk${level}/${name}`,import.meta.url)));const ids=new Set();for(const figure of lesson.illustrationManifest??[]){assert.ok(!ids.has(figure.id));ids.add(figure.id);if(figure.publicationStatus!=='approved')continue;assert.match(figure.file,/^illustrations\/[a-z0-9-]+\.svg$/);const bytes=fs.readFileSync(new URL('../public/'+figure.file,import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),figure.assetSha256);assert.equal(figure.originalTextbookImage,false);assert.ok(!/<(?:image|script|foreignObject)\b|(?:href=|url\()/i.test(bytes.toString()));assert.ok(figure.alt.zh&&figure.alt.vi);count++}}
 assert.equal(count,235);
});

function editableHeaders(){const {l,a}=matrix();a.kind='survey';a.matrix.mode='responses';a.fields.forEach(f=>f.input='text');const name={...a.fields[0],id:a.fields[0].id+':header-name',prompt:{zh:'A姓名',vi:'Tên A'}};a.fields.push(name);a.matrix.headerFieldIds=[null,name.id];return {l,a}}
test('source survey headers bind editable names independently from all body responses',()=>{const {l,a}=editableHeaders();assert.deepEqual(verifyActivities(l),[]);assert.equal(a.matrix.rows[0].fieldIds.length,2);assert.equal(a.fields.length,3)});
test('editable survey headers cannot hide, duplicate, omit, mismatch or auto-grade a name',()=>{for(const mutate of [a=>a.matrix.headerFieldIds.pop(),a=>a.matrix.headerFieldIds[0]=a.matrix.headerFieldIds[1],a=>a.matrix.headerFieldIds[1]=a.fields[0].id,a=>a.matrix.headerFieldIds[1]='foreign-name',a=>a.matrix.headerFieldIds[1]=null,a=>a.matrix.headerFieldIds='bad',a=>a.matrix.headerFieldIds[1]=7,a=>a.matrix.hideColumnHeaders=true,a=>a.fields[2].input='checkbox',a=>a.fields[2].assessment='official',a=>a.kind='self-assessment']){const {l,a}=editableHeaders();mutate(a);assert.ok(verifyActivities(l).length)}});

test('field-level question provenance cannot point outside actual source questions',()=>{const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-10.json',import.meta.url)));const f=l.activities.flatMap(a=>a.fields).find(f=>f.targetRef);assert.ok(f);for(const invalid of ['foreign-question',l.id+':missing-question',7]){const clone=structuredClone(l);clone.activities.flatMap(a=>a.fields).find(x=>x.id===f.id).targetRef=invalid;assert.ok(verifyActivities(clone).length)}assert.deepEqual(verifyActivities(l),[])});

// Explicit bilingual blank corner is a printed source feature, not a missing label.
test('frequency matrix permits only an explicit bilingual blank corner and retains caption context',()=>{const {l,a}=matrix();a.kind='survey';a.matrix.mode='responses';a.fields.forEach(f=>f.input='text');a.matrix.rowHeading={zh:'',vi:''};a.matrix.contextHeaders=[{zh:'时间',vi:'Thời gian'}];a.matrix.rows[0].contextCells=[{zh:'一个星期',vi:'Một tuần'}];assert.deepEqual(verifyActivities(l),[]);assert.ok(a.title.zh&&a.title.vi);assert.ok(a.matrix.rows[0].prompt.zh&&a.matrix.rows[0].prompt.vi);delete a.matrix.rowHeading;assert.deepEqual(verifyActivities(l),[])});
test('matrix corner rejects one-sided empty, missing language, non-string and whitespace-only headings',()=>{for(const invalid of [{zh:'',vi:'Hoạt động'},{zh:'行为',vi:''},{zh:undefined,vi:''},{zh:'',vi:undefined},{zh:0,vi:''},{zh:'',vi:0},{zh:null,vi:''},{zh:'',vi:null},{zh:' ',vi:''},{zh:'',vi:' '},{},null,'',0,false]){const {l,a}=matrix();a.matrix.rowHeading=invalid;assert.ok(verifyActivities(l).some(x=>x.includes('invalid matrix shape')),JSON.stringify(invalid))}});
