import test from 'node:test';import assert from 'node:assert/strict';
import {commitCourseActivity} from '../src/activity-commit.ts';import {createLearningStore} from '../src/state.ts';import {configs} from '../src/config.ts';
function fixture(level=3){const config=configs[level],id=config.id+':l01:activity:new',oldId=config.id+':l01:activity:old',m=new Map();let fail=false,hold=false,release;const gate=new Promise(r=>release=r);const storage={getItem:k=>m.get(k)??null,setItem:(k,v)=>{if(fail)throw new DOMException('test quota','QuotaExceededError');m.set(k,v)}};const store=createLearningStore(config,storage,async f=>{if(hold)await gate;return f()});store.edit(s=>{s.activities[id]={values:{answer:'draft'},checkedAt:null,updatedAt:10};s.activities[oldId]={values:{answer:'old confirmed'},checkedAt:9,updatedAt:9}});return {config,id,oldId,m,store,fail:v=>fail=v,hold:()=>hold=true,release:()=>{hold=false;release()},disk:()=>JSON.parse(m.get(config.storageKey)).data};}
for(const level of [2,3]){
 test(`HSK${level} failed candidate never enters draft and later ordinary save cannot invent submission`,async()=>{const f=fixture(level);await f.store.save();const old=f.store.snapshot().data.activities[f.oldId];f.fail(true);assert.equal(await commitCourseActivity(f.store,f.id,{answer:'draft'},20,new AbortController().signal),false);assert.equal(f.store.snapshot().data.activities[f.id].checkedAt,null);assert.equal(f.disk().activities[f.id].checkedAt,null);f.fail(false);f.store.edit(s=>s.favorites.push(f.config.id+':word:test'));assert.equal((await f.store.save()).ok,true);assert.equal(f.disk().activities[f.id].checkedAt,null);assert.deepEqual(f.disk().activities[f.oldId],old);});
 test(`HSK${level} waiting candidate stays unsubmitted and confirmed reload preserves old record`,async()=>{const f=fixture(level);await f.store.save();const old=f.store.snapshot().data.activities[f.oldId];f.hold();const p=commitCourseActivity(f.store,f.id,{answer:'draft'},20,new AbortController().signal);assert.equal(f.store.snapshot().data.activities[f.id].checkedAt,null);assert.equal(f.disk().activities[f.id].checkedAt,null);f.release();assert.equal(await p,true);assert.equal(f.disk().activities[f.id].checkedAt,20);assert.deepEqual(f.disk().activities[f.oldId],old);const restored=createLearningStore(f.config,{getItem:k=>f.m.get(k)??null,setItem:(k,v)=>f.m.set(k,v)},async fn=>fn());assert.equal(restored.snapshot().data.activities[f.id].checkedAt,20);});
 test(`HSK${level} lock-wait edit invalidates candidate without losing newer draft`,async()=>{const f=fixture(level);await f.store.save();f.hold();const p=commitCourseActivity(f.store,f.id,{answer:'draft'},20,new AbortController().signal);f.store.edit(s=>s.activities[f.id]={values:{answer:'newer draft'},checkedAt:null,updatedAt:21});f.release();assert.equal(await p,false);assert.equal(f.store.snapshot().data.activities[f.id].values.answer,'newer draft');await f.store.save();assert.equal(f.disk().activities[f.id].checkedAt,null);assert.equal(f.disk().activities[f.id].values.answer,'newer draft');});
 test(`HSK${level} composition and cancelled pending view never commit a marker`,async()=>{const f=fixture(level);await f.store.save();assert.equal(await commitCourseActivity(f.store,f.id,{answer:'draft'},20,new AbortController().signal,()=>true),false);const c=new AbortController();f.hold();const p=commitCourseActivity(f.store,f.id,{answer:'draft'},20,c.signal);c.abort();f.release();assert.equal(await p,false);await f.store.save();assert.equal(f.disk().activities[f.id].checkedAt,null);});
}
test('stale values and unsafe unavailable lock fail closed without adopting submissions',async()=>{const f=fixture();await f.store.save();assert.equal(await commitCourseActivity(f.store,f.id,{answer:'not current'},20,new AbortController().signal),false);const noLock=createLearningStore(f.config,{getItem:k=>f.m.get(k)??null,setItem:()=>{throw Error('must not write')}});assert.equal(await commitCourseActivity(noLock,f.id,{answer:'draft'},20,new AbortController().signal),false);assert.equal(noLock.snapshot().data.activities[f.id].checkedAt,null);});
