import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {verifyActivities} from '../tools/verify-activities.mjs';
const source=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-01.json',import.meta.url)));
function matrix(){const l=structuredClone(source),a=l.activities.find(a=>a.kind==='self-assessment');a.fields=a.fields.slice(0,2);a.matrix={columns:[{zh:'理解',vi:'Đã hiểu'},{zh:'会用',vi:'Biết sử dụng'}],rows:[{prompt:{zh:'示例语法',vi:'Ví dụ ngữ pháp'},fieldIds:a.fields.map(f=>f.id)}]};return {l,a}}
test('existing pilot activities and a separately bound self-assessment matrix are structurally sound',()=>{assert.deepEqual(verifyActivities(source),[]);assert.deepEqual(verifyActivities(matrix().l),[])});
test('matrix cannot drop, repeat, misorder dimensions or bind non-checkbox answers',()=>{for(const mutate of [a=>a.matrix.rows[0].fieldIds.pop(),a=>a.matrix.rows[0].fieldIds[1]=a.fields[0].id,a=>a.fields[1].input='textarea',a=>a.matrix.columns.pop(),a=>a.matrix.rows[0].prompt.vi='']){const {l,a}=matrix();mutate(a);assert.ok(verifyActivities(l).length)}});
test('editorial references never acquire automatic grading answers or unrelated picture IDs',()=>{for(const mutate of [f=>f.answer='自动判错',f=>f.illustrationId='foreign-image']){const l=structuredClone(source);mutate(l.activities.flatMap(a=>a.fields).find(f=>f.assessment==='reference'));assert.ok(verifyActivities(l).length)}});

test('source surveys retain text/select/checkbox matrix bindings and reject mismatched context columns',()=>{for(const n of [1,2,4]){const l=JSON.parse(fs.readFileSync(new URL(`../content/hsk2/lesson-0${n}.json`,import.meta.url)));assert.deepEqual(verifyActivities(l),[]);const a=l.activities.find(a=>a.kind==='survey'&&a.matrix);assert.ok(a);if(a.matrix.contextHeaders?.length){a.matrix.rows[0].contextCells.pop();assert.ok(verifyActivities(l).length)}else{a.matrix.rows[0].cellLabels.pop();assert.ok(verifyActivities(l).length)}}});
test('cross-page activities reject unrelated or inconsistent per-field source pages',()=>{for(const mutate of [f=>f.source.pdfPage=999,f=>f.source.printedPage=1]){const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-04.json',import.meta.url)));mutate(l.activities.find(a=>a.id.endsWith('comprehensive-words')).fields[2]);assert.ok(verifyActivities(l).length)}});

test('every approved instructional illustration exists with its reviewed bytes and no external source',async()=>{
 const {createHash}=await import('node:crypto');let count=0;
 for(const level of [2,3])for(const name of fs.readdirSync(new URL(`../content/hsk${level}/`,import.meta.url)).filter(n=>/^lesson-\d\d\.json$/.test(n))){const lesson=JSON.parse(fs.readFileSync(new URL(`../content/hsk${level}/${name}`,import.meta.url)));const ids=new Set();for(const figure of lesson.illustrationManifest??[]){assert.ok(!ids.has(figure.id));ids.add(figure.id);if(figure.publicationStatus!=='approved')continue;assert.match(figure.file,/^illustrations\/[a-z0-9-]+\.svg$/);const bytes=fs.readFileSync(new URL('../public/'+figure.file,import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),figure.assetSha256);assert.equal(figure.originalTextbookImage,false);assert.ok(!/<(?:image|script|foreignObject)\b|(?:href=|url\()/i.test(bytes.toString()));assert.ok(figure.alt.zh&&figure.alt.vi);count++}}
 assert.equal(count,133);
});
