import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateSegments,mergeSegmentData} from '../src/audio-segment-contract.ts';
const segments=JSON.parse(fs.readFileSync(new URL('../content/audio-segments-pilot.json',import.meta.url))),tracks=JSON.parse(fs.readFileSync(new URL('../content/audio-manifest.json',import.meta.url))).tracks;
const authority=JSON.parse(fs.readFileSync(new URL('../content/audio-segment-authority.json',import.meta.url)));
test('verified pilot clip ranges carry exact original identities and source text',()=>{assert.deepEqual(validateSegments(segments,tracks,authority),segments);assert.ok(Object.keys(segments.words).length>0);assert.equal(Object.keys(segments.lines).length,42)});
test('unverified, foreign, out-of-track and source-hash substitutions are rejected',()=>{for(const mutate of [x=>Object.values(x.words)[0].verification.status='unresolved',x=>Object.values(x.words)[0].end=10000,x=>Object.values(x.tracks)[0].sourceHash='bad',x=>{const [id,s]=Object.entries(x.words)[0];x.words[id.replace('hsk2','hsk3')]=s;delete x.words[id]}]){const x=structuredClone(segments);mutate(x);assert.throws(()=>validateSegments(x,tracks,authority))}});
test('multi-sentence source fragments cannot be swapped or replaced',()=>{const x=structuredClone(segments),line=Object.values(x.lines).find(l=>l.subsegments?.length);line.subsegments.reverse();assert.throws(()=>validateSegments(x,tracks,authority));const y=structuredClone(segments);Object.values(y.subsegments)[0].sourceText='错误句子';assert.throws(()=>validateSegments(y,tracks,authority))});

test('source text, pinyin, per-entry hash, scope and reviewed timing cannot be forged',()=>{for(const mutate of [x=>Object.values(x.words)[0].sourceHash='0'.repeat(64),x=>Object.values(x.words)[0].sourceText='错误',x=>Object.values(x.words)[0].sourcePinyin='cuòwù',x=>x.scope.lessons=[2],x=>{const s=Object.values(x.words)[0];s.start=0;s.end=19},x=>Object.values(x.words)[0].verification.humanListening=true,x=>Object.values(x.words)[0].verification.devicePlaybackCertified=true,x=>Object.values(x.words)[0].verification.pronunciationToneCertified=true]){const x=structuredClone(segments);mutate(x);assert.throws(()=>validateSegments(x,tracks,authority))}});
test('word partitions and actual sentence coverage reject losses, orphans and relabeled whole paragraphs',()=>{for(const mutate of [x=>delete x.words[Object.keys(x.words)[0]],x=>{const u=x.unresolved[0];x.words[u.id]={...Object.values(x.words)[0],...u}},x=>delete x.lines[Object.keys(x.lines)[0]],x=>{const l=Object.values(x.lines).find(l=>l.subsegments?.length);for(const id of l.subsegments)delete x.subsegments[id];delete l.subsegments;l.unit='sentence'},x=>Object.values(x.subsegments)[0].parentLineId='foreign']){const x=structuredClone(segments);mutate(x);assert.throws(()=>validateSegments(x,tracks,authority))}});
test('no source authority or duplicate merged IDs can silently expose segments',()=>{assert.throws(()=>validateSegments(segments,tracks));assert.throws(()=>mergeSegmentData([segments,segments]));assert.deepEqual(mergeSegmentData([segments]).words,segments.words)});

test('pending bounds, inflated decoded duration, claimed certification and forged transcript are rejected',()=>{for(const mutate of [x=>x.unresolved[0].start=0,x=>x.unresolved[0].end=10,x=>Object.values(x.tracks)[0].duration+=100,x=>x.humanListening=true,x=>Object.values(x.words)[0].verification.observedTranscript='forged']){const x=structuredClone(segments);mutate(x);assert.throws(()=>validateSegments(x,tracks,authority))}const x=structuredClone(segments);x.unresolved=[{...x.unresolved[0],id:Object.keys(x.lines)[0]}];assert.throws(()=>mergeSegmentData([x]))});

test('reviewed HSK2 lessons 2–3 retain exact 25 verified and seven pending words after runtime merge',()=>{
 const extra=JSON.parse(fs.readFileSync(new URL('../content/audio-segments-hsk2-lessons02-03.json',import.meta.url)));
 assert.deepEqual(validateSegments(extra,tracks,authority),extra);assert.equal(Object.keys(extra.words).length,25);assert.equal(extra.unresolved.length,7);assert.equal(Object.keys(extra.lines).length,36);assert.equal(Object.keys(extra.subsegments).length,10);
 assert.ok(extra.unresolved.some(x=>x.id==='hsk2-fltrp-2026:l03:word09'&&x.sourceText==='手'));
 const combined=mergeSegmentData([validateSegments(segments,tracks,authority),validateSegments(extra,tracks,authority)]);assert.equal(Object.keys(combined.words).length,61);assert.equal(combined.unresolved.length,13);assert.equal(Object.keys(combined.lines).length,78);assert.equal(Object.keys(combined.subsegments).length,33);
 for(const pending of combined.unresolved){assert.ok(!(pending.id in combined.words));assert.ok(!('start' in pending));assert.ok(!('end' in pending))}
});
