// Deterministic renderer/state regression only. Real CSS/focus/storage needs browser CI.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {mountLesson} from '../src/lesson-view.ts';import {blank,validateState} from '../src/state.ts';import {configs} from '../src/config.ts';import {verifyActivities} from '../tools/verify-activities.mjs';
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.events={};this.classes=new Set();this.scrollWidth=0;this.clientWidth=0;this.value='';this._text='';this.classList={add:(...c)=>c.forEach(x=>this.classes.add(x)),toggle:(c,v)=>v?this.classes.add(c):this.classes.delete(c)}}append(...xs){for(const x of xs){this.children.push(x);x.parent=this}}prepend(...xs){this.children.unshift(...xs);xs.forEach(x=>x.parent=this)}set textContent(v){this._text=v;this.children=[]}get textContent(){return this._text+this.children.map(x=>x.textContent??String(x)).join('')}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,v){this.events[k]=v}querySelector(){return null}remove(){}replaceChildren(...xs){this.children=[];this.append(...xs)}}
class TextArea extends Element{constructor(){super('textarea')}}
const all=n=>[n,...n.children.flatMap(all)];

function grouped(){const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-01.json',import.meta.url))),g=l.grammar[0];l.grammarPresentations=[{grammarId:g.id,groups:[{title:{zh:'用法一',vi:'Cách dùng một'},explanation:{zh:'第一组说明',vi:'Giải thích nhóm một'},exampleIndices:[0],source:g.source},{title:{zh:'用法二',vi:'Cách dùng hai'},explanation:{zh:'第二组说明',vi:'Giải thích nhóm hai'},exampleIndices:g.examples.slice(1).map((_,i)=>i+1),source:g.source}]}];return{l,g,p:l.grammarPresentations[0]}}
test('grammar group metadata cannot omit duplicate reorder or replace baseline examples or lose bilingual sources',()=>{
 const {l}=grouped();assert.deepEqual(verifyActivities(l),[]);
 for(const mutate of [(l,p)=>p.grammarId='foreign',(l,p)=>l.grammarPresentations.push(p),(l,p)=>p.groups=[],(l,p)=>p.groups.pop(),(l,p)=>p.groups[0].title.vi='',(l,p)=>p.groups[0].explanation.zh='',(l,p)=>p.groups[0].exampleIndices=[-1],(l,p)=>p.groups[0].exampleIndices=['0'],(l,p)=>p.groups[0].exampleIndices=[1],(l,p)=>p.groups[1].exampleIndices.reverse(),(l,p)=>p.groups[1].exampleIndices.push(999),(l,p)=>p.groups[0].source={...p.groups[0].source,pdfPage:999},(l,p)=>p.groups[0].source={...p.groups[0].source,printedPage:999},(l,p)=>p.groups[0].source={...p.groups[0].source,provenance:'supplemental'},(l,p)=>p.groups[0].source={...p.groups[0].source,section:''},(l,p)=>p.groups[0].source=null,(l,p)=>l.grammarPresentations='not-an-array']){const{l,p}=grouped();mutate(l,p);assert.ok(verifyActivities(l).some(s=>s.includes('grammar')),String(mutate))}
});
test('actual grouped grammar retains full baseline summary and interleaves every original bilingual pinyin example once',()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const{l,g,p}=grouped(),before=JSON.stringify(l.grammar),state=blank(configs[2]);function render(){const host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:1,section:'grammar'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});return all(host).find(n=>n.classes.has('grammar'))}
 const sec=render(),groups=all(sec).filter(n=>n.classes.has('grammar-explanation-group'));assert.equal(groups.length,2);assert.ok(sec.textContent.includes(g.explanation.zh));assert.ok(sec.textContent.includes(g.explanation.vi));assert.ok(sec.textContent.includes(g.structure));assert.ok(sec.children.findIndex(n=>n.textContent.includes(g.explanation.zh))<sec.children.indexOf(groups[0]));assert.deepEqual(groups.map(n=>n.dataset.grammarGroup),['1','2']);for(const[i,group]of groups.entries()){assert.ok(group.textContent.includes(p.groups[i].title.zh));assert.ok(group.textContent.includes(p.groups[i].title.vi));assert.ok(group.textContent.includes(p.groups[i].explanation.zh));assert.ok(group.textContent.includes(p.groups[i].explanation.vi));const examples=all(group).filter(n=>n.classes.has('example'));assert.equal(examples.length,p.groups[i].exampleIndices.length);for(const[j,ex]of examples.entries()){const original=g.examples[p.groups[i].exampleIndices[j]];assert.equal(ex.children[0].textContent,original.zh);assert.equal(ex.children[1].textContent,original.py);assert.equal(ex.children[2].textContent,original.vi)}assert.ok(group.children.at(-1).textContent.includes(String(p.groups[i].source.printedPage)))}assert.equal(all(sec).filter(n=>n.classes.has('example')).length,g.examples.length);assert.equal(JSON.stringify(l.grammar),before);delete l.grammarPresentations;const flat=render();assert.equal(all(flat).filter(n=>n.classes.has('grammar-explanation-group')).length,0);assert.deepEqual(all(flat).filter(n=>n.classes.has('example')).map(n=>n.children[0].textContent),g.examples.map(x=>x.zh));
});

test('both supplemental picture-description labels retain full bilingual text after the source activity',()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 for(const prefix of ['图片描述','图片说明']){
  const{l}=grouped(),section=l.sections.find(s=>s.kind==='practice'&&l.activities.some(a=>a.targetRef===s.id||a.targetRef.startsWith(s.id+':')));assert.ok(section);const source={...section.source,provenance:'supplemental'},hint={kind:'paragraph',zh:prefix+'（编辑补充）：完整场景提示。',vi:'Toàn bộ gợi ý bằng tiếng Việt.',source};section.blocks.push(hint);const state=blank(configs[2]),host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:1,section:'practice'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});const detail=all(host).find(n=>n.tagName==='DETAILS'&&n.textContent.includes(hint.zh));assert.ok(detail);assert.equal(detail.attrs.open,undefined);assert.ok(detail.textContent.includes(hint.vi));assert.equal(all(host).filter(n=>n.tagName==='P'&&n.textContent.includes(hint.zh)).length,1);const position=all(host).indexOf(detail),activities=l.activities.filter(a=>a.targetRef===section.id||a.targetRef.startsWith(section.id+':'));for(const a of activities)assert.ok(all(host).findIndex(n=>n.dataset.activityId===a.id)<position);
  section.blocks[section.blocks.length-1]={...hint,source:{...source,provenance:'textbook'}};const literalHost=new Element('div');mountLesson(literalHost,l,{route:{view:'lesson',lesson:1,section:'practice'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});assert.equal(all(literalHost).filter(n=>n.tagName==='DETAILS'&&n.textContent.includes(hint.zh)).length,0);assert.equal(all(literalHost).filter(n=>n.tagName==='P'&&n.textContent.includes(hint.zh)).length,1);
 }
});

test('cross-page grammar examples retain their own visible source beside the unchanged explanation page',()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const l=JSON.parse(fs.readFileSync(new URL('../content/hsk3/lesson-04.json',import.meta.url))),g=l.grammar[1],before=JSON.stringify(l.grammar),state=blank(configs[3]),host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:4,section:'grammar'},level:3,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});const section=all(host).filter(n=>n.classes.has('grammar'))[1],examples=all(section).filter(n=>n.classes.has('example'));assert.equal(g.source.pdfPage,44);assert.equal(g.source.printedPage,32);assert.equal(examples.length,3);for(const [i,example]of examples.entries()){assert.equal(g.examples[i].source.pdfPage,45);const notes=example.children.filter(n=>n.classes.has('source-note'));assert.equal(notes.length,1);assert.ok(notes[0].textContent.includes('教材第33页'));assert.ok(notes[0].textContent.includes('SGK trang 33'))}const groupNote=section.children.filter(n=>n.classes.has('source-note'));assert.equal(groupNote.length,1);assert.ok(groupNote[0].textContent.includes('教材第32页'));assert.equal(JSON.stringify(l.grammar),before);const samePage=all(host).filter(n=>n.classes.has('grammar'))[0];assert.equal(all(samePage).filter(n=>n.classes.has('example')).flatMap(n=>n.children.filter(x=>x.classes.has('source-note'))).length,0);
});

test('source grammar explanations are additive, bilingual and tied to one real source grammar',()=>{
 const make=()=>{const{l,g}=grouped();delete l.grammarPresentations;l.grammarSourceExplanations=[{grammarId:g.id,explanation:{zh:'教材原句说明',vi:'Giải thích gốc trong sách'},source:g.source}];return{l,g,n:l.grammarSourceExplanations[0]}};
 const{l}=make();assert.deepEqual(verifyActivities(l),[]);
 for(const mutate of [(l,n)=>n.grammarId='foreign',(l,n)=>l.grammarSourceExplanations.push(n),(l,n)=>n.explanation.zh='',(l,n)=>n.explanation.vi='',(l,n)=>n.source={...n.source,provenance:'supplemental'},(l,n)=>n.source={...n.source,pdfPage:999},(l,n)=>n.source={...n.source,printedPage:999},(l,n)=>n.source={...n.source,section:''},(l,n)=>n.source=null,(l,n)=>l.grammarSourceExplanations={},(l,n)=>l.grammarSourceExplanations=[]]){const{l,n}=make();mutate(l,n);assert.ok(verifyActivities(l).some(s=>s.includes('source grammar')),String(mutate))}
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const fixture=make(),before=JSON.stringify(fixture.l.grammar),host=new Element('div'),state=blank(configs[2]);mountLesson(host,fixture.l,{route:{view:'lesson',lesson:1,section:'grammar'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});const section=all(host).find(n=>n.classes.has('grammar')),source=all(section).find(n=>n.classes.has('grammar-source-explanation'));assert.ok(source);assert.ok(section.textContent.includes(fixture.g.explanation.zh));assert.ok(section.textContent.includes(fixture.g.explanation.vi));assert.ok(source.textContent.includes('教材原句说明'));assert.ok(source.textContent.includes('Giải thích gốc trong sách'));assert.ok(source.textContent.includes(String(fixture.g.source.printedPage)));assert.deepEqual(all(section).filter(n=>n.classes.has('example')).map(n=>n.children[0].textContent),fixture.g.examples.map(x=>x.zh));assert.equal(JSON.stringify(fixture.l.grammar),before);assert.ok(section.children.indexOf(source)<section.children.findIndex(n=>n.classes.has('example')));
});

test('unmapped supplemental picture paragraphs collapse without hiding textbook text tasks or safety notes',()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 for(const kind of ['practice','activity']) for(const prefix of ['图片描述','图片说明']) {
  const{l}=grouped(),source={...l.source,provenance:'supplemental'},hint={kind:'paragraph',zh:prefix+'（编辑补充）：不提前展开的完整提示。',vi:'Gợi ý đầy đủ chỉ hiện khi mở.',source};
  const section={id:l.id+':unmapped-test',kind,title:{zh:'图片提示',vi:'Gợi ý'},source,blocks:[hint,{...hint,zh:prefix+'：教材正文保持可见',source:{...source,provenance:'textbook'}},{...hint,zh:'这是补充辨析与安全说明'},{...hint,kind:'instruction',zh:prefix+'：任务说明保持可见'}]};l.sections.push(section);
  const state=blank(configs[2]),host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:1,section:'practice'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});
  const nodes=all(host),details=nodes.filter(n=>n.tagName==='DETAILS'&&n.textContent.includes(hint.zh));assert.equal(details.length,1);assert.equal(details[0].attrs.open,undefined);assert.ok(details[0].textContent.includes(hint.vi));assert.equal(nodes.filter(n=>n.tagName==='P'&&n.textContent.includes(hint.zh)).length,1);
  for(const block of section.blocks.slice(1)){const p=nodes.filter(n=>n.tagName==='P'&&n.textContent.includes(block.zh));assert.equal(p.length,1);assert.notEqual(p[0].parent.tagName,'DETAILS')}
 }
});
