// Deterministic renderer/state regression only. Real CSS/focus/storage needs browser CI.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {mountLesson} from '../src/lesson-view.ts';import {blank,validateState} from '../src/state.ts';import {configs} from '../src/config.ts';import {verifyActivities} from '../tools/verify-activities.mjs';
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.events={};this.classes=new Set();this.scrollWidth=0;this.clientWidth=0;this.value='';this._text='';this.classList={add:(...c)=>c.forEach(x=>this.classes.add(x)),toggle:(c,v)=>v?this.classes.add(c):this.classes.delete(c)}}append(...xs){for(const x of xs){this.children.push(x);x.parent=this}}prepend(...xs){this.children.unshift(...xs);xs.forEach(x=>x.parent=this)}set textContent(v){this._text=v;this.children=[]}get textContent(){return this._text+this.children.map(x=>x.textContent??String(x)).join('')}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,v){this.events[k]=v}querySelector(){return null}remove(){}replaceChildren(...xs){this.children=[];this.append(...xs)}}
class TextArea extends Element{constructor(){super('textarea')}}
const all=n=>[n,...n.children.flatMap(all)];
test('editable source-table names stay in headers and remain independent through save/remount/reset',async()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-01.json',import.meta.url)));const a=l.activities.find(a=>a.id.endsWith('travel-survey'));const base=a.fields[0];a.fields=[];
 function field(id,zh){const f={...base,id:l.id+':field:header-test-'+id,prompt:{zh,vi:zh},input:'text',assessment:'open'};a.fields.push(f);return f.id}
 const names=['A','B','C'].map(x=>field('name-'+x,x+'姓名'));a.matrix={mode:'responses',rowHeading:{zh:'问题',vi:'Câu hỏi'},columns:[{zh:'我',vi:'Tôi'},...['A','B','C'].map(x=>({zh:x,vi:x}))],headerFieldIds:[null,...names],rows:['几点起床？','几点睡觉？','跑步快不快？'].map((question,row)=>({prompt:{zh:question,vi:question},fieldIds:['我','A','B','C'].map((person,column)=>field(`row${row}-col${column}`,person+question))}))};assert.deepEqual(verifyActivities(l),[]);
 let state=blank(configs[2]);function render(){const host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:1,section:'overview'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});const card=all(host).find(n=>n.dataset.activityId===a.id);return{card,table:all(card).find(n=>n.tagName==='TABLE'),nodes:all(card)}}
 let v=render();const head=all(v.table).find(n=>n.tagName==='THEAD'),body=all(v.table).find(n=>n.tagName==='TBODY');assert.equal(v.table.dataset.headerInputs,'true');assert.equal(head.children[0].children.length,5);assert.equal(body.children.length,3);assert.deepEqual(all(head).filter(n=>n.tagName==='INPUT').map(n=>n.id),names);assert.deepEqual(all(body).filter(n=>n.tagName==='INPUT').map(n=>n.id),a.matrix.rows.flatMap(r=>r.fieldIds));assert.equal(all(head.children[0].children[1]).filter(n=>n.tagName==='INPUT').length,0);
 for(const [i,f]of a.fields.entries()){const input=v.nodes.find(n=>n.id===f.id);assert.ok(input);const label=v.nodes.find(n=>n.htmlFor===f.id);assert.ok(label);input.value='值'+i;input.oninput()}
 const button=v.nodes.find(n=>n.tagName==='BUTTON'&&n.classes.has('primary'));button.events.click();await Promise.resolve();await Promise.resolve();assert.ok(state.activities[a.id].checkedAt);const feedback=v.nodes.find(n=>n.classes.has('activity-feedback'));assert.ok(!all(feedback).some(n=>n.classes.has('feedback-correct')||n.classes.has('feedback-retry')));
 const before={...state.activities[a.id].values},nameInput=v.nodes.find(n=>n.id===names[1]);nameInput.value='新昵称';nameInput.oninput();assert.equal(state.activities[a.id].checkedAt,null);assert.equal(feedback.textContent,'');for(const f of a.fields)if(f.id!==names[1])assert.equal(state.activities[a.id].values[f.id],before[f.id]);
 state=validateState(JSON.parse(JSON.stringify(state)),configs[2]);v=render();for(const f of a.fields)assert.equal(v.nodes.find(n=>n.id===f.id).value,f.id===names[1]?'新昵称':before[f.id]);state=blank(configs[2]);v=render();for(const f of a.fields)assert.equal(v.nodes.find(n=>n.id===f.id).value,'');
});

test('cross-page review cites each identical row once while mixed provenance stays beside separate cells',()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-15.json',import.meta.url))),a=l.activities.find(a=>a.id.endsWith('review-grammar')),before=JSON.stringify(a);let state=blank(configs[2]);function render(){const host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:15,section:'culture'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});const card=all(host).find(n=>n.dataset.activityId===a.id);return{card,body:all(card).find(n=>n.tagName==='TBODY')}}
 let {card,body}=render();assert.equal(body.children.length,9);assert.equal(all(card).filter(n=>n.tagName==='INPUT').length,18);for(const[i,row]of body.children.entries()){const notes=all(row).filter(n=>n.classes.has('source-note'));assert.equal(notes.length,1);assert.equal(notes[0].parent,row.children[0]);assert.ok(notes[0].textContent.includes(i<4?'139':'140'));assert.equal(all(row.children[1]).filter(n=>n.classes.has('source-note')).length,0);assert.equal(all(row.children[2]).filter(n=>n.classes.has('source-note')).length,0);for(const [j,td]of row.children.slice(1).entries())assert.equal(all(td).find(n=>n.tagName==='INPUT').id,a.matrix.rows[i].fieldIds[j])}assert.equal(JSON.stringify(a),before);
 for(const change of [{pdfPage:155,printedPage:140},{section:'different source section'}]){const l2=JSON.parse(before);Object.assign(a,l2);a.fields[1].source={...a.fields[1].source,...change};({card,body}=render());const row=body.children[0];assert.equal(all(row.children[0]).filter(n=>n.classes.has('source-note')).length,0);for(const td of row.children.slice(1))assert.equal(all(td).filter(n=>n.classes.has('source-note')).length,1);assert.equal(all(card).filter(n=>n.tagName==='INPUT').length,18)}
});
