import test from 'node:test';import assert from 'node:assert/strict';import{mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,symlinkSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{packageFrozen,entryHTML,updatePortal,inputPath,deploymentPath,hash}from'../tools/package-core.mjs';
const html='<!doctype html><html><head><meta name="hsk-level" content="2"><title>HSK2</title><script type="module" src="./assets/index-a.js"></script><link rel="stylesheet" href="./assets/index-a.css"></head><body><div id="app"></div></body></html>';
const portal=readFileSync(new URL('../../index.html',import.meta.url),'utf8');
function fixture(){const root=mkdtempSync(join(tmpdir(),'hsk-package-')),input=join(root,'dist'),output=join(root,'release'),p=join(root,'portal.html');mkdirSync(join(input,'assets'),{recursive:true});writeFileSync(join(input,'index.html'),html);writeFileSync(join(input,'assets/index-a.js'),'export const version="2026.1";');writeFileSync(join(input,'assets/index-a.css'),'body{color:green}');writeFileSync(p,portal);writeFileSync(join(input,'content-manifest.json'),JSON.stringify({schemaVersion:1,mode:'release',lessons:[...Array.from({length:15},(_,n)=>({level:2,number:n+1})),...Array.from({length:18},(_,n)=>({level:3,number:n+1}))]}));for(const level of[2,3]){const d=join(input,`course-assets/hsk${level}/audio`);mkdirSync(d,{recursive:true});for(let n=1;n<=(level===2?15:18);n++)for(let t=1;t<=8;t++)writeFileSync(join(d,`${n}-${t}.mp3`),`fixture-${level}-${n}-${t}`)}const m=JSON.parse(readFileSync(join(input,'content-manifest.json')));m.audio=[];for(const level of[2,3])for(let n=1;n<=(level===2?15:18);n++)for(let t=1;t<=8;t++){const file=`course-assets/hsk${level}/audio/${n}-${t}.mp3`,bytes=readFileSync(join(input,file));m.audio.push({file,sha256:hash(bytes),bytes:bytes.length})}writeFileSync(join(input,'content-manifest.json'),JSON.stringify(m));return{root,input,output,portal:p,sourceCommit:'a'.repeat(40)}}
test('two locked course entries share identical frozen assets with nested relative media paths',()=>{for(const level of[2,3]){const out=entryHTML(html,level);assert.match(out,new RegExp(`hsk-level" content="${level}"`));assert.match(out,/hsk-level-locked/);assert.match(out,/asset-base" content="\.\.\/\.\.\/course-engine\//);assert.match(out,/src="\.\.\/\.\.\/course-engine\/assets\/index-a.js/)}assert.throws(()=>entryHTML(html,4));assert.throws(()=>entryHTML('<html/>',2))});
test('portal updates only2/3 course cards and retains exact HSK1 and both HSK4 cards',()=>{const next=updatePortal(portal);assert.match(next,/new-hsk2\/hsk2\//);assert.match(next,/new-hsk3\/hsk3\//);assert.match(next,/<b>18<\/b><span>BÀI HỌC/);for(const m of portal.matchAll(/<a class="level-card h[14]"[^>]*>[\s\S]*?<\/a>/g))assert.ok(next.includes(m[0]));assert.throws(()=>updatePortal('<html/>'))});
test('package manifest binds every scoped output byte to the frozen source input without copying raw sources',()=>{const f=fixture();try{const m=packageFrozen(f);assert.equal(m.files.length,272);assert.equal(m.sourceInputFiles.length,268);assert.equal(m.sourceCommit,f.sourceCommit);for(const item of m.files){assert.ok(deploymentPath(item.path));assert.equal(hash(readFileSync(join(f.output,item.path))),item.sha256)}assert.equal(readFileSync(join(f.output,'course-engine/assets/index-a.js'),'utf8'),readFileSync(join(f.input,'assets/index-a.js'),'utf8'));assert.ok(!existsSync(join(f.output,'hsk1')));assert.equal(JSON.parse(readFileSync(join(f.output,'course-engine/release-manifest.json'))).mode,'release');assert.throws(()=>packageFrozen(f),/must not exist/)}finally{rmSync(f.root,{recursive:true,force:true})}});
test('missing audio, unknown raw PDF, symlinks and wrong identity fail before release creation',()=>{for(const kind of['audio','pdf','symlink','identity','pilot','content','changedAudio']){const f=fixture();try{if(kind==='audio')rmSync(join(f.input,'course-assets/hsk2/audio/1-1.mp3'));if(kind==='pdf')writeFileSync(join(f.input,'textbook.pdf'),'raw');if(kind==='symlink')symlinkSync(join(f.input,'index.html'),join(f.input,'copy.html'));if(kind==='identity')f.sourceCommit='main';if(kind==='pilot')writeFileSync(join(f.input,'content-manifest.json'),JSON.stringify({schemaVersion:1,mode:'pilot',lessons:[]}));if(kind==='content')rmSync(join(f.input,'content-manifest.json'));if(kind==='changedAudio')writeFileSync(join(f.input,'course-assets/hsk2/audio/1-1.mp3'),'changed');assert.throws(()=>packageFrozen(f));assert.ok(!existsSync(f.output))}finally{rmSync(f.root,{recursive:true,force:true})}}});
test('output and public-input allowlists reject legacy overwrites and source package paths',()=>{for(const p of['hsk1/index.html','hsk3/index.html','hsk4/index.html','new-hsk1/hsk1/index.html','assets/script.js','course-engine/../../hsk1/index.html','/course-engine/index.html'])assert.equal(deploymentPath(p),false);for(const p of['raw.pdf','answers.zip','assets/app.js.map','course-assets/hsk2/audio/1-9.mp3','../index.html'])assert.equal(inputPath(p),false)});

import{restoreFrozen}from'../tools/restore-frozen.mjs';
import{copyFileSync}from'node:fs';
import{walkFiles}from'../tools/package-core.mjs';
function splitFixture(f){const manifest=packageFrozen(f),code=join(f.root,'code');for(const path of walkFiles(f.output).filter(p=>!p.endsWith('.mp3'))){mkdirSync(join(code,path,'..'),{recursive:true});copyFileSync(join(f.output,path),join(code,path))}return{code,audio:f.input,output:join(f.root,'restored'),sourceCommit:f.sourceCommit,manifest}}
test('small frozen-code transfer restores all exact tested bytes from264 hash-bound originals without rebuilding',()=>{const f=fixture();try{const x=splitFixture(f),m=restoreFrozen(x);assert.equal(m.files.length,x.manifest.files.length);for(const p of walkFiles(f.output))assert.deepEqual(readFileSync(join(x.output,p)),readFileSync(join(f.output,p)));assert.throws(()=>restoreFrozen(x),/must not exist/)}finally{rmSync(f.root,{recursive:true,force:true})}});
test('frozen transfer fails before output on changed audio, code, extra raw source or wrong source commit',()=>{for(const kind of['audio','code','extra','identity']){const f=fixture();try{const x=splitFixture(f);if(kind==='audio')writeFileSync(join(x.audio,'course-assets/hsk2/audio/1-1.mp3'),'changed');if(kind==='code')writeFileSync(join(x.code,'index.html'),'changed');if(kind==='extra')writeFileSync(join(x.code,'raw.pdf'),'private');if(kind==='identity')x.sourceCommit='b'.repeat(40);assert.throws(()=>restoreFrozen(x));assert.ok(!existsSync(x.output))}finally{rmSync(f.root,{recursive:true,force:true})}}});
