import {test} from 'node:test';
import assert from 'node:assert/strict';
import {canonicalPrecisionJSON,precisionSHA256,validatePrecisionManifest} from '../src/precision-contract.ts';
const h=x=>x.repeat(64),source={file:'course-assets/hsk2/audio/1-2.mp3',sha256:h('a'),duration:5};
async function fixture(){
 const target={id:'hsk2-fltrp-2026:l01:word01',level:2,lesson:1,unit:'word',sourceText:'就',sourceLessonFile:'course-app/content/hsk2/lesson-01.json',sourceLessonSHA256:h('b')};
 const annotation={...target,id:'stage-note',unit:'sentence',sourceText:'（老师来了。）'};
 const row={...target,sourceTrack:source.file,sourceSHA256:source.sha256,sourcePCM_SHA256:h('c'),sourceSampleRange16k:[8000,24000],cropPCM_SHA256:h('d'),clipUnit:'single-original-pronunciation',readingCount:1,reviewDecisionId:'independent-actual-source-frame-decision'};
 const manifestText=JSON.stringify({schemaVersion:1,status:'accepted',sampleRate:16000,records:[row]}),targetCatalogText=JSON.stringify({schemaVersion:1,targets:[target,annotation]});
 const authority={schemaVersion:1,status:'accepted',manifestSHA256:await precisionSHA256(manifestText),targetCatalogSHA256:await precisionSHA256(targetCatalogText),independentReportSHA256:h('e'),acceptedSourceFrameGates:[row],nonSpokenAnnotations:[{id:annotation.id,sourceLessonSHA256:annotation.sourceLessonSHA256,reason:'Printed stage direction is absent from the original recording.',reviewDecisionId:'independent-source-context-annotation'}],certifications:{humanListening:false,pronunciationToneCertified:false,devicePlaybackCertified:false}};
 return {manifestText,targetCatalogText,authority,authoritySHA256:await precisionSHA256(canonicalPrecisionJSON(authority)),sources:[source]};
}
test('one exact independently approved word and one source-bound nonspoken annotation pass',async()=>{const rows=await validatePrecisionManifest(await fixture());assert.equal(rows.length,1);assert.deepEqual(rows[0].sourceSampleRange16k,[8000,24000]);});
test('two agreeing altered manifests cannot replace the pinned independent authority',async()=>{const f=await fixture();const m=JSON.parse(f.manifestText);m.records[0].sourceSampleRange16k=[0,80000];f.manifestText=JSON.stringify(m);f.authority.acceptedSourceFrameGates=m.records;f.authority.manifestSHA256=await precisionSHA256(f.manifestText);await assert.rejects(validatePrecisionManifest(f),/authority checksum/);});
test('a different source recording with otherwise valid hashes is rejected',async()=>{const f=await fixture();f.sources=[{...source,sha256:h('f')}];await assert.rejects(validatePrecisionManifest(f),/original source identity/);});
test('omitting a required target cannot masquerade as complete precision',async()=>{const f=await fixture();f.authority.nonSpokenAnnotations=[];f.authoritySHA256=await precisionSHA256(canonicalPrecisionJSON(f.authority));await assert.rejects(validatePrecisionManifest(f),/complete target partition/);});
test('a vocabulary word cannot be excluded as an unspoken stage direction',async()=>{const f=await fixture();const r=f.authority.acceptedSourceFrameGates[0];f.authority.acceptedSourceFrameGates=[];f.authority.nonSpokenAnnotations.push({id:r.id,sourceLessonSHA256:r.sourceLessonSHA256,reason:'fake note',reviewDecisionId:'fake'});f.authoritySHA256=await precisionSHA256(canonicalPrecisionJSON(f.authority));await assert.rejects(validatePrecisionManifest(f),/annotation exclusion/);});
test('zero duration and extra repeated readings are held even if both JSON files agree',async()=>{for(const edit of [r=>{r.sourceSampleRange16k=[8000,8000];},r=>{r.readingCount=2;}]){const f=await fixture(),m=JSON.parse(f.manifestText);edit(m.records[0]);f.manifestText=JSON.stringify(m);f.authority.acceptedSourceFrameGates=m.records;f.authority.manifestSHA256=await precisionSHA256(f.manifestText);f.authoritySHA256=await precisionSHA256(canonicalPrecisionJSON(f.authority));await assert.rejects(validatePrecisionManifest(f),/sample range|pronunciation unit/);}});
test('duplicate runtime IDs and a partial approval status are rejected',async()=>{for(const edit of [m=>m.records.push(m.records[0]),m=>{m.status='candidate';}]){const f=await fixture(),m=JSON.parse(f.manifestText);edit(m);f.manifestText=JSON.stringify(m);f.authority.manifestSHA256=await precisionSHA256(f.manifestText);f.authoritySHA256=await precisionSHA256(canonicalPrecisionJSON(f.authority));await assert.rejects(validatePrecisionManifest(f),/duplicate|manifest or catalog shape/);}});
