// Source editorial caveats remain tied to each question and delayed until feedback.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {mountLesson} from '../src/lesson-view.ts';import {blank,validateState} from '../src/state.ts';import {configs} from '../src/config.ts';
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.events={};this.classes=new Set();this.scrollWidth=0;this.clientWidth=0;this.value='';this._text='';this.classList={add:(...c)=>c.forEach(x=>this.classes.add(x)),toggle:(c,v)=>v?this.classes.add(c):this.classes.delete(c)}}append(...xs){for(const x of xs){this.children.push(x);x.parent=this}}prepend(...xs){this.children.unshift(...xs);xs.forEach(x=>x.parent=this)}set textContent(v){this._text=v;this.children=[]}get textContent(){return this._text+this.children.map(x=>x.textContent??String(x)).join('')}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,v){this.events[k]=v}querySelector(){return null}remove(){}replaceChildren(...xs){this.children=[];this.append(...xs)}}
class TextArea extends Element{constructor(){super('textarea')}}
const all=n=>[n,...n.children.flatMap(all)];
for(const mapped of [false,true])test(`question editorial note survives ${mapped?'mapped':'fallback'} rendering without leaking before submit`,async()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-13.json',import.meta.url))),text=l.texts[3],q=text.questions[1],note=q.editorialNote;assert.ok(note?.zh&&note?.vi);delete l.activities;
 const a={id:l.id+':activity:editorial-note-test',kind:'choice',title:{zh:'课文4听后练习',vi:'Bài tập nghe'},origin:'textbook',targetRef:text.id+':listening',source:q.source,fields:text.questions.slice(0,2).map(x=>({id:x.id+':test-answer',targetRef:x.id,prompt:{zh:x.zh,vi:x.vi},input:'select',assessment:'official',source:x.source,options:x.options.map(o=>({zh:o,vi:o})),answer:x.options[x.answer],answerSource:{document:'hsk2-answers',pdfPage:18,item:'课文4'}}))};if(mapped)l.activities=[a];
 let state=blank(configs[2]);function render(){const host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:13,section:'text',scene:4},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,audio:{},audioControl:()=>new Element('div'),message:()=>{}});return {host,card:all(host).find(x=>x.dataset.activityId===(mapped?a.id:q.id))}}
 let v=render();assert.ok(!v.host.textContent.includes(note.zh));async function submit(){all(v.card).find(x=>x.tagName==='BUTTON'&&x.classes.has('primary')).events.click();await Promise.resolve();await Promise.resolve()}
 await submit();assert.ok(!v.host.textContent.includes(note.zh));function fill(value){for(const input of all(v.card).filter(x=>x.tagName==='SELECT')){input.value=value;input.onchange()}}
 fill('正确');await submit();let notes=all(v.card).filter(x=>x.classes.has('question-editorial-note'));assert.equal(notes.length,1);assert.ok(notes[0].textContent.includes(note.zh)&&notes[0].textContent.includes(note.vi));assert.ok(notes[0].textContent.includes('教材第119页'));assert.ok(all(v.card).some(x=>x.classes.has('feedback-retry')));
 state=validateState(JSON.parse(JSON.stringify(state)),configs[2]);v=render();assert.equal(all(v.card).filter(x=>x.classes.has('question-editorial-note')).length,1);fill('错误');assert.ok(!v.card.textContent.includes(note.zh));await submit();assert.equal(all(v.card).filter(x=>x.classes.has('question-editorial-note')).length,1);assert.ok(all(v.card).some(x=>x.classes.has('feedback-correct')));fill('');await submit();assert.ok(!v.card.textContent.includes(note.zh));state=blank(configs[2]);v=render();assert.ok(!v.host.textContent.includes(note.zh));
});
