// Deterministic renderer/state regression only. Real CSS/focus/storage needs browser CI.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {commitCourseActivity} from '../src/activity-commit.ts';
import {mountLesson} from '../src/lesson-view.ts';import {blank,validateState,createLearningStore} from '../src/state.ts';import {configs} from '../src/config.ts';import {verifyActivities} from '../tools/verify-activities.mjs';
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.events={};this.classes=new Set();this.scrollWidth=0;this.clientWidth=0;this.value='';this._text='';this.classList={add:(...c)=>c.forEach(x=>this.classes.add(x)),toggle:(c,v)=>v?this.classes.add(c):this.classes.delete(c)}}append(...xs){for(const x of xs){this.children.push(x);x.parent=this}}prepend(...xs){this.children.unshift(...xs);xs.forEach(x=>x.parent=this)}set textContent(v){this._text=v;this.children=[]}get textContent(){return this._text+this.children.map(x=>x.textContent??String(x)).join('')}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,v){this.events[k]=v}querySelector(){return null}remove(){}replaceChildren(...xs){this.children=[];this.append(...xs)}}
class TextArea extends Element{constructor(){super('textarea')}}
const all=n=>[n,...n.children.flatMap(all)];

const bilingual=zh=>({zh,vi:'VI '+zh});
function fixture(){const l=JSON.parse(fs.readFileSync(new URL('../content/hsk2/lesson-01.json',import.meta.url)));const a=l.activities.find(a=>a.id.endsWith('warmup-matching'));const original=a.fields[0];a.fields=Array.from({length:5},(_,i)=>({...original,id:l.id+':field:menu-test-'+i,prompt:bilingual('菜单空格'+(i+1)),input:'select',assessment:'official',options:[bilingual('A'),bilingual('B')],answer:'A'}));delete a.illustrationIds;a.fields.forEach(f=>delete f.illustrationId);a.kind='fill';a.menu={titleFieldId:a.fields[0].id,columns:2,sections:[{heading:bilingual('肉'),items:[{text:bilingual('鱼肉')},{fieldId:a.fields[1].id}]},{heading:bilingual('甜品'),items:[{fieldId:a.fields[2].id},{text:bilingual('冰激凌（bīngjīlíng）')}]},{heading:bilingual('主食'),items:[{text:bilingual('面条儿')},{text:bilingual('饺子')}]},{headingFieldId:a.fields[3].id,items:[{text:bilingual('红茶')},{fieldId:a.fields[4].id}]}]};return{l,a}}
test('source menu accepts exact exclusive slots and rejects dropped duplicated foreign or malformed fields',()=>{
 const {l}=fixture();assert.deepEqual(verifyActivities(l),[]);
 for(const mutate of [a=>a.menu=null,a=>a.menu.columns=1,a=>a.menu.sections.pop(),a=>a.menu.sections[0].heading.vi='',a=>a.menu.sections[0].headingFieldId=a.fields[1].id,a=>delete a.menu.sections[0].heading,a=>a.menu.sections[0].items=[],a=>a.menu.sections[0].items[0].fieldId=a.fields[1].id,a=>a.menu.sections[0].items[0]={},a=>a.menu.sections[0].items[0].text.zh='',a=>a.menu.titleFieldId='foreign',a=>a.menu.sections[3].items[1].fieldId=a.fields[0].id,a=>a.menu.sections[3].items.pop(),a=>a.menu.sections[0].items[1].fieldId=0,a=>a.fields[0].input='checkbox',a=>a.fields[0].input='textarea',a=>a.kind='survey',a=>a.matrix={columns:[],rows:[]}]){const {l,a}=fixture();mutate(a);assert.ok(verifyActivities(l).some(i=>i.includes('menu')),String(mutate))}
 for(const value of [null,'not-array',['unknown'],[l.illustrationManifest[0].id,l.illustrationManifest[0].id],[false]]){const {l,a}=fixture();a.illustrationIds=value;assert.ok(verifyActivities(l).some(i=>i.includes('support images')))}
});
test('actual menu renderer retains source quadrants bilingual fixed foods and every saved answer without early feedback',async()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const{l,a}=fixture();let state=blank(configs[2]);function render(){const host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:1,section:'overview'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,commitActivity:async(id,values,checkedAt,signal)=>{if(signal.aborted)return false;state.activities[id]={values:{...values},checkedAt,updatedAt:checkedAt};return true},audio:{},audioControl:()=>new Element('div'),message:()=>{}});const card=all(host).find(n=>n.dataset.activityId===a.id);return{card,nodes:all(card)}}
 let v=render(),menu=v.nodes.find(n=>n.classes.has('activity-menu'));assert.equal(menu.attrs.role,'group');assert.ok(menu.attrs['aria-label'].includes(a.title.vi));const blocks=all(menu).filter(n=>n.classes.has('activity-menu-section'));assert.deepEqual(blocks.map(n=>n.dataset.menuSection),['1','2','3','4']);assert.deepEqual(blocks.map(n=>all(n).filter(x=>x.tagName==='SELECT').map(x=>x.id)),[[a.fields[1].id],[a.fields[2].id],[],[a.fields[3].id,a.fields[4].id]]);const title=all(menu).find(n=>n.classes.has('activity-menu-title'));assert.deepEqual(all(title).filter(n=>n.tagName==='SELECT').map(n=>n.id),[a.fields[0].id]);assert.equal(v.nodes.filter(n=>n.tagName==='SELECT').length,5);for(const select of v.nodes.filter(n=>n.tagName==='SELECT'))assert.equal(select.children[0].textContent,'选 · Chọn');assert.ok(menu.textContent.includes('冰激凌（bīngjīlíng）'));assert.ok(menu.textContent.includes('VI 鱼肉'));for(const f of a.fields)assert.ok(v.nodes.find(n=>n.htmlFor===f.id));let feedback=v.nodes.find(n=>n.classes.has('activity-feedback'));assert.equal(feedback.textContent,'');const submit=()=>v.nodes.find(n=>n.tagName==='BUTTON'&&n.classes.has('primary')).events.click();await submit();assert.equal(state.activities[a.id]?.checkedAt??null,null);assert.equal(all(feedback).filter(n=>n.classes.has('feedback-correct')).length,0);
 for(const f of a.fields){const input=v.nodes.find(n=>n.id===f.id);input.value='A';input.onchange()}await submit();assert.ok(state.activities[a.id].checkedAt);assert.equal(all(feedback).filter(n=>n.classes.has('feedback-correct')).length,5);state=validateState(JSON.parse(JSON.stringify(state)),configs[2]);v=render();for(const f of a.fields)assert.equal(v.nodes.find(n=>n.id===f.id).value,'A');feedback=v.nodes.find(n=>n.classes.has('activity-feedback'));assert.equal(all(feedback).filter(n=>n.classes.has('feedback-correct')).length,5);const edit=v.nodes.find(n=>n.id===a.fields[3].id);edit.value='B';edit.onchange();assert.equal(feedback.textContent,'');assert.equal(state.activities[a.id].checkedAt,null);for(const f of a.fields)assert.equal(state.activities[a.id].values[f.id],f.id===edit.id?'B':'A');await submit();assert.equal(all(feedback).filter(n=>n.classes.has('feedback-retry')).length,1);assert.equal(all(feedback).filter(n=>n.classes.has('feedback-correct')).length,4);state=blank(configs[2]);v=render();for(const f of a.fields)assert.equal(v.nodes.find(n=>n.id===f.id).value,'');
});
test('activity support gallery excludes field-bound pictures and places each original image once',()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 const{l,a}=fixture();const ids=l.illustrationManifest.slice(0,3).map(p=>p.id);a.illustrationIds=ids;a.fields[0].illustrationId=ids[0];assert.deepEqual(verifyActivities(l),[]);const state=blank(configs[2]),host=new Element('div');mountLesson(host,l,{route:{view:'lesson',lesson:1,section:'overview'},level:2,assetBase:'/',state:()=>state,edit:fn=>fn(state),flush:async()=>true,commitActivity:async(id,values,checkedAt,signal)=>{if(signal.aborted)return false;state.activities[id]={values:{...values},checkedAt,updatedAt:checkedAt};return true},audio:{},audioControl:()=>new Element('div'),message:()=>{}});const card=all(host).find(n=>n.dataset.activityId===a.id),nodes=all(card),gallery=nodes.find(n=>n.classes.has('activity-support-figures'));assert.ok(gallery);assert.deepEqual(all(gallery).filter(n=>n.tagName==='FIGURE').map(n=>n.dataset.illustrationId),ids.slice(1));assert.equal(nodes.filter(n=>n.tagName==='FIGURE').length,3);assert.equal(new Set(nodes.filter(n=>n.tagName==='FIGURE').map(n=>n.dataset.illustrationId)).size,3);const input=nodes.find(n=>n.id===a.fields[0].id),row=input.parent;assert.equal(row.children[0].dataset.illustrationId,ids[0]);assert.equal(row.children[1].htmlFor,a.fields[0].id);assert.ok(card.children.indexOf(gallery)<card.children.findIndex(n=>n.classes.has('activity-fields')));for(const img of nodes.filter(n=>n.tagName==='IMG'))assert.ok(img.alt.includes(' · '));
});


test('production-store delayed submit cannot restore feedback after edit newer submit dispose or failed write',async()=>{
 globalThis.HTMLTextAreaElement=TextArea;globalThis.document={createElement:t=>t==='textarea'?new TextArea():new Element(t)};globalThis.window={addEventListener(){}};globalThis.location={href:'https://renderer-test.invalid/'};
 for(const scenario of ['edit','newer-submit','dispose','failed-write']){
  const{l,a}=fixture(),disk=new Map(),locks=[];let fail=scenario==='failed-write';const port={getItem:k=>disk.get(k)??null,setItem:(k,v)=>{if(fail)throw new DOMException('full','QuotaExceededError');disk.set(k,v)}},store=createLearningStore(configs[2],port,fn=>new Promise(resolve=>locks.push(()=>resolve(fn())))),host=new Element('div');const dispose=mountLesson(host,l,{route:{view:'lesson',lesson:1,section:'overview'},level:2,assetBase:'/',state:()=>store.snapshot().data,edit:fn=>store.edit(fn),flush:async()=>(await store.save()).ok,commitActivity:(...args)=>commitCourseActivity(store,...args),audio:{},audioControl:()=>new Element('div'),message:()=>{}}),card=all(host).find(n=>n.dataset.activityId===a.id),nodes=all(card),feedback=nodes.find(n=>n.classes.has('activity-feedback')),submit=()=>nodes.find(n=>n.tagName==='BUTTON'&&n.classes.has('primary')).events.click(),put=(i,value)=>{const input=nodes.find(n=>n.id===a.fields[i].id);input.value=value;input.onchange()},release=async()=>{assert.ok(locks.length,scenario);locks.shift()();await new Promise(setImmediate)};
  a.fields.forEach((f,i)=>put(i,'A'));submit();assert.equal(locks.length,1);assert.equal(feedback.textContent,'');assert.equal(store.snapshot().data.activities[a.id].checkedAt,null);
  if(scenario==='edit'||scenario==='newer-submit')put(0,'B');if(scenario==='newer-submit')submit();if(scenario==='dispose')dispose();await release();assert.equal(feedback.textContent,'',scenario+' old callback must not repopulate feedback');
  if(scenario==='edit'){assert.equal(store.snapshot().data.activities[a.id].checkedAt,null);assert.equal(store.snapshot().data.activities[a.id].values[a.fields[0].id],'B');const pendingSave=store.save();await release();assert.equal((await pendingSave).ok,true);const loaded=createLearningStore(configs[2],port,fn=>Promise.resolve(fn()));assert.equal(loaded.snapshot().data.activities[a.id].checkedAt,null);assert.equal(loaded.snapshot().data.activities[a.id].values[a.fields[0].id],'B');loaded.dispose()}
  if(scenario==='newer-submit'){await release();assert.equal(all(feedback).filter(n=>n.classes.has('feedback-retry')).length,1);assert.equal(all(feedback).filter(n=>n.classes.has('feedback-correct')).length,4)}
  if(scenario==='failed-write'){assert.equal(store.snapshot().status,'unsaved');assert.equal(store.snapshot().data.activities[a.id].checkedAt,null);assert.equal(disk.has(configs[2].storageKey),false);fail=false;submit();await release();assert.equal(all(feedback).filter(n=>n.classes.has('feedback-correct')).length,5);assert.equal(store.snapshot().status,'saved')}
  dispose();store.dispose();
 }
});
