#!/usr/bin/env python3
"""Explicit individually read original recording/context recommendations."""
import hashlib,importlib.util,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];BASE=ROOT/'course-app/docs/final-quality-20261006';OUT=BASE/'audio-context-peer-hsk3-optional-r'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':str(p.relative_to(ROOT)),'sha256':sha(p)}
def dump(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
# Per-ID observation scopes were read from the eight actual PCM waveform/spectrum sheets.
# Approximate foreground windows aid reproducible context review, not phoneme timestamp certification.
NOTES={'l02:text1:line1': ([0.86, 5.31], '家月、李文两个独立name声组，和你们看看菜单/想吃点什么两分句实际谱齐全；家月原printedJiāyuè，嘉悅/佳月/whole佳越均保原字，不全局改名字：嘉/佳/家在此Jiā同音、悦/月/越此yuè同音，source同一named-person开餐语境固定。原末什么尾保留，下一谢谢一雪姐始于本quiet后。', '点儿'), 'l05:text2:line4': ([19.13, 24.04], '我觉得这张有点难看和那时候我不知道她在给我照相两个源声组完整，前漂亮已结束后这样的照片才好看另起；originalwhole明确她/一飞照相人物，当前两raw他保留，tā代词声韵相同而书面性别由printed母句固定，不宣称音频可区分他她。点位于首声组内部，末相鼻韵衰减齐全。', '有点儿'), 'l08:text1:line4': ([11.97, 18.03], '因为我今年胖了十多斤/不能再胖下去了/有点不健康三原声组及末康鼻韵完整。small10与medium十及whole十原单位斤声序相同，实际十的原shi节在多斤前完整，没有录音10与其它数量冲突，不做全文数字替换。前运动习惯真不错尾与后羽毛球开头排除，点与不健康内部连续完整。', '有点儿'), 'l11:text3:line2:sentence2': ([4.97, 7.61], '父首老张没来尾在current4.82前结束，原他说家里有点事到所以请假了的两声群和末了完整，后好几个同事从9秒另起；medium她与small/whole他原样保留，printed老张的男代词及tā同声韵说明是书面gender预测而非漏core声。原点/事过渡完整留在句内。', '有点儿'), 'l12:text2:line7': ([29.12, 31.75], '雨已经下起来了与咱们快点走吧两声群首雨原圆唇ü韵及末吧尾完整，前天气变化很快及后source尾静音排除。small魚有不同字/调预测保持、medium/whole雨与printedYǔ及原伞/有雨source身份固定；这里不称鱼yú与雨yǔ同调、不认证声调，不用单个ASR字做r或数量通过。source本句完整legal原雨utterance，点在走吧前的连读样本完整。', '点儿'), 'l13:text2:line6': ([30.54, 33.75], '你把声音开得太大了完整首声群与我去关小一点末声群周期尾全部在30.06–33.81cuts内，前合适吗与后好那我们就等客人来另起排除。whole观与crop关保留，当前printedguān动词关小及两个crop完整音序定位同声的书写预测，不把观另字变原print。末点弱韵/原背景均保留。', '一点儿'), 'l13:text3:line6': ([32.89, 37.21], '我去把盘子拿过来/咱们一边吃蛋糕/一边聊天吧三个原实声群完整，前我太喜欢了落尾已结束，末吧及天韵在37.28cut前衰减，后原轨真实pause尾。聊天核心liao/tian完整在末群，无别的词或核心节未读，不将可选儿的省字当坏cut。', '聊天儿'), 'l13:text4:line1:sentence4': ([12.84, 19.35], '父前三句末英国的红茶落尾在current12.38之前，当前那天我跟他们/一边喝红茶一边聊天/直到十二点多才回家完整声群及家a尾齐全，父下一他们年轻时另起在20后排除。small12/medium十二/whole十二保留真实原字，shi-er两节和点/多原书量序匹配，没有偷借他句数字或不同数量。聊天自然末韵在内部留全。', '聊天儿'), 'l14:text4:line1:sentence4': ([19.84, 28.79], '我最喜欢的节目是留学生们跳舞、最后老师和校长也被叫起来一块跳、特别有意思三实声群及末思弱尾全部保留；父前累坏了尾在当前19.28前结束，父后过几天在本cut后起。块完整原kuai复合韵与跳初声留全，人物/表演语义及原两crop/whole一致，没有省核心名词。', '一块儿'), 'l15:text1:line3': ([13.12, 14.85], '平时孩子们在哪玩首平/末玩鼻韵全留，原问句仅一个源声组，前方便/超市已结束，后小区树/放学游戏另起。medium实际哪儿与small/whole省儿都保留，哪与玩的原内部连接完整，只闭合合法完整原声，不从模型任一有儿/无儿独自声学认证。', '哪儿'), 'l15:text2:line6': ([33.12, 37.01], '那太多了和我得一点一点给您讲两声群完整，两个点周期核与连续韵/给您讲的末讲鼻韵保留；前不知道地方已结束、后行下班吃饭在37.7后开启。printed两个一点儿不被改字，原两个point core完整且不是漏读/少读次数。', '一点儿、一点儿'), 'l15:text4:line1:sentence6': ([27.92, 41.97], '父前河里游泳末尾在current27.42前结束，长大以后/不开心事情/河边树下坐着/听听鸟叫看看河水/朋友聊聊天/难过事情不一会就忘了各实际源声群与全文逐一对照完整；末了落尾及父后那是我最喜欢地方开头排除。聊天和会原核心都在长句内部，保留原子句暂停与所有连读。', '聊天儿、一会儿'), 'l16:text2:line7': ([37.97, 41.35], '我听说有的熊猫出国了首声群、他们去哪了末问句完整，前中国是熊猫家落尾已完、后关于这个问题另起在42以后；small当前哪儿及whole哪儿与medium省儿都保原字。哪完整原韵和了尾在当前41.44cut前，未裁掉末句或邻问答。', '哪儿'), 'l17:text1:line2:sentence1': ([6.54, 9.24], '你进去吧首群与我在楼梯那等你第二群起尾全部保留，父后我害怕见李老师从9.85另起在cut后；前办公室已经到了在6.12start前尾完。原那核心a韵与等你连接留在完整source，whole那儿和两crop省儿全保，不把r文字差异泛化为未知clip。', '那儿')}
def main():
 obsfile=OUT/'next14-independent-actual-source-observations.json';obs=json.loads(obsfile.read_text());decisions=[];annotations=[]
 for t in obs['targets']:
  tail=t['id'].split(':',1)[1];voice,note,form=NOTES[tail];a,b=t['sourceSampleRange16k'];assert a/16000<=voice[0]<voice[1]<=b/16000
  rationale=note+' 已独立实际读3个local source/crop谱页与3个complete原轨页并逐ID对print/py、whole-source原raw和双crop原raw。精切接受范围为固定完整合法原录音及可选儿化自然语流variant；不把任一ASR省儿或脚本字符删儿证明r缺失，也不新增canonical-r/native/全音素/声调认证门。教材ZH/pinyin/IDs不动，学生明确原录音自然读法；若需声学canonical-r证书此scope不提供。'
  rawdif=[{**{k:m[k]for k in ['file','sha256','actualInference','modelRepository','modelRevision']},'sourceText':t['sourceText'],'observedRawText':m['rawTranscript'],'rawRetainedVerbatim':True,'decoderWarningsRetained':m['warningSegmentsRetained'],'holdsUnchanged':m['holdsUnchanged'],'flagsUnchanged':m['flagsUnchanged']}for m in t['actualCropModelEvidence']]
  annotation='教材标注：'+form+'；本段按原录音的自然语流读法播放。'
  variant={k:t[k]for k in ['id','candidateId','sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};variant.update({'canonicalPrintedZH':t['sourceText'],'canonicalPrintedPinyin':t['sourcePinyin'],'canonicalPrintedSource':t['canonicalPrintedSource'],'sourceOriginalCoreUtteranceComplete':True,'sourceSamplesAndCanonicalTextUnchanged':True,'studentVisibleAnnotationZH':annotation,'recordedPronunciationDifference':'可选儿化在自然连读中呈现；此审只闭合完整合法原core/utterance，不额外声称canonical-r音素逐一认证或声学r绝对缺失。','scope':'fixed-complete-legal-original-recording-optional-rime-variant-context','acousticCanonicalRClaim':False,'rAbsenceAbsoluteNativeClaim':False,'annotationSuggestedNotRuntimeModified':True,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False})
  proof={k:t[k]for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256','sourceText','sourcePinyin']};proof.update({'canonicalPrintedSource':t['canonicalPrintedSource'],'sourceGroupEvidence':t['sourceGroupEvidence'],'wholeSourceGroupUnpromptedASRReviewed':True,'sourceOrderChecked':True,'neighborSpeechExcluded':True,'actualCropBoundariesChecked':True,'phoneticEquivalenceIsAuxiliaryOnly':True,'rawDifferences':rawdif,'actualOriginalObservationEvidence':{**ref(obsfile),'id':t['id']},'actualCurrentSourceCropSpectrum':t['actualCurrentSourceCropPlot'],'actualCompleteOriginalSourceSpectrum':t['actualCompleteOriginalSourcePlot'],'actualFourEdgeRMSDbFS20ms':t['actualFourEdgeRMSDbFS20ms'],'actualForegroundObservationSecondsApproximateNotPhonemeBoundaries':voice,'wholeSourceWordsIntersectingCurrentCropAuxiliaryOnly':t['wholeSourceWordsIntersectingCurrentCropAuxiliaryOnly'],'recordedPronunciationVariantEvidence':variant,'explanation':rationale,'acousticCanonicalRClaim':False,'fullPhonemeCertification':False})
  d={k:t[k]for k in ['id','candidateId','sourceSampleRange16k','cropPCM_SHA256']};d.update({'decision':'accept','category':'fixed-recorded-rime-variant-context','recommendationOnly':True,'sourceContextChecked':True,'rationale':rationale,'sourceContextEvidence':proof,'resolvedTextHolds':t['holdsUnchanged'],'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[],'acknowledgedFlags':t['flagsUnchanged'],'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False,'productionApproved':False});decisions.append(d);annotations.append(variant)
 out=OUT/'explicit-next14-complete-original-rime-context-peer-recommendations.json';dump(out,{'status':'explicit-independent-recommendations-awaiting-central-compile','reviewer':'acceptance_scope_plan','reviewReportEvidence':obs['targets'][0]['currentActualReportEvidence'],'observationEvidence':ref(obsfile),'scriptEvidence':ref(Path(__file__)),'decisions':decisions,'counts':{'recommendations':14,'runtimeApprovals':0},'sourceModified':False,'newASR':False,'runtimeModified':False,'acousticCanonicalRClaim':False,'allHumanNativeToneDeviceAndFullPhonemeCertificationsFalse':True})
 annotationfile=OUT/'next14-student-visible-optional-rime-context-proposal.json';dump(annotationfile,{'status':'proposal-for-root-display-overlay-not-runtime-write','decisionsEvidence':ref(out),'entries':annotations,'count':20,'canonicalTextPinyinIDsAndHistoryPreserved':True,'sourceAudioAndFramesPreserved':True})
 s=importlib.util.spec_from_file_location('h3_optional_validate',ROOT/'tools/final-quality-20261006/review-decisions.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);reports={};validated=[]
 for t,d in zip(obs['targets'],decisions):
  rp=ROOT/t['currentActualReportEvidence']['file'];r=reports.setdefault(str(rp),json.loads(rp.read_text()));row=next(z for z in r['targets']if z['id']==t['id']and z['candidateId']==t['candidateId']and z['sourceSampleRange16k']==t['sourceSampleRange16k']);m.contextual_decision(row,d,ROOT);validated.append(d['id'])
 val=OUT/'read-only-next14-source-context-validation.json';dump(val,{'status':'actual-context-schema-and-identity-validation-passed-not-authority','decisionEvidence':ref(out),'IDs':validated,'passed':len(validated),'runtimeModified':False});print(json.dumps({'proof':ref(out),'validation':ref(val),'annotation':ref(annotationfile)}))
if __name__=='__main__':main()
