#!/usr/bin/env python3
"""Independent complete real utterance physical handoff; held decoder scope stays explicit."""
import hashlib,importlib.util,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'course-app/docs/final-quality-20261006';O=B/'audio-context-peer-hsk3-optional-r'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':str(p.relative_to(ROOT)),'sha256':sha(p)}
def dump(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def mod(n,p):s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
support=mod('solezero_physical_support',ROOT/'tools/final-quality-20261006/review-decisions.py');syllable=mod('solezero_actual_voiced_features',ROOT/'tools/final-quality-20261006/review-syllable-evidence.py');report=B/'audio-review/hsk3-paired-full-03.json';row=next(z for z in json.loads(report.read_text())['targets']if z['id']=='hsk3-fltrp-2026:l16:text3:line1');obsfile=O/'sole-zero-sentence-independent-actual-source-observations.json';obs=json.loads(obsfile.read_text())['targets'][0];raw=support.original_pcm(ROOT,row);a,z=row['sourceSampleRange16k'];identity={k:row[k]for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};identity['sourceText']=row['sourceZH'];bins=syllable.features(raw,a,z);feature={**identity,'featureBins':bins,'featureBinsSHA256':syllable.feature_sha(bins),'method':'actual-original-PCM-normalized-autocorrelation-32ms-5ms-75-to-500Hz-energy-gated','fullPhonemeCertification':False,'pronunciationToneCertified':False,'productionApproved':False};fp=O/'sole-zero-original-utterance-actual-voiced-features.json';dump(fp,feature)
wp=O/'sole-zero-original-utterance-waveform-observation.json';dump(wp,{**identity,'sourceSampleCount16k':len(raw)//4,'plots':[obs['actualCurrentSourceCropPlot']],'wholeOriginalPlot':obs['actualCompleteOriginalSourcePlot'],'localYiHuiSourcePhaseEvidence':ref(O/'sole-zero-original-yi-hui-physical-phases.json'),'newInferencePerformed':False,'sourceModified':False})
explanation='独立真实读本source完整开首熊猫句、crop原谱及两次yi-hui细谱和whole原谱，原这只大熊猫/yihuir爬上去/yihuir跳下来/可爱极了全部核心声群齐全。第二yi实际3.28–3.42有完整高前i的periodic核/低F1及上部共振条带，再经真实hui fric/圆唇复韵到跳下来的原声群；medium word11的start=end3.22只是该decoder词排时错误，其源绝对3.4699375落在原hui过渡，不是源声为零或裁片未读第二yi。small该一实际2.92–3.12正长、同原whole medium3.36–3.50正长的raw仅辅助；三个完整source/crop模型原字全文literal保原无改，不拿模型字造phone。原首zh摩擦/周期起声前留真实leading quiet、原末了弱尾5.35左右后才cut5.58，下一它好像没吃饱从6.7以后另起排除。打印Zhè zhī dàxióngmāo yíhuìr pá shàngqu, yíhuìr tiào xiàlai, kě\'ài jí le与合法完整原core对应，无姓名/数量/词核矛盾；不要求为每个自然可选儿化或声调另加native证书。zero原raw及warning/invalidIndices全保、不改词时间、不合成静音/phoneme对齐。'
physical={**identity,'selectedCompleteOriginalReadingFrames16k':[11040,86080],'independentlyReviewedNeighborLimits16k':[0,101120],'completeOriginalOnsetRimeAndFinalReviewed':True,'neighborPhonemesExcluded':True,'sourceOrderChecked':True,'originalPrintedPronunciationChecked':True,'allASRWarningsRetained':True,'noSyntheticPadding':True,'phonemeIdentityUnknown':False,'explanation':explanation,'onsetExplanation':'原source帧0到起声前的真实leading静音存在，当前start3999在全部首zh-fric/periodic及熊猫核心以前；完整第一声群没有借邻句或另一读。','rimeAndFinalExplanation':'第二yi-hui原真实源3.28–3.42高前i周期核至hui摩擦/periodic复韵完整留在本句内；可爱极了末弱韵到保守5.38前，end5.58 after完整尾及真实quiet，未缺该yi或了尾。','originalReadingExplanation':'本原16-5整轨首印刷句，只有一次该完整sentence；按真实whole source/父印ZHpy/首实体声群和下一它好像还没吃饱原邻声群闭合身份，不按script词序虚定未朗读字。','originalPrintedSource':{k:row['canonicalSource'][k]for k in ['file','sha256','sourceJSONPointer']},'waveformObservation':ref(wp),'actualSyllableFeatureEvidence':ref(fp),'actualOriginalObservationEvidence':ref(obsfile),'actualOriginalYiHuiPhaseEvidence':ref(O/'sole-zero-original-yi-hui-physical-phases.json'),'sourceUtteranceEvidence':{'canonicalSourceId':row['canonicalSource']['sourceId'],'sentenceOrdinal':row['canonicalSource']['sentenceOrdinal'],'parentZH':row['canonicalSource']['parentZH'],'actualUtteranceFrames16k':[11040,86080],'completeOriginalUtteranceIndependentlyReviewed':True,'previousActualSpeechFrames16k':None,'followingActualSpeechFrames16k':[107520,173440],'wholeSourceEvidence':[obs['sourceGroupEvidence']]},'actualFourEdgeRMSDbFS20ms':obs['actualFourEdgeRMSDbFS20ms'],'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False}
rawzero={'modelRepository':'Systran/faster-whisper-medium','modelRevision':'08e178d48790749d25932bbc082711ddcfdfbc4f','bindingEvidence':{'file':obs['actualCropModelEvidence'][1]['file'],'sha256':obs['actualCropModelEvidence'][1]['sha256']},'rawEvidence':obs['actualCropModelEvidence'][1]['actualInference'],'rawSegmentIndex':0,'rawSegmentId':1,'rawWordIndex':11,'flattenedWordIndex':11,'rawWordUnchanged':row['rawModelEvidence'][1]['words'][11],'relativeTimestampSeconds':[3.22,3.22],'auxiliaryAbsoluteSourcePositionSeconds':3.4699375,'actualSourceYiObservationSeconds':[3.28,3.42],'sourceObservationNotDecoderAlignment':True}
d={'id':row['id'],'candidateId':row['candidateId'],'sourceSampleRange16k':row['sourceSampleRange16k'],'cropPCM_SHA256':row['cropPCM_SHA256'],'status':'core-source-physical-known; fixed-decoder-scope-and-actualCTC-pending-central-registration','actualOriginalUtteranceSourcePhysicalEvidence':physical,'preservedDecoderDiagnosticEvidence':rawzero,'originalRawResultWhitelist':[{k:e[k]for k in ['file','sha256','modelRepository','modelRevision','rawTranscript']}for e in row['rawModelEvidence']],'originalHoldsUnchanged':row['holds'],'flagsUnchanged':row['flags'],'notProductionApproved':True}
p=O/'sole-zero-original-utterance-independent-physical-handoff.json';dump(p,{'status':'independent-real-physical-source-core-known-handoff-not-authority','reviewer':'acceptance_scope_plan','sourceReportEvidence':ref(report),'scriptEvidence':ref(Path(__file__)),'decisions':[d],'actualCTCEvidenceAvailable':False,'missingCentralGateRequirements':['exact fixed-original-utterance scope registration','actual same-crop CTC bytes/source-frame verification required by current fixed gate; no existing result known'],'sourceModified':False,'newASR':False,'runtimeModified':False,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'fullPhonemeCertification':False});print(ref(p))
