#!/usr/bin/env python3
"""Explicit individually read original recording/context recommendations."""
import hashlib,importlib.util,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];BASE=ROOT/'course-app/docs/final-quality-20261006';OUT=BASE/'audio-context-peer-hsk3-optional-r'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'file':str(p.relative_to(ROOT)),'sha256':sha(p)}
def dump(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
# Per-ID observation scopes were read from the eight actual PCM waveform/spectrum sheets.
# Approximate foreground windows aid reproducible context review, not phoneme timestamp certification.
NOTES={'l01:text1:line3': ([10.24, 14.25], '原我还以为是同乐呢与他们看上去有点像两完整声群及呢/像韵尾 retained；current使用已存sentence114改善[163200,234240]，不是triage旧first[162560,229952]。同乐printedTónglè与当前small铜乐/medium同樂及whole彤乐原字保留，铜/同/彤在本printed人名 occurrence的Tóng节兼容；保留source双问答人物身份，非从name字指定未知声音。background在真实双sourcepause及cut延续，邻前朋友/邻后是长得另声群排除。', '有点儿'), 'l01:text1:line4': ([15.07, 19.87], '是长得有点像/但是他比同乐高/身高有一米八三个原声群完整。small市長的与medium是長得原字保留：本printedShì zhǎng de三节与原完整人物比较turn兼容，市/是同shì、的/得neutralde；同乐/铜乐按本Tónglè人名同源context，非全局同字改写。双raw1米8是原一米八全value/unit，yi-mi-ba完整末声在currentcut前，whole一米八对应无quantity异文；旧start与保守onset同帧，选择现存更早240480改善geometry保留原弱起。真实持续background不当邻词。', '有点儿'), 'l01:text1:line5': ([20.15, 22.67], '看起来/也比同乐/瘦一点全声群及periodic点尾完整保留在改善[321280,366561]，原前一米八尾与后一位后句另起排除。actualsmall同乐、medium彤乐/whole彤乐原字保留，printedTónglè原name声序与本same-person比较一致无新姓名；点尾属于原自然语流，无绝对rabsence或canonical-r音素认证。两realpause sourcebaseline保存无静音合成。', '一点儿'), 'l02:text1:line4:sentence1': ([14.58, 16.47], '那多点点与别客气两个完整源声群及气尾在改善[221760,270561]；原source前飞这么远句尾与后你们喝什么饮料首声各在独立邻界外。旧ASRguard的子句起尾过早，使用已有实际sourcepause/foreground及true neighbor[221760,271040]，不修改原guards或假quiet。两个点原周期核完整，printed母行py Nà duō diǎn diǎnr bié kèqi与source一致；candidate row sourcePinyin空值照实保留、canonical parent py独立保留，不造源row字节。', '点儿'), 'l05:text1:line4': ([14.02, 17.64], '那我带点水和吃的首声群/咱们现在就去末问群及去ü尾完整；选择现存end285601 after实际完整弱尾282240，cut前好主意/后咱们怎么去的原新声群排除。mediumactual点儿、small点全文predictions原样保留，点与水内transition均在真实source内部，不从任何预测有儿给音素证书。原背景低带连续及two pauses exactPCM preserved。', '点儿'), 'l06:text3:line8': ([29.91, 33.43], '检票口在二层与我们一会坐电梯上去两完整原声群以及去ü尾都在改善[472319,537280]，前走这么久与后对方新句首声排除。small减票口/medium检票口原字保留，printedJiǎnpiàokǒu的jiǎn在本票口station真实语境与原音序闭合，减/检同jiǎn而不是改原文字。二层数字2的èr与层节完整；它不是可选儿化字，不全局对儿/二替换。会与坐的语流完整原样。', '一会儿'), 'l08:text2:line2': ([4.9, 8.8], '昨天游完泳以后与耳朵一直有点疼两个源声群完整，current改选已有sentence114[77280,142080]，end142080 after先前独立保守foreground140800；不将旧first end139840套用这个较晚弱尾scope，也不以保守envelope宣称旧cut一定缺某音素。首昨初声/疼鼻尾原样、前不舒服及后是不是感冒了首声excluded；耳朵独立erduo合法音节完整，不误归optionalr过滤。真实低background延续跨原pause但target broadband/周期群可分。', '有点儿'), 'l18:text2:line6': ([29.62, 34.67], '你先坐着看会儿电视/饺子很快就包好了两原声群及末了弱尾全留在已有改善[471359,556320]，之前保守foreground554720不套旧553280 cut。sourceparent/whole/cropmedium坐着与small坐著保原字，printedzuòzhe方面标记zhe在此同source语流，著不按zhù读去替教材。两crop会儿实际literal仍不单独代替声学r证书；完整会韵/儿连电视transition与饺子起群均保留，前喝什么/后我刚刚新句excluded，背景全原样。', '会儿')}
def main():
 obsfile=OUT/'boundary8-independent-actual-source-observations.json';obs=json.loads(obsfile.read_text());boundaryfile=BASE/'audio-context-peer-hsk3-boundary/explicit-sentence-boundary-recommendations.json';boundaries={r['id']:r for r in json.loads(boundaryfile.read_text())['decisions']};decisions=[];annotations=[]
 for t in obs['targets']:
  tail=t['id'].split(':',1)[1];voice,note,form=NOTES[tail];a,b=t['sourceSampleRange16k'];assert a/16000<=voice[0]<voice[1]<=b/16000
  rationale=note+' 已独立实际读2个local source/crop谱页与2个complete原轨页并逐ID对print/py、whole-source原raw和双crop原raw。精切接受范围为固定完整合法原录音及可选儿化自然语流variant；不把任一ASR省儿或脚本字符删儿证明r缺失，也不新增canonical-r/native/全音素/声调认证门。教材ZH/pinyin/IDs不动，学生明确原录音自然读法；若需声学canonical-r证书此scope不提供。'
  rawdif=[{**{k:m[k]for k in ['file','sha256','actualInference','modelRepository','modelRevision']},'sourceText':t['sourceText'],'observedRawText':m['rawTranscript'],'rawRetainedVerbatim':True,'decoderWarningsRetained':m['warningSegmentsRetained'],'holdsUnchanged':m['holdsUnchanged'],'flagsUnchanged':m['flagsUnchanged']}for m in t['actualCropModelEvidence']]
  annotation='教材标注：'+form+'；本段按原录音的自然语流读法播放。'
  variant={k:t[k]for k in ['id','candidateId','sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256']};variant.update({'canonicalPrintedZH':t['sourceText'],'canonicalPrintedPinyin':t.get('canonicalPrintedParentPinyin',t['sourcePinyin']),'canonicalPrintedSource':t['canonicalPrintedSource'],'sourceOriginalCoreUtteranceComplete':True,'sourceSamplesAndCanonicalTextUnchanged':True,'studentVisibleAnnotationZH':annotation,'recordedPronunciationDifference':'可选儿化在自然连读中呈现；此审只闭合完整合法原core/utterance，不额外声称canonical-r音素逐一认证或声学r绝对缺失。','scope':'fixed-complete-legal-original-recording-optional-rime-variant-context','acousticCanonicalRClaim':False,'rAbsenceAbsoluteNativeClaim':False,'annotationSuggestedNotRuntimeModified':True,'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False})
  proof={k:t[k]for k in ['sourceTrack','sourceSHA256','sourcePCM_SHA256','sourceSampleRange16k','cropPCM_SHA256','sourceText','sourcePinyin']};proof.update({'canonicalPrintedSource':t['canonicalPrintedSource'],'sourceGroupEvidence':t['sourceGroupEvidence'],'wholeSourceGroupUnpromptedASRReviewed':True,'sourceOrderChecked':True,'neighborSpeechExcluded':True,'actualCropBoundariesChecked':True,'phoneticEquivalenceIsAuxiliaryOnly':True,'rawDifferences':rawdif,'actualOriginalObservationEvidence':{**ref(obsfile),'id':t['id']},'actualCurrentSourceCropSpectrum':t['actualCurrentSourceCropPlot'],'actualCompleteOriginalSourceSpectrum':t['actualCompleteOriginalSourcePlot'],'actualFourEdgeRMSDbFS20ms':t['actualFourEdgeRMSDbFS20ms'],'actualForegroundObservationSecondsApproximateNotPhonemeBoundaries':voice,'wholeSourceWordsIntersectingCurrentCropAuxiliaryOnly':t['wholeSourceWordsIntersectingCurrentCropAuxiliaryOnly'],'recordedPronunciationVariantEvidence':variant,'explanation':rationale,'acousticCanonicalRClaim':False,'fullPhonemeCertification':False})
  d={k:t[k]for k in ['id','candidateId','sourceSampleRange16k','cropPCM_SHA256']};d.update({'decision':'accept','category':'fixed-recorded-rime-variant-context','recommendationOnly':True,'sourceContextChecked':True,'rationale':rationale,'sourceContextEvidence':proof,'resolvedTextHolds':t['holdsUnchanged'],'resolvedSourceHolds':[],'resolvedBoundaryHolds':[],'resolvedDecoderASRDiagnosticHolds':[],'acknowledgedFlags':t['flagsUnchanged'],'humanListening':False,'nativeSpeakerReview':False,'pronunciationToneCertified':False,'devicePlaybackCertified':False,'fullPhonemeCertification':False,'productionApproved':False});prior=boundaries[t['id']];assert prior['sourceSampleRange16k']==t['sourceSampleRange16k']and prior['cropPCM_SHA256']==t['cropPCM_SHA256'];d['boundaryDecisionEvidence']=prior['boundaryDecisionEvidence'];d['resolvedBoundaryHolds']=prior['resolvedBoundaryHolds'];d['resolvedTextHolds']=[h for h in t['holdsUnchanged']if h in ['crop-ASR-Chinese-differs-from-source-needs-phonetic-or-glyph-review','crop-ASR-foreign-lexical-token-or-digit-needs-explicit-review']];proof['existingExactIndependentBoundaryEvidence']={**ref(boundaryfile),'id':t['id']};proof['canonicalPrintedParentPinyin']=t.get('canonicalPrintedParentPinyin');decisions.append(d);annotations.append(variant)
 out=OUT/'explicit-boundary8-complete-original-rime-context-peer-recommendations.json';dump(out,{'status':'explicit-independent-recommendations-awaiting-central-compile','reviewer':'acceptance_scope_plan','reviewReportEvidence':obs['targets'][0]['currentActualReportEvidence'],'observationEvidence':ref(obsfile),'scriptEvidence':ref(Path(__file__)),'decisions':decisions,'counts':{'recommendations':8,'runtimeApprovals':0},'sourceModified':False,'newASR':False,'runtimeModified':False,'acousticCanonicalRClaim':False,'allHumanNativeToneDeviceAndFullPhonemeCertificationsFalse':True})
 annotationfile=OUT/'boundary8-student-visible-optional-rime-context-proposal.json';dump(annotationfile,{'status':'proposal-for-root-display-overlay-not-runtime-write','decisionsEvidence':ref(out),'entries':annotations,'count':20,'canonicalTextPinyinIDsAndHistoryPreserved':True,'sourceAudioAndFramesPreserved':True})
 s=importlib.util.spec_from_file_location('h3_optional_validate',ROOT/'tools/final-quality-20261006/review-decisions.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);reports={};validated=[]
 for t,d in zip(obs['targets'],decisions):
  rp=ROOT/t['currentActualReportEvidence']['file'];r=reports.setdefault(str(rp),json.loads(rp.read_text()));row=next(z for z in r['targets']if z['id']==t['id']and z['candidateId']==t['candidateId']and z['sourceSampleRange16k']==t['sourceSampleRange16k']);m.contextual_decision(row,d,ROOT);m.boundary_decision(row,d,ROOT);validated.append(d['id'])
 val=OUT/'read-only-boundary8-source-context-validation.json';dump(val,{'status':'actual-context-schema-and-identity-validation-passed-not-authority','decisionEvidence':ref(out),'IDs':validated,'passed':len(validated),'runtimeModified':False});print(json.dumps({'proof':ref(out),'validation':ref(val),'annotation':ref(annotationfile)}))
if __name__=='__main__':main()
